### PR TITLE
Fix LBC e2e test after cluster API change

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by hakman** [comment]
Duplicate of https://github.com/kubernetes/kops/pull/14826 ?

**Comment by olemarkus** [comment]
Yeah

**Comment by justinsb** [comment]
Should we be versioning these field paths?  I hadn't realized we were exposing v1alpha3 to users...

**Comment by olemarkus** [comment]
It's actually working on the internal unversioned API.

**Comment by justinsb** [comment]
> It's actually working on the internal unversioned API.

Well that is a mirror of v1alpha3, so I hadn't realized that we were breaking the `--set` command here.

I guess we should look at targeting an explicit version for the set command, and maybe even allowing that version to be explicitly specified (e.g. --set-version=v1alpha3)

**Comment by olemarkus** [comment]
I am thinking we need a strategy for multi-version support in general. Like e.g getting cluster spec in various versions.

**Review by johngmyers — APPROVED** [review]

**Comment by johngmyers** [comment]
To follow kubectl, it'd have to be something like `kubectl create cluster.v1alpha2 ...`. But writing a `--set` that uses versioned APIs would be a pain.

**Comment by johngmyers** [comment]
I suppose it would convert unversioned to versioned, do the reflection, then convert back

**Comment by johngmyers** [comment]
This change was applied by #14826
/close

**Pull request closed without merging**
