### PR TITLE
Update amazon-vpc-routed-eni to v1.2.1

### PR DESCRIPTION
**Pull request by adammw**
Changelog: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by chrisz100** [comment]
/ok-to-test

Thanks for signing the CLA!

**Comment by rdrgmnzs** [comment]
@adammw looks like 1.2.1 was released which fixes the issue you mentioned. Mind bumping the version?

**Comment by justinsb** [comment]
Thanks @adammw !

/approve
/lgtm

**Pull request merged**
