### PR TITLE
Copy weaveworks/mesh to avoid doing in-place changes

### PR DESCRIPTION
**Pull request by hakman**
/cc @olemarkus @justinsb

### CODE REVIEW

**Comment by hakman** [comment]
Failures `pull-kops-e2e-kubernetes-do-gossip` should be addressed by https://github.com/kubernetes/kubernetes/pull/110277.

**Comment by rifelpet** [comment]
Why can't we use the clean vendored version now that we're off bazel and can support build tags?

**Comment by hakman** [comment]
> Why can't we use the clean vendored version now that we're off bazel and can support build tags?

Do we want to add those build tags to both test and protokube build?
I think the plan to find some other solution in the near future.

**Comment by hakman** [comment]
https://github.com/kubernetes/kops/pull/13706 looks like a better and simpler alternative. Will close this PR.

**Comment by hakman** [comment]
Doing some more testing with gossip enabled.
/hold

**Pull request closed without merging**
