### PR TITLE
Update dockerconfig.go

### PR DESCRIPTION
**Pull request by AdamDang**
Line 39: "defailt"
I guess it should be "default".

### CODE REVIEW

**Comment by mikesplain** [comment]
/ok-to-test
/lgtm

Thanks!

**Comment by chrislovecnm** [comment]
Do the other two dockerconfig.go files have the same typo?  They live under alpha* folders.  They are pretty much identical files used for the API.

**Comment by AdamDang** [comment]
@chrislovecnm yes, the same typo exists in the other two alpha version directories.

**Comment by chrislovecnm** [comment]
They are all basically the same files, can we please get all three updated at the same time. Thanks

**Pull request closed without merging**
