### PR TITLE
WIP trivial change for e2e testing

### PR DESCRIPTION
**Pull request by johngmyers**
/ok-to-test
/test pull-kops-e2e-aws-irsa

### CODE REVIEW

**Comment by olemarkus** [comment]
Some really strange errors there. and It is supposed to be identical to 
https://testgrid.k8s.io/kops-misc#kops-grid-scenario-service-account-iam

See https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/kops-presubmits.yaml#L575
and https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/kops/kops-periodics-misc2.yaml#L275

**Comment by rifelpet** [comment]
looks like that fixed it.

**Pull request closed without merging**
