### PR TITLE
Use dep to maintain vendor directory

### PR DESCRIPTION
**Pull request by justinsb**
Lots of notes here: https://github.com/kubernetes/kubernetes/issues/59332

### CODE REVIEW

**Comment by justinsb** [comment]
Hat-tip to @aledbf BTW for pushing us down this road :-)

**Comment by justinsb** [comment]
Very few deps have actually changed in this mega-diff, it is mostly deletions:

```
git diff --name-status  origin/master | grep -v D
A	Gopkg.lock
A	Gopkg.toml
M	Makefile
A	hack/dep.py
M	vendor/github.com/chai2010/gettext-go/gettext/hello.go
A	vendor/github.com/petar/GoLLRB/AUTHORS
A	vendor/github.com/petar/GoLLRB/LICENSE
A	vendor/github.com/petar/GoLLRB/llrb/avgvar.go
A	vendor/github.com/petar/GoLLRB/llrb/iterator.go
A	vendor/github.com/petar/GoLLRB/llrb/llrb-stats.go
A	vendor/github.com/petar/GoLLRB/llrb/llrb.go
A	vendor/github.com/petar/GoLLRB/llrb/util.go
A	vendor/golang.org/x/tools/AUTHORS
A	vendor/golang.org/x/tools/CONTRIBUTORS
A	vendor/golang.org/x/tools/LICENSE
A	vendor/golang.org/x/tools/PATENTS
A	vendor/golang.org/x/tools/cmd/getgo/LICENSE
A	vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
A	vendor/golang.org/x/tools/go/ast/astutil/imports.go
A	vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
A	vendor/golang.org/x/tools/go/ast/astutil/util.go
A	vendor/golang.org/x/tools/imports/fastwalk.go
A	vendor/golang.org/x/tools/imports/fastwalk_dirent_fileno.go
A	vendor/golang.org/x/tools/imports/fastwalk_dirent_ino.go
A	vendor/golang.org/x/tools/imports/fastwalk_portable.go
A	vendor/golang.org/x/tools/imports/fastwalk_unix.go
A	vendor/golang.org/x/tools/imports/fix.go
A	vendor/golang.org/x/tools/imports/imports.go
A	vendor/golang.org/x/tools/imports/mkindex.go
A	vendor/golang.org/x/tools/imports/mkstdlib.go
A	vendor/golang.org/x/tools/imports/sortimports.go
A	vendor/golang.org/x/tools/imports/zstdlib.go
A	vendor/golang.org/x/tools/third_party/moduleloader/LICENSE
A	vendor/golang.org/x/tools/third_party/typescript/LICENSE
A	vendor/golang.org/x/tools/third_party/webcomponents/LICENSE
A	vendor/google.golang.org/appengine/.travis.yml
R100	vendor/github.com/coreos/go-semver/LICENSE	vendor/google.golang.org/appengine/LICENSE
A	vendor/google.golang.org/appengine/appengine.go
A	vendor/google.golang.org/appengine/appengine_vm.go
A	vendor/google.golang.org/appengine/errors.go
A	vendor/google.golang.org/appengine/identity.go
A	vendor/google.golang.org/appengine/internal/api.go
A	vendor/google.golang.org/appengine/internal/api_classic.go
A	vendor/google.golang.org/appengine/internal/api_common.go
A	vendor/google.golang.org/appengine/internal/app_id.go
A	vendor/google.golang.org/appengine/internal/app_identity/app_identity_service.pb.go
A	vendor/google.golang.org/appengine/internal/app_identity/app_identity_service.proto
A	vendor/google.golang.org/appengine/internal/base/api_base.pb.go
A	vendor/google.golang.org/appengine/internal/base/api_base.proto
A	vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
A	vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
A	vendor/google.golang.org/appengine/internal/identity.go
A	vendor/google.golang.org/appengine/internal/identity_classic.go
A	vendor/google.golang.org/appengine/internal/identity_vm.go
A	vendor/google.golang.org/appengine/internal/internal.go
A	vendor/google.golang.org/appengine/internal/log/log_service.pb.go
A	vendor/google.golang.org/appengine/internal/log/log_service.proto
A	vendor/google.golang.org/appengine/internal/main.go
A	vendor/google.golang.org/appengine/internal/main_vm.go
A	vendor/google.golang.org/appengine/internal/metadata.go
A	vendor/google.golang.org/appengine/internal/modules/modules_service.pb.go
A	vendor/google.golang.org/appengine/internal/modules/modules_service.proto
A	vendor/google.golang.org/appengine/internal/net.go
A	vendor/google.golang.org/appengine/internal/regen.sh
A	vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
A	vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
A	vendor/google.golang.org/appengine/internal/transaction.go
A	vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
A	vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
A	vendor/google.golang.org/appengine/namespace.go
A	vendor/google.golang.org/appengine/timeout.go
A	vendor/google.golang.org/appengine/urlfetch/urlfetch.go
M	vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
M	vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/doc.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/empty.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/int.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
M	vendor/k8s.io/gengo/examples/set-gen/sets/string.go
M	vendor/k8s.io/gengo/generator/execute.go
M	vendor/k8s.io/gengo/namer/plural_namer.go
M	vendor/k8s.io/gengo/parser/parse.go
R100	vendor/github.com/go-openapi/analysis/LICENSE	vendor/k8s.io/kubernetes/staging/src/k8s.io/api/LICENSE
R100	vendor/github.com/go-openapi/loads/LICENSE	vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/LICENSE
R100	vendor/k8s.io/kube-deploy/LICENSE	vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/LICENSE
A	vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/LICENSE
A	vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/LICENSE
A	vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/LICENSE
R100	vendor/github.com/kubernetes-incubator/apiserver-builder/LICENSE	vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/LICENSE
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 24256 and retry the command.
```

So a handful of added files, which mostly seem harmless (I hope), and no modified code files, other than `vendor/k8s.io/gengo`, where I think we had the wrong version previously

**Comment by aledbf** [comment]
@justinsb I tested this and works great. Thank you for doing this ;)
Just two comments, in the Makefile you should check the dep version to be >= 0.4.1 and the second the task `copydeps` should not be removed?

**Comment by mikesplain** [comment]
FYI, this also passes travis with [osx](https://github.com/kubernetes/kops/pull/4388) as a build target: https://travis-ci.org/mikesplain/kops/builds/337693572

**Comment by chrislovecnm** [comment]
@aledbf will let you work with @justinsb on this.  You probably can lgtm this as well :)  You know more than I do about dep and such!

**Comment by justinsb** [comment]
@aledbf I probably should, but that feature should really be added to dep.  Is there a nice way to do it?

I'll remove copydeps & the submodules in the next PR.  I'm a little afraid that dep 0.4.2 is going to stop working again...

**Comment by justinsb** [comment]
@aledbf are you OK with merging as-is?

**Comment by aledbf** [comment]
@justinsb yes

**Comment by chrislovecnm** [comment]
/lgtm

holding my breath

**Pull request merged**
