### PR TITLE
Support string-or-slice in IAM policies

### LINKED ISSUE #1920: additionalPolicies broken?
kops version: 1.5.1
k8s version: 1.5.2
This policy looks correct according to: https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

```yaml  
additionalPolicies:
    node: |
      [
        {
          "Action": [ "sts:AssumeRole" ],
          "Resource": "*",
          "Effect": "Allow"
        }
      ]
```

But I get this error during update:
`error creating/updating IAMRolePolicy: MalformedPolicyDocument: Syntax errors in policy.`

It changes `node: |` to `node: |+` when edit saves the spec, I'm not sure if that's related.

### PR DESCRIPTION
**Pull request by justinsb**
Fix #1920

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1928)

### CODE REVIEW

**Comment by yissachar** [comment]
LGTM. I can approve and merge once Travis finishes.

**Comment by yissachar** [comment]
Closing and re-opening to trigger Travis.

**Comment by yissachar** [comment]
@justinsb Getting a weird test failure. PTAL

**Comment by justinsb** [comment]
Ah - it's a weird failure indeed.  If we don't use any glog statements in a test (or reference any code which uses glog), we don't get the `-v` and `-logtostderr` flags defined, which is then an error.  For now I just added a glog statement.

**Comment by yissachar** [comment]
Interesting. Should we open a new issue for that? Doesn't seem right to force each test to have a glog statement.

Also, that seems to have fixed the error, but CI still failed, now due to `hack/.packages` not being up to date.

**Comment by justinsb** [comment]
I was unsure if it was worth an issue.  The other option is to not pass log options in the makefile.

It isn't quite as bad as "every test needs glog" - if you use a library that uses glog, the flag gets added as well.  So this particular test just fired because it was testing a utility.

Thanks on the heads up on the package as well - gets me every time :-)

**Pull request merged**
