### PR TITLE
Upgrade to calico v2.6.6

### PR DESCRIPTION
**Pull request by blakebarnett**

### CODE REVIEW

**Comment by blakebarnett** [comment]
2.6.2 has security holes, and can't upgrade to calico 3.x, and kube-controllers has some important fixes.  I think we should probably upgrade it even if they haven't tested it (it is only a point release after all)

**Comment by chrislovecnm** [comment]
/ok-to-test
/lgtm

when can we upgrade to calico 3?

**Comment by chrislovecnm** [comment]
@blakebarnett you need to bump the version in boostrap go file :)

**Comment by blakebarnett** [comment]
gah, I forget every time.

**Pull request merged**
