### PR TITLE
Skip Docker install

### PR DESCRIPTION
**Pull request by austinmoore-**
Adds configuration (`spec.dockerInstall.skipInstall`) that indicates to nodeup that it should skip the Docker tasks. See the added [docs](https://github.com/austinmoore-/kops/blob/cf6c04bfc597717786855f36eeb88cba8dcac28a/docs/cluster_spec.md#skip-install) for details on how to use it. My thinking with this configuration is that if the user specifies it, nodeup should not do anything related to Docker and it's up to the user to ensure Docker is setup as it needs to be.

The motivation for this came from an old situation I encountered. The base AMIs we were building from already had Docker install. So to get kops working with these AMIs, we would simply uninstall Docker from our AMIs and then just let kops install Docker. 🙄

Even though I personally don't have a use for this right now, I figured that while I was working on #6956 I could do this real quick. Hopefully someone out there in a similar situation finds this useful!

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
Thanks @austinmoore- this looks great, I actually have a use case for this similar to the one you described. 

I'm wondering if instead of adding yet another feature flag `skipInstall`, if there is any way of just leveraging the existing `docker` spec and setting `version` to something like noop to simplify things such as:
```
spec:
  docker:
    version: noop
```

What do you think?

/ok-to-test

**Comment by austinmoore-** [comment]
My personal opinion is that I usually prefer to have the key indicate the operation, rather than a value. It feels more explicit to me that way. In my mind, `docker.version` is unrelated to whether or not kops should install Docker or not. But I don't really have strong feelings one way or the other though, so if simplifying it to just `noop` fits kops' solution pattern better, just let me know I can definitely make that change!

**Comment by chrisz100** [comment]
I would love if people could choose their own docker version here (and noop if none) looking at all the CVE's from the last year. Do you think something getting close to this goal could be doable?

**Comment by austinmoore-** [comment]
I cleaned up those commits. And yes I think it's totally doable. Since there are two voice support for that, I can go ahead and make that change.

So just to confirm the new spec will look like:

```yaml
spec:
  docker:
    version: noop
```

**Comment by austinmoore-** [comment]
@chrisz100 Actually, I might have misread what you said. By specifying your own Docker version are you thinking of something like this: https://github.com/kubernetes/kops/pull/6956

Or were you referring to @rdrgmnzs suggestion?

**Comment by mikesplain** [comment]
Thanks for the ping on this @rdrgmnzs, I agree with everyones comments above. 

A separate `DockerInstallSpec` feels like a bit much for me considering the simplicity of what's being accomplished here, since as you noted, this isn't new behavior, just allowing users to configure it.  

Is there a reason this couldn't just be part of the `DockerConfig` spec? If all of those attributes only drove docker I would say no, but we already have nodeup using the Version attribute.

So I think my preference would be:
```
spec:
  docker:
    skipInstall: true
```

**Comment by austinmoore-** [comment]
The reason I had added a new `DockerInstallSpec` field was because I knew that I would also be implementing https://github.com/kubernetes/kops/pull/6956 which also uses that. But I think 
```spec:
  docker:
    skipInstall: true
```

is a good place for it. So if we go through with this, I think we should also move `overrideSources` from the other PR to `spec.docker`. What do you think?

**Comment by mikesplain** [comment]
Ahh yeah I see, that makes sense but personally, I don't mind having that in `DockerConfig` as well, others may feel more strongly.  Before you move things over, lets confirm that @rdrgmnzs and @chrisz100 agree.  Thanks for the work on this!

**Comment by rdrgmnzs** [comment]
👍 to having everything under `DockerConfig`.

**Comment by austinmoore-** [comment]
@mikesplain @rdrgmnzs How's it look?

**Comment by rdrgmnzs** [comment]
This looks great @austinmoore- ! Thanks you so much for sticking with this and getting it to this point.

/lgtm
/approve

**Pull request merged**
