### PR TITLE
Fixes #2708 broken kubernetes-dashboard due to RBAC

### LINKED ISSUE #2708: Dashboard not correctly configured with for use with RBAC
If I create a new cluster with
```
kops create cluster ... --authorization RBAC
```
And then install the Dashboard with
```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kops/master/addons/kubernetes-dashboard/v1.6.0.yaml
```
Opening the Dashboard reports an error:
```
Unknown Server Error (403)

User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)
```
This looks like it is related to RBAC.

### PR DESCRIPTION
**Pull request by BradErz**
Added cluster role binding which uses the cluster-admin role (updated using https://git.io/kube-dashboard as a template)

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @BradErz - I'll merge on green - or maybe before as I accidentally broke head just before you sent this PR :-)

**Comment by BradErz** [comment]
@justinsb hahah i think it was probally my bad.... i was running an outdated local in the pull request...

**Comment by gianrubio** [comment]
This was already discussed on https://github.com/kubernetes/kops/pull/2789
The conclusion was to not give the full permission to kubernetes-dashboard and just add a note on the [Readme](https://github.com/gianrubio/kops/blob/f330b40e1aa8267f71204a9a77f4e60a2f1c6031/docs/addons.md#rbac)

**Pull request merged**
