### PR TITLE
Version bump coredns to 1.3.1

### PR DESCRIPTION
**Pull request by mikesplain**

### CODE REVIEW

**Comment by rajansandeep** [comment]
/hold
[Till the image is available in gcr.io](https://github.com/kubernetes/kubernetes/issues/72908).

**Comment by mikesplain** [comment]
Good catch, thanks @rajansandeep!

**Comment by chrisz100** [comment]
its there now. 
/lgtm 
/hold cancel

**Comment by neolit123** [comment]
@mikesplain 
please try the `/skip` command later (e.g tomorrow). currently github seems to be dropping hooks and the bots are not triggering the removal of the `pull-kops-e2e-kubernetes-aws`. this job is no longer merge blocking.

**Comment by justinsb** [comment]
So I believe that #6485 moved to coredns 1.3.1, so I'm going to close this one @mikesplain - thanks for the fix though!

**Pull request closed without merging**
