### PR TITLE
Add comment on blocking jobs to actions

### PR DESCRIPTION
**Pull request by mikesplain**
To document the changes in https://github.com/kubernetes/test-infra/pull/17857.

/cc @rifelpet

Holding until that PR merges and make sure it works.
/hold

### CODE REVIEW

**Comment by mikesplain** [comment]
Also FYI, branch protection runs hourly: https://github.com/kubernetes/test-infra/blob/a88f4c8938029faecec901355c78fe58a9c14a14/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L968-L1007

**Comment by rifelpet** [comment]
not sure why tide isn't picking this up...

> Pending - Not mergeable

yet the tide link says it's ready to merge.

**Comment by mikesplain** [comment]
/retest 

I’m not sure either. Status reconciler should update and retest if need be. I’ll look tomorrow and worst case we can revert.

**Comment by mikesplain** [comment]
Close and reopening to re-trigger tests

**Comment by hakman** [comment]
Same thing here https://github.com/kubernetes/kops/pull/9233.

**Comment by hakman** [comment]
@mikesplain I prepared the revert with approval. I just requires the LGTM.

**Pull request merged**
