### PR TITLE
Update aws-load-balancer-controller to v2.3.1

### PR DESCRIPTION
**Pull request by hakman**
Ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.3.1

/cc @olemarkus

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by johngmyers** [comment]
@hakman The kops-aws-load-balancer-controller e2e tests started failing once this landed.

**Comment by johngmyers** [comment]
Looks like this merged despite pull-e2e-kops-aws-load-balancer-controller not passing.

**Comment by rifelpet** [comment]
the [LBC pod logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1471595433733132288/artifacts/cluster-info/kube-system/aws-load-balancer-controller-64dc9bb69d-tnl2p/logs.txt) report missing security group deletion permissions:

`{"level":"error","ts":1639691580.7722676,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"ing-1","namespace":"aws-lb-e2e-a0152d","error":"failed to delete securityGroup: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: 3n3HsA5kZG_f339tN8qrbAG5auaE3BzDCWspmGX9NBW3Vf_4x_XU9bsDYxXLM-ZBHZoz8C708r-K7KwmUaDoKHmDj-izFtPJQ010xGNIW1xFVRN86ofFHNSyrnfRKljPlKJ9UrJFk8g6-dCw4hjVz9bERwUQ7zEgckhf1jn0f7doHnHUR3111LDnhYFGHz9hbs11jCRiFPJ8QmdERsMhPYLkNWsCZ-nGduuPyjZ32XsyF9mhjQqjgGoRrsFT7KVREI_a-hnV7EgGjf5Skgg57Kl_AopM7w9mzNDEflQDj0A6AJYh2NNPdpQTr8en71ndB42LPRXqZrOvMQ6BRMY-PbeTyzlrEJ0rSvTWniIB8Qap_X-uJpVjJGsmxaob4edI0PfXc8y0wTD2ogGyrOdHOG5LiJVcvjDwmLotmlTDcgLYpkh0WERykvMATFSJEP5d8Y2uf0_aM7GFNX7SUP_j-aORjNHGX-iL697iZ5SE4FK23FKqOFRNHR3sD3le77TV72Hc57VGALTCwzTseFRCNLWJxeJoIDlAJVVAeSNxVY28JPpiNRYAEF6GtNGNuab2XW4WTI_y38Ng3DWctzSI8jhl8Zu8J6N6_A6qAi8rsjASnAd9_cqg_q9NWxb4dkTa9t0aObbo59-LKieJvVv89eSyhqVxN-PfSkbbEDCmz3dMVoSop_sVS1tn7UBMZKd9aq6LrQdkmTe-rx-QLg\n\tstatus code: 403, request id: 054a4afd-9bac-4ffb-861a-f2227b34f97b"}`

whereas [prior to the upgrade](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1468696364488593408/artifacts/cluster-info/kube-system/aws-load-balancer-controller-5c84c87d6-k75cv/logs.txt) security groups were successfully being deleted:

`{"level":"info","ts":1639001514.606533,"logger":"controllers.ingress","msg":"deleting securityGroup","securityGroupID":"sg-0ed371e72fbcd8485"}
{"level":"info","ts":1639001535.1458447,"logger":"controllers.ingress","msg":"deleted securityGroup","securityGroupID":"sg-0ed371e72fbcd8485"}
`

**Comment by johngmyers** [comment]
`ec2:DeleteSecurityGroup` is added as a cluster tagged action. Perhaps the new version isn't tagging the security group?

**Comment by johngmyers** [comment]
The "k8s-traffic-*" security group that it creates for the ALB only has `elbv2.k8s.aws/cluster` and `elbv2.k8s.aws/resource` tags on it. It is not tagging it with `KubernetesCluster`.

**Comment by johngmyers** [comment]
Filed kubernetes-sigs/aws-load-balancer-controller#2424

**Pull request merged**
