### PR TITLE
Remove dead code from tasks

### PR DESCRIPTION
**Pull request by johngmyers**
/kind cleanup

### CODE REVIEW

**Comment by hakman** [comment]
Should "upup/pkg/fi/cloudup/awstasks/launchtemplate_fitask.go" be part of the "make codegen" commit?

**Comment by johngmyers** [comment]
launchtemplate_fitask.go isn't actually automatically generated.

**Comment by hakman** [comment]
> launchtemplate_fitask.go isn't actually automatically generated.

Anything that can be done about it, or we should leave it as is?

**Comment by johngmyers** [comment]
It looks like it would be possible to make it autogenerated in a follow-up PR.

**Comment by hakman** [comment]
Cool. Thanks!
/hold cancel

**Pull request merged**
