### PR TITLE
Set Karpenter ttlSecondsAfterEmpty to 5 min

### PR DESCRIPTION
**Pull request by hakman**
/cc @olemarkus @rifelpet

### CODE REVIEW

**Comment by hakman** [comment]
I don't think this helps much with the test failures, so...
/hold

**Comment by rifelpet** [comment]
I dont understand whats going on in these failing tests.

pod: `inline-volume-tester-8f87m`
volume: `pvc-d1fb947e-10e4-4dff-b919-9e7cea7344a7`

EBS CSI controller logs:

`I0702 16:13:21.238077       1 controller.go:102] CreateVolume: called with args {Name:pvc-d1fb947e-10e4-4dff-b919-9e7cea7344a7 CapacityRange:required_bytes:1073741824  VolumeCapabilities:[mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > ] Parameters:map[csi.storage.k8s.io/pv/name:pvc-d1fb947e-10e4-4dff-b919-9e7cea7344a7 csi.storage.k8s.io/pvc/name:inline-volume-tester-8f87m-my-volume-0 csi.storage.k8s.io/pvc/namespace:ephemeral-2270] Secrets:map[] VolumeContentSource:<nil> AccessibilityRequirements:requisite:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"ap-southeast-1a" > > preferred:<segments:<key:"topology.ebs.csi.aws.com/zone" value:"ap-southeast-1a" > >  XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}`

`I0702 16:13:24.603424       1 controller.go:858] successfully created PV pvc-d1fb947e-10e4-4dff-b919-9e7cea7344a7 for PVC inline-volume-tester-8f87m-my-volume-0 and csi volume name vol-0600055a2e636f530`

kube-scheduler logs:

`I0702 16:13:25.875464       9 scheduler.go:351] "Unable to schedule pod; no fit; waiting" pod="ephemeral-2270/inline-volume-tester-8f87m" err="0/9 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 8 node(s) had volume node affinity conflict. preemption: 0/9 nodes are available: 9 Preemption is not helpful for scheduling."`

While we cant see the PV definition itself, the CSI controller log suggests that the volume's affinity was for `topology.ebs.csi.aws.com/zone: ap-southeast-1a` which [all of the nodes](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13938/pull-kops-e2e-aws-karpenter/1543255254311636992/artifacts/cluster-info/nodes.yaml) have

**Comment by olemarkus** [comment]
I would probably do #13918 first. They have fixed some of the node bindings that they did and rely more directly on kube-scheduler.

**Comment by hakman** [comment]
I am using the latest snapshot for Karpenter in this PR, so most likely there are still things broken.

**Comment by olemarkus** [comment]
Short version is: in-tree drivers has affinity on `topology.kubernetes.io/region`

Karpenter does not set this label on node objects, nor does anything else. And so the volume doesn't schedule.
It's at the bottom here: https://karpenter.sh/preview/tasks/scheduling/#persistent-volume-topology

**Comment by hakman** [comment]
Part of #13918 now, so no longer needed.

**Pull request closed without merging**
