### PR TITLE
Remove docker-prestart hook

### PR DESCRIPTION
**Pull request by stevenjm**
This breaks networking if Docker is restarted (https://github.com/kubernetes/kops/issues/6191). Since that issue has not seen any progress since it was raised in December, I am raising a PR with the solution I suggested there.

The Docker issue linked in the hook's comments has been closed for over 3 years, and this workaround has not been used by upstream Kubernetes for over a year:

  https://github.com/kubernetes/kubernetes/commit/5f9735de53c0a7f1334d91b59bcd87c6fbe2a06f#diff-af1d281c3ce49f7bfe110f7c64c96fdc

It therefore seems unlikely that this hook is still necessary.

### CODE REVIEW

**Comment by stevenjm** [comment]
My organisation has signed the CLA. I thought I was on it, but it seems not. I'm working on getting that resolved now.

**Comment by stevenjm** [comment]
I signed it

**Comment by stevenjm** [comment]
I signed it (maybe now it'll work?)

**Comment by stevenjm** [comment]
I signed it (trying again)

**Comment by stevenjm** [comment]
I signed it (one more time)

**Comment by stevenjm** [comment]
I signed it (two more times, I lied)

**Comment by dbyron0** [comment]
I can't say definitively yet, but this feels like it's been the cause of much pain for our kube clusters.  Any chance this can get some attention?

Thanks much.

**Comment by justinsb** [comment]
Technically we should only do this for k8s >= 1.12, but as it seems this has not been needed for so long, I think it's reasonable just to remove it.

Thanks @stevenjm !

/approve
/lgtm

**Pull request merged**
