### PR TITLE
Add flag to disable Basic Auth.

### PR DESCRIPTION
**Pull request by fernandocarletti**
This is an excerpt from @valdisrigdon's PR #4799, Since the source branch was removed and the work in the PR appears to be stopped. It adds a flag to remove the basic authentication as requested on #290.

### CODE REVIEW

**Comment by chrisz100** [comment]
I’ve been waiting for this, thanks! 

/lgtm

**Comment by fernandocarletti** [comment]
@justinsb & @chrisz100 I just rebased it to fix the conflicts. Shall we merge it?

**Comment by chrisz100** [comment]
Good to go from my POV. Unsure if we shouldn't wait for after 1.11 is stable? 
@mikesplain what do you think? 

/lgtm

**Comment by fernandocarletti** [comment]
Just my two cents here, the original PR (https://github.com/kubernetes/kops/pull/4799) was already set to the 1.10 milestone, but due to the abandonment, it wasn't released. Also, RBAC is enabled by default, so I don't think there is anything risky in here, specially when the flag is just to disable it, so by default Basic Auth is still enabled.

**Comment by chrisz100** [comment]
It’s more about the risk of this breaking the application or introducing more bugs. But it’s fine to make 1.11 from my side.

**Comment by justinsb** [comment]
I'm a little uneasy to introduce a flag that deviates from the kubernetes flags, but we can do it and eventually it will just be the default.  (And because these options map to kubernetes flags, which are themselves frequently deprecated / changing, these are considered "power options" anyway)

So: It does make things more secure, and while I'd like to make it the default, this is a good first step.  And by creating the flag, we minimize the risk of breaking anyone.
 
/approve

**Pull request merged**
