### PR TITLE
Bump Cilium to 1.7.1 for k8s 1.12+

### PR DESCRIPTION
**Pull request by errordeveloper**
/assign @olemarkus

xref https://github.com/cilium/cilium/issues/10468

### CODE REVIEW

**Comment by olemarkus** [comment]
There are two other locations in the template that needs updating the version too.

**Comment by errordeveloper** [comment]
Thanks @olemarkus! I've pushed a new commit just now.

**Comment by olemarkus** [comment]
Cool. Looks good

**Comment by justinsb** [comment]
Thanks @errordeveloper  (and @olemarkus for confirming!)

/approve
/lgtm

**Comment by errordeveloper** [comment]
@justinsb thanks!

**Pull request merged**
