### PR TITLE
adding k8s code of conduct

### PR DESCRIPTION
**Pull request by chrislovecnm**
adding the kode of konduct

Fixes this https://github.com/kubernetes/kops/issues/740

### CODE REVIEW

**Comment by kris-nova** [comment]
Should we reference the Kubernetes/Kubernetes CoC? In case it changes (again)?

**Comment by justinsb** [comment]
LGTM.  Merge when you're happy @kris-nova  / @chrislovecnm  :-)

**Comment by chrislovecnm** [comment]
@kris-nova thought about that, but I don't want to reference something that references something.  We need a link checker in our project anyways.... adding link linter

**Comment by kris-nova** [comment]
LGTM

**Comment by kris-nova** [comment]
This means best behavior gentlemen..

**Pull request merged**
