### PR TITLE
pin nvidia-docker2 version to avoid installation failure

### PR DESCRIPTION
**Pull request by adrianlyjak**
https://github.com/kubernetes/kops/issues/6767

### CODE REVIEW

**Comment by geojaz** [comment]
@adrianlyjak thanks for the great bug reporting and solving your own issue- resulting in your first kops contribution! :D 🎉

i think your code should be just fine. but it looks like this would most naturally be 1 commit, absent some CICD struggles. could you please squash and push this back so we can get you merged?
also- bonus points for writing an issue/feature req for an improved or additional test that can find these bugs in advance :)

**Comment by geojaz** [comment]
closes #6767

**Comment by adrianlyjak** [comment]
thanks @geojaz. I removed the crufty commits and the jobs have passed. I'll check out the testing infrastructure and see if I can suggest some tests

**Comment by chrisz100** [comment]
/lgtm
/approve

Thanks for the squash 👍

**Comment by stevenpall** [comment]
We've run into the same issue as described in #6767 and were wondering how this can be deployed currently? Is it part of a release? I see that there was a custom image created (https://github.com/kubernetes/kops/issues/6767#issuecomment-482464513), but I'd rather avoid that if possible.

**Pull request merged**
