### PR TITLE
Update rules go and rules docker

### PR DESCRIPTION
**Pull request by mikesplain**
Doing some testing on this now.

/hold

### CODE REVIEW

**Comment by mikesplain** [comment]
Could be related to See https://github.com/bazelbuild/rules_go/issues/2115

**Comment by chrislovecnm** [comment]
I am running into crossbuild issues right now with some components, in another project.

**Comment by rifelpet** [comment]
curious if the latest bazel update fixes this

/retest

**Comment by mikesplain** [comment]
Just rebased off master, we'll see if @rifelpet's fixes help this.

**Comment by mikesplain** [comment]
Outdated

**Pull request closed without merging**
