### PR TITLE
Avoid concurrent write corruption to /etc/hosts

### PR DESCRIPTION
**Pull request by justinsb**
When we have multiple writers racing to write /etc/hosts, we could
have file corruption where we see a mix of both files.

We can't use a traditional atomic file write, because we are
bind-mounting /etc/hosts.

Instead we write to /etc/hosts, pause, then re-read the contents.  If
the contents don't match, we repeat.  This will not result in fair
queuing, but will avoid corruption.

### CODE REVIEW

**Comment by justinsb** [comment]
Builds on #6885

**Comment by mikesplain** [comment]
Not sure how I removed the lgtm but...
/lgtm

Thanks @justinsb!

**Pull request merged**
