### PR TITLE
First test of a fi.Task

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1096)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Travis did not like that test much

**Comment by justinsb** [comment]
Ah ... that's because it depends on #1092

**Comment by justinsb** [comment]
In other words: this test caught a real problem, the elasticip problem fixed in #1092 (which also fixes other things).  Would be good to try to catch the mistake I made in #1092, but that requires mocking ELB also...

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kops/pull/1092 is in :)

**Comment by chrislovecnm** [comment]
restarted build

**Comment by justinsb** [comment]
Rebased, added licenses to make travis happy.  Now if only we could get a gofmt checker :-)

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
