### PR TITLE
move boot-sequence doc into docs directory

### PR DESCRIPTION
**Pull request by dwradcliffe**
Move this doc to it's proper home :)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-boy ok to test

**Comment by chrislovecnm** [comment]
LGTM

**Comment by chrislovecnm** [comment]
@dwradcliffe really appreciate the PR, more PRs are always appreciated!

**Comment by dwradcliffe** [comment]
@chrislovecnm Thanks! I'm sure there will be more as I keep going :)

**Pull request merged**
