### PR TITLE
Adding support for adding ssh public key from file

### PR DESCRIPTION
**Pull request by mad01**
MVP implementation of adding secret from file related to #2195 

```bash
cat > secret.yaml <<EOF
apiVersion: kops/v1alpha2
kind: SSHSecret
metadata:
  labels:
    kops.k8s.io/cluster: dev.k8s.example.com
spec:
  username: "admin"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EEEAADA dev@devbox"
EOF
```

`kops create -f secret.yaml`

### CODE REVIEW

**Comment by mad01** [comment]
should be good to go. Did a new PR since i broke something in git on the old one. 
/assign @justinsb

**Comment by justinsb** [comment]
Looks good but two thoughts... Not sure if we discussed them on the previous PR or not:

The username isn't used afaict. And it won't do anything so it might just cause confusion. I like the idea, but I'm thinking we add it when we can make it work? Or we could move it out of spec and into status.

SshSecret implies it is secret, but the public key isn't. I'm thinking either SshCredential, or SshKey or ClusterKey because key is ambiguous. Or ClusterSecret, and we put more secrets in the same api object.

Actually though neither of these is significant enough to block the PR, but I wanted to get your thoughts

**Comment by justinsb** [comment]
Flakiness is being tracked in upstream issue: https://github.com/kubernetes/kubernetes/issues/51128, hopefully fixed by https://github.com/kubernetes/kubernetes/pull/51144

**Comment by eparis** [comment]
/retest
merged the referenced fix

**Comment by mad01** [comment]
@justinsb right. It's true it's not actually a secret, your idea of changing the name makes since to something like SshCredential. I rather change it in this PR. 

Do you mean that the username can just be that i set to admin can just me a static string of `admin` in the `AddSSHPublicKey` func in the create.go file?

**Comment by mad01** [comment]
@justinsb update the PR to not use secret, i changed it to SSHCredential. if i understand it correctly the username it static to admin. from my understanding it should be ok for now to set the key in AddSSHPublicKey to `admin` is that correct ?

**Comment by justinsb** [comment]
Thanks @mad01.  On AWS, the SSH public key is currently only set in the user data, and then it is up to the AMI to configure it for whatever account makes sense.  debian uses `admin`, ubuntu uses `ubuntu` etc.  There's no way to configure the username as it is entirely up to the AMI.

The name of the SSH public key as stored by kops is `admin`, but that isn't always the username used (confusingly!)

/lgtm

**Pull request merged**
