### PR TITLE
Update to Calico 2.4.1

### PR DESCRIPTION
**Pull request by tmjd**
- Switch Calico images to be pulled from quay.io

Addresses #3161

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@blakebarnett you mind taking a peek?  I think we are changing the backend for Calico, but you know better than I.

**Comment by chrislovecnm** [comment]
@tmjd you are going to need to update upup/pkg/fi/cloudup/bootstrapchannelbuilder.go as well.  See areound line 406, we version Calico addon.

Also wondering if we should do Cannel and Calico in different PRs or at least different SHA commits.  We would have to revert both if we have problems with one of them.

**Comment by tmjd** [comment]
Thanks for taking a look.  I've updated bootstrapchannelbuilder.go and split out Canal from this PR.  I'll get another PR up with the Canal updates.

@chrislovecnm did you happen to take a look at the issue that I raised also for this update?  The tldr is that the DefaultDeny behavior has changed. I want to make sure that is understood so we can handle it in the appropriate kops manner.

**Comment by blakebarnett** [comment]
The networking backend and the datastore_type are separate.  This is fine, we should update the version regardless of my other changes, I can rebase on this.

**Comment by tmjd** [comment]
#3187 is the PR with updates to Canal (that were split out from this PR).

**Comment by felipejfc** [comment]
Maybe we could merge with this:

https://github.com/kubernetes/kops/pull/3206

**Pull request merged**
