### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by twpayne**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2302)

### CODE REVIEW

**Comment by justinsb** [comment]
This looks good, but sadly we require a CLA for all contributions :-(   The good news is that the same CLA is valid across all the kubernetes projects!

**Comment by twpayne** [comment]
I signed it!

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
Waiting on ci

**Comment by justinsb** [comment]
This is blocked on e2e (which is waiting on "ok to test"); no point running an e2e for a docs change though!  Merging :-)

**Pull request merged**
