### PR TITLE
MVP of templating 

### PR DESCRIPTION
**Pull request by mad01**
MVP implementation of templating to generate cluster.yaml file: related to #2404 implementation is using the `text/template`

```bash
cat > values.yaml <<EOF
clusterName: eu1
kubernetesVersion: 1.7.1
dnsZone: k8s.example.com
awsRegion: eu-west-1
EOF
```

```bash
cat > cluster.tmpl.yaml <<EOF
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
	kops.k8s.io/cluster: {{.clusterName}}.{{.dnsZone}}
  name: nodes
spec:
  image: coreos.com/CoreOS-stable-1409.6.0-hvm
  machineType: m4.large
  maxPrice: "0.5"
  maxSize: 2
  minSize: 15
  role: Node
  rootVolumeSize: 100
  subnets:
  - {{.awsRegion}}a
  - {{.awsRegion}}b
  - {{.awsRegion}}c

EOF
```

running the templating command
```bash
  kops toolbox template \
      --values values.yaml \
      --template cluster.tmpl.yaml \
      --output cluster.yaml
```

output
```bash
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
	kops.k8s.io/cluster: eu1.k8s.example.com
  name: nodes
spec:
  image: coreos.com/CoreOS-stable-1409.6.0-hvm
  machineType: m4.large
  maxPrice: "0.5"
  maxSize: 2
  minSize: 15
  role: Node
  rootVolumeSize: 100
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c
```

### CODE REVIEW

**Comment by zmerlynn** [comment]
Hey, sorry, I thought I could get to this today but haven't had a chance.
/assign justinsb

**Comment by justinsb** [comment]
So I would have said that templating is probably out of scope, but the toolbox is where we do things that we think might be out of scope - it doesn't have the same guarantees that we'll continue to support it and doesn't have the same implication that things are core - although in practice things tend to wither rather than being removed :-)

I am wondering if we should force people to specify the style of templating they want to use.  i.e. either pass a `templatesyntax=go` flag or specify the template using `gotemplate`.  But I think we could add this later...

/lgtm

**Comment by stefancocora** [comment]
> I am wondering if we should force people to specify the style of templating they want to use. i.e. either pass a templatesyntax=go flag or specify the template using gotemplate. But I think we could add this later...

👍 
This should be a feature imho.
Having users specify the style of templating makes things a lot clearer and more specific, removes ambiguity. Reduced ambiguity brings clarity and that is a very important point in my book !

**Pull request merged**
