### PR TITLE
add user agent to openstack api requests

### PR DESCRIPTION
**Pull request by zetaab**

### CODE REVIEW

**Comment by olemarkus** [comment]
/lgtm

This can be quite useful

**Comment by zetaab** [comment]
@olemarkus can you check again, I just modified the names little bit. The problem that we have currently is that some kops component is calling openstack apis quite heavily. We have currently 30 kops clusters in openstack and those makes 1.2M requests in 24 hours against api. The problem is not csi-cinder or openstack cloud controller manager those do have own user agents.

**Pull request merged**
