### PR TITLE
Updating Canal manifests

### LINKED ISSUE #2588: Canal networking needs RBAC support
Canal networking is not functioning in the latest version (1.6) when RBAC is enabled. 
Canal manifest would probably need the same(?) RBAC rules as calico in #2337

### PR DESCRIPTION
**Pull request by heschlie**
Fixes #2588 

- Updated manifests to the latest versions
- Added RBAC to k8s 1.6 manifest

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2635)

### CODE REVIEW

**Comment by heschlie** [comment]
@chrislovecnm I tested against 1.5 and 1.6 to cover both manifests.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
/lgtm

waiting on CI

**Comment by chrislovecnm** [comment]
@heschlie I noticed that flannel image version was not updated :(  Can you PR that?

**Comment by heschlie** [comment]
@chrislovecnm Flannel looks to be at the latest stable, I can update to the latest RC `v0.8.0-rc1` if you would like.

**Comment by chrislovecnm** [comment]
You know Canal better to me :)  Just noticed that our Flannel manifest version is different from Flannel used in Canal.

**Comment by heschlie** [comment]
Ah I see now, let me double check that what I put in is sane with someone more familiar with Flannel, I'll update if need be, thanks for the catch :)

**Pull request merged**
