### PR TITLE
channels: accept -f and --files

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2336)

### CODE REVIEW

**Comment by kenden** [comment]
Wouldn't `--filename`, not `--files` be better, to match `kops create`, `kops replace`, `kubectl create`.... ?

**Comment by chrislovecnm** [comment]
@justinsb --filename does match kubectl :)

**Comment by justinsb** [comment]
Thank you @kenden & @chrislovecnm  - nice catch!

**Pull request merged**
