### PR TITLE
Run scenarios as presubmit tests

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by olemarkus** [comment]
@johngmyers @rifelpet this should allow us to define presubmits of all the scenarios

**Comment by olemarkus** [comment]
Node that this failing test is not related to this PR.

**Review by rifelpet — APPROVED** [review]

**Comment by olemarkus** [comment]
I guess I cannot just stop that test. But #11811 should fix this, I think.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
