### PR TITLE
WIP: Use bootstrap kubeconfig in 1.9

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Punting this to 1.10

**Comment by KashifSaadat** [comment]
Hey @justinsb, just wondering if you've had any more luck with this? Would be awesome to have for 1.10 :)

**Comment by techdragon** [comment]
/remove lifecycle-rotten

Theres lots of references to this.

**Comment by techdragon** [comment]
/remove-lifecycle rotten

There are references to this in other issue activity, so it doesn't seem to truly be stale/rotten.

**Comment by justinsb** [comment]
Functionality implemented (better) in #5253 - closing

**Pull request closed without merging**
