### PR TITLE
Kubelet API RBAC Manifest

### PR DESCRIPTION
**Pull request by gambol99**
I was mistaken how the key in the namespace is used, looks like you can only have the one key per addon as the anonnotations on the namespace are addon_name -> version, so if you already have a old rbac.addons.k8s.io referenced it won't work. I didn't notice before as the cluster was new.

```shell
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    addons.k8s.io/core.addons.k8s.io: '{"version":"1.4.0","channel":"s3://bucket/path/addons/bootstrap-channel.yaml"}'
    addons.k8s.io/coredns.addons.k8s.io: '{"version":"1.2.6-kops.1","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.6"}'
    addons.k8s.io/dns-controller.addons.k8s.io: '{"version":"1.11.0-alpha.1","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.6"}'
    addons.k8s.io/kube-dns.addons.k8s.io: '{"version":"1.14.10","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.6"}'
    addons.k8s.io/limit-range.addons.k8s.io: '{"version":"1.5.0","channel":"s3://bucket/path/addons/bootstrap-channel.yaml"}'
    addons.k8s.io/networking.projectcalico.org.canal: '{"version":"3.3.0-kops.1","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.12"}'
    addons.k8s.io/node-authorizer.addons.k8s.io: '{"version":"v0.0.4","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.10.yaml"}'
    addons.k8s.io/podsecuritypolicy.addons.k8s.io: '{"version":"0.0.4","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.10"}'
    addons.k8s.io/rbac.addons.k8s.io: '{"version":"v0.0.1","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"k8s-1.8"}'
    addons.k8s.io/storage-aws.addons.k8s.io: '{"version":"1.7.0","channel":"s3://bucket/path/addons/bootstrap-channel.yaml","id":"v1.7.0"}'                                                                                                    
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"kube-system","namespace":""}}
  creationTimestamp: 2017-09-07T12:33:35Z

### CODE REVIEW

**Comment by gambol99** [comment]
@KashifSaadat

**Comment by KashifSaadat** [comment]
Ah completely missed that! Change LG thanks for fixing, will wait for the tests to report clean.

**Pull request merged**
