### PR TITLE
Update Karpenter template to v0.27.3

### PR DESCRIPTION
**Pull request by ltellesfl**
It has been a while since the Karpenter template has been updated, missing a lot of changes and bugfixes. This change is to use Karpenter version 0.27.3 (currently the latest).

### CODE REVIEW

**Comment by ltellesfl** [comment]
Any updates?

**Comment by hakman** [comment]
> Any updates?

Please see https://github.com/kubernetes/kops/pull/15144. Once that is merged, we can look at this patch release. Thanks!

**Comment by ltellesfl** [comment]
Oh thanks, that PR will cover most of the changes I did, after the merge I take another look at this one.

**Comment by hakman** [comment]
@ltellesfl We are merging https://github.com/kubernetes/kops/pull/15144, which is very close to this.
Please check if there's anything else needed here one it merges.

**Comment by ltellesfl** [comment]
That's good for now, thanks @hakman. I'm closing this PR

**Comment by ltellesfl** [comment]
https://github.com/kubernetes/kops/pull/15144

**Pull request closed without merging**
