### PR TITLE
Controller Manager Flag

### PR DESCRIPTION
**Pull request by gambol99**
- adding the controller manager flag as this default to bootstrapsigner, tokencleaner disabled

### CODE REVIEW

**Comment by KashifSaadat** [comment]
/lgtm

Cheers @gambol99

**Comment by gambol99** [comment]
@KashifSaadat ... I'm just double checking if this is a e2e error or a error I've introduced ..

**Comment by gambol99** [comment]
```shell
$ kubectl get no
NAME                                           STATUS    ROLES     AGE       VERSION
ip-10-250-100-229.eu-west-2.compute.internal   Ready     node      1m        v1.10.3
ip-10-250-101-77.eu-west-2.compute.internal    Ready     node      1m        v1.10.3
ip-10-250-31-15.eu-west-2.compute.internal     Ready     master    3m        v1.10.3
ip-10-250-32-151.eu-west-2.compute.internal    Ready     master    3m        v1.10.3
ip-10-250-33-83.eu-west-2.compute.internal     Ready     master    3m        v1.10.3
```
ok .. i'm guessing an e2e issue .. rerunning tests

**Pull request merged**
