### PR TITLE
kops toolbox template: sort formatted YAML output

### PR DESCRIPTION
**Pull request by lwf**
Sort by kind to have Cluster objects appear first in output if --format-yaml is specified. This is desirable since other objects (like InstanceGroups) will typically reference Cluster objects.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
If you could sign the CLA that would be awesome!

**Comment by justinsb** [comment]
I'd love to accept this PR if you're able to sign the CLA @lwf - are you able to sign it?  It's a bit of a pain the first time, but the same CLA is then used for contributions across the entire kubernetes ecosystem (i.e. it's not just for kops!)

**Comment by lwf** [comment]
Hey @justinsb, I've been waiting for my employer's legal department to get back on signing the CNCF CLA. Seeing as it's taking a bit of time maybe you'd be better of reimplementing this (it's trivial anyway).

**Pull request closed without merging**
