### PR TITLE
Update resource tracking test scenario

### PR DESCRIPTION
**Pull request by hakman**
Not sure if this test is still useful, but updating it to not fail.

/cc @olemarkus @johngmyers

### CODE REVIEW

**Comment by olemarkus** [comment]
We still need this one. It's how we detect that channels correctly prune stuff.

**Comment by hakman** [comment]
> We still need this one. It's how we detect that channels correctly prune stuff.

It's stuck in k8s & kOps 1.21. Not very useful.

**Comment by olemarkus** [comment]
It starts with those versions, yes. But it upgrades to latest kops. I think  it's fine to move the k8s target at the lowest supported k8s version.

**Comment by hakman** [comment]
Missed the `kops-acquire-latest` call...

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
