### PR TITLE
tweaking protokube perms

### PR DESCRIPTION
**Pull request by chrislovecnm**
Removing `--privileged` and using `SYS_ADMIN` .... not much difference, but lets see if this works.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/retest 

Will need to test this on my own, we may need some dev mounts

**Comment by justinsb** [comment]
What are we trying to do here?

**Comment by chrislovecnm** [comment]
Trying to not run protokube with the evil `--priveledged` .... and failing :)  Have not dug into it much.

**Comment by chrislovecnm** [comment]
closing as this does not work

**Pull request closed without merging**
