### PR TITLE
Add doc for our approach to dependencies

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
What about godeps or glide?

**Comment by justinsb** [comment]
@chrislovecnm  They break down with vendored deps that include vendor directories.  Have you tried them? :-)  Perhaps they are better now, but we do now have something that works.

@kris-nova can you try joining the k8s org https://github.com/orgs/kubernetes/people  ?  I'm not sure how you do that though, but it looks like I can't add you to the reviewer list until I've done that.

**Comment by chrislovecnm** [comment]
@justinsb we are in the middle of selecting a deps tool for Dualspak/Datapipe. Will let you know how it goes. Both seems decent.

**Comment by chrislovecnm** [comment]
Will merge this and open an issue

**Pull request merged**
