### PR TITLE
Add service account for elasticsearch and fluentd

### PR DESCRIPTION
**Pull request by thoslin**
Fix issue https://github.com/kubernetes/kops/issues/3729

### CODE REVIEW

**Comment by thoslin** [comment]
The CNCF CLA is signed

**Comment by thoslin** [comment]
@chrislovecnm right. the version should be incremented. I checked the api version. rbac.authorization.k8s.io/v1beta1 is supported as of v1.6.0. I'm gonna update the version number to v1.6.0.

**Comment by thoslin** [comment]
Sorry. My mistake. Added a separate manifest for 1.6.
Please check again. Thanks!

**Comment by justinsb** [comment]
/retest

/lgtm

Thanks @thoslin !

**Pull request merged**
