### PR TITLE
bumping weave version

### PR DESCRIPTION
**Pull request by chrislovecnm**
bumped weave to 1.8.1

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1021)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
IT IS ALIVE!!

```console
$ kubectl -n kube-system get ds weave-net -o yaml
```

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"DaemonSet","apiVersion":"extensions/v1beta1","metadata":{"name":"weave-net","namespace":"kube-system","creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"weave-net"},"annotations":{"scheduler.alpha.kubernetes.io/tolerations":"[\n  {\n    \"key\":
      \"dedicated\",\n    \"operator\": \"Equal\",\n    \"value\": \"master\",\n    \"effect\":
      \"NoSchedule\"\n  }\n]\n"}},"spec":{"volumes":[{"name":"weavedb","emptyDir":{}},{"name":"cni-bin","hostPath":{"path":"/opt"}},{"name":"cni-bin2","hostPath":{"path":"/home"}},{"name":"cni-conf","hostPath":{"path":"/etc"}}],"containers":[{"name":"weave","image":"weaveworks/weave-kube:1.8.1","command":["/home/weave/launch.sh"],"resources":{"requests":{"cpu":"10m"}},"volumeMounts":[{"name":"weavedb","mountPath":"/weavedb"},{"name":"cni-bin","mountPath":"/opt"},{"name":"cni-bin2","mountPath":"/host_home"},{"name":"cni-conf","mountPath":"/etc"}],"livenessProbe":{"httpGet":{"path":"/status","port":6784,"host":"127.0.0.1"},"initialDelaySeconds":30},"securityContext":{"privileged":true}},{"name":"weave-npc","image":"weaveworks/weave-npc:1.8.1","resources":{"requests":{"cpu":"10m"}},"securityContext":{"privileged":true}}],"restartPolicy":"Always","hostNetwork":true,"hostPID":true}}},"status":{"currentNumberScheduled":0,"numberMisscheduled":0,"desiredNumberScheduled":0}}'
  creationTimestamp: 2016-12-02T02:35:37Z
  generation: 1
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
  resourceVersion: "258"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/weave-net
  uid: 02124bda-b838-11e6-a9d1-0a3e6fc76af3
spec:
  selector:
    matchLabels:
      name: weave-net
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "dedicated",
              "operator": "Equal",
              "value": "master",
              "effect": "NoSchedule"
            }
          ]
      creationTimestamp: null
      labels:
        name: weave-net
    spec:
      containers:
      - command:
        - /home/weave/launch.sh
        image: weaveworks/weave-kube:1.8.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /status
            port: 6784
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: weave
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /weavedb
          name: weavedb
        - mountPath: /opt
          name: cni-bin
        - mountPath: /host_home
          name: cni-bin2
        - mountPath: /etc
          name: cni-conf
      - image: weaveworks/weave-npc:1.8.1
        imagePullPolicy: IfNotPresent
        name: weave-npc
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: weavedb
      - hostPath:
          path: /opt
        name: cni-bin
      - hostPath:
          path: /home
        name: cni-bin2
      - hostPath:
          path: /etc
        name: cni-conf
status:
  currentNumberScheduled: 6
  desiredNumberScheduled: 6
  numberMisscheduled: 0
```

**Comment by brandoncole** [comment]
I verified that the weave-daemonset.yaml files have no changes other than the container version so this should be good.

**Comment by kris-nova** [comment]
LGTM - thanks for the review @brandoncole

**Comment by kris-nova** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kops/1021)*

**Pull request merged**
