### PR TITLE
Bumping calico for bugfixes.

### PR DESCRIPTION
**Pull request by michalschott**
Bump mainly for bug fixes:
* https://github.com/projectcalico/cni-plugin/pull/716
* https://github.com/projectcalico/node/pull/166
* https://github.com/projectcalico/libcalico-go/pull/1050
* https://github.com/projectcalico/libcalico-go/pull/1032
* https://github.com/projectcalico/node/pull/133
* https://github.com/projectcalico/confd/pull/204

### CODE REVIEW

**Comment by michalschott** [comment]
@mikesplain Done, force-pushed update.

**Comment by michalschott** [comment]
Not quite familiar with kops E2E test, any ideas what might be causing this timeouts?

I've successfully deployed these versions to my clusters.

**Comment by mikesplain** [comment]
I'm going to open cherry-picks for this as well for the upcoming releases.

**Comment by michalschott** [comment]
What about 1.12? Will it be picked up automatically due to version bump in https://github.com/kubernetes/kops/blob/3b0af771e88e236bab51bdc7390dd2c370b95ad3/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L828 ?

**Comment by mikesplain** [comment]
@michalschott Most likely this won't make it into a 1.12 release unless theres a security vulnerability.  We're pretty close to a kops 1.13 and 1.14 release so ensuring those are well prepared are our priority at the moment.

**Comment by michalschott** [comment]
Looks like calico was bumped to 3.7.2 in master, no longer needed.

**Comment by michalschott** [comment]
According to https://www.projectcalico.org/security-bulletins/ 3.7.2 is affected with security issue, might be worth to do upgrade again.

**Pull request closed without merging**
