### PR TITLE
Add (proposed) roadmap for etcd

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
cc @jpbetz

**Comment by blakebarnett** [comment]
Looks great

**Comment by robinpercy** [comment]
+1 /lgtm

**Comment by chrislovecnm** [comment]
Odd that Robins lgtm did not work

/lgtm

It may need to be on its own line.

**Pull request merged**
