### PR TITLE
Don't use PublicJWKS in TestAWSLBController

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by olemarkus** [comment]
Thanks for this. The name of the PR/commit perhaps does not reflect the test actually being changed?

**Comment by johngmyers** [comment]
@olemarkus fixed

**Review by olemarkus — APPROVED** [review]

**Comment by johngmyers** [comment]
@olemarkus one more fix...

**Comment by johngmyers** [comment]
@olemarkus I think my second commit and your approval raced. Prow seems to have taken the approval.

**Pull request merged**
