### PR TITLE
Override Docker download URL

### PR DESCRIPTION
**Pull request by austinmoore-**
Allows users to specify where to download Docker with a new `spec.dockerInstall.overrideSources` spec. See the added [docs](https://github.com/austinmoore-/kops/blob/eea95c26eaf75af9b5a597f378f6ecd89d5c1dbe/docs/cluster_spec.md#source-overrides) for details on how to use it.

This is effectively a way to override the built in [dockerVersions](https://github.com/austinmoore-/kops/blob/eea95c26eaf75af9b5a597f378f6ecd89d5c1dbe/nodeup/pkg/model/docker.go#L89) slice and specify your own. This provides a nice escape hatch if you cannot download from external repos and must use internal mirrors (as in my company's situation). Ideally this would just be a url and hash. However, some packages have dependencies that need to be specified and other packages need to be installed simultaneously with other packages.

There are some considerations to keep in mind with this feature. This solution isn't the most intuitive for a user because the user will probably just end up looking at `dockerVersions` to find their OS and Docker version. If the user changes their OS or Docker version, this might cause problems if they forget to update this configuration. I'm open to ideas on how to handle these situations.

I think this might be a stop-gap measure for a more robust solution. For example, in the future it might be better to provide a way to override the base download URL like we do for some other resources. I didn't do this because I figured it was better to expose full control for something like this. I also wasn't sure if we need to consider mirrored repos that do not have the same path (not sure how common this would be).

Another option could be to allow a way to externalize the data in `dockerVersions` to a YAML file in S3 as part of the cluster that the user could then edit or specify.

### CODE REVIEW

**Comment by michaelajr** [comment]
Hi. Hoping this can get looked at, tested, and merged. We really need this as we can not download Docker from the public repo. Thanks!

**Comment by selslack** [comment]
@justinsb @robinpercy @rdrgmnzs please take a look at the PR.

**Comment by Nitecon** [comment]
This looks good and would be nice to have!

**Comment by selslack** [comment]
@justinsb @robinpercy @rdrgmnzs is there anything needs to be done from the community to get this PR merged?

**Comment by austinmoore-** [comment]
Removed `DockerInstallSpec` per [this discussion](https://github.com/kubernetes/kops/pull/6957#issuecomment-531346820).

**Comment by michaelajr** [comment]
Any chance this will make it into the next release? @rdrgmnzs

**Comment by austinmoore-** [comment]
Rebased on to master

**Comment by austinmoore-** [comment]
Rebased onto master

**Comment by michaelajr** [comment]
@rdrgmnzs @chrisz100 @granular-ryanbonham hoping to get this merged for the next release. Can you (or someone) take a look? This is a needed feature for my workplace.

**Comment by austinmoore-** [comment]
/hold

Reconsidering this, because it doesn't handle instance groups

**Comment by austinmoore-** [comment]
Closing in favor of #7974.

**Pull request closed without merging**
