### PR TITLE
Fix typos in create cluster docs

### PR DESCRIPTION
**Pull request by benhartley**
Just a couple of minor typo fixes in `create cluster` docs

Replaces kubernetes/kops#2927

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Thanks for you PR!

@benhartley can you run `make gen-cli-docs` and push the md files as well please.  That is why ci is failing.  For future reference you can run `make ci` to test ci locally.

/ok-to-test

**Comment by benhartley** [comment]
Thanks for you patience. I have now run `gen-cli-docs` and `ci` locally.

**Comment by chrislovecnm** [comment]
No worries, we need to get a template for those docs, so that people know to update the code ;)

**Comment by justinsb** [comment]
Thanks @benhartley !

**Pull request merged**
