### PR TITLE
Add verbosity

### PR DESCRIPTION
**Pull request by mikesplain**
Add some verbosity to bazel builds.

Includes some python changes from #7508

### CODE REVIEW

**Comment by mikesplain** [comment]
Stamp was also deprecated

**Comment by rifelpet** [comment]
I think --stamp was needed based on https://github.com/kubernetes/kops/pull/7493#issuecomment-526837120

**Comment by mikesplain** [comment]
Good catch, that was a different stamp that was deprecated I think. I'll leave as is for now.

**Pull request merged**
