### PR TITLE
Copy dnsprovider into our code, implement route53 batching

### LINKED ISSUE #3121: DNS-Controller hitting AWS changeset limit after 1.7 upgrade
Hi,

I tried rolling my cluster from 1.6.4 to 1.7.2 with kops 1.7.0 an hour ago or so, starting with 2 out of my 3 masters. I noticed that after doing this my kubectl commands were becoming very slow, something that in the past had been a symptom of the api.* records in Route53 being incorrect. Checking them indeed showed that the new IP's had not been recorded. 
Next suspect was a faulty DNS-Controller, but I saw it had been updated to v1.7.1 and had started correctly. The logs however do show something interesting: it is trying to replace all my record sets with new IP's. This is already a first bug I believe, since the only change were my masters there should be no changes to my records, as those only include nodes? 
Besides that, it seems that the amount of nodes times the amount of records I have, exceeds the AWS limit. This causes the following error: 
```
I0802 15:02:52.300886       1 dnscontroller.go:301] applying DNS changeset for zone example.com.::Z30ETTSQ28ABDA
W0802 15:02:52.648670       1 dnscontroller.go:303] error applying DNS changeset for zone example.com.::Z30ETTSQ28ABDA: InvalidChangeBatch: Number of records limit of 1000 exceeded.
	status code: 400, request id: a8247983-7793-11e7-96b3-7d2348af7e8f
W0802 15:02:52.648712       1 dnscontroller.go:119] Unexpected error in DNS controller, will retry: error applying DNS changeset for zone example.com.::Z30ETTSQ28ABDA: InvalidChangeBatch: Number of records limit of 1000 exceeded.
```
So none of my records are being updated currently. Rolling dns-controller back to 1.6.1 has the same issue, I presume I just never had this many records to be changed before...

### PR DESCRIPTION
**Pull request by justinsb**
Fixes #3121

### CODE REVIEW

**Comment by justinsb** [comment]
Marked for 1.9, not going in to 1.8

**Comment by egeland** [comment]
The sooner we get this, the better!

**Pull request merged**
