### PR TITLE
gce: Set labels on ForwardingRules

### PR DESCRIPTION
**Pull request by justinsb**
We add the cluster-name label, now that labels are supported on
ForwardingRules.

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by justinsb** [comment]
Both look like dns lookup errors; unrelated (?)

/retest

**Comment by justinsb** [comment]
Looks like we can't set labels on creation, which is ... annoying.  Added code to set them explicitly immediately after creation.

**Comment by hakman** [comment]
> Looks like we can't set labels on creation, which is ... annoying. Added code to set them explicitly immediately after creation.

Pretty annoying also that you have to re-read the resource. Would be nice to at least return the fingerprint as part of the result of the create.

**Comment by justinsb** [comment]
> Pretty annoying also that you have to re-read the resource. 

Agreed, and technically we can get it from the operation, it's just a pain to do so.

**Review by hakman — APPROVED** [review]

**Pull request merged**
