### PR TITLE
Dont generate the ssl_certificate_id field on TCP listeners in Terraform

### PR DESCRIPTION
**Pull request by rifelpet**

### CODE REVIEW

**Comment by justinsb** [comment]
I'm guessing terraform gives an error?

Code lgtm!

/approve
/lgtm

/hold just to give others time to comment, but feel free to remove the hold

**Comment by rifelpet** [comment]
no error, it's just unnecessary. we do have the `pull-kops-verify-terraform` job that validates our integration test .tf files and it is (still) passing.

**Pull request merged**
