### PR TITLE
Automated cherry pick of #7566: Update DO objects to use tags

### PR DESCRIPTION
**Pull request by mikesplain**
Cherry pick of #7566 on release-1.14.

#7566: Update DO objects to use tags

### CODE REVIEW

**Comment by rifelpet** [comment]
hm based on the travis error I'm wondering if there was a vendoring update that this depends on but wasnt backported to 1.14?

**Comment by rifelpet** [comment]
Yes, i believe #7467 needs to be cherry-picked to 1.14 first before this will build

**Comment by mikesplain** [comment]
Ahh yes, thanks @rifelpet! Opened https://github.com/kubernetes/kops/pull/7635

**Pull request closed without merging**
