### PR TITLE
fix-pkg-staticcheck and remove the repeat code

### PR DESCRIPTION
**Pull request by tanjunchen**
1：remove some repeat code 
2：fix some staticcheck

### CODE REVIEW

**Comment by johngmyers** [comment]
I don't quite see the value of removing the unreferenced convenience functions. I think it would make sense to either consolidate the convenience functions to just the ones in `fi` or just leave them alone.

**Comment by tanjunchen** [comment]
@johngmyers Thanks your view.
1:Maybe you can refer to the issue https://github.com/kubernetes/kubernetes/issues/81657
2:And we need to delete unused code because of golang rules(recommend to do this)

**Comment by tanjunchen** [comment]
@rifelpet The Same Question

**Comment by justinsb** [comment]
I'd say if there is a linter that is reliable that we can use, I am in favor of more static analysis to help us in code review.  We've started using hack/verify-staticcheck.sh (albeit with a lot of excluded packages right now)

While in general I agree with @johngmyers that if we have two functions i32 and i64, and we stop using i64, then we shouldn't necessarily rush to delete i64.  But I do think that having static checkers helping us avoid mistakes is possibly more important.  I think @johngmyers raises an excellent point though, in that we could also put these into a helper package.  (Unfortunately `fi` has become a bit big, so we started `pkg/values`)

So I'm in favor of this PR, in that if we can get `hack/verify-staticcheck.sh` checking all our code, it should save us a lot of time in code review.  I _personally_ think some of the rules are not what I would have chosen, but having a set of rules will save us a lot of time.  (It's the same as the `gofmt` argument: not perfect, but at least we don't have to debate tabs vs spaces)

/approve
/lgtm

**Pull request merged**
