### PR TITLE
Automated cherry pick of #7992: Add CloudControllerConfigArgv template function, Expose

### PR DESCRIPTION
**Pull request by DavidSie**
Cherry pick of #7992 on release-1.17.

#7992: Add CloudControllerConfigArgv template function, Expose

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by geojaz** [comment]
/needs-ok-to-test
but looks like it needs some other attention as well

**Comment by DavidSie** [comment]
@geojaz  please take a look. Also please take a look at this pr: https://github.com/kubernetes/kops/pull/8077 since they are both adding the same feature to existing releases.

**Comment by DavidSie** [comment]
@zetaab  pls take  a look.

**Comment by DavidSie** [comment]
@geojaz imho it can be merged.

**Pull request merged**
