### PR TITLE
Remove duplicated and outdated docs

### LINKED ISSUE #6414: docs/index.md bad link and outdated feature matrix
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
N/A
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
N/A
**3. What cloud provider are you using?**
N/A
**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Reading docs/index.md

**5. What happened after the commands executed?**

1. when I clicked on link 'To check out Live documentation' I got a 404 error
2. In the doc the compatibility matrix needs to be updated 

**6. What did you expect to happen?**
no 404
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
N/A
**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
N/A
**9. Anything else do we need to know?**

### PR DESCRIPTION
**Pull request by gtrafimenkov**
- remove outdated docs/index.md which was a copy of README.md
- remove not working command `make live-docs`, `make build-docs`

This PR fixes #6414

This PR reverts most of the changes done in https://github.com/kubernetes/kops/pull/5085.

### CODE REVIEW

**Comment by justinsb** [comment]
I would really like to get these docs working though!  The current doc generation is using some apimachinery that is complicated and basically unmaintained, and #5085 had a lot of promise as being much easier and more maintainable - it's what nginx-ingress uses.

**Comment by gtrafimenkov** [comment]
> #5085 had a lot of promise as being much easier and more maintainable

@justinsb I looks like that promise didn't materialized: https://kubernetes.github.io/kops/ gives 404

**Pull request closed without merging**
