### PR TITLE
Add kubetest2-kops template for testing dedicated APIServer nodes

### PR DESCRIPTION
**Pull request by rifelpet**
depends on https://github.com/kubernetes/test-infra/pull/23755

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by rifelpet** [comment]
unrelated, checking if we're still seeing issues with this:
/test pull-kops-verify-terraform

**Comment by rifelpet** [comment]
The test failures are known and unrelated to apiserver. We can see the new api-server node in the e2e job's [artifacts](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12428/pull-kops-e2e-aws-apiserver-nodes/1442495036418691072/artifacts/cluster-info/nodes.yaml).

This is ready for review

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
