### PR TITLE
implement router interface task for OpenStack platform

### PR DESCRIPTION
**Pull request by zengchen1024**
Router interface will attach a subnet to a router.

This is part of work of issue (#3566)

### CODE REVIEW

**Comment by zetaab** [comment]
@zengchen1024 could you fix that bazel thing `./hack/update-bazel.sh`

**Comment by justinsb** [comment]
Thanks @zengchen1024  - I think this just needs a `git fetch origin && git rebase origin/master && hack/update-bazel.sh` (I tried it and hack/verify-bazel.sh then worked for me).

/approve
/lgtm

(Though it won't actually merge until verify-bazel is happy)

**Comment by justinsb** [comment]
Going to force-merge this one and just fix up the bazel in a quick follow-on PR

**Comment by zengchen1024** [comment]
@justinsb sorry to reply to you so late. I saw your comment 2 days ago. I am trying to fix this pr now, but i see you have done it for me. Thanks very much!

**Pull request merged**
