### PR TITLE
Fix rendering of the Node Authorizer template

### PR DESCRIPTION
**Pull request by KashifSaadat**

### CODE REVIEW

**Comment by KashifSaadat** [comment]
On master the Node Authorizer template currently renders as the following which is invalid and cannot be applied:
```yml
{}

---

apiVersion: v1
kind: ServiceAccount
...
```

**Comment by rifelpet** [comment]
/lgtm

This template hasn't changed recently, should this get backported to 1.15 as well?

**Comment by KashifSaadat** [comment]
Thanks! Yes it would be good to backport to v1.15 also.

**Comment by KashifSaadat** [comment]
Cherry-pick for v1.15: #8288

**Pull request merged**
