### PR TITLE
WIP: Update to go 1.13.4

### PR DESCRIPTION
**Pull request by justinsb**
Matching the go version for kubernetes 1.17

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks @justinsb!

/lgtm
/approve

**Comment by mikesplain** [comment]
Actually, looks like @rifelpet may have beat you on this one #7973 

/hold

**Comment by mikesplain** [comment]
I'm fine with either but marking this as hold until we decide which PR!

**Comment by justinsb** [comment]
We should definitely do @rifelpet 's.  I will mark this as WIP, then rebase and make sure it is covered (looks like he did a more complete job than I did anyway, but might as well double-check)

**Comment by justinsb** [comment]
All done in  #7973 - thanks @rifelpet !

/close

**Pull request closed without merging**
