### PR TITLE
Cleanup get command

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2311)

### CODE REVIEW

**Comment by justinsb** [comment]
This isn't terribly important, but is another cleanup that just improves our code a bit.  I was originally going to embed `channels` into kops, but I realize we should probably not do that until channels is more fully baked.

**Comment by chrislovecnm** [comment]
Can we mark this as for 1.7?

**Comment by chrislovecnm** [comment]
Needs a rebase.  Do we want this in 1.6?

**Comment by chrislovecnm** [comment]
/lgtm

waiting on ci

**Pull request merged**
