### PR TITLE
Update tolerations in Canal spec so the pods can run on all nodes.

### PR DESCRIPTION
**Pull request by KashifSaadat**

### CODE REVIEW

**Comment by KashifSaadat** [comment]
/assign @chrislovecnm @gambol99 

Apologies I missed this out in my earlier PR :(

**Comment by gambol99** [comment]
LGTM

**Comment by chrislovecnm** [comment]
@KashifSaadat do the other providers have this as well??

**Comment by KashifSaadat** [comment]
@chrislovecnm yeah, I brought this over from the working 1.6 policy (Calico v2.4.1).

**Pull request merged**
