### PR TITLE
Automated cherry pick of #11709: Add proxy envs to calico to make possible usage of AWS source

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #11709 on release-1.21.

#11709: Add proxy envs to calico to make possible usage of AWS source

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by johngmyers** [comment]
This looks like a feature. Why should it go into 1.21 branch?

**Comment by hakman** [comment]
To me seems more like a bug, as it used to work before removing k8s-ec2-srcdst.

**Review by johngmyers — APPROVED** [review]
/hold cancel

**Pull request merged**
