### PR TITLE
Use short service name with discovery labels

### PR DESCRIPTION
**Pull request by hakman**
Closes https://github.com/kubernetes/kops/issues/14759
Ref https://github.com/kubernetes/kops/issues/14877

/cc @olemarkus @johngmyers

### CODE REVIEW

**Comment by johngmyers** [comment]
Could this perhaps break upgrade of a cilium-etcd cluster?

**Comment by hakman** [comment]
> Could this perhaps break upgrade of a cilium-etcd cluster?

You mean with dedicated API servers? That is still experimental, so no expectations there. Also, the current DNS names for the etcd clusters are not quite right without the `.internal.` part.

**Comment by johngmyers** [comment]
I was wondering about cilium-etcd without apiserver nodes. We don't appear to have an upgrade test for that. I haven't researched the details; I'd like @olemarkus to give his opinion on the upgrade implications of changing those DNS names.

**Comment by hakman** [comment]
The DNS names for the etcd clusters are only used when the apiserver nodes feature is enabled. Other than that, DNS names remain the same, so any upgrades should work just fine.
https://github.com/kubernetes/kops/blob/4cf5418eb83f5aa29e22caae1bc39fb1e7b9da7b/pkg/model/components/kopscontroller/template_functions.go#L87-L104

**Review by johngmyers — APPROVED** [review]
Okay, it's fine for apiserver-node clusters to have a disruptive upgrade

**Pull request merged**
