### PR TITLE
WIP use AWS LBC to create the API server load balancer

### PR DESCRIPTION
**Pull request by olemarkus**
Just testing if this is feasible at all.
LBC can do IP targeting and may work on IPv6-only networks. This makes a few addons non-optional though.

### CODE REVIEW

**Comment by johngmyers** [comment]
I'm not sure we necessarily want to pull in LBC for this. We could have kops-controller update the IP-based targets.

**Comment by olemarkus** [comment]
Yeah not sure either.
At first I was thinking of using protokube actually, but the complexity of handling and cleaning up targets is not insignificant. Hence LBC.

**Comment by johngmyers** [comment]
I don't think it has to be in protokube. The node would presumably be able to come up enough to run kops-controller before it needs to be made a target of the load balancer. But getting all the dependencies of LBC up before the control plane is healthy could be a challenge.

**Pull request closed without merging**
