### PR TITLE
nodeup: Add docker.service dep to LoadImageTask

### LINKED ISSUE #685: Problem with custom docker images
From slack...

I tracked something down on my local setup. `kube-apisever` isn't even coming up on the master. It looks like the `docker load` isn't actually firing, because I'm seeing e.g.
```I1018 17:41:06.983607     694 load_image.go:59] running command docker load -i /var/cache/nodeup/sha1:e80d29cb3ee70426fb2a4940c662ee544678b656_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-scheduler_tar
I1018 17:41:10.956744     694 files.go:115] Hash matched for "/var/cache/nodeup/sha1:e72207e65b8b56fe681dfc9b10e81daf6b564ef0_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-controller-manager_tar": sha1:e72207e65b8b56fe681dfc9b10e81daf6b564ef0
I1018 17:41:10.956997     694 load_image.go:59] running command docker load -i /var/cache/nodeup/sha1:e72207e65b8b56fe681dfc9b10e81daf6b564ef0_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-controller-manager_tar
I1018 17:41:13.113209     694 files.go:115] Hash matched for "/var/cache/nodeup/sha1:d8725c0a95d66ae34d1b33081f0a3d73ee98880d_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-apiserver_tar": sha1:d8725c0a95d66ae34d1b33081f0a3d73ee98880d
I1018 17:41:13.113433     694 load_image.go:59] running command docker load -i /var/cache/nodeup/sha1:d8725c0a95d66ae34d1b33081f0a3d73ee98880d_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-apiserver_tar
I1018 17:41:14.624790     694 files.go:115] Hash matched for "/var/cache/nodeup/sha1:1e2fc6e12d469643aa4dbe153210e230137bca4e_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-proxy_tar": sha1:1e2fc6e12d469643aa4dbe153210e230137bca4e
I1018 17:41:14.625103     694 load_image.go:59] running command docker load -i /var/cache/nodeup/sha1:1e2fc6e12d469643aa4dbe153210e230137bca4e_https___storage_googleapis_com_kubernetes-release-dev_ci_v1_5_0-alpha_1_499_6e1bb2d2f7c410_bin_linux_amd64_kube-proxy_tar
```

... but a corresponding `sudo docker images` showed it wasn't loaded. Kubelet confirms that it's failing to pull that tag (which doesn't really exist outside the sideload).

### PR DESCRIPTION
**Pull request by zmerlynn**
Tested with manual build and NODEUP_URL

Fixes #685, #686

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@zmerlynn anyway to unit test this code?  May be hard, so a valid answer may be not really.

**Comment by zmerlynn** [comment]
@chrislovecnm: You can easily hallucinate tasks, call `GetDependencies` and verify. Can I deal with it in a follow-on? There are no existing tests in `nodeup/nodetasks`, and I'm trying to get https://k8s-testgrid.appspot.com/google-aws#kops-aws-updown back operational.

**Comment by zmerlynn** [comment]
Opened #689 for unit testing there.

**Comment by chrislovecnm** [comment]
Will hold yah too it ... Evil laugh

**Pull request merged**
