### PR TITLE
Update 1.3.0 to 1.3.3

### PR DESCRIPTION
**Pull request by mikesplain**
Get things up-to-date for new instance types

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks!

I think we should still bump the version in bootstrapchannelbuilder, even though this is a weird case (and I'm not sure we handle updates to image overrides correctly generally)

Also, do you think we want this in 1.12 or can it wait till 1.13?

**Comment by mikesplain** [comment]
Oh yeah good eye @justinsb, I'll bump that as well. I'd like to see it in 1.12 but it certainly shouldn't hold up the release.

**Pull request merged**
