### PR TITLE
add support for varcheck linter

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by olemarkus** [comment]
Isn't varcheck in the list of deprecated linters?

**Comment by remyleone** [comment]
I don't see any deprecation notice here: https://golangci-lint.run/usage/linters/#varcheck besides it seems it caught some unused variables :)

**Comment by olemarkus** [comment]
There is a comment with a link a few lines above the one you added there.

**Comment by remyleone** [comment]
Would you still like to have the fix without enabling the linter? The fixes could be nice regardless of the status of the linter. The deprecation is still in the process and there does not seem to be an official replacement notice yet.

**Comment by remyleone** [comment]
@hakman rebased :)

**Review by hakman — APPROVED** [review]
/test all

**Pull request merged**
