### PR TITLE
Updated docs for openstack cloud provider.

### PR DESCRIPTION
**Pull request by prankul88**
#7021

### CODE REVIEW

**Comment by adisky** [comment]
from code it seems the actual flag is `AlphaAllowOpenstack`, but its should be fixed in code or doc it is not clear, as we refer openstack as `OpenStack`
cc @zetaab

**Comment by chrisz100** [comment]
/ok-to-test 

Thank you for your work @prankul88 ! 
/assign @zetaab 
Can you please check @adisky concerns before approval?

**Comment by zetaab** [comment]
@adisky yes we should refer to `OpenStack` instead of `Openstack`. However, if we change that behaviour now it will break things. As I see it this is not that huge problem that we should do it. Instead the next step that I want to see is that we remove this feature flag from OpenStack.

/lgtm

**Comment by chrisz100** [comment]
/approve

Thanks :-)

**Comment by adisky** [comment]
> @adisky yes we should refer to `OpenStack` instead of `Openstack`. However, if we change that behaviour now it will break things. As I see it this is not that huge problem that we should do it. Instead the next step that I want to see is that we remove this feature flag from OpenStack.
> 
> /lgtm

@zetaab Thanks!! yes i understand that.

**Pull request merged**
