### PR TITLE
Update security.md

### PR DESCRIPTION
**Pull request by vegasbrianc**
Added the new params to the kops create secret step as a required flag

### CODE REVIEW

**Comment by vegasbrianc** [comment]
CLA has been verified now cc @k8s-ci-robot

**Comment by mikesplain** [comment]
@vegasbrianc Thanks for the contribution! We're always happy to have people help get docs in better shape!

It looks like `--state` is a global flag, why do you feel it belongs in this doc specifically?

**Comment by vegasbrianc** [comment]
Hi @mikesplain Thanks for the message. I will be sure to add more. 

I added this as KOPS prompted me/other members of my team to add this flag in order to complete the command. `kops create secret`

//assign

**Comment by mikesplain** [comment]
Hmm you shouldn't need that, as long as you're setting up the environment variables properly:

https://github.com/kubernetes/kops/blob/6629548a4f3b67086b3968e9091b20b67d978748/docs/aws.md#prepare-local-environment

**Comment by vegasbrianc** [comment]
@mikesplain Doh! That was indeed it. Thanks and sorry for the extra work here.

**Comment by mikesplain** [comment]
No worries! Happy to help!

**Pull request closed without merging**
