### PR TITLE
minor grammar improvements to kops terraform docs

### PR DESCRIPTION
**Pull request by discdiver**

### CODE REVIEW

**Comment by discdiver** [comment]
CLA signed.

**Comment by rifelpet** [comment]
Thanks for the improvements!

/ok-to-test

**Comment by chrisz100** [comment]
/lgtm
/assign @mikesplain @justinsb 
Thanks! :-)

**Comment by mikesplain** [comment]
Thanks @discdiver!

/area documentation
/lgtm
/approve

**Pull request merged**
