### PR TITLE
Add i3en instance types

### PR DESCRIPTION
**Pull request by mikesplain**
Should probably be merged after https://github.com/kubernetes/kops/pull/6890 since I included it here, but it seems stuck right now so if this merges first, that's fine too.

### CODE REVIEW

**Comment by mikesplain** [comment]
Tagging as 1.12 so we users can have the latest instances asap! I'll open cherry-picks once this merges.

**Comment by mikesplain** [comment]
/assign rdrgmnzs

A fresh pr may help the stuck jobs.. gotta figure out what's up with test infra lately. . .

**Comment by justinsb** [comment]
/retest

CSI failures

**Comment by mikesplain** [comment]
Rebased to make it easier to cherry-pick

**Pull request merged**
