### PR TITLE
Specify instance tenancy on AWS

### PR DESCRIPTION
**Pull request by dacohen**
For a variety of use cases, including launching HIPAA-compliant clusters, it is a requirement to run AWS instances with dedicated tenancy, meaning they run on their own dedicated hardware.

This pull request implements the capability to specify the tenancy of the masters and nodes separately, at creation time, which is also currently under discussion in #1756.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2155)

### CODE REVIEW

**Comment by apenney** [comment]
This is awesome.  As someone in a HIPAA constrained environment, I just want to say thanks for this PR!

**Comment by hollowimage** [comment]
Thank you!!!

**Comment by justinsb** [comment]
This looks great - putting them at the instance group level is spot-on IMO.  The two challenges that I'm going to ponder:

* Should we have the default value be empty / nil so that the field only appears if specified (probably not)
* Are the Default / Dedicated names too restrictive / too tied to AWS?  Is there some easy way to generalize this?  Does any other cloud offer anything similar?  (Not expecting answers, just that this is the thought process...).  It is the API, so it isn't trivial to rename these things, though we can do it.  AFAICT though, nobody else has this notion, so this is probably splitting hairs.

As a nit, we seem to also prefer capital letters for our "enums", i.e. "Default" and "Dedicated"

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Comment by hollowimage** [comment]
@justinsb default values should be empty. if unspecified aws assumes tenancy parameter based on the configuration of the VPC. in most cases its shared, so leaving it empty will mean whatever exists, will be setup.

as for other cloud platforms, do they offer similar functionality? aws actually has 3 tenancy levels:

1. shared (default)
2. dedicated
3. host

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html

**Comment by dacohen** [comment]
I agree with @hollowimage here. It's not immediately clear in the AWS documentation, but it appears that if we default to "default", and someone tries to launch into a pre-configured VPC, it won't inherit tenancy as expected. I updated the PR to reflect this, and support the "host" tenancy mode as well.

It looks like neither Google Cloud, nor Azure supports the same concept of tenancy, so this will likely have to be tightly coupled to AWS.

@justinsb Regarding the enum naming, AWS expects those parameters to be lowercase, so we can create an enum with capitalized names, but then we'll have to map from it to the AWS naming convention.

**Comment by hollowimage** [comment]
> It looks like neither Google Cloud, nor Azure supports the same concept of tenancy, so this will likely have to be tightly coupled to AWS.

it may be prudent to add a check to allow tenancy specification to only be specified if `--cloud aws` was specified.

**Comment by dacohen** [comment]
I updated the instance group population to throw a warning if tenancy is set on a now AWS-environment. Since the Tenancy field isn't mapped by GCE, it will just ignore it.

I added an exception list as well to throw an error if the user attempts to launch a t2.* instance, which is not supported in a dedicated tenancy environment.

Thanks for the suggestions @hollowimage!

**Comment by hollowimage** [comment]
Looking over the PR, some thoughts here:

given poor AWS nomenclature patterns (default literally is shared, unless its not), do we want to NOT use default in the params?

if left as unspecified we can set it to empty, which will inherit, but you can launch shared instances into a dedicated VPC and vice versa, and "default" meaning "shared|dedicated" is rather confusing. just thinking outloud here.

as in if there's no value passed for `--tenancy` assume `""` but else require `--tenancy shared|dedicated|host`

**Comment by dacohen** [comment]
Perhaps a better name for "default" would be "inherited", since that's what it does if you launch into an existing VPC. But if you create a VPC from scratch with kops, then "shared" would be a better name.

Since tenancy is so intertwined with the AWS ecosystem, I don't see the value in creating an abstraction around a single API. I totally agree that "default" is an ambiguous name for shared/inherited instances. But it has a completely unambiguous meaning in the context of AWS, which is fully explained in the documentation you linked above. For these reasons, I think it will be more confusing if we have Kops and AWS use different names. Even though it might make the interface to Kops more elegant, I think it will make the system as a whole less so.

As it stands, if tenancy is not specified for an AWS cluster, nothing is passed to AWS. If tenancy is set, it must be one of "default", "dedicated" or "host".

**Comment by dacohen** [comment]
@k8s-bot aws e2e test this

**Comment by justinsb** [comment]
LGTM - thanks!

**Pull request merged**
