### PR TITLE
Add support for extensible IAM permissions

### PR DESCRIPTION
**Pull request by yissacharcw**
This is a continuation of https://github.com/kubernetes/kops/pull/550, now hopefully with CLA issues worked out, and with added tests.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1170)

### CODE REVIEW

**Comment by yissacharcw** [comment]
I signed it!

**Comment by yissacharcw** [comment]
Fixes https://github.com/kubernetes/kops/issues/379

**Comment by chrislovecnm** [comment]
I am not a IAM expert by any means ... I pinged a couple of outside folks as well.

@kris-nova / @justinsb tag.  I would like one of our security gurus to take a look as well.

**Comment by chrislovecnm** [comment]
We are trying to get https://github.com/kubernetes/kops/pull/1183 in, and it most likely will impact this PR. Appreciate you patience. 1183 is a big change, with huge benefits.

**Comment by chrislovecnm** [comment]
Can we get a rebase?

**Comment by chrislovecnm** [comment]
Updating https://github.com/kubernetes/kops/issues/1206

**Comment by yissachar** [comment]
@chrislovecnm Rebased and tested - everything is good now.

**Comment by chrislovecnm** [comment]
We need a rebase

**Comment by yissachar** [comment]
@chrislovecnm Rebased

**Comment by chrislovecnm** [comment]
I pinged @justinsb about this PR. Would like a review from him. Then we can merge.

**Comment by justinsb** [comment]
@yissachar my understanding is that you're planning on revisiting this when you have time, to create a second IAM policy without modification, and attach both.  Going to mark as WIP so @chrislovecnm stops bugging me about it ;-)

**Comment by yissachar** [comment]
@justinsb That's correct. Just getting back to work now after the holidays, and catching up on things, but I should have time to work on it this week. I'll post back here once I have something to show.

**Comment by yissachar** [comment]
@justinsb @chrislovecnm I've updated the PR with the discussed changes (moving from modifying the existing IAM policy in-place to creating a separate IAM policy that is also mounted to the instances). I've also slightly refactored the cluster spec to have the field be a map instead of hardcoded fields for the masters and nodes. Seeing as we are starting to have more roles than just those two (e.g. bastion), this feels like a more elegant approach.

**Comment by yissachar** [comment]
I followed the [existing code](https://github.com/yissacharcw/kops/blob/0d53f41f5ca7a24457589e48ac58eef749b65e54/upup/pkg/kutil/delete_cluster.go#L1901) to delete IAM roles but I believe it's prone to becoming incorrect as more roles are added. Indeed, I see that we've already had an [issue](https://github.com/kubernetes/kops/issues/1427) where we forgot to update the code to remove the bastion IAM role. 

I think the code could be updated to iterate through all roles we have and add those to the list of things to be removed. This way, if we add another role in the future, deletion would automatically be handled and we wouldn't have to remember to specifically add it.

**Comment by justinsb** [comment]
This LGTM - thanks!

**Pull request merged**
