### PR TITLE
test: Utilize max-nodes-to-dump to leverage on large scale tests to reduce storage

### PR DESCRIPTION
**Pull request by hakuna-matatah**
- Set max-nodes-to-dump to leverage on large scale tests to reduce storage and disable ServiceTrafficDistribution

### CODE REVIEW

**Comment by hakuna-matatah** [comment]
cc: @dims

**Comment by hakuna-matatah** [comment]
Scale test with **CLUSTER_NAME** `scale-5000.periodic.test-cncf-aws.k8s.io` seem to have succeeded - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16718/presubmit-kops-aws-small-scale-amazonvpc-using-cl2/1819095148122869760 
And ASG seem to have created without issues.

**Comment by hakuna-matatah** [comment]
Now lets try to use the old name which was causing issues with **CLUSTER_NAME**  `scale-1000.periodic.test-cncf-aws.k8s.io`

**Comment by hakuna-matatah** [comment]
> Now lets try to use the old name which was causing issues with **CLUSTER_NAME** `scale-1000.periodic.test-cncf-aws.k8s.io` in our periodics here - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2/1818950113440043008

Cluster seem to be created and succeed fine even with this name - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16718/presubmit-kops-aws-small-scale-amazonvpc-using-cl2/1819123862298693632

**Comment by dims** [comment]
intentionally pulled the rug under the CI job by deleting the ASG by hand

**Comment by hakuna-matatah** [comment]
> Error: field spec.kubeAPIserver.featureGates not found in *Cluster

Interesting - I see the field in the kops APIServerComponent defined [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L471)  and v2/v3 api's and in here the crd spec - https://github.com/kubernetes/kops/blob/master/k8s/crds/kops.k8s.io_clusters.yaml#L1913-L1917 

why would it throw this error ?

**Comment by hakuna-matatah** [comment]
> > Error: field spec.kubeAPIserver.featureGates not found in *Cluster
> 
> Interesting - I see the field in the kops APIServerComponent defined [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L471) and v2/v3 api's and in here the crd spec - https://github.com/kubernetes/kops/blob/master/k8s/crds/kops.k8s.io_clusters.yaml#L1913-L1917
> 
> why would it throw this error ?

Will try to take it directly off from model  to see if it works.

**Comment by hakuna-matatah** [comment]
/assign @dims @hakman 

Successful test run at small scale [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16718/presubmit-kops-aws-small-scale-amazonvpc-using-cl2/1819583833746444288)

**Pull request merged**
