### PR TITLE
Route53 mapper issue 2825

### PR DESCRIPTION
**Pull request by icicimov**

### CODE REVIEW

**Comment by icicimov** [comment]
CLA signed

**Comment by icicimov** [comment]
Addresses https://github.com/kubernetes/kops/issues/2825

**Comment by chrislovecnm** [comment]
Sorry my friend, CLA is still not happy. Do you have git user setup with the same email address you used for the cla?

**Comment by chrislovecnm** [comment]
Bump

**Comment by chrislovecnm** [comment]
Sorry that it is a pain, but are you able to sign the cla?

**Comment by igoratencompass** [comment]
Hi @chrislovecnm , not a pain at all, sorry for me doing something wrong and what ever it is I don't know how to fix it. I have signed the CNCF on 5th of July as you can see on the screen shot attached.
I also attached the pdf of the agreement, not sure what else can I do abd why it thinks I haven't signed. Any suggestions?

[CNCF_Individual_Contributor_License_Agreement.pdf](https://github.com/kubernetes/kops/files/1565405/CNCF_Individual_Contributor_License_Agreement.pdf)

cncf

**Comment by chrislovecnm** [comment]
@igoratencompass task a look at https://github.com/kubernetes/community/blob/aab85b83698dbb70f1c5fb9946e7d8d062a960a5/CLA.md#3-enter-the-correct-e-mail-address-to-validate

**Comment by justinsb** [comment]
/close

Closing because of lack of CLA; if you are able to sign the CLA we would welcome the contributions!

**Comment by justinsb** [comment]
Although I just looked at the branch - the issue here is that there are two commits, with two different email addresses.  You would have to sign the CLA for both, and I'm guessing one of them doesn't have it.

Easy way is to simply squash the commits, I suspect.  If you then repush ping this and we can reopen!

**Pull request closed without merging**
