### PR TITLE
Bug: Explicitly set default StorageClass to support upgrades

### PR DESCRIPTION
**Pull request by joshbranham**
Dropping the annotation versus setting it to `false` breaks cluster upgrades.

Set the old `gp2` StorageClass explicitly not the default

Fixes https://github.com/kubernetes/kops/issues/9336

### CODE REVIEW

**Comment by hakman** [comment]
Any thoughts on using `storageclass.kubernetes.io/is-default-class` instead of the `beta` version?

**Comment by joshbranham** [comment]
Does 1.17 honor that annotation as well?

**Comment by hakman** [comment]
The beta one seems deprecated since 1.6:
https://github.com/kubernetes/kubernetes/pull/40088

**Comment by joshbranham** [comment]
> The beta one seems deprecated since 1.6:
> [kubernetes/kubernetes#40088](https://github.com/kubernetes/kubernetes/pull/40088)

Yeah we can change the `kops-ssd-1-17` to use the non-beta label but we will need to use the beta label (and maybe if we want the non-beta) on the `gp2` in order to have the desired behavior.

Otherwise, we go back to the original point of how to make upgrades work on immutable fields, where if we just made `gp2` have these updated settings alongside a breaking change of `you have to run this with --force to upgrade` 🤷

**Comment by johngmyers** [comment]
Since we've released 1.17.0, I don't think we can change the name of the annotation. Otherwise clusters updated with 1.17.0 will encounter this bug when we need to make `kops-ssd-1-17` non-default.

**Comment by joshbranham** [comment]
So I think the only other thing would be to maybe just add some wording to release notes in case someone runs into a conflict on upgrade, its easy enough and zero risk to fix themselves. We can even provide a few one-liners. Thoughts?

**Comment by olemarkus** [comment]
+1 from me!

**Comment by hakman** [comment]
+1 from me also

**Comment by johngmyers** [comment]
The only reason we left the `gp2` StorageClass in the manifest was to remove the annotation upon upgrade. It seems a poor user experience to require a manual step on upgrade. What is the downside of explicitly setting the annotation to `"false"`?

**Comment by johngmyers** [comment]
Ah, that release note commit was added; not a replacement for the first one.
/lgtm

**Comment by rifelpet** [comment]
I agree that this sounds good to me. We can get this merged now to get it under e2e test coverage, and open a cherry-pick to release-1.17.
I presume we wont have a 1.17.1 release before office hours on friday, so we can take any final feedback there.

/approve

**Pull request merged**
