### PR TITLE
WIP - Update autogenerated api docs

### PR DESCRIPTION
**Pull request by KashifSaadat**

### CODE REVIEW

**Comment by gambol99** [comment]
Perhaps we could add a verify to the Makefile and tests?

**Comment by KashifSaadat** [comment]
Running into a problem with this when attempting to generate the docs, struggling to debug through the code though:
```
kops-server --etcd-servers=http://localhost:2379 --secure-port=9443 --print-openapi
  97942 authorization.go:34] Authorization is disabled
  97942 authentication.go:55] Authentication is disabled
  97942 genericapiserver.go:342] Skipping API kops/v1alpha1 because it has no resources.

~/go/bin/gen-apidocs --build-operations=false --use-tags=true --allow-errors --config-dir=docs/apireference
  Could not load json file docs/apireference/openapi-spec/swagger.json as api-spec: json: cannot unmarshal array into Go struct field SwaggerProps.paths of type map[string]json.RawMessage
```

The generated content for swagger.json from the `kops-server .. --print-openapi` command is:
```json
{
  "paths": [
    "/apis",
    "/apis/kops",
    "/apis/kops/v1alpha2",
    "/version"
  ]
}
```

@justinsb any ideas?

**Comment by justinsb** [comment]
I hit a similar problem and also wasn't able to get it working.  I'm hoping that when the upstream library is updated for 1.10 that we'll just pick up the fix...

**Comment by KashifSaadat** [comment]
Aha ok no problem, I shall close this PR for now then :)

**Pull request closed without merging**
