### PR TITLE
Configure docker on CoreOS/ContainerOS

### PR DESCRIPTION
**Pull request by johanneswuerbach**
While the installation of docker should be skipped, docker should still be
configured to allow overriding the docker config using kops.

Fixes https://github.com/kubernetes/kops/issues/3057

//cc @aledbf

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @johanneswuerbach - nice fix!

**Comment by johanneswuerbach** [comment]
Looks like I made a mistake and while the config is written successfully, the docker daemon is actually started before and the config only loaded on reload.

Will look into fixing that.

**Comment by johanneswuerbach** [comment]
Fix https://github.com/kubernetes/kops/pull/3134

**Pull request merged**
