### PR TITLE
Update AWS Logo In Docs

### LINKED ISSUE #4480: Update AWS Logo In Docs
The current logo under `docs/aws.md` is not using the new `smile` AWS logo.

### PR DESCRIPTION
**Pull request by christopherhein**
**Why:**

* The current logo is using the block type logo, this updates to the
smile logo

**This change addresses the need by:**

* closes #4480

Signed-off-by: Christopher Hein <me@christopherhein.com>

### CODE REVIEW

**Comment by christopherhein** [comment]
CLA Signed

**Comment by mikesplain** [comment]
Great thanks @christopherhein! Looks good!
/ok-to-test
/area documentation
/lgtm

**Comment by chrislovecnm** [comment]
Thanks @christopherhein - let me know if you are interested in writing some go code!!

**Comment by christopherhein** [comment]
@chrislovecnm I definitely am, just doing that chop wood and carry water thing 👍

**Comment by chrislovecnm** [comment]
I somehow removed the approved label ... should merge now

**Comment by christopherhein** [comment]
thanks @chrislovecnm :+1:

**Pull request merged**
