### PR TITLE
WIP testing new presubmit jobs

### PR DESCRIPTION
**Pull request by rifelpet**
using this PR to test the new presubmit jobs created in https://github.com/kubernetes/test-infra/pull/15794

### CODE REVIEW

**Comment by rifelpet** [comment]
just being explicit here..

/test pull-kops-bazel-test-podutils
/test pull-kops-verify-bazel-podutils
/test pull-kops-verify-generated-podutils
/test pull-kops-verify-gomod-podutils
/test pull-kops-verify-boilerplate-podutils
/test pull-kops-verify-gofmt-podutils
/test pull-kops-verify-govet-podutils
/test pull-kops-verify-packages-podutils
/test pull-kops-verify-staticcheck-podutils

**Comment by rifelpet** [comment]
The new jobs look good so far, most are faster than the old ones. Looks like the new ones are missing timestamp prefixes though, I'll look into that before switching the jobs to their new versions.

**Comment by rifelpet** [comment]
now that the e2e jobs have been migrated...


/test pull-kops-e2e-kubernetes-aws
--

**Comment by rifelpet** [comment]
now that the e2e jobs are migrated...
/test pull-kops-e2e-kubernetes-aws

**Comment by hakman** [comment]
One more try...
/test pull-kops-e2e-kubernetes-aws

**Comment by rifelpet** [comment]
I'm done with test-infra improvements for the time being, so closing this out. we shaved a few minutes off our e2e job times by enabling remote bazel cache.

**Pull request closed without merging**
