### PR TITLE
Have kops-controller create headless k8s services for dns=none clusters 

### LINKED ISSUE #16332: DNS None clusters fails OIDC e2e test
/kind bug
Since the migration to dns=none by default, the prow e2e grid is failing the OIDC tests:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-calico-amzn2-k26/1754164241511747584

```
I0204 15:43:18.456158       1 log.go:198] Full, not-validated claims: 
    openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://api.internal.e2e-e2e-kops-grid-calico-amzn2-k26.test-cncf-aws.k8s.io/", Subject:"system:serviceaccount:svcaccounts-9692:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1707061997, NotBefore:1707061397, IssuedAt:1707061397, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-9692", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"15bf3196-cfd3-40cb-9ee0-8f05454c7e85"}}}
    I0204 15:43:18.460415       1 log.go:198] Get "https://api.internal.e2e-e2e-kops-grid-calico-amzn2-k26.test-cncf-aws.k8s.io/.well-known/openid-configuration": dial tcp: lookup api.internal.e2e-e2e-kops-grid-calico-amzn2-k26.test-cncf-aws.k8s.io on 100.64.0.10:53: no such host
```

the test pod created in the cluster is not able to resolve the api.internal domain name.

In https://github.com/kubernetes/kops/pull/12792 we populate coredns pods' /etc/hosts for gossip clusters. We probably need to expand that to cover dns=none clusters too.

### PR DESCRIPTION
**Pull request by rifelpet**
Fixes #16332

Like gossip clusters, dns=none clusters wont be able to resolve these DNS names which causes e2e test failures for OIDC tests. This ensures the OIDC test pods can resolve the DNS names.

Example failure: https://testgrid.k8s.io/kops-grid#kops-grid-calico-amzn2-k26

`I0204 15:43:18.460415       1 log.go:198] Get "https://api.internal.e2e-e2e-kops-grid-calico-amzn2-k26.test-cncf-aws.k8s.io/.well-known/openid-configuration": dial tcp: lookup api.internal.e2e-e2e-kops-grid-calico-amzn2-k26.test-cncf-aws.k8s.io on 100.64.0.10:53: no such host`

### CODE REVIEW

**Comment by rifelpet** [comment]
/cc @hakman @justinsb 

All of our "kops latest" grid jobs are failing because of this OIDC test 
https://testgrid.k8s.io/kops-grid#kops-grid-calico-u2004-k28

**Comment by hakman** [comment]
@rifelpet I believe the fix for the issue is more on the line of changing this condition to include dns=none, instead of the headless service. What do you think?
https://github.com/kubernetes/kops/blob/3d6599bb20b92d2801d3ed87a4074c59063fcfc1/upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.12.yaml.template#L79-L84

**Comment by hakman** [comment]
@rifelpet Is this still needed?

**Comment by rifelpet** [comment]
> @rifelpet Is this still needed?

To be honest, I'm not sure. This comment https://github.com/kubernetes/kops/pull/12792#issuecomment-974181669 suggests that this was meant to replace the /etc/hosts mount, but we seem to have both in place. Ideally we can figure out if these headless services are used and remove them if not. If we do want to keep them around, I'm inclined to keep their behavior in sync with the /etc/hosts strategy which would mean merging this.

Perhaps a good topic for office hours.
/kind office-hours

**Comment by rifelpet** [comment]
in office hours we decided this isn't needed. we will remove the kops-controller headless services at the same time that we eventually remove gossip support

**Pull request closed without merging**
