### PR TITLE
Have channels create PKI for addons

### PR DESCRIPTION
**Pull request by olemarkus**
Alternative to #10149 
Here we create a PKI (CA + cert-manager issuer) per addon and use this to create the certificates needed.

metrics-server addon is updated to make use of this as an example.

### CODE REVIEW

**Comment by olemarkus** [comment]
/hold

Two things that needs improving on:
* metrics-server change depends on cert-manager, so we need some validation there
* since this forces cert-manager also for those who have installed metrics-server, this should only happen for k8s 1.20+

**Comment by olemarkus** [comment]
/hold.cancel

Should be good now.

**Comment by hakman** [comment]
> Should be good now.

I agree 😄.
/lgtm

**Pull request merged**
