### PR TITLE
Fix node counts

### PR DESCRIPTION
**Pull request by ihoegen**
When running `kops validate`, and the cluster size is greater than the minimum configuration, the display message is 
screen shot 2017-12-07 at 1 10 14 pm

This PR sets the NodeCount value to the length of the nodes array instead of the configuration.

### CODE REVIEW

**Comment by KashifSaadat** [comment]
Hi @ihoegen, thanks for the PR!

It looks like your tests are failing due to an unused import in the `validate_cluster.go` file: `k8s.io/kops/upup/pkg/fi`. Please can you drop this and we'll kick off the e2e tests.

**Comment by ihoegen** [comment]
Hi @KashifSaadat, I've removed the unused import

**Comment by KashifSaadat** [comment]
Thanks!

Please can you flatten your commits and fix up the test failure here: `pkg/validation/validate_cluster_test.go`

Let me know if you have any questions.

**Comment by chrislovecnm** [comment]
/ok-to-test

Travis is reporting an error.

**Comment by ihoegen** [comment]
@chrislovecnm Tests are passing now

**Comment by KashifSaadat** [comment]
Tested and looks good, thanks @ihoegen! 👍

/lgtm

**Pull request merged**
