### PR TITLE
Use k8s.gcr.io for k8s side-loaded images

### PR DESCRIPTION
**Pull request by hakman**
Refs: #13365

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by ameukam** [comment]
@hakman curious about why the switch to `k8s.gcr.io` ? Anything we need to improve for `registry.k8s.io` ?

**Comment by hakman** [comment]
@ameukam We sideload k8s images from .tgz files. Those are built with `k8s.gcr.io` as registry. Once `registry.k8s.io` is GA, k/k should switch too.

**Pull request merged**
