### PR TITLE
v1alpha3: Move GCE-specific CloudConfig settings to GCESpec

### PR DESCRIPTION
**Pull request by johngmyers**
Getting close to emptying CloudConfig out.

A good question is where `ManageStorageClasses` belongs. Perhaps a `Storage` field under `ClusterSpec`? We could put `SnapshotController` there. Not sure what else, unless we want to put the CSI drivers there.

### CODE REVIEW

**Comment by hakman** [comment]
`ManageStorageClasses` is more of a per CSI driver setting. Not sure if all of kOps implementations respect it. Would be nice to be added to each CSI driver separately to avoid misconfiguration.

**Comment by olemarkus** [comment]
While I probably was the one encouraging a common config, I agree that this config makes more sense to have per CSI implementation.

**Comment by johngmyers** [comment]
I still see it as common. The feature is to create a default StorageClass using whatever is appropriate for the cloud provider. (and maintain StorageClasses that used to be the default in older clusters.)

**Comment by hakman** [comment]
In theory it is common. In practice, there is no requirement to be implemented and it is dependent on the cloud provider implementation in kOps.

**Review by hakman — APPROVED** [review]

**Pull request merged**
