### PR TITLE
WIP: ELB custom SG

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
@chrislovecnm this is how I think we should be using our model to support SG reuse.  It's only for the API ELB right now.

I've split it into commits.  In order:

* Define the new api field - note I define it where it used.  We ideally want a name that is more cloud-agnostic, but we've already using securityGroups elsewhere so I think it's _fine_ if we can't think of something better.
* Generate the apimachinery (pretty small)
* Actually map the parameter - set the ID on the SecurityGroup task and mark it shared
* Create a new update_cluster integration test where we will put the custom security group tests (I thought we should use a new one, though we probably could have reused e.g. privatekopeio).  Note that I didn't actually override the security group in the tests, yet, so that...
* Finally override the ELB security group in the integration tests, so we can see the changes.  At the terraform level, we don't create the SG, but we still create the rules.

If you want to not create the rules, that is what a phase will do.  But reuse of the security group is separate from the create vs validate behaviour for these tasks.

**Comment by blakebarnett** [comment]
FWIW I tested this (without kops support) and ran into bugs.  We are focusing on using Ingress instead.

**Comment by justinsb** [comment]
@blakebarnett interesting - do you mean you tested this PR and there were bugs, or do you mean that there were issues with reusing a shared security group with e.g. the AWS cloudprovider?

**Comment by blakebarnett** [comment]
Yeah it would use the shared security group, but Services in k8s would never get their `LoadBalancer` status field set, and would never pickup backends properly. I didn't have time to diagnose it, so we moved to Ingresses.

**Comment by justinsb** [comment]
Closing - functionality is in #5744 :tada:

**Pull request closed without merging**
