### PR TITLE
Expose Felix metrics

### PR DESCRIPTION
**Pull request by atopuzov**
* Exposes Felix prometheus endpoint
* Same as `networking.projectcalico.org.canal`

### CODE REVIEW

**Comment by robinpercy** [comment]
Thanks for the PR @atopuzov!

/ok-to-test

**Comment by robinpercy** [comment]
@atopuzov Apologies, but I missed this earlier:  When updating addons, we need to bump their versions in the boootstrap builder (https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L470)

The versions for calico would now become:
```
// 2.6.7-kops.1 = 2.6.6 with kops manifest tweaks.  This should go away with the next version bump.
"pre-k8s-1.6": "2.4.2-kops.1",
"k8s-1.6":     "2.6.7-kops.1",
"k8s-1.7":     "2.6.7-kops.1",
```

Similar to how canal versions were updated here: https://github.com/kubernetes/kops/commit/148a65e1ad9041ceb1d46932fc6214d1a61a58e6#diff-e6c11b77cff2eb23d70f34c74ae63563L506


/lgtm cancel

**Comment by atopuzov** [comment]
@robinpercy Versions bumped.

**Comment by justinsb** [comment]
/lgtm

And with luck this will actually mesh with the other PR as well

**Pull request merged**
