### PR TITLE
Rework openstack authentication

### PR DESCRIPTION
**Pull request by rissson**
The goal here is to use the native [clouds.yaml](https://docs.openstack.org/python-openstackclient/latest/configuration/index.html) provided by OpenStack to authenticate to it, instead of a custom INI file.

As such, this PR deprecates the usage of that INI file, update gophercloud, and while we're at it, refactors the way we authenticate to OpenStack, which duplicates less code and uses native features from gophercloud.

This is still very much a work in progress.

TODO:
* [ ] remove my nixeries
* [ ] write some changelog
* [ ] cleanup the commits
* [ ] test it a bit more than just creating a cluster
* [x] rebase onto master
* [ ] ?

### CODE REVIEW

**Comment by hakman** [comment]
Hey @rissson! Please sign the CLA before going forward with this.

**Comment by rissson** [comment]
I signed it.

**Comment by hakman** [comment]
Thanks @rissson.
/check-cla

**Comment by rissson** [comment]
Closing this as I won't continue working on it.

**Pull request closed without merging**
