### PR TITLE
Convert registry to k8s.gcr.io

### PR DESCRIPTION
**Pull request by thockin**
This PR was auto-generated.  Please apply human expertise to review for correctness.

Followup to https://github.com/kubernetes/kubernetes/pull/54174 and https://github.com/kubernetes/kubernetes/pull/57824

xref https://github.com/kubernetes/release/issues/281

### CODE REVIEW

**Comment by justinsb** [comment]
Hmmm ... looks like the rename to k8s.gcr.io was reverted @thockin ?

**Comment by thockin** [comment]
this one seems ok to proceed.

**Comment by thockin** [comment]
PTAL

**Comment by thockin** [comment]
Rebased.  PTAL

**Comment by thockin** [comment]
Rebased and pushed.  This is the last such PR..

**Comment by justinsb** [comment]
/lgtm

Thanks for the perseverance @thockin !

**Pull request merged**
