### PR TITLE
Fix cluster autoscaler docs

### LINKED ISSUE #10223: Question: ClusterAutoscaler addon not installed, what is missing?
kOps version: v1.19.0.-beta.1
K8s version: 1.18.9

I've added the cluster-autoscaler config to our cluster spec, as described in the [docs](https://kops.sigs.k8s.io/cluster_spec/#cluster-autoscaler), but when creating a new cluster or updating an existing cluster, nothing changes at all.

```yaml
spec:
  cluster:
    clusterAutoscaler:
      enabled: true
      skipNodesWithLocalStorage: false
      skipNodesWithSystemPods: true
```

It seems I'm missing something, but I can't figure out what. Can you give me a hint? Thanks in advance! 😄

### PR DESCRIPTION
**Pull request by djablonski-moia**
This fixes #10223

### CODE REVIEW

**Comment by hakman** [comment]
Nice! Thanks @djablonski-moia. Please let us know when the CLA is signed.
/ok-to-test
/cc @olemarkus

**Comment by djablonski-moia** [comment]
I just signed the CLA 😃

**Comment by hakman** [comment]
Wonderful :)

**Comment by olemarkus** [comment]
/lgtm

Thanks for catching this

**Pull request merged**
