### PR TITLE
Respect the shared tag when deleting route tables

### LINKED ISSUE #3828: Kops always tries to delete the main AWS route table for a cluster
Kops verison: `1.8.0-beta.1`
K8s version: `1.7.x - 1.8.x`

If a routing table is tagged as `kubernetes.io/cluster/<cluster name>: shared`, kops should ignore it when deleting the cluster.  Currently if you tag all subnets and NAT gateways as shared this way it ignores the route tables associated with them but still attempts to delete the single route table with the name that matches the cluster no matter how it's tagged.

### PR DESCRIPTION
**Pull request by georgebuckerfield**
Fixes #3828.

Modifies the `buildTrackerForRouteTable` function (used by `ListRouteTables`) to set the `Shared` field of each returned route table resource, based on the presence of the `kubernetes.io/cluster/<clustername>: shared` tag. This prevents route tables with this tag from being deleted.

WIP while I add some more tests.

### CODE REVIEW

**Comment by georgebuckerfield** [comment]
I've tested with a few different scenarios (shared VPC, public/private topologies) and the route table no longer gets deleted when the shared tag is present, so hopefully this is good to go.

**Comment by justinsb** [comment]
/lgtm

Awesome work @georgebuckerfield - and with tests as well :-)

**Comment by hfgbarrigas** [comment]
Is this going to be released only with 1.8? Currently using 1.7.1 and having this issue.

**Pull request merged**
