### PR TITLE
Bump AWS CNI to 1.10.2

### PR DESCRIPTION
**Pull request by MoShitrit**
Version 1.10.2 was released 4 days ago - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.10.2

### CODE REVIEW

**Comment by hakman** [comment]
@MoShitrit There were some changes to the manifest since 1.9. Could you also update the template?

**Comment by MoShitrit** [comment]
> @MoShitrit There were some changes to the manifest since 1.9. Could you also update the template?

Hey @hakman !
So the only thing I could see in their [upgrade PR](https://github.com/aws/amazon-vpc-cni-k8s/pull/1850) is the addition of one ENV:
image

However, since we now don't have these explicitly set, I wasn't sure if I should add that or not. I can probably add that and comment it out like the other ENVs there. Does that work?
Also- is there anything else I might've missed besides that?
Thanks!

**Comment by hakman** [comment]
Hey @MoShitrit! :)
I think the changes in these commit are missing:
https://github.com/aws/amazon-vpc-cni-k8s/commit/01654383404fe88f18a89508d9406ad52c6eec1f
https://github.com/aws/amazon-vpc-cni-k8s/commit/cf017e525abcc038341929431c91c8767f32c672
https://github.com/aws/amazon-vpc-cni-k8s/commit/fe817b84a7d00a0037d7feefbea20f90a6804eae

Probably the easiest way to check would be to compare the template with https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml.

**Comment by MoShitrit** [comment]
> Probably the easiest way to check would be to compare the template with https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml.

Good point! 
Let me do that and make the necessary update.
Thanks 😄

**Comment by MoShitrit** [comment]
@hakman I took your suggestion and compared our template with the one from `aws-cni`'s `master` branch. There were a couple of cosmetic changes the were causing noise, so I moved things around a bit to reduce that noise.
Then I also noticed the additional changes you've mentioned. At this point, I think we should be good, but feel free to verify my sanity.
Thanks again! 😄

**Comment by hakman** [comment]
Thanks @MoShitrit. Looks pretty good. Will do the final review during the weekend.

**Review by hakman — CHANGES_REQUESTED** [review]
Looks great, just a few nits left.

**Review by hakman — APPROVED** [review]
Excellent! Thanks @MoShitrit. :)

**Pull request merged**
