### PR TITLE
Enable use of irsa for aws load balancer controller

### PR DESCRIPTION
**Pull request by olemarkus**
This also improves how we can add irsa data to a manifest.

### CODE REVIEW

**Comment by rifelpet** [comment]
Can we update an integration test case to use this functionality? I'd expect a new iam role for aws-load-balancer-controller being created in the terraform/cloudformation output.

**Comment by olemarkus** [comment]
Sure. I can PR an integration test for aws load balancer controller that can go in first.

**Comment by olemarkus** [comment]
@rifelpet now you can see a policy/role diff here.

**Comment by rifelpet** [comment]
`W0404 19:37:06.307277   10744 executor.go:139] error running task "VPC/e2e-6d9ce33ad2-8dfcf.test-cncf-aws.k8s.io" (2m21s remaining to succeed): error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.`

:(  we can probably rerun each of the e2e tests one at a time. otherwise this LGTM 👍🏻

**Review by rifelpet — APPROVED** [review]
/retest

**Pull request merged**
