### PR TITLE
Add initial github actions workflow

### LINKED ISSUE #8984: add CI support for Github Actions
On the Apr 24 office hours call, @justinsb expressed an interest in Github Actions over Travis. I have a working implementation and wanted to confirm the desired scope. 

What I've got now is:

* ubuntu-18.04 and macOS-10.15, each running `make nodeup examples test`, under go 1.13.x and go 1.14.x
* ubuntu-18.04, running what's currently `make travis-ci`, under go 1.13.x and go 1.14.x
* rename `travis-ci` target to `github-actions`
* update CI badges in EN and ES readmes

Once I worked out syntax issues, these six jobs ran concurrently in a little over eight minutes.

Uncertainties:

* The travis configuration only runs `make travis-ci` on linux (both travis and github disallow docker on macOS, so this target would fail there), and only under go 1.13. Should this be carried over as-is?
* Should travis.yml be removed as part of this PR, or as a subsequent step?
* Is Windows worth looking at?

I appreciate the opportunity to try out Actions, which was more polished than I expected. Thanks for all the work on kops.

### PR DESCRIPTION
**Pull request by irons**
Resolves #8984. This adds a parallel Github Actions implementation of what's also being run at Travis CI.

### CODE REVIEW

**Comment by irons** [comment]
Actions' output on a closely related branch can be seen at https://github.com/irons/kops/actions?query=branch%3Agithub-actions-ci-testing.

**Comment by hakman** [comment]
Looks cool! What needs to be done to enable this?
/assign @justinsb @rifelpet 
/lgtm

**Comment by johngmyers** [comment]
A nit: I don't think we need two MacOS builds. One MacOS build on the primary Go version would be sufficient.

**Comment by mikesplain** [comment]
This is a great start! We can add a few more things in follow ups if need be. 

Thanks @irons! Let’s get this merged and see if it starts running or if we need an admin to enable actions. 

/lgtm
/approve

**Comment by hakman** [comment]
First run 😄 
https://github.com/kubernetes/kops/actions/runs/89142765

**Comment by rifelpet** [comment]
I haven't had a chance to look this up, but do GH actions for PRs merge the target branch into the branch being tested? Prow and Travis do that, so it'd be nice to make sure that is consistent.

**Comment by irons** [comment]
@rifelpet The merge commit is apparently the only one being tested when the `pull_request` event fires. There's an [open request](https://github.community/t5/GitHub-Actions/Support-pull-request-events-without-merge-commit-into-the-target/m-p/36190#M2470) to also support isolated testing the latest commit on a PR change, but right now that only happens when the `push` event calls for it.

I found [this description of the `pull_request` event](https://help.github.com/en/actions/reference/events-that-trigger-workflows) more helpful than the event docs it links to.

**Pull request merged**
