### PR TITLE
Make chrisz100 a reviewer for kops

### PR DESCRIPTION
**Pull request by chrisz100**
As discussed with @mikesplain here is my application as a reviewer. Objections anyone? :)

### CODE REVIEW

**Comment by mikesplain** [comment]
Wahoo! @chrisz100 has been working hard for awhile on reviewing PRs so I think this is overdue.

/lgtm

(leaving open for now to allow for any other [comments/objections](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer))

**Comment by justinsb** [comment]
Big +1 from me - thanks for all the hard work @chrisz100 :-)

/approve

**Comment by chrisz100** [comment]
Inconsistency in commands is always a thing lol @justinsb 
/hold cancel

**Pull request merged**
