### PR TITLE
Update scalability test so it passes

### PR DESCRIPTION
**Pull request by justinsb**
Update the scalability test so it passes: use calico, also a fix misc fixes.

### CODE REVIEW

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

Make sure to build kubetest2 (we're not currently using the lib, for parity with the new job in cloud-provider-gcp, though I suspect I'll end up converging back to it!)

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

hmmm... shellcheck does not like the way we are building the args

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

With the shellcheck fix, and a tweak to log more when we can't match an instance type

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

Increasing validation timeout ... 100 nodes takes more time (we _just_ missed it at 10m previously)

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

/retest

Looks like a broad test failure to pull from git (branch not found)

**Comment by justinsb** [comment]
/retest

It looks like the latest prow image may be bad, or something has gone wrong with this PR...

**Comment by hakman** [comment]
Using Calico should fix the failing test.

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

Switching to calico for now...

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

After pushing the calico change this time...

**Comment by hakman** [comment]
@justinsb Should we go with `--dns=none` also for this scenario?

**Comment by justinsb** [comment]
> Should we go with --dns=none also for this scenario?

Good call - done!

/test presubmit-kops-aws-scale

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

Two failures, checking if they are flakes:

* ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer
* HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol

**Comment by hakman** [comment]
I guess `--dns=none` somehow breaks these tests...

**Comment by justinsb** [comment]
/test presubmit-kops-aws-scale

I commented out dns=none for now - we can track it down and re-enable it in a separate PR.

**Review by hakman — APPROVED** [review]

**Pull request merged**
