### PR TITLE
Changing base image for node authorizer.

### PR DESCRIPTION
**Pull request by michalschott**
`fedora:27` is quite old

### CODE REVIEW

**Comment by michalschott** [comment]
Looks like there is no build pipeline set for node_authorizer.

```./pkg/model/components/node-authorizer/options.go:	return "quay.io/gambol99/node-authorizer:v0.0.4@sha256:078b948b8207e43d35885f181713de3d3c0491fe40661d198f9bc00136cff271"```

Could use some guidance to build one, and also serve image from "official" repo.

**Comment by hakman** [comment]
Until this is addressed, you should build an image and test it locally. I see there is a field for that in the cluster spec:
https://github.com/kubernetes/kops/blob/318e7faa79a238faa90fa9ae1a147b42da6d5c0f/pkg/apis/kops/cluster.go#L209

**Comment by rifelpet** [comment]
thanks for the update!
/approve

**Pull request merged**
