### PR TITLE
Install ethtool in nodeup

### PR DESCRIPTION
**Pull request by justinsb**
Issue #1830

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1862)

### CODE REVIEW

**Comment by itskingori** [comment]
@justinsb I was just about to send in a PR to do this. Figured this would only apply to 1.5+. By applying this to `master` will `release-1.4` nodeup get it as well, or just `release-1.5`?

I also noticed that the nodeup structure was heavily refactored from how it was in `release-1.4`. I was about to drop `ethtool` file in [kubernetes/kops/tree/release-1.4/upup/models/nodeup/top/packages][1] but wasn't sure if that was the right thing to do.

[1]: https://github.com/kubernetes/kops/tree/release-1.4/upup/models/nodeup/top/packages

**Comment by itskingori** [comment]
@justinsb 🤦‍♂️, forget [my dumb question][1] ... just realised that nodeup version follows kops version. 😄 

[1]: https://github.com/kubernetes/kops/pull/1862#issuecomment-279184991

**Comment by justinsb** [comment]
@itskingori it's a valid question!  This will only work with kops 1.5.  I think in general we're thinking that people will run the latest kops, even if they are running an older k8s.  We'll see how true that is.

We could backport this, but I'm inclined to put it into the next 1.4 image instead.  If you want to backport it, that's fine, but I think you probably should be using kops 1.5 instead.  Let me know if that doesn't make sense - will be interesting to hear if there is a reason to stick with kops 1.4!

**Comment by justinsb** [comment]
@chrislovecnm we're not closing #1830 BTW.

**Comment by itskingori** [comment]
> Let me know if that doesn't make sense - will be interesting to hear if there is a reason to stick with kops 1.4!

We aren't sticking with kops 1.4. It's complicated ... 😄.

Let me share some context ... we're in a precarious position where we started using kops 1.4 `HEAD` (when weave + private networking + bastions were introduced ... which we liked!) and K8s 1.5 wasn't really being pushed (we pretty much started on the `stable` branch, we ended up with 1.4.7) and have built considerably around it.

Now, we've upgraded up to kops 1.5 as it's the official release that does have (weave + private networking + bastions) ... but we're still on 1.4.7 ... which means we have a 1.4 base image which doesn't have `ethtool`. I'm convinced that weave + base-image-without-ethtool is a bad idea and we have a cluster with a very unstable network (like 9/10) which was difficult to debug i.e. tonnes of "vetoed installation of hairpin" errors with no clear solution.

There are two ways to fix this:

1. Get a new 1.4 base image (with `ethtool`).
2. Upgrade to K8s 1.5 after you build a new 1.5 image (with `ethtool`).
3. Wait for new K8s versions i.e. 1.4.9 & 1.5.3, which we've cherry picked the bug fix into 1.6 ... then bump K8s without changing AMI:
    * Automated cherry pick of #36990  into 1.4 - https://github.com/kubernetes/kubernetes/issues/40816
    * Automated cherry pick of #36990  into 1.5 - https://github.com/kubernetes/kubernetes/pull/40993
4. Manually install `ethtool` on the nodes and write `0` to hairpin mode files to reset the damage (this is what we are doing to get by).

We do not oppose moving to 1.5 ... we just:

1. Don't know what awaits us with a minor version bump of K8s.
2. Don't know how easy it is to do so, I mean, does kops actually handles change the AMI to a 1.5-image and upgrade K8s to 1.5? Sounds too magical. 😱 

I think we were taking the path with the least risk i.e. stick with K8s version but use AMI with fix. Then worry about upgrading K8s later.

But if we can get a new AMI (with `ethtool`) and you guys strongly recommend that we upgrade our cluster to K8s 1.5 ... then we can look into it.

**Pull request merged**
