### PR TITLE
Update HA doc

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1544)

### CODE REVIEW

**Comment by justinsb** [comment]
@vendrov I hope you don't mind - I took your HA doc and filled it out a bit.  Same structure etc.  I also moved it into `docs/`  Do you want to review? :-)

**Comment by justinsb** [comment]
Thanks @geojaz  - I can't see your change, but when I do I'll review it  :-)

@vendrov any thoughts?

**Comment by justinsb** [comment]
@geojaz never mind - found your PR now!

**Comment by vendrov** [comment]
@justinsb  LGTM

**Comment by kris-nova** [comment]
Thanks for the review @geojaz and @vendrov

**Pull request merged**
