### PR TITLE
Add release notes for 1.6.2

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2786)

### CODE REVIEW

**Comment by kenden** [comment]
On the release notes, it would be nice to have links to PRs or commit SHA for each feature.
It's hard to get more information about the changes otherwise.
That's what Kubernetes does:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v166

**Comment by chrislovecnm** [comment]
@kenden I think we have an open issue for a sha, otherwise please open one.

**Comment by kenden** [comment]
Thanks @chrislovecnm I think this is this ticket https://github.com/kubernetes/kops/issues/980

**Pull request merged**
