### PR TITLE
If specified, posts event data to URL upon instance interruption action.

### PR DESCRIPTION
**Pull request by voriol**
Fixes: https://github.com/kubernetes/kops/issues/14561

Hi,

It is OK?

Thanks

### CODE REVIEW

**Comment by olemarkus** [comment]
Looks good. You probably need a `./hack/update-expected.sh` to update the golden outputs.

**Comment by johngmyers** [comment]
/test pull-kops-build

The gofmt failures are probably legitimate

**Comment by voriol** [comment]
This continues in: https://github.com/kubernetes/kops/pull/16009

**Pull request closed without merging**
