### PR TITLE
New inventory assets API

### PR DESCRIPTION
**Pull request by chrislovecnm**
First PR of many for the Assets functionality.

See https://github.com/kubernetes/kops/pull/2917 for details

### CODE REVIEW

**Comment by justinsb** [comment]
Will need to see this in context, but generally looks good so far :-)

Assets is used for nodeup config also.  I think the naming is fine though - I don't foresee any real confusion.

**Comment by chrislovecnm** [comment]
rebased to catch missed api machinery changes that floated in from another PR.

**Pull request merged**
