### PR TITLE
more detail for IAM user

### PR DESCRIPTION
**Pull request by jasondewitt**
@kris-nova Opened this new PR to brute force the merge issues that arose in my last one.

Adds more details to the IAM user section, detailing the IAM permissions required and some bash/awscli commands to create said user.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1696)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by apenney** [comment]
@jasondewitt Not sure if you mind but I merged this PR into https://github.com/kubernetes/kops/pull/1709 as part of a larger rewrite.

**Comment by jasondewitt** [comment]
@apenney no problem here, I'll defer to @kris-nova , who I had been working with on these changes, or another member on the team on how best to proceed.

**Comment by kris-nova** [comment]
Thank you for the PR @jasondewitt 

This is great stuff, and we really have been needing this list for some time. Cheers!

**Pull request merged**
