### PR TITLE
Use k8s.gcr.io alias only for 1.10

### PR DESCRIPTION
**Pull request by justinsb**
The k8s.gcr.io prefix is an alias, but for CI builds we run from a
docker load, and we only double-tag from 1.10 onwards.  For versions
prior to 1.10, remap k8s.gcr.io to the old name.  This also means that
we won't start using the aliased names on existing clusters, which could
otherwise be surprising to users.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@justinsb Do you have any ETA for that to be merged?

**Comment by chrislovecnm** [comment]
@wojtek-t I just pinged @justinsb about the broken tests, but once those are fixed @mikesplain or I can lgtm

**Pull request merged**
