### PR TITLE
Refactor the --name error message

### PR DESCRIPTION
**Pull request by kris-nova**
Closes https://github.com/kubernetes/kops/issues/1222

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1255)

### CODE REVIEW

**Comment by justinsb** [comment]
I don't love it, but you can use `--name` with positional arguments.  The problem is that `--name` should probably be `--cluster` (`--name` is a little ambiguous), and the order gets a little confusing.  However, I believe we've defaulted to having the cluster name come first.

**Comment by chrislovecnm** [comment]
@kris-nova any comments on what @justinsb mentioned?

**Comment by chrislovecnm** [comment]
Status on this?

**Comment by kris-nova** [comment]
Closing in favor of a broader PR in the mix.. Thanks for the note on `--name` @justinsb!

**Pull request closed without merging**
