### PR TITLE
Add config to KubeSchedulerConfig

### PR DESCRIPTION
**Pull request by vvbogdanov87**
Related to #7740

PR adds `config` field to `kubeScheduler`. It enables the ability to use `--config` kube-scheduler flag instead of deprecated flags like `--kubeconfig`, `--policy-configmap`, `--policy-configmap-namespace`.

### CODE REVIEW

**Comment by hakman** [comment]
@vvbogdanov87 I think there was some work here to reduce tight coupling. https://github.com/kubernetes/kops/pull/8057
Maybe you can ask some advice about this on Slack.

**Comment by vvbogdanov87** [comment]
From [vendoring.md](https://github.com/kubernetes/kops/blob/master/docs/development/vendoring.md#adding-a-dependency-to-the-vendor-directory) 
```
Run make gomod
...
Open a pull request with these changes separately from other work so that it is easier to review.
```
Should I open a second PR with "vendor" changes to master? And merge master back to my branch after the second PR is merged to master?

**Comment by vvbogdanov87** [comment]
verify-generated fails because few fields don't have Json tag
https://github.com/kubernetes/kubernetes/blob/ef69bc910f0e47bbe3cf396d4bebf4f678cf6f3a/staging/src/k8s.io/apimachinery/pkg/runtime/types.go#L119
Should I make a fix for this? Or it is a bad idea to embed the whole kube-scheduler config type into cluster spec? How should we handle the scheduler configuration in that case?

**Comment by vvbogdanov87** [comment]
anyone?

**Comment by Mhs-220** [comment]
is there any news for this pr?

**Comment by mlushpenko** [comment]
It's still an issue with the latest 1.16 release, anyone knows when/if this one is planned to be implemented?

**Comment by olemarkus** [comment]
We probably want something like this PR to go in. Since this was made, we have support for the config file now, and there are examples for how to set this in the API files. See `Burst` and `Qps` as examples.

**Pull request closed without merging**
