### PR TITLE
Release notes for 1.11

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Added curated section, no longer WIP

**Comment by rdrgmnzs** [comment]
Looks great, thanks @justinsb! Will add a hold, feel free to remove it once you are ready for the release.

/lgtm
/hold

**Comment by mikesplain** [comment]
Thanks @justinsb! And thanks @rdrgmnzs for the review!

/lgtm

**Comment by justinsb** [comment]
Thanks all!

/hold remove

**Pull request merged**
