### PR TITLE
Update terraform.md

### PR DESCRIPTION
**Pull request by perryao**
fix typo

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @perryao, thanks for your PR!  Before we can get this in, would you mind signing the CLA above?  You'll only have to do this the first time.  Thanks so much for your contribution!

**Comment by mikesplain** [comment]
@perryao Any update on this? We always love new contributors so please keep me updated if you have an issue with the CLA or whatnot! Thanks!

**Comment by perryao** [comment]
@mikesplain Sorry for the delay on this. CLA is signed now

**Comment by mikesplain** [comment]
@perryao No worries! Thanks!
/area documentation
/ok-to-test

**Pull request merged**
