### PR TITLE
Release 1.27.0-alpha.1

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by johngmyers** [comment]
Deliberately not merge-method-squash so that all commits off of the release-1.26 branch point get included in release notes.

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
A force push should clear the need for pull-kops-e2e-aws-upgrade-125-ko125-to-klatest-kolatest-many-addons to pass.

**Comment by johngmyers** [comment]
Upgrade tests are failing because no 1.27.0-alpha.1 tag of dns-controller exists yet.

@justinsb could you clear the failing status checks so this can merge?

**Comment by hakman** [comment]
@johngmyers Can you rebase? I think it will merge after that.

**Comment by johngmyers** [comment]
We no longer rely on the .0-alpha.1 tag to generate release notes, so we can rebase and merge-method-squash.

**Pull request merged**
