### PR TITLE
fix spell error

### PR DESCRIPTION
**Pull request by sunlintong**

### CODE REVIEW

**Comment by KashifSaadat** [comment]
/ok-to-test
/lgtm

Thanks!

**Comment by KashifSaadat** [comment]
@sunlintong there's a conflict on the README file, looks like something made it into master just before! Please could you take a look?

**Comment by sunlintong** [comment]
@KashifSaadat resolve conflict,please see it in my new PR [#4841](#4841) ,and them I'll close this. Thank you!  :p

**Comment by KashifSaadat** [comment]
Ok thanks, will close this.

/close

**Pull request closed without merging**
