### PR TITLE
upgrade calico to 2.6.12 to fix TTA-2018-001

### PR DESCRIPTION
**Pull request by mechpen**
https://www.projectcalico.org/security-bulletins/#TTA-2018-001

### CODE REVIEW

**Comment by KashifSaadat** [comment]
@mechpen thanks for the PR and sorry about the hassle with having to recreate it a couple times!

/ok-to-test
/lgtm
/approve

**Comment by mechpen** [comment]
@KashifSaadat could you help take a look at the job error?

**Comment by KashifSaadat** [comment]
Hey @mechpen, this is a wider e2e job error currently affecting all kops PRs. We may have to wait until it's fully resolved and then can trigger a retest.

**Pull request merged**
