### PR TITLE
Initial bazel support

### PR DESCRIPTION
**Pull request by justinsb**
Builds on the 1.8 version bump

The "trick" is to strip the BUILD & BUILD.bazel files from the vendor-ed deps.

Will rebase after 1.8 version bump merges.

### CODE REVIEW

**Comment by justinsb** [comment]
cc @chrislovecnm and @alrs ... it's alive :-)

**Comment by chrislovecnm** [comment]
WAHOO ... The 1.8 version bump is in the merge queue now

**Comment by chrislovecnm** [comment]
we will need the hack scripts for maintaining and validating the bazel files.  Will create issue.

**Comment by alrs** [comment]
Congrats!

**Comment by justinsb** [comment]
Still lots of work needed ... this is really just the bare minimum.  But rebase so should be cleaner now.  Second commit is all autogen, first commit is the interesting stuff.

**Comment by chrislovecnm** [comment]
Can we rebase and get this in?  Would like to start adding some TLC with hack files and such.

**Comment by justinsb** [comment]
It is rebased @chrislovecnm ...

**Pull request merged**
