### PR TITLE
Document existing-subnet requirements

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1602)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
And travis is not happy again ... "Waiting for status to be reported"

**Comment by justinsb** [comment]
Docs; merging.

**Comment by justinsb** [comment]
Oh, although we probably should merge the code first... not merging :-)

**Comment by chrislovecnm** [comment]
@justinsb please self merge docs

**Pull request merged**
