### PR TITLE
Add socat to CoreOS

### PR DESCRIPTION
**Pull request by justinsb**
We build a statically linked version and distribute it with kops.

Note that our version of socat does not include libssl, but kubernetes
does not use it anyway.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1909)

### CODE REVIEW

**Comment by aledbf** [comment]
@justinsb [this is change](https://github.com/justinsb/kops/compare/socat_coreos_option_2...aledbf:static-socat-build?expand=1) to the build to generate a static binary with openssl

**Comment by justinsb** [comment]
@aledbf the challenge with that is that it puts (even more of) the burden on us to update when there are issues in any of those packages (AFAICT).  Another option might be to pull the latest source packages from debian and then build from there, so we pick up the latest fixes.  (Nothing particular about debian, it's just what I am most familiar with)

**Comment by aledbf** [comment]
@justinsb the problem with debian (or any other distro) is that you need to build glibc statically before compiling socat.

**Comment by geojaz** [comment]
close/reopen for travis

**Comment by justinsb** [comment]
Hmmm... I think that might be a real test failure - I'll take care of it!

**Pull request merged**
