### PR TITLE
Adding installation guidelines for Windows

### PR DESCRIPTION
**Pull request by EchoDelta**

### CODE REVIEW

**Comment by chrisz100** [comment]
@EchoDelta can you please sign the CLA? As someone else already figured out having a Linux Foundation ID is not enough and it needs to be signed to the email address you used to create the commits with, not the one you used to sign up to GitHub with. 
Thanks!

**Comment by EchoDelta** [comment]
@chrisz100 Should have been signed now :)

**Comment by chrisz100** [comment]
Great, thanks! 

/lgtm
/ok-to-check

**Comment by chrisz100** [comment]
I'm getting old...
/ok-to-test

**Comment by mikesplain** [comment]
Thanks for this @EchoDelta! Is there a more windowsy way to do this via script? Based on my knowledge, we can't guarantee they have curl or something similiar so I'll approve this for now since it's definitely an improvement!

Thanks!

/lgtm
/approve

**Comment by EchoDelta** [comment]
@mikesplain A good solution might be to publish to [chocolatey](https://chocolatey.org/) so it can be installed from there. Chocolatey is not a native package manager for Windows, but is like Homebrew for Mac OS and is widely used. An install would then be something like:
```
choco install kops
```

I could probably also write a Powershell script for installation, but it is probably just as easy to use the written instructions.

**Pull request merged**
