### PR TITLE
WIP: Update containerd to 1.5.2 for kubernetes >= 1.22

### PR DESCRIPTION
**Pull request by justinsb**
Aiming to address some flakiness observed with static pods.

### CODE REVIEW

**Comment by hakman** [comment]
Seems like a good time to do this.
/lgtm

**Comment by rifelpet** [comment]
I still see 0-length log files for certain components which leads me to believe this doesnt fix the issue https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/11913/pull-kops-e2e-k8s-ci/1411157716746899456/artifacts/15.206.168.184/

**Comment by hakman** [comment]
Already using 1.6.x beta in 1.23.

**Pull request closed without merging**
