### PR TITLE
Small typo fix

### PR DESCRIPTION
**Pull request by AdamDang**
Fix the typos :
 "a ssh"->"an ssh"
"an new ssh"->"a new ssh"

### CODE REVIEW

**Comment by chrisz100** [comment]
@AdamDang before we merge this, can you please complete: 
```bash 
FAIL: make verify-gendocs failed, as the generated markdown docs are out of date.
FAIL: Please run the following command: make gen-cli-docs.
```

**Comment by bheesham** [comment]
Looks like there's a lot of overlap with #4687. The only files not covered are:
- docs/cli/kops_rolling-update.md; and
- docs/cli/kops_rolling-update_cluster.md.

**Comment by justinsb** [comment]
Going to force-merge and throw into the docs-fix PR I have for the other one where I did the same thing.

Thanks for the fix @AdamDang !

**Pull request merged**
