### PR TITLE
Update kube-router to 0.3.1

### PR DESCRIPTION
**Pull request by combor**
Bump kube-router version to v 0.3.1. This version includes various security fixes and performance improvements.

### CODE REVIEW

**Comment by combor** [comment]
I think we can close https://github.com/kubernetes/kops/pull/7026 as this one replicates it but I have signed the CLA.

**Comment by rifelpet** [comment]
Thanks for the contribution!

You'll need to update the version defined here so that Kops knows to apply the new version of the manifest:

https://github.com/kubernetes/kops/blob/44723c35cfbf8e093b08db6533c6a88c099761dc/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L962

`0.3.1-kops.1`

/ok-to-test

**Comment by combor** [comment]
Sure, done.

**Comment by combor** [comment]
Hi, Is this OK to go ?

**Comment by justinsb** [comment]
Thanks @combor!

/approve
/lgtm

**Pull request merged**
