### PR TITLE
add os.RemoveAll err verification

### PR DESCRIPTION
**Pull request by zhouhao3**
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>

### CODE REVIEW

**Comment by johngmyers** [comment]
@zhouhau3 Thank you for your PR. I appreciate efforts to improve the tests.

Unfortunately, this particular change does not bring a lot of value. The failure it is checking for neither indicates a problem in the code under test nor would it invalidate a successful test result. It adds the cost of code complexity to negligible benefit.

I would suggest that your time and the time of the reviewers would be better spent on a different class of improvement. Perhaps you could pick an issue from https://github.com/kubernetes/kops/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by zhouhao3** [comment]
@johngmyers Okay, I will focus on these issues you mentioned in the future, thank you for your suggestion.

**Comment by justinsb** [comment]
Going to merge this one; these sorts of things can be a good way to get into the codebase - thanks @zhouhao3 and looking forward to seeing what you tackle next :-)  I always find fixing problems you're encountering yourself is a good way to proceed, particularly if you're trying to do something a little different which other people might not yet have encountered.

/approve
/lgtm

**Pull request merged**
