### PR TITLE
Fix terraform output of shared subnets

### LINKED ISSUE #1977: Terraform output for additional security groups is broken
I want to attach additional security groups to my nodes. Therefore I did a `kops edit ig nodes` and added the following:

```yaml
 spec:
   additionalSecurityGroups:
   - sg-abcd1234
```

When running version 1.5.1 of kops the terraform output is not updated correctly, which seems to be fixed with PR #1854. So I tried the same with the current master version. However, the corresponding terraform output looks like this:

```
security_groups             = ["${aws_security_group.nodes-staging-k8s-gridx-de.id}", "${aws_security_group.sg-abcd1234.id}"]
```

As expected terraform fails because the `aws_security_group.sg-abcd1234` does not exist in the terraform config. 

I think this might be caused by commit 5bba483a611e05adaf4bd92daaaa611bbe9af3a6, which removes the part introduced by the PR:

```
 -     for _, sg := range e.AdditionalSecurityGroupIDs {
 -		tf.SecurityGroups = append(tf.SecurityGroups, terraform.LiteralFromStringValue(sg))
 -	}
```

and instead creates a `awstasks.SecurityGroup` for every additional security group like this:

```
+                    for _, id := range ig.Spec.AdditionalSecurityGroups {
 +				sgTask := &awstasks.SecurityGroup{
 +					Name:   fi.String(id),
 +					ID:     fi.String(id),
 +					Shared: fi.Bool(true),
 +				}
 +				if err := c.EnsureTask(sgTask); err != nil {
 +					return err
 +				}
 +				t.SecurityGroups = append(t.SecurityGroups, sgTask)
 +			}
```

And an `awstasks.SecurityGroup` itself is rendered using `aws_security_group.<name>.id`.

I would sent a PR myself, however, I'm not sure how to fix this the best way...

### PR DESCRIPTION
**Pull request by justinsb**
Also add a test

Fix #1977

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1987)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
CI does not appear happy

**Comment by geojaz** [comment]
@justinsb Something weird is going on here and I'm not sure how to debug. Would you mind sharing? :) It compiles on my machine and LGTM otherwise but need to sort out CI

```
go test k8s.io/kops/dns-controller/pkg/... -args -v=1 -logtostderr
ok  	k8s.io/kops/dns-controller/pkg/dns	0.005s
ok  	k8s.io/kops/dns-controller/pkg/util	0.003s
?   	k8s.io/kops/dns-controller/pkg/watchers	[no test files]
go test k8s.io/kops/cmd/... -args -v=1 -logtostderr
# k8s.io/kops/cmd/kops
cmd/kops/integration_test.go:61: not enough arguments in call to runTest
FAIL	k8s.io/kops/cmd/kops [build failed]
?   	k8s.io/kops/cmd/kops/util	[no test files]
?   	k8s.io/kops/cmd/nodeup	[no test files]
make: *** [test] Error 2
The command "make ci" exited with 2.
Done. Your build exited with 1.
```

**Comment by geojaz** [comment]
@justinsb Any news on this? I'd like to get this in for 1.5.2. Can you fix the tests and please show me how you did it for my education?

**Comment by justinsb** [comment]
You're implying I have the answers @geojaz ... were that were true.

I think travis was building SHA d813cc2, which was not the version I pushed most recently.  The failing line is also a comment in the latest code, and doesn't match the error message.

I suspect I pushed two commits - one with a mistake, and then I fixed and pushed again.  But travis was still testing the first.

Normally opening & closing would fix that, though it appears not in this case.

Instead I rebased my branch onto `origin/master`, and then pushed that.  Travis then saw that change, built in and gave more sensible errors...  (and I just had to fix a merge conflict)

**Pull request merged**
