### PR TITLE
Update to golang v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**
Relates to https://github.com/Homebrew/homebrew-core/pull/44774

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @chenrui333 thanks so much for submitting, unfortunately kops has to keep it's versions in line with the overall Kubernetes version, which is why we specify kops 1.14 needs to be built with the same version as Kubernetes 1.14 (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#notable-features) which is go1.12. What's the issue with 1.12 and Catalina?

**Comment by mikesplain** [comment]
Oh we don't lock ours to 1.12, I'll ammend.

**Comment by chenrui333** [comment]
Totally make sense, I will close the PR now.

**Comment by chenrui333** [comment]
If just the brew build issue (i.e. `brew install` issue) with Catalina, we can still go for the merge.

Otherwise if it is the test failure, we need to fix with the Catalina build.

**Comment by chenrui333** [comment]
> Oh we don't lock ours to 1.12, I'll amend thanks!

Sounds like we can still go with 1.13 for the build, right?

I am mostly thinking from the build perspective.

**Comment by rifelpet** [comment]
Now that we released Kops 1.15 and are targeting 1.16, we were able to land the Go 1.13 upgrade in #7973 but we appreciate the thought!
/close

**Pull request closed without merging**
