### PR TITLE
changed weave logs to warning instead of info

### PR DESCRIPTION
**Pull request by prune998**

### CODE REVIEW

**Comment by justinsb** [comment]
@prune998 is there any reason/issue I can point to to justify the change?

Or @bboreham (as a weave-person) do you agree should we make `--log-level=warning` the standard configuration?

**Comment by prune998** [comment]
unless you want to deal with TONS of INFO level logs on your prod k8s cluster, you should consider logging warnings only.
Let me also point that weave-npc log DEBU(G) too, which, as far as I understant, can be changed by adding a WEAVE_DEBUG="" env variable ? right ?

**Comment by bboreham** [comment]
I would expect tons of logs in DEBUG mode from `weave-npc`, which won't be affected by this change, but if you are getting tons of logs from the `weave` container then something is broken.

Please raise an issue at https://github.com/weaveworks/weave/issues/new

**Comment by prune998** [comment]
@bboreham could you please confirm how to stop DEBU(G) messages from `weave-npc` ?

**Comment by bboreham** [comment]
You'd want to add that flag to the other container.

E.g.

```
        - name: weave-npc
          image: 'weaveworks/weave-npc:2.0.1'
          args:
            - --log-level=info
```

Arguably we (Weaveworks) should change the default, but there always seems a chance someone is going to show up next week with a bug where we need that information.

**Comment by justinsb** [comment]
So perhaps we should set both `--log-level` flags, and then they will be there explicitly, which will be a little easier to change to debug mode.  Personally I'd be fine with info or warning for both.

/ok-to-test

This PR therefore looks good, but I don't know if you want to add explicit log-level configuration to the other weave components @prune998 before I lgtm it?

In any case though, we also need to update the weave version in bootstrapchannelbuilder.go https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L308 .  And would you mind also applying the same changes to the `pre-k8s-1.6.yaml` version of the manifest also?

Bumping the version is tricky; it is currently `2.0.1`, but that is still the latest version.  semver doesn't understand the idea of a "post-release", so we should probably mark it `2.0.2-kops.1` as we did with calico:

```
// calico:
		// 2.1.2-kops.1 = 2.1.1 with CIDR change
		version := "2.1.2-kops.1"
```

**Comment by prune998** [comment]
just updated the PR to add a configurable `loglevel`  value in the deployment template. I also updated the documentation so people are aware of this option

Anything else I could do ?

**Comment by justinsb** [comment]
So I really like the idea of exposing this option.  It's actually a little involved wiring this up though - see https://github.com/kubernetes/kops/pull/3190/files for an example (but note that most of the code there is generated by `make apimachinery`).

Can I suggest picking a level more or less arbitrarily (your choice), and hard-coding it.  And then ping me if you want to work through setting it up as an API field (which would be great!)

I think though you do need to:

* Hard code the version in both manifests (k8s-1.6 and pre-k8s-1.6)
* update the version in bootstrapchannelbuilder to `2.0.2-kops.1`

But that should be all then :-)

**Comment by prune998** [comment]
giving a look at it right now. will ping back when done. Thanks

**Comment by prune998** [comment]
I think I'm done but don't really have a way to test it...  
I updated bootstrapchannelbuilder to 2.0.2-kops.1 but did not changed the Weave docker image version...

**Comment by prune998** [comment]
Sorry I don't have time for this right now. 
If the change is too long to process so I need to rebase many times, it's a sign there is an issue with Kops architecture.
I'm moving to Google Cloud and stop using Kops. 
It was a so simple PR at the beginning, I'm really sad it went that big just to be able to stop the INFO logs...
Sorry.

**Comment by justinsb** [comment]
Sorry this one didn't work out @prune998 - I was suggesting hard-coding the values because making them dynamic requires touching all the various layers of the system and is a hard place to start.  You did get really far with it though and it's really close - I've been meaning to come back to this for the final pieces, but things have been a little busy with 1.8...

**Comment by bboreham** [comment]
> stop the INFO logs

I'd really like more detail on the circumstances that led to this desire, please.

I see why you wouldn't want DEBUG logs in a big install, but if INFO is too much it's either a bug in the software or a broken install.

**Comment by prune998** [comment]
@bboreham I had tons of logs from Weave network driver, with only informations in them... I don't really remember, but it was mac address disappearing and stuff like that.
Maybe it was my install that was broken, but I really don't see the usage of INFO logs in production.

Either it is working and I don't need them, or they correlates to an issue, and they should be WARN or ERROR.

My first proposal was to hard code them to WARN, and I was asked to make it dynamic, which I tried and failed. 
As it sounds I mostly did a good PR, I suggest you go on with it and rebase it yourself. In any way, next time I have to use kops, I'll go with Calico and get rid of weave driver.

more generally, I'm really amazed how everything around K8s/Kops/Helm almost never take care of logging levels. I have tons of PRs of Helm Charts to solve that...

**Comment by bboreham** [comment]
I guess we have different experiences trying to piece together a history of what went wrong from information available later.

**Comment by justinsb** [comment]
Going to close this - please reopen / ping if that's not correct.

**Comment by bboreham** [comment]
FYI I did some work to trim the debug level https://github.com/weaveworks/weave/pull/3183

**Comment by prune998** [comment]
thanks @bboreham

**Pull request closed without merging**
