### PR TITLE
Configure DockerVersion in Docker Spec

### PR DESCRIPTION
**Pull request by justinsb**
And automatically choose 1.12.3 for k8s >= 1.5, 1.11.2 for < 1.5

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1209)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
CI is not happy.  Also this smells like more than just docker 😀

**Comment by justinsb** [comment]
Test coverage on the cloudup side https://github.com/kubernetes/kops/pull/1209/files#diff-54b089917fdadd64900e55cb6f81c8e4 , no test coverage (yet) on the nodeup side

I want to try to figure out a nice way to do something on the nodeup side, similar to what we now do on the cloudup side...

**Comment by chrislovecnm** [comment]
I am wonder if the user provides a custom image, and the image has the correct version of docker installed, should we make any tweaks?  Checking the code if you are doing that.

**Comment by chrislovecnm** [comment]
Centos7 and RHEL are going to tend towards using lvm for docker storage, do we support that?

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
