### PR TITLE
pkg/apis/kops: Allow configuring dockerd --max-* upload and download concurrency and retry options.

### PR DESCRIPTION
**Pull request by anthonyrisinger**
YAML config options are maxConcurrentDownloads, maxConcurrentUploads, and maxDownloadAttempts.
Defaults are maxConcurrentDownloads=3, maxConcurrentUploads=5, and maxDownloadAttempts=5.

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
Same patch with all tests passing is here (only author/committer email is different) https://github.com/ZipRecruiter/kops/actions/runs/1230217292

**Comment by johngmyers** [comment]
What's the use case for setting `max-concurrent-uploads`?

**Comment by johngmyers** [comment]
Needs to update the v1alpha3 API as well, now that #12406 has merged.

**Review by hakman — APPROVED** [review]
Thanks @anthonyrisinger!
/test pull-kops-e2e-cni-calico-ipv6

**Pull request merged**
