### PR TITLE
Refactor lyft config file to Go code

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by olemarkus** [comment]
Thanks for this!
This template stuff just for the lyft plugin was bothering me as well.

**Comment by hakman** [comment]
I am very happy to see this one go too. I think now we can even remove the tags usage from NodeUp. 🍾

**Comment by johngmyers** [comment]
And thanks @olemarkus for extracting `LoadLyftTemplateFunctions()` into `lyft.go`. It made this much easier than the first time I attempted it.

**Pull request merged**
