### PR TITLE
aws: Use instance metadata to get warm pool state

### PR DESCRIPTION
**Pull request by rifelpet**
This should eliminate some of the API throttling during scale tests and help with time for nodes to join the cluster

See the example userdata [here](https://docs.aws.amazon.com/autoscaling/ec2/userguide/tutorial-lifecycle-hook-instance-metadata.html#instance-metadata-create-hello-world-function) for usage of this instance metadata endpoint. I confirmed the 404 behavior works on non-ASG instances.

### CODE REVIEW

**Comment by rifelpet** [comment]
Apparently we dont have a presubmit job to test warmpool behavior, just [this](https://testgrid.k8s.io/kops-misc#kops-warm-pool) periodic. but that job should make it clear if this cause any regressions.

**Comment by hakman** [comment]
@rifelpet Could you add the changes from https://github.com/kubernetes/kops/pull/16212 into this?

**Comment by rifelpet** [comment]
> @rifelpet Could you add the changes from #16212 into this?

done

**Review by hakman — APPROVED** [review]

**Pull request merged**
