### PR TITLE
dns: use resolved region rather than re-resolving every time

### PR DESCRIPTION
**Pull request by justinsb**
This should allow the fallback behaviour to work as expected.

### CODE REVIEW

**Comment by justinsb** [comment]
/hold

As I'm not very sure about this

**Comment by rifelpet** [comment]
I want to make sure we dont reintroduce https://github.com/kubernetes/kops/issues/16645

My initial idea for this fix was to only include the `awsconfig.WithEC2IMDSRegion()` call if IMDS is available - that is if `imdsClient.GetRegion()` returns a nil error.

**Comment by justinsb** [comment]
> My initial idea for this fix was to only include the awsconfig.WithEC2IMDSRegion() call if IMDS is available - that is if imdsClient.GetRegion() returns a nil error.

Ah - that does sound like a better approach than mine here!  Do you want to send a PR, or if you want I can adapt this one?

**Comment by rifelpet** [comment]
Feel free to test my theory in this PR :)

**Comment by rifelpet** [comment]
Looks like this didn't fix the problem:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-addon-resource-tracking/1827929845212909568

```
Error: error reading cluster configuration "e2e-c0d41e2af2-13250.tests-kops-aws.k8s.io": error reading s3://k8s-kops-ci-prow-state-store/e2e-c0d41e2af2-13250.tests-kops-aws.k8s.io/config: Unable to list AWS regions: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
CredentialsEndpointError: invalid endpoint host, "169.254.170.23", only loopback hosts are allowed.
Error: exit status 1 
```

**Pull request merged**
