### PR TITLE
Add comment about IAM roles in case of master/slave zones

### PR DESCRIPTION
**Pull request by icicimov**
Addresses https://github.com/kubernetes/kops/issues/2825

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@icicimov you mind signing our CLA?

**Comment by icicimov** [comment]
@chrislovecnm CLA done.

**Comment by icicimov** [comment]
@chrislovecnm ok I think the PR was submitted with wrong email address. Should we delete one and submit a new one with correct email?

**Comment by chrislovecnm** [comment]
Thanks!

**Pull request closed without merging**
