### PR TITLE
fix function comment error

### PR DESCRIPTION
**Pull request by jonyhy96**
fix function comment error
```release-note
None
```

### CODE REVIEW

**Comment by justinsb** [comment]
/lgtm

/ok-to-test

Thanks @jonyhy96

**Comment by jonyhy96** [comment]
@justinsb
 It seems like some tests has failed 
Please help me to check it out

**Comment by jonyhy96** [comment]
@chrislovecnm Can u help me to fix this ?

**Comment by chrislovecnm** [comment]
First you need to rebase and squash your PR.  Then if the tests fail you will want to look at the details links next to the test that fails. Here on the page is where I am talking about:

screen shot 2018-03-25 at 8 58 55 am

**Comment by jonyhy96** [comment]
@justinsb i already fix the conflit and please check this out

**Comment by jonyhy96** [comment]
@chrislovecnm Thanks a lot for your help. I'll try to fix this

**Comment by jonyhy96** [comment]
@justinsb Please label lgtm to this PR

**Comment by mikesplain** [comment]
@jonyhy96 it looks like there's no actual changes in your PR anymore. Seems like something is wrong, at least in github?

**Comment by jonyhy96** [comment]
@mikesplain Thanks for your reply 
I find that justinsb has chagned the name of the function so my PR now seems make no sense 
close it

**Pull request closed without merging**
