### PR TITLE
use the private dns name first if it resolves

### PR DESCRIPTION
**Pull request by polarbizzle**
We've been using the private dns type on all our clusters and have set up dns such that it resolves properly in all the places it needs to. I tried running the latest 1.9.0-alpha.1 build on our sandbox cluster yesterday. It issued a new master cert but then unfortunately when I try to do rolling-update it fails because all the current masters are using the old cert. I suppose as a workaround I could just rotate the masters manually one at a time. This manual step is going to make my cluster upgrades in production a bit more stressful though.

 To avoid failure on the first rolling update, we can check to see if the private dns resolves correctly where we're running kops from and if so, use that.

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks for the contribution @polarbizzle! This looks good to me, though I'm not sure if there may be implications? Mind taking a look @chrislovecnm 
/lgtm
/assign @chrislovecnm

**Comment by justinsb** [comment]
We definitely need to fix this.  I'm concerned that a transient DNS flake might be problematic with this particular workaround - trying to think of alternatives.

**Comment by polarbizzle** [comment]
We've done quite a bit of work to make our internal dns servers forward to the Amazon resolvers. It's probably true that this is somewhat flakier than the internal elb name from amazon but it doesn't seem like it will a lot flakier. We depend on our internal dns working for more than kops. If transient dns failures cause a rolling update to fail at some point, it should be fine to just restart the rolling update. We've noticed that restarting for other reasons (more specifically the aws credentials expiring on rolling update of large clusters) just picks up where it left off no problem.

**Comment by justinsb** [comment]
Question @polarbizzle - is your LoadBalancer of type Internal or type Public?  I'm thinking maybe that is how we can reliably tell the two cases apart.

**Comment by polarbizzle** [comment]
all our api ELBs are internal

**Comment by justinsb** [comment]
Thanks @polarbizzle - I pushed up #4748 which I think is probably a safer heuristic (because DNS is notoriously flaky - I'm more worried about everybody else's DNS than I am yours :-) ).  Want to take a look?

I'm also going to look at the multiple certificates issue.  We are _supposed_ to be able to have multiple certificates.  One option there might be not to include the ELB in the certificate in this case, but we'll see.

**Comment by polarbizzle** [comment]
👍 thanks

**Pull request closed without merging**
