### PR TITLE
Support setting --dynamic-config-dir to enable dynamic kubelet configuration

### PR DESCRIPTION
**Pull request by chotiwat**
This PR allows us to set `--dynamic-config-dir` flag via `dynamicConfigDir` field in the kubelet component config. The directory setting is required to enable dynamic kubelet configuration.

### CODE REVIEW

**Comment by chotiwat** [comment]
@rifelpet @zetaab @chrislovecnm It seems like all tests passed. Is there anything else I need to do on my end?

**Comment by lgg42** [comment]
Can't wait for this to be merged 😍

**Comment by mat285** [comment]
Any update on this?

**Pull request closed without merging**
