### PR TITLE
Upgrade Amazon VPC CNI to 1.6.3

### PR DESCRIPTION
**Pull request by MoShitrit**
Ref: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.6.3

### CODE REVIEW

**Comment by rifelpet** [comment]
> pull-kops-e2e-cni-amazonvpc Pending — Job triggered.

👀

**Comment by MoShitrit** [comment]
@rifelpet all tests passed :tada:

**Comment by rifelpet** [comment]
👍 we'll have to figure out those teardown failures, i think thats happened in the periodic jobs too

/lgtm
/approve

**Pull request merged**
