### PR TITLE
Don't install the misc packages for k8s 1.20+

### PR DESCRIPTION
**Pull request by johngmyers**
I intend to make the boundary be 1.20, but the e2e tests are currently configured with 1.19.

### CODE REVIEW

**Review by hakman — COMMENTED** [review]
> I intend to make the boundary be 1.20, but the e2e tests are currently configured with 1.19.

Any special reason not to start with 1.19?

I would move the "nfs-*" packages to `packages.go` and skip `miscutils.go` completely.

**Comment by johngmyers** [comment]
It didn't seem that the benefit from this merited backporting to the 1.19 branch.

**Comment by hakman** [comment]
Sounds good to me. Thanks.
/lgtm

**Pull request merged**
