### PR TITLE
Fix misspellings 📝

### PR DESCRIPTION
**Pull request by onlydole**
Update misspellings of "parallel" and "consistency"

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2632)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@onlydole that documentation is actually generated from code

1. get kops building
2. edit https://github.com/kubernetes/kops/blob/master/cmd/kops/create_cluster.go
3. make gen-cli-docs

**Comment by chrislovecnm** [comment]
@onlydole you will need to sign our CLA as well ... please and thanks

**Comment by onlydole** [comment]
@chrislovecnm - I digitally signed and filled out the CLA via the Linux Foundation link, is there anything more you need beyond that?

**Comment by chrislovecnm** [comment]
It just picked it up :)

**Comment by onlydole** [comment]
Oh perfect! Thank you sir, I'll close this PR and get those changed as noted! 👍

**Pull request closed without merging**
