### PR TITLE
Cilium hubble pointer

### LINKED ISSUE #9966: Inaccurate instructions for enabling Cilium
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.19.1

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster --name foo.k8s.local --node-count 1 --master-count 1 --zones us-west-2a --cloud aws
kops edit cluster --name foo.k8s.local # see details below
```
**5. What happened after the commands executed?**
`edit cluster` failed
**6. What did you expect to happen?**
`edit cluster` to succeed
**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-09-17T20:04:28Z"
  generation: 2
  name: foo.k8s.local
spec:
  api:
    dns: {}
  authentication:
    aws:
      backendMode: CRD
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://tune-kops-state-us-west-2/foo.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 67.4.208.203/32
  kubernetesVersion: 1.19.0-rc.1
  masterInternalName: api.internal.foo.k8s.local
  masterPublicName: api.foo.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      hubble: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 67.4.208.203/32
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

The [docs](https://kops.sigs.k8s.io/networking/cilium/#installing-cilium-on-a-new-cluster) mention that enabling cilium just requires:

```yaml
spec:
  networking:
    cilium: {}
```

but the following error is reported when using this cluster spec:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
# ...
#     networkCIDR: 172.20.0.0/16
#     networking:
# -     cilium:
# +     cilium: {}
# -       hubble: {}
#     nonMasqueradeCIDR: 100.64.0.0/10
#     sshAccess:
# ...
```

It seems like we should either make the hubble field optional by making it a pointer, or update the docs to include `hubble: {}`

### PR DESCRIPTION
**Pull request by olemarkus**
Fixes #9966 

/cc @hakman @rifelpet

### CODE REVIEW

**Comment by hakman** [comment]
Would it be a better idea to flatten the struct? Seems that the Hubble thing is the only one.
Something like: https://github.com/hakman/kops/commit/490da2046650637f40f5ebd186f6a07b5c67eb6c

**Comment by olemarkus** [comment]
> Would it be a better idea to flatten the struct? Seems that the Hubble thing is the only one.
> Something like: [hakman@490da20](https://github.com/hakman/kops/commit/490da2046650637f40f5ebd186f6a07b5c67eb6c)

You would need both HubbleEnable and HubbleEnableMetrics.
The primary use case for hubble is to attach hubble-ui or similar to it and view things like service graphs and such. EnableMetrics just enables some prometheus metrics in addition like number of drops per service etc.

**Comment by hakman** [comment]
HubbleMetrics is an array, enable/disable can be based on number of items. In any case, was just a suggestion. Structs seems to complicate templates.

**Comment by olemarkus** [comment]
So HubbleMetrics already determines if _prometheus_ metrics should be enabled or not by the number of items. But one may want to enable hubble without any prometheus metrics enabled.

**Comment by hakman** [comment]
OK, I understand. It was not meant as an alternate PR, just a suggestion.
The point was not to complicate the code unnecessarily with extra structs and pointer validations. I don't mind either way.

**Comment by olemarkus** [comment]
Yep. Thanks for the suggestion :) 
As long as one uses options builders, one can get away with quite a bit of pointer checks. More annoying that any non-nil bool pointer is evaluated as true by sprig ...

**Pull request merged**
