### PR TITLE
simple -> simply

### PR DESCRIPTION
**Pull request by nckturner**

### CODE REVIEW

**Comment by kris-nova** [comment]
Solid find - LGTM

**Comment by nckturner** [comment]
Thanks, I can't seem to get the email from the linux foundation though :(

**Comment by kris-nova** [comment]
@nckturner - It takes a little longer than the google SLA - just be patient and we will get it in ASAP

**Comment by chrislovecnm** [comment]
Any email from the Linux Foundation?

**Comment by nckturner** [comment]
Yup, and looks like the CLA was finally authorized as well.

**Pull request merged**
