### PR TITLE
let aws command output json

### PR DESCRIPTION
**Pull request by zouguangxian**

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @zouguangxian! Thanks for the PR, can you sign the CLA? Good news is once you take care of it it applies to all CNCF projects.  

Reply back here once it's taken care of and the bot will check again. Thanks!

**Comment by zouguangxian** [comment]
I want to sign the CLA, can you resend it to me ?

**Comment by justinsb** [comment]
Thanks - this is a good fix for people that have a different default.  (And I think the default default is text, so I'm guessing that is most people!)

/approve
/lgtm

**Pull request merged**
