### PR TITLE
Reduce CPURequests, so we can run on 1 core machine

### LINKED ISSUE #776: Need to reduce cpu requests on master
We don't have enough CPU left for a weave/calico daemonset.

Compounded by kubernetes/kubernetes#31369 when using a machine with a single core.

### PR DESCRIPTION
**Pull request by justinsb**
Fix #776

### CODE REVIEW

**Comment by kris-nova** [comment]
@justinsb - Can you get back to @chrislovecnm and then we can merge in :)

**Comment by justinsb** [comment]
They're requests, not limits.  Not sure exactly what you're saying @chrislovecnm

**Comment by chrislovecnm** [comment]
Cool ... I understand now.  Merging.

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
