### PR TITLE
Removed deprecated secrets command subtree from CLI and docs

### PR DESCRIPTION
**Pull request by WillemMali**
This solves #2519

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2563)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@justinsb merge now or after 1.6?

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
After 1.6.0 - it is cleanup, right?

**Comment by chrislovecnm** [comment]
Yes this is house cleaning

**Comment by chrislovecnm** [comment]
Can we get a rebase, and we can merge

**Comment by chrislovecnm** [comment]
The master build is a bit broke right now, so that is the problem ;)

**Comment by WillemMali** [comment]
Great, that means I can take it off my mental checklist for now.

Good luck fixing master!

**Comment by chrislovecnm** [comment]
When https://github.com/kubernetes/kops/pull/2582 is merged please rebase

**Pull request merged**
