### PR TITLE
Replace custom codegen package with gengo

### PR DESCRIPTION
**Pull request by johngmyers**
This uncovered that the OpenStack `SecurityGroupRule` task had hand-edited "generated" code. ~~My attempt to fix it may well be incorrect.~~

/kind cleanup

### CODE REVIEW

**Comment by johngmyers** [comment]
The verify-gomod failure has me stumped.

**Comment by hakman** [comment]
I guess this solves the mystery of why dependencies were flaky with launch templates.

**Comment by hakman** [comment]
> The verify-gomod failure has me stumped.

`make gomod` contains a few workaround and replaces `go mod vendor`. You should be ok just running that and pushing the changes. I did a quick test in https://github.com/kubernetes/kops/pull/9634 and seems fine.

**Comment by johngmyers** [comment]
I'm not confident of my change to `SecurityGroupRule`. The requirement appears to be for every `Task` to have a unique value in a field called `Name`. I'd appreciate a PR before this one that adds that field and modifies all the code that creates a `SecurityGroupRule` to supply it.

@zetaab @olemarkus

**Comment by johngmyers** [comment]
Since the `SecurityGroupRule` boilerplate was hand-edited, moved it out of the `_fitask.go` file.

**Comment by rdrgmnzs** [comment]
This is great, thank you @johngmyers !

/lgtm
/approve

**Comment by hakman** [comment]
In case @johngmyers wants some feedback from @zetaab or @olemarkus .
/hold

**Comment by johngmyers** [comment]
I moved the hand-edited `SecurityGroupRole` boilerplate out of scope, so I no longer need feedback from @zetaab or @olemarkus. It can either remain out of scope or be moved back to being autogenerated in a later PR.

/hold cancel

**Pull request merged**
