### PR TITLE
Add support for docker 17.09.0 version

### PR DESCRIPTION
**Pull request by dvavili**
Add support for docker version 17.09.0 version

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Thanks for your PR!

We already include the correct version of docker for Kubernetes 1.8, which version is this for?  You are able to set the docker version as well. #sig-node certifies the different docker versions.

/assign @justinsb

**Comment by dvavili** [comment]
From my understanding, the docker version needs to be part of this list to be set explicitly in the cluster spec. This is my use-case - I'm trying to run P3 instances on AWS with nvidia-docker2 and nvidia-docker:2.0 is dependent on 17.09.0 features. Would be good to have this version supported.

**Comment by dvavili** [comment]
I also hit a couple of issues with P3 instances because of the driver version. Will raise a PR to address that as well.

**Comment by justinsb** [comment]
Makes sense - thanks @dvavili .  @chrislovecnm is right that we don't want to change the default, but you're right that mapping it doesn't change the default and is required for people to specify that docker version (e.g. if you suspect a problem fixed in a later docker version).

Apparently we should be using device plugins, BTW, but I haven't really looked into this:

https://github.com/kubernetes/kubernetes/issues/54011

/ok-to-test
/lgtm

**Pull request merged**
