### PR TITLE
Update kops as kOps and remove extra spaces from .md files

### PR DESCRIPTION
**Pull request by axpraka**
Minor updates in documentation. Below are two changes which I am suggesting in few .md files.
- Updated kops as kOps in .md files.
- Remove extra spaces from .md files

### CODE REVIEW

**Comment by axpraka** [comment]
I signed.

**Comment by hakman** [comment]
Very nice update! Thanks for fixing all these.
The `docs/cli` files are generated from `cmd/kops`. Please update those also to pass the tests.
/ok-to-test

**Comment by hakman** [comment]
Do you need help, @axpraka ?

**Comment by axpraka** [comment]
@hakman - yes. Can you tell me why it is failing at CI/verify? Is this because of file conflict?

**Review by hakman — CHANGES_REQUESTED** [review]
You have to run `make gen-cli-docs` and commit the changes, or check the log file and see what changes differ between the .go files and the .md files.

**Comment by hakman** [comment]
I regenerated the CLI docs and the tests should pass now. Could you take one last look to see if it looks right?
A preview of the changes should be available here: https://5fafe4e0236b120007071fe6--kubernetes-kops.netlify.app.

**Comment by axpraka** [comment]
@hakman thanks for helping with conflicts. I checked and it looks fine now.

**Comment by hakman** [comment]
Great! Thanks for checking.
/lgtm
/approve

**Pull request merged**
