### PR TITLE
Fixed duplicate info

### PR DESCRIPTION
**Pull request by marceliwac**
Fixed duplicate info about default value for --topology flag

### CODE REVIEW

**Comment by marceliwac** [comment]
CLA verification check

**Comment by mikesplain** [comment]
Hi @marceliwac! Thanks for the contribution! That's a great find, we definitely should get that cleaned up.  

Those docs are actually autogenerated from here: https://github.com/kubernetes/kops/blob/617ce047e6ae194a058de12cabdce0696f5509d9/cmd/kops/create_cluster.go#L313:69

Mind making the change there as well? It also looks like we have the same thing for the dns flag: https://github.com/kubernetes/kops/blob/617ce047e6ae194a058de12cabdce0696f5509d9/cmd/kops/create_cluster.go#L319

To make those changes:

1. Clone the repo locally
2. Make the changes to the go file
3. run `make gen-api-docs`
4. checkin the resulting code.

Let me know if you need any further help!

/area documentation
/ok-to-test

**Comment by mikesplain** [comment]
/assign 
/unassign @chrislovecnm 

(unassigning Chris till things are good to go!)

**Comment by mikesplain** [comment]
Hi @marceliwac any update on this?

**Comment by justinsb** [comment]
Going to force-merge and then submit the source change.  Thanks for spotting @marceliwac !

**Pull request merged**
