### PR TITLE
Automated cherry pick of #7961: Initial work

### PR DESCRIPTION
**Pull request by srikiz**
Cherry pick of #7961 on release-1.16.

#7961: Initial work

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by srikiz** [comment]
@rifelpet - Can you please help why this e2e tests are failing. Am I missing something here?

**Comment by rifelpet** [comment]
Yea, its a bug in our E2E setup. It should be fixed if https://github.com/kubernetes/kubernetes/pull/85929 gets merged. If it doesnt get accepted we'll disable the `pull-kops-e2e-kubernetes-aws-1-16` job. I'm hoping to get this straightened out at the kops office hours tomorrow.

**Pull request merged**
