### PR TITLE
Update aws-sdk-go to support new AWS SSO profile

### PR DESCRIPTION
**Pull request by avdhoot**
Fixes: https://github.com/kubernetes/kops/issues/15308

### CODE REVIEW

**Comment by johngmyers** [comment]
@avdhoot the test failures, particularly that for pull-kops-verify-gomod, are valid.

**Comment by hakman** [comment]
@avdhoot Please also squash the commits and change the message to be without "Fix 15308".

**Review by johngmyers — APPROVED** [review]

**Pull request merged**
