### PR TITLE
Update containerd to v1.6.0-beta.2

### PR DESCRIPTION
**Pull request by hakman**
Ref: https://github.com/containerd/containerd/releases/tag/v1.6.0-beta.2

This release comes with official ARM64 builds.
The [plan](https://github.com/kubernetes/kops/pull/11913) was to default to a newer version than 1.4 for some time now, but the ARM64 situation was blocking it.
Most likely it will come out of beta much sooner than the next kOps release, so would be good to see if it's stable enough to be the default for k8s 1.23.

### CODE REVIEW

**Comment by hakman** [comment]
The ARM64 e2e error is consistent with what we see in periodic tests with current dfault version also:
https://testgrid.k8s.io/kops-misc#kops-aws-misc-arm64-ci
```
[Fail] [sig-apps] Deployment [It] should not disrupt a cloud load-balancer's connectivity during rollout
```

**Comment by hakman** [comment]
https://github.com/kubernetes/kops/pull/12726 was merged earlier today so this should work now.
/test pull-kops-e2e-arm64

**Review by johngmyers — APPROVED** [review]

**Comment by hakman** [comment]
No other feedback, so...
/hold cancel

**Comment by hakman** [comment]
@johngmyers I had to rebase. Would you mind approving one more time? Thanks!

**Pull request merged**
