### PR TITLE
WIP For testing purposes

### PR DESCRIPTION
**Pull request by hakman**
/cc @justinsb

### CODE REVIEW

**Comment by rifelpet** [comment]
@hakman you could try printing the output of `aws autoscaling describe-scaling-activities` on the nodes ASG to see why it isn't scaling all the way to 500

**Comment by hakman** [comment]
@rifelpet As expected:
> "You have requested more vCPU capacity than your current vCPU limit of 384 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit. Launching EC2 instance failed."

**Pull request closed without merging**
