### PR TITLE
kops-change-main

### PR DESCRIPTION
**Pull request by zehuaiWANG**
I do some cleanup in main file and model/utils.go, to make code more cleaner.

### CODE REVIEW

**Comment by hwdef** [comment]
please update the PR introduction,
/ok-to-test

**Comment by tanjunchen** [comment]
> please update the PR introduction,
> /ok-to-test

Agree +1
@zehuaiWANG  An obvious title is better , not "a liitle change" 
/cc @rifelpet @justinsb

**Comment by zehuaiWANG** [comment]
@tanjunchen I add more description to the pr, it's a liitle clean up job.

**Comment by tanjunchen** [comment]
ok. Thanks

**Comment by rifelpet** [comment]
Having all the variables defined together and all the flags defined together does make it easier to read. thanks for the contribution!

/approve
/lgtm

**Pull request merged**
