### PR TITLE
Preliminary support for CentOS7 / RHEL7

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
cc @yissachar if you want to combine with the work you've been doing?

**Comment by yissachar** [comment]
This is great!

This PR actually covers everything I've done so far (in some cases with identical code, which I think is a nice sign that the kops codebase is well structured so that there's usually one logical way to do things). I'll test this out tomorrow.

The only slight nitpick I have is that it seems odd to call RHEL a CentOS, if anything the relationship is the other way around.

**Comment by dlin128** [comment]
Agree with yissachar, Centos is in the RHEL family probably should be flipped.

Also you can use /etc/redhat-release across all rhel family. On centos it's symlinked to /etc/centos-release.

Also I don't understand much of kops yet so I might be wrong about the usage, but generally only repo packages write to /usr/lib/systemd/system. Might want to use /etc/systemd/system?

**Comment by yissachar** [comment]
LGTM

**Comment by justinsb** [comment]
Thanks @yissachar and @dlin128 .  I am going to merge this as it should be nodeup only, so won't hit normal users.  And I think I can publish this version of nodeup before switching kops to it, so people can try it relatively easily if you want to!

**Comment by justinsb** [comment]
If you want to test this before I officially bump kops to use this version of nodeup, you can `export NODEUP_URL="https://kubeupv2.s3.amazonaws.com/kops/1.4.1/linux/amd64/nodeup"`

Do report any issues (and don't forget to unset that env var once we have 1.4.2!)

**Pull request merged**
