### PR TITLE
Remove BLM banner 

### PR DESCRIPTION
**Pull request by hakman**
Banner was already removed from the main Kubernetes site. I think it's time to do the same:
https://github.com/kubernetes/website/blob/87c6923445193d6a5d8b3d029c1f4bb4ee6562cc/data/announcements/scheduled.yaml#L55-L63

/kind office-hours

### CODE REVIEW

**Comment by justinsb** [comment]
We discussed this in office hours; I'm going to put together a "values" page and then we can move this statement to that page.

**Comment by hakman** [comment]
@justinsb Maybe this helps:
https://github.com/kubernetes/community/blob/master/values.md

**Comment by hakman** [comment]
With #11094 this one is unblocked now.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
