### PR TITLE
Export outputs to aid with VPC peering in Terraform

### PR DESCRIPTION
**Pull request by chrissnell**
This small PR adds a few additional Terraform outputs to assist with VPC peering when a kops-generated Terraform configuration is used as a module.

### CODE REVIEW

**Comment by chrissnell** [comment]
@k8s-ci-robot CLA signed.

**Comment by mikesplain** [comment]
Hi @chrissnell Thanks for the PR! For this to pass tests you'll need to update the TF output in our tests as well: https://github.com/kubernetes/kops/tree/master/tests/integration

/ok-to-test

**Comment by chrissnell** [comment]
@justinsb Re: TF output, I don't have the slightest idea what to do here.

**Comment by chrislovecnm** [comment]
/assign @rdrgmnzs 
Are you able to help?  I know you know TF

**Comment by justinsb** [comment]
Once we have #5265 you should be able to just do `HACK_UPDATE_TF_IN_PLACE=1 make test` to have the terraform output automatically fixed in place.  We still need to check it, but it avoids the annoying copying / pasting.

I sent https://github.com/chrissnell/kops/pull/1 which has the updated TF output, along with some simpler naming for the variables (IMO)

**Comment by justinsb** [comment]
Thanks @chrissnell - I think it's good to go :-)

/approve
/lgtm

**Comment by chrissnell** [comment]
Sigh... looks like we failed a Terraform output test again. @justinsb I was unable to get the new stuff from  #5265 to generate new outputs.  Can you help me again?  I guess something changed again upstream.

**Comment by justinsb** [comment]
Yeah - this one was my fault actually - I changed one of the integration tests - sorry.

After a rebase against master, you should now be able to run `HACK_UPDATE_TF_IN_PLACE=1 go test ./cmd/kops` and the expected TF output should be auto-updated.

But it's a bit tricky to juggle all these branches, so I'm just going to force-merge this one and then send a PR to fix master...

**Pull request merged**
