### PR TITLE
Use 0.9.0 release of nginx-ingress-controller

### PR DESCRIPTION
**Pull request by cap10morgan**

### CODE REVIEW

**Comment by justinsb** [comment]
/ok-to-test

I'm thinking we probably want `--annotations-prefix=ingress.kubernetes.io` as well, otherwise there are going to be a lot of surprised users!

Are you able to sign the CLA @cap10morgan - it is a bit of a pain, but then the same CLA applies across all the kubernetes projects.

**Comment by 1810755jiawei** [comment]
-----BEGIN PGP SIGNATURE-----

iQEcBAABAgAGBQJaQPThAAoJEPmLhIS+i/HF87YIAIpVcm0LHXE1Ipq51VNactjh
0HYUAvLIs07YEzTl44UtQreDh56Sv6EpJIaROyjIS8JWc9KELtcIClAPVIgtGlXq
PzcPbIacyAG07tWbM/pv4MlHaQR4LQ89/wC8v0od1AxwsBPWxCG/eVUpk5zs+jjr
PNs3uRz5mqz22ecBPSeV2yGaqbO3a/T0/UE0PoZhIDn2tBuYhmUp9i0X1ifNYNv+
uAg8DxRTdfENHDM49AU9uLMq1oq+vo4lbRwYQzkrHc6d61TT+7G8MnV02mSgrvyu
RIVWAm6eTvVFiYVZMKpheC77m6XzV65YwTMPwF7oRBQRyO7iprsrt7PYjklERRo=
=UnAI
-----END PGP SIGNATURE-----

**Comment by 1810755jiawei** [comment]
END PGP SIGNATURE

**Comment by cap10morgan** [comment]
OK, I think I've signed the CLA. Hopefully this comment will update it.

**Comment by cap10morgan** [comment]
@justinsb Want me to add that annotation prefix change too?

**Comment by mikesplain** [comment]
Thanks @cap10morgan! Good find!

/lgtm

**Comment by chrislovecnm** [comment]
Thanks for the update!!

I noticed that https://github.com/cap10morgan/kops/blob/2ab5f115b3c1369e5599386d61732bd0f0a22ac2/addons/ingress-nginx/addon.yaml is not actually up to date to be used by channels.  I am not going to ask for those changes in this PR, but do you mind making those changes?  Here is an example https://github.com/kubernetes/kops/blob/master/addons/kubernetes-dashboard/addon.yaml

Because of that, I do not know if the new container version will be picked up in existing clusters, we need to actually document how to maintain these addons a bit better.

Thanks

/approve

**Pull request merged**
