### PR TITLE
Add confirmation message upon successful edit

### LINKED ISSUE #1680: No confirmation message for edit cluster
```
$ kops edit cluster
Using cluster from kubectl context: liea-ginny.dev.datapipe.io

I0129 00:28:14.909656   61886 populate_cluster_spec.go:235] Defaulting DNS zone to: Z2PKVP3BDFE581
```

We give out "Defaulting DNS zone" message but nothing about the fact we edited the cluster.

### PR DESCRIPTION
**Pull request by kamilhristov**
Fixes #1680

Also added hints to verify the results in case of failed validation 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1697)

### CODE REVIEW

**Comment by justinsb** [comment]
I am hoping we don't need that "please validate changes" hint... there are a few PRs that might address it in flight.  Just wanted to let you know why I'm not merging yet!

**Comment by yissachar** [comment]
Let's wait for #1741 and #1772 to be resolved, and then circle back to this.

**Comment by kamilhristov** [comment]
Sure, I agree that this message does not feel right. My intention was to warn the user that there might be an issue with editing the resources. Waiting for a more stylish fix... :)

**Comment by justinsb** [comment]
We merged #1741 and #1772.  If you want to make it just say "Edit successful" or similar, I don't think we need to tell people to double-check any more :-)

**Comment by yissachar** [comment]
@kamilhristov Looks like something weird happened here with the history... Can you rebase and clean up? Or alternatively you can close this and open a new PR if that's easier for you.

**Pull request closed without merging**
