### PR TITLE
Add test for float args

### PR DESCRIPTION
**Pull request by justinsb**
We likely need to change from floats to resource.Quantity, so we need
to estabilsh more test coverage before we can safely make the change.

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @rifelpet ... this is for CRD generation - I'm trying out your PR :-)

**Comment by rifelpet** [comment]
Awesome. I noticed the changes to the CRD yamls were more significant than i anticipated. I'm not sure if we need additional markers in the API .go files or if the changes are desired. I can resolve the merge conflicts if you haven't already.

**Pull request merged**
