### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by szemek**
Tiny contribution, fixed typo cluser => cluster.

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @szemek Thanks so much for the contribution! A contribution is a contribution no matter the size! Before we can get started on this, we need you to sign the CLA for CNCF.  Luckily this only has to be done once, and then you'll be good in the future.

**Comment by mikesplain** [comment]
/lgtm

Sorry thought I saw an issue but it’s fine. Thanks!

**Comment by justinsb** [comment]
/approve

Thanks @szemek

**Pull request merged**
