### PR TITLE
[cilium - eni IPAM MODE] problem with connection from POD to external resource in additional subnet after kops upgrade from 1.23 -> 1.25 #14575

### PR DESCRIPTION
**Pull request by glomikuz**
More info here:
https://github.com/kubernetes/kops/issues/14575

### CODE REVIEW

**Comment by glomikuz** [comment]
i will sign

got it , no rush )

**Comment by johngmyers** [comment]
@glomikuz You need to run the script `hack/update-expected.sh` and commit the results.

/test pull-kops-e2e-cni-cilium-ipv6
because it is likely a flake.

**Comment by olemarkus** [comment]
The EBS controller complains about things like this:
```
I1125 09:10:35.534790       1 controller.go:764] CreateVolume failed, supports topology = true, node selected true => may reschedule = true => state = Background: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1125 09:10:35.534830       1 controller.go:1082] Temporary error received, adding PVC ed8ccfc9-9db4-44a4-8e1e-cd9bfd3f8cc4 to claims in progress
W1125 09:10:35.534842       1 controller.go:934] Retrying syncing claim "ed8ccfc9-9db4-44a4-8e1e-cd9bfd3f8cc4", failure 5
E1125 09:10:35.534866       1 controller.go:957] error syncing claim "ed8ccfc9-9db4-44a4-8e1e-cd9bfd3f8cc4": failed to provision volume with StorageClass "provisioning-982-e2e-scrrw7m": rpc error: code = DeadlineExceeded desc = context deadline exceeded
I1125 09:10:35.535363       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"provisioning-982", Name:"ebs.csi.aws.comktzwq", UID:"ed8ccfc9-9db4-44a4-8e1e-cd9bfd3f8cc4", APIVersion:"v1", ResourceVersion:"47858", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "provisioning-982-e2e-scrrw7m": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

This suggests the controller not being able to reach the AWS API.

Note that failing volume tests tend to mean broken pod networking. Reason volumes are particularly affected is that the controller runs on the pod network, while most other components used in the e2e tests are using the host network (KCM and CCM for example).

**Comment by olemarkus** [comment]
I have been looking at this for a few hours now and I cannot really see anything wrong.

Are you able to tell where the traffic may stop?

**Comment by glomikuz** [comment]
hello. sorry fro delay 
Maybe its problem with AWS policies ?

i dont deep dive to cni (

**Comment by glomikuz** [comment]
hello. sorry fro delay 
Maybe its problem with AWS policies ?

i dont deep dive to cni

**Comment by olemarkus** [comment]
Also see #14694 for my experimentation.

It wasn't trivial to get this working. I also had problems getting this to work with 1.10 ...

**Comment by glomikuz** [comment]
closed  by 
https://github.com/kubernetes/kops/pull/14694

**Pull request closed without merging**
