### PR TITLE
CoreDNS version 1.3.0

### PR DESCRIPTION
**Pull request by harshal-shah**
Signed-off-by: Harshal Shah <harshal2623@gmail.com>

Adding latest CoreDNS version to kops.

### CODE REVIEW

**Comment by harshal-shah** [comment]
Will work only once https://github.com/kubernetes/kubernetes/issues/72274 is fixed.

**Comment by vietwow** [comment]
Hi,

looks like kubernetes/kubernetes#72274 is fixed, could we merge this PR ?

Best Regards,
VietNC

**Comment by harshal-shah** [comment]
@rajansandeep is there a way to rerun the CI? I think we should be able to merge this now.

**Comment by harshal-shah** [comment]
@rajansandeep The CI seems to fail with below error; any suggestions on how to fix? 

~~~
warning: ignoring symlink /Users/travis/gopath/src/k8s.io/kops/vendor/github.com/prometheus/procfs/fixtures/self
hack/verify-apimachinery.sh
sh -c hack/make-apimachinery.sh
/Users/travis/gopath/bin/conversion-gen --verify-only --skip-unsafe=true --input-dirs k8s.io/kops/pkg/apis/kops/v1alpha1 --v=0  --output-file-base=zz_generated.conversion \
		 --go-header-file "hack/boilerplate/boilerplate.go.txt"
/Users/travis/gopath/bin/conversion-gen --verify-only --skip-unsafe=true --input-dirs k8s.io/kops/pkg/apis/kops/v1alpha2 --v=0  --output-file-base=zz_generated.conversion \
		 --go-header-file "hack/boilerplate/boilerplate.go.txt"
/Users/travis/gopath/bin/deepcopy-gen --verify-only --input-dirs k8s.io/kops/pkg/apis/kops --v=0  --output-file-base=zz_generated.deepcopy \
		 --go-header-file "hack/boilerplate/boilerplate.go.txt"
F1221 10:12:14.520196    5359 main.go:81] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kops/pkg/apis/kops":
output for "kops/zz_generated.deepcopy.go" differs; first existing/expected diff: 
  "if *in == nil {\n\t\t\t*out = nil\n\t\t} else {\n\t\t\t*out = new(bool)\n\t\t\t**out = **in\n\t\t}\n\t}\n\tif in.Hosts != "
  "*out = new(bool)\n\t\t**out = **in\n\t}\n\tif in.Hosts != nil {\n\t\tin, out := &in.Hosts, &out.Hosts\n\t\t*out ="
make[1]: *** [apimachinery-codegen] Error 255
\n FAIL: - the verify-apimachinery.sh test failed, apimachinery is not up to date
\n FAIL: - please run the command 'make apimachinery'
make: *** [verify-apimachinery] Error 1
The command "make ci" exited with 2.
~~~

**Comment by rdrgmnzs** [comment]
@harshal-shah could you rebase your change? That should fix the apimachinery issues as you are not touching them in this diff.

**Comment by harshal-shah** [comment]
Closing this in favor of https://github.com/kubernetes/kops/pull/6326

**Pull request closed without merging**
