### PR TITLE
Update etcd_backup_restore_encryption.md

### PR DESCRIPTION
**Pull request by aberenshtein**

### CODE REVIEW

**Review by hakman — APPROVED** [review]
Thanks for fixing the typos @aberenshtein.

**Comment by hakman** [comment]
@aberenshtein Please sign the CLA so that we can merge this.
/lgtm cancel

**Comment by aberenshtein** [comment]
I signed it

**Comment by aberenshtein** [comment]
@hakman signed

**Comment by hakman** [comment]
Thanks!
/lgtm

**Pull request merged**
