### PR TITLE
fix-up bug in nodeup/pkg/model

### PR DESCRIPTION
**Pull request by tanjunchen**
fix-up some gosimple errors
@justinsb  @zetaab  can you help  me review these changes?Thanks!

### CODE REVIEW

**Comment by tanjunchen** [comment]
@zetaab

**Comment by tanjunchen** [comment]
@mikesplain

**Comment by tanjunchen** [comment]
@yuxiaobo96

**Comment by tanjunchen** [comment]
@mikesplain can you help me review this pr? Thanks

**Comment by justinsb** [comment]
Thanks @tanjunchen - nice spot on the flag name!

/approve
/lgtm

**Pull request merged**
