### PR TITLE
remove unused functions and simplify return str

### PR DESCRIPTION
**Pull request by tanjunchen**
@justinsb @zetaab 
can you help me review these changes?Thanks!
Maybe some functions are important,we need to talk about them remove or not?
#7800

### CODE REVIEW

**Comment by tanjunchen** [comment]
@zetaab

**Comment by tanjunchen** [comment]
@mikesplain

**Comment by tanjunchen** [comment]
@hwdef

**Comment by hwdef** [comment]
/lgtm
/ok-to-test
Thanks for your contribution.

**Comment by tanjunchen** [comment]
@mikesplain @justinsb  Can you help me review this pr? Thanks

**Comment by tanjunchen** [comment]
@mikesplain @justinsb  Can you help me review this pr? Thanks

**Comment by justinsb** [comment]
Wow - thanks for finding all these unused functions!

We should delete them if they are unused!  I know some of them may be related to e.g. the memberlist work, so I'm first going to make sure that there's not another PR that references these functions.  But this LGTM!

Or maybe we merge this as one of the first PRs after we cut the 1.16 branch, just in case... Because of go interface rules it can sometimes be tricky to see if a function is indeed unused!

**Comment by rifelpet** [comment]
now that we have plenty of new release branches, this seems safe for master.

/lgtm
/approve

**Pull request merged**
