### PR TITLE
Add support for new us-east-2 region

### PR DESCRIPTION
**Pull request by justinsb**
Our defaulting logic didn't recognize the new us-east-2 AZs

### CODE REVIEW

**Comment by justinsb** [comment]
We're still blocked on https://github.com/kubernetes/kubernetes/pull/35013, but this is our bit

**Comment by justinsb** [comment]
Actually, turns out this test depends on valid AWS credentials.  Once #681 merges, that has the mock ec2 infrastructure and I can fake DescribeRegions easily.

**Comment by chrislovecnm** [comment]
Can you rebase to bounce the test?

**Comment by kris-nova** [comment]
LGTM - Good job on the tests

**Pull request merged**
