### PR TITLE
Add unit test for func RenderInstanceGroupSubnets in instancegroup.go

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by johngmyers** [comment]
/ok-to-test
Looks like you need to merge in master or rebase to pass the checks on license year.

**Comment by fenggw-fnst** [comment]
@johngmyers Done, thanks!

**Comment by johngmyers** [comment]
Thanks!
/lgtm

**Pull request merged**
