### PR TITLE
add kube-ingress-aws-controller + skipper addons

### PR DESCRIPTION
**Pull request by szuecs**
Adds an addon that needs some more requirements, because it has to have the rights to create/update/delete ALBs, find certificates, ..

I hope this is ok to have here a more long page to explain requirements and show some features that are not common in ingress implementations.

### CODE REVIEW

**Comment by szuecs** [comment]
@justinsb I added a section to update an existing cluster adding cloudLabels as requierd by this ingress controller

**Comment by szuecs** [comment]
@chrislovecnm are you sure the test cluster will be created with cloud labels enabled? That would be required to make the aws controller working, if not it will not find the required resources in AWS

**Comment by szuecs** [comment]
@chrislovecnm merge? :)

**Comment by justinsb** [comment]
/lgtm

Thanks for getting this in - I think we have some things coming that might help simplify some of these steps also :-)

**Comment by szuecs** [comment]
who can merge? :)

**Pull request merged**
