### PR TITLE
Automated cherry pick of #6878: Change code from glog to klog

### PR DESCRIPTION
**Pull request by mikesplain**
Cherry pick of #6878 on release-1.13.

#6878: Change code from glog to klog

### CODE REVIEW

**Comment by mikesplain** [comment]
I believe this is blocked by https://github.com/kubernetes/kops/pull/6975

**Comment by justinsb** [comment]
Thanks @mikesplain 

/approve
/lgtm

**Comment by mikesplain** [comment]
Looks like we're running into issues with loading klog and glog, might be an issue with dep

**Comment by mikesplain** [comment]
If the fix works, I'll do the same in https://github.com/kubernetes/kops/pull/6974

**Comment by mikesplain** [comment]
I believe this cherry-pick should fix this issue https://github.com/kubernetes/kops/pull/6978

**Comment by mikesplain** [comment]
Finally passing, woot!
/assign @granular-ryanbonham 
cc: @justinsb

**Pull request merged**
