### PR TITLE
doc: support to debug kops-apiserver

### PR DESCRIPTION
**Pull request by Sn0rt**
This script tests on aws as follows output:

```
kubectl -n kube-system logs kops-api-server-c4dbdfc54-dvmns -f

I0617 09:05:57.182345       1 serving.go:311] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
W0617 09:05:57.571489       1 start.go:133] Authentication/Authorization disabled
I0617 09:05:57.572928       1 plugins.go:158] Loaded 2 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,MutatingAdmissionWebhook.
I0617 09:05:57.572944       1 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionWebhook.
W0617 09:05:57.620374       1 genericapiserver.go:338] Skipping API kops.k8s.io/v1alpha1 because it has no resources.
I0617 09:05:57.735572       1 secure_serving.go:116] Serving securely on [::]:443
```

and get 

```
$ curl -k https://172.20.42.164/swagger.json
{
  "swagger": "2.0",
  "info": {
   "title": "Kops API",
   "version": "0.1"
```

Signed-off-by: guohaowang <wangguohao.2009@gmail.com>

### CODE REVIEW

**Comment by Sn0rt** [comment]
the /api-server/README.md  has been renamed with kops-server.

**Comment by justinsb** [comment]
/ok-to-test

/lgtm

This looks good @Sn0rt - thank you (but I do encourage you to look into the upcoming CRD support instead...)

**Comment by justinsb** [comment]
PR failure is a well-known flake: https://github.com/kubernetes/kubernetes/issues/73099

Looks like you have a conflict with your other PR as well

**Comment by justinsb** [comment]
/retest
/lgtm

I think the e2e issues should have been resolved now!

**Pull request merged**
