### PR TITLE
Missing step to pull down template file required by migration script.

### PR DESCRIPTION
**Pull request by j14s**
added missing step to pull down template file and correct step 2 word…ing to reflect the existence of the template file

### CODE REVIEW

**Comment by j14s** [comment]
CNCF registration complete

**Comment by j14s** [comment]
CNCF registration complete. Attempt 2.

**Comment by j14s** [comment]
CNCF registration really complete with actual correct email which is warned about a million times and yet I still managed to screw up and hopefully now it will be good.*sigh*

**Comment by j14s** [comment]
CNCF registration, second account, second signing

**Comment by chrislovecnm** [comment]
Did you do the git commit with the wrong git user?

**Comment by j14s** [comment]
Argh, ok, canceling pull request and redoing with a local user/email set in the config.

**Pull request closed without merging**
