### PR TITLE
Automated cherry pick of #11459: fix(coredns/rbac): add permission to list and watch

### PR DESCRIPTION
**Pull request by dntosas**
Cherry pick of #11459 on release-1.21.

#11459: fix(coredns/rbac): add permission to list and watch

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by rifelpet** [comment]
You'll need to run ./hack/update-expected.sh on this cherry pick

**Review by johngmyers — APPROVED** [review]

**Pull request merged**
