### PR TITLE
Update aws.md

### PR DESCRIPTION
**Pull request by jrnt30**
Small correction around region the demo actually uses

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1299)

### CODE REVIEW

**Comment by jrnt30** [comment]
I signed it!

**Comment by justinsb** [comment]
LGTM

**Comment by justinsb** [comment]
Thanks @jrnt30 :-)

**Comment by jrnt30** [comment]
Thanks for doing all the heavy lifting :)

**Comment by chrislovecnm** [comment]
E2E is failing. Will wait on it, but not sure why

**Pull request merged**
