### PR TITLE
Support "egress: External" to avoid configuring networking

### PR DESCRIPTION
**Pull request by moustafab**
We've done some work on top of #5141 to get this working, and wanted to contribute back. @justinsb we've tested and got this working with our clusters on kubernetes 1.10.x 

Please let me know if we need to do anything else to get this in or if it should go into a different branch!

### CODE REVIEW

**Comment by xrl** [comment]
I am also using a custom branch of kops to support external networking configurations. I would greatly appreciate this being stabilized and merged in to master!

**Comment by moustafab** [comment]
I signed it

**Comment by arjuncomar** [comment]
I have also signed.

**Comment by arjuncomar** [comment]
I signed it

**Comment by chrisz100** [comment]
@moustafab there seems to be an issue with your code when running go vet:
https://travis-ci.org/kubernetes/kops/jobs/469166475

Can you look into this before moving forward?

**Comment by moustafab** [comment]
@chrisz100 I took a look and I think I got the issues sorted

**Comment by moustafab** [comment]
Ironically, it works on my machine 😂. Looks like the gofmt change in 1.11 broke a bunch of things. I retested everything in a golang:1.10 docker container so hopefully that just works

**Comment by moustafab** [comment]
@chrisz100 should I move this to go to master as 1.11 has been released?

**Comment by arjuncomar** [comment]
@mikesplain @rdrgmnzs Tagging you both in per the conversation during office hours today.

**Comment by rdrgmnzs** [comment]
@moustafab code looks good just a couple things I'd like to follow up on before I lgtm.

1) Could we add documentation around this new feature and it's intended usage.
2) I'd like to understand your use case here a little better, would be great if you could share your use case. I'm assuming it's similar to #232 but would love clarification.

cc: @xrl @arjuncomar if your use cases are different, it would be great if you could also share those.

**Comment by arjuncomar** [comment]
@moustafab and I have the same use case. In this particular instance, we want to allow egress entries on the route table to be managed by an alternative tool to better support the needs of other teams. Asking kops to not manage the route tables/egress is necessary for us so that we can manage it ourselves with the other tool. 

I imagine it's also useful for others in that alternative egress types that are supported by AWS but not kops can also be used. This also saves kops from having to stay in sync with the egress types supported by Amazon - for instance, VPN Gateways and the like. Essentially, the PR allows more complex networking configurations managed externally and avoids reproducing that complexity in kops.

We'll get this updated with documentation.

**Comment by rdrgmnzs** [comment]
@arjuncomar  @moustafab one last thing I had missed initially, can we move this to the master branch as well.

**Comment by xrl** [comment]
Hi, I'm happy to provide info about my use case. We're in an enterprise network with some engineering policies which state all traffic must stay inside of our network. We peer our VPC with the enterprise network through a DX connection. If we enable an IGW it will show up in the audit logs and we'll get in big trouble!

This feature has worked very well, I keep a watchful eye on `kops update` output to make sure no IGW or route stuff is happening. We are running multiple production clusters this way and it's great. We manage our network configuration in a separate cloudformation. The main fear I have is doing something like `kops delete` and it deletes all the VPC/subnets/peerings I have set up.

**Comment by moustafab** [comment]
@rdrgmnzs I updated the target to be master, and rebased on master. Still working on the documentation.

**Comment by xrl** [comment]
@moustafab thanks for pushing on this! I'm very excited to tell the team we'll be off a custom branch!

**Comment by moustafab** [comment]
rebased, @rdrgmnzs can we get this tested by the ci?

**Comment by justinsb** [comment]
For the record, I'm in favor of this, but I had some pushback originally when I proposed it.  If we can agree that it's a good idea, I'm in favor.

I do think we want to work towards separating networking into its own set of objects, as something we've learned is that _nobody_ has the same networking configuration.  The cluster continues to grow in complexity, and I don't think we've captured everything yet!

The other bit of complexity in the cluster object (the configuration of apiserver, k-c-m etc), will likely be split out into separate objects as part of component config.

(We'll still have to support the existing types, I'm just talking about the preferred location for storing this configuration that we could aim for)

**Comment by moustafab** [comment]
> For the record, I'm in favor of this, but I had some pushback originally when I proposed it. If we can agree that it's a good idea, I'm in favor.
> 
> I do think we want to work towards separating networking into its own set of objects, as something we've learned is that _nobody_ has the same networking configuration. The cluster continues to grow in complexity, and I don't think we've captured everything yet!
> 
> The other bit of complexity in the cluster object (the configuration of apiserver, k-c-m etc), will likely be split out into separate objects as part of component config.
> 
> (We'll still have to support the existing types, I'm just talking about the preferred location for storing this configuration that we could aim for)

So where do we go from here? How can we move this discussion forward? I think this change is relatively innocuous in terms of the impact of separating networking into its own set of objects. 

My first approach to solving our issue with kops was to look into implementing the virtual private gateway type. I figured out a couple things when I went down that route:
1. Adding that to kops would be far less vanilla and common across multiple use cases
2. If it was going to be useful at all it would have to allow a good amount of fine grain control, and likely warrant the separation you are suggesting you all have on the roadmap for networking objects. 

I think when you get to that part of the roadmap, a stub for unimplemented or unsupported networking configuration types and controls may be the way to go anyways to allow various use cases to take advantage of kops' ease of use.

**Comment by rdrgmnzs** [comment]
I'm actually ok with this going in as is right now. As @justinsb said, separating networking into its own set of objects sounds like a great thing, however I think it falls out of scope with this specific change and should be done separately.

Thanks for all the work @moustafab!

/lgtm

**Comment by moustafab** [comment]
@chrisz100 do you need to LGTM or approve as well?

**Comment by chrisz100** [comment]
No I dont, as I am not one of the approves right now. @justinsb or @mike.splain can you take over? 

/lgtm

**Comment by mikesplain** [comment]
Agreed with all of the above. Thanks everyone for all the hard work on this, I think it's time we get this one in! As mentioned above, I think this change is fairly simple for the moment and solves a number of users immediate use cases.  If anyone is up for looking into some of those heavier networking refactors, feel free to let us know!

Thanks all!

/lgtm
/approve

**Comment by moustafab** [comment]
@mikesplain @rdrgmnzs Looks like another change caused the integration tests to fail, I fixed the terraform output. Can I get a LGTM?

**Comment by chrisz100** [comment]
Not @mikesplain but yes indeed you can! 

/lgtm

**Pull request merged**
