### PR TITLE
Update Weave Net to version 2.1.3

### PR DESCRIPTION
**Pull request by bboreham**
This version supports 'v1' NetworkPolicy semantics.

Also includes a feature to clear down data for deleted nodes, which is probably the most-requested fix.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
You want this in kops 1.8? How have you tested this with kops?

I would love to get this in, but I do not want to break stuff as well ;)

**Comment by bboreham** [comment]
Tested by creating a kops cluster, changing the ASG to 10 nodes, down to 5, up to 10, and so on.
Inspecting `weave` container logs and running the `nettest` container used in Weave Net CI.
In the process I found a race condition in 2.1.2, which is fixed in 2.1.3.

**Comment by bboreham** [comment]
Any thoughts on getting this merged?

**Comment by justinsb** [comment]
/lgtm

We also need to bump the version in bootstrapchannelbuilder, but I'll just send a PR for that

**Comment by justinsb** [comment]
Sent https://github.com/kubernetes/kops/pull/4062

**Pull request merged**
