### PR TITLE
Add EtcdVersion cli flag for cluster create

### LINKED ISSUE #4236: Specify etcd version from cli
I would like to be able to specify etcd version from command line.

I am working on adding Cilium as a CNI plugin for k8s clusters deployed by kops. Cilium needs etcd>=3.1.0, default version in kops is much older.

This change would allow deployment of kops with Cilium as a one-liner, but is possibly beneficial for users not using Cilium, so I want to do this as separate PR.

### PR DESCRIPTION
**Pull request by nebril**
fixes #4236

### CODE REVIEW

**Comment by chrislovecnm** [comment]
We actually already have one hiding, take a look at the overrides flag. It uses a feature flag

**Comment by chrislovecnm** [comment]
Appreciate the contribution btw

**Comment by nebril** [comment]
@chrislovecnm thanks, I completely missed this! Would be nice to have this documented somewhere. Closing this one.

**Comment by chrislovecnm** [comment]
@nebril it is a super new feature we are working out the syntax for, hence why it is a bit hidden. Users that utilize manifests already had access to this option, as we do not put every option in the cli. I dropped in the PR for etcd version actually because of e2e testing/

**Pull request closed without merging**
