### PR TITLE
Add .build to .dockerignore

### PR DESCRIPTION
**Pull request by alrs**
There is no root-level Dockerfile, so I suspect this .dockerignore is a vestige of an earlier time.

I want to be able to use build containers without volume mounts, so I need to be able to copy the tree into a container image. I don't want the .build directory to get copied in.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@alrs  I0930 22:52:14.176] Makefile:361: recipe for target 'protokube-image' failed
I0930 22:52:14.176] Starting pull-kops-e2e-kubernetes-aws-3303...

**Comment by alrs** [comment]
@chrislovecnm My goals:

1. Get the Makefile straightened out so that we can things in parallel.
2. Be rid of volume-mounting, so that in-Docker build jobs can't damage the tree or leave root artifacts laying around.
3. Be rid of instances where the Makefile is calling itself inside a container.
4. Be rid of the current-working-directory and `cd` gymnastics that are confusing and are the likely culprit of the `protoc` flakiness.
5. DRY out the Makefile.
6. Retain the ability to build all distributable artifacts inside containers

I've created a `NG.mk` in a local branch where I can start working on a refactored Makefile without touching the current one. Once I know what's possible with the `.dockerignore` I plan on hanging out in that file for awhile.

**Comment by alrs** [comment]
@chrislovecnm  As for this PR, obviously it's a no-go until I figure out `protokube-image`.

**Comment by alrs** [comment]
I can make my work responsible for ignoring the stuff it needs to ignore, so maybe the better thing to do is just remove the `.dockerignore`? This can't happen if the presence of the `.dockerignore` is providing some safety. Is it? @chrislovecnm @justinsb

**Comment by alrs** [comment]
I found a way around this, so I'll close this PR.

**Pull request closed without merging**
