### PR TITLE
Replace gofmt with gofumpt

### PR DESCRIPTION
**Pull request by hakman**
Ref: https://github.com/mvdan/gofumpt

/cc @olemarkus @rifelpet @johngmyers 

/hold for feedback

### CODE REVIEW

**Comment by johngmyers** [comment]
IntelliJ IDEA supports gofmt before commit. It does not support gofmpt before commit.  This change would make development harder.

**Comment by olemarkus** [comment]
As in goland? Can't you configure it to run whatever? As in https://github.com/mvdan/gofumpt#goland
or run the hack script as a precommit?

**Comment by johngmyers** [comment]
I also work with Java so use IDEA instead of Goland. Those Goland instructions don't match what's in IDEA and I can't find any corresponding settings.

**Comment by hakman** [comment]
@johngmyers @olemarkus Should we commit the script and the one-time run as a first step and keep gofmt around until we find a more permanent solution?

**Comment by olemarkus** [comment]
I am for that. I will probably keep using gofumpt if you don't mind, and doing that one-time pass will make my commits easier for you :)

**Comment by johngmyers** [comment]
I have no objections to script and one-time pass.

**Pull request closed without merging**
