### PR TITLE
VFS: WriteFile takes an io.ReadSeeker

### PR DESCRIPTION
**Pull request by justinsb**
Means we don't have to buffer big files in memory, in combination with
WriteTo for reading.

### CODE REVIEW

**Comment by justinsb** [comment]
This is actually pretty important for the etcd backups, which uses the VFS layer from kops.  Without this, etcd backups must be read into a byte array (i.e. must be read entirely into RAM)

**Comment by chrislovecnm** [comment]
@justinsb I am guessing this does not block 1.9 alpha but needs to be in 1.9 release.  Marked it as blocks next.

**Pull request merged**
