### PR TITLE
fix(cluster-autoscaler): add missing permission

### PR DESCRIPTION
**Pull request by guilhermef**
While trying to create a new cluster with Kops, I noticed the following error:
```
I0922 19:58:53.909807       1 aws_wrapper.go:706] 0 launch configurations to query
I0922 19:58:53.909814       1 aws_wrapper.go:707] 0 launch templates to query
I0922 19:58:53.909822       1 aws_wrapper.go:727] Successfully queried 0 launch configurations
I0922 19:58:53.909830       1 aws_wrapper.go:738] Successfully queried 0 launch templates
E0922 19:58:53.965192       1 aws_wrapper.go:744] Failed to query instance requirements for ASG spot-arm64-us-east.case.k8s.local: UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:sts::359113738869:assumed-role/cluster-autoscaler.kube-system.sa.case.k8s.local/1727035092386409452 is not authorized to perform: ec2:DescribeImages because no identity-based policy allows the ec2:DescribeImages action
status code: 403, request id: bb96e296-3fe3-4650-9b03-822707465041
I0922 19:58:53.965225       1 aws_wrapper.go:749] Successfully queried instance requirements for 1 ASGs 
E0922 19:58:53.965241       1 mixed_nodeinfos_processor.go:160] Unable to build proper template node for spot-arm64-us-east.case.k8s.local: could not find instance type for spot-arm64-us-east.case.k8s.local
E0922 19:58:53.965258       1 static_autoscaler.go:380] Failed to get node infos for groups: could not find instance type for spot-arm64-us-east.case.k8s.local
```

According to the [recommend cluster-autoscale policy](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#iam-policy) the actions `ec2:DescribeImages` and `ec2:GetInstanceTypesFromInstanceRequirements` are required.

```shell
kops version
Client version: 1.30.1
```
Cluster.yaml used during the creation
```yaml
---
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: case.k8s.local
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://case-kops-state/kops-state/case.k8s.local
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1b
          name: b
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1c
          name: c
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1b
          name: b
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1c
          name: c
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
    - ::/0
  kubernetesVersion: 1.30.2
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://case-discovery-store/discovery/case.k8s.local
    enableAWSOIDCProvider: true
  # sshAccess:
  #   - 0.0.0.0/0
  #   - ::/0
  # SSM Access doesn't need SSH ports to be open
  subnets:
    - name: us-east-1a
      type: Private
      zone: us-east-1a
    - name: us-east-1b
      type: Private
      zone: us-east-1b
    - name: us-east-1c
      type: Private
      zone: us-east-1c
    - name: utility-us-east-1a
      zone: us-east-1a
      type: Utility
    - name: utility-us-east-1b
      zone: us-east-1b
      type: Utility
    - name: utility-us-east-1c
      zone: us-east-1c
      type: Utility
  topology:
    masters: private
    nodes: private
    dns:
      type: None

  metricsServer:
    enabled: true

  clusterAutoscaler:
    enabled: true
    expander: least-waste
    awsUseStaticInstanceList: false

  externalPolicies:
    node:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  certManager:
    enabled: true
    defaultIssuer: CaseIssuer
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: control-plane-us-east-1a
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: control-plane-us-east-1b
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: control-plane-us-east-1c
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: nodes-us-east-1a
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 10
  minSize: 0
  role: Node
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1a

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: nodes-us-east-1b
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 10
  minSize: 0
  role: Node
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1b

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: nodes-us-east-1c
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  machineType: t3.medium
  maxSize: 10
  minSize: 0
  role: Node
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: spot-us-east
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id
  mixedInstancesPolicy:
    instanceRequirements:
      cpu:
        min: "2"
        max: "32"
      memory:
        min: "2G"
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/capacity: spot
  maxSize: 10
  minSize: 0
  role: Node
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1a
    - us-east-1b
    - us-east-1c

---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: case.k8s.local
  name: spot-arm64-us-east
spec:
  image: ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id
  mixedInstancesPolicy:
    instanceRequirements:
      cpu:
        min: "2"
        max: "32"
      memory:
        min: "2G"
    onDemandAboveBase: 0
    onDemandBase: 0
    spotAllocationStrategy: capacity-optimized
  nodeLabels:
    kops.k8s.io/capacity: spot
    kops.k8s.io/architecture: arm64
  taints:
    - architecture=arm64:NoSchedule
  maxSize: 10
  minSize: 0
  role: Node
  rootVolumeSize: 50
  rootVolumeEncryption: true
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  subnets:
    - us-east-1a
    - us-east-1b
    - us-east-1c

```

### CODE REVIEW

**Comment by hakman** [comment]
@guilhermef Thanks for finding this. Would you mind updating the whole block as described [in the docs](https://github.com/kubernetes/autoscaler/blob/6429e4bcc9da6f25ddf15c3ef2403040a441cbd2/cluster-autoscaler/cloudprovider/aws/README.md?plain=1#L47-L55)?
Also, please run `hack/update-expected.sh` and commit the result.

**Comment by guilhermef** [comment]
Thanks @hakman, I updated the PR

**Comment by guilhermef** [comment]
@hakman, I checked both jobs' logs but couldn't find any failed resource that would prevent the cluster from being created.

**Comment by hakman** [comment]
@guilhermef No worries, I will take care of those failing tests. Please also squash the commits. I would like to cherry-pick this PR.

**Review by hakman — APPROVED** [review]

**Pull request merged**
