### PR TITLE
test: Use latest K8s build for scale tests

### PR DESCRIPTION
**Pull request by hakuna-matatah**
Want to test 1.31.beta to see if it works on AWS.

### CODE REVIEW

**Comment by hakman** [comment]
presubmit-kops-aws-small-scale-amazonvpc-using-cl2

**Review by hakman — APPROVED** [review]

**Comment by hakuna-matatah** [comment]
cc: @dims @shyamjvs @BenTheElder

**Comment by hakuna-matatah** [comment]
cc: @dims @shyamjvs @BenTheElder

**Comment by dims** [comment]
@hakuna-matatah next time we could add `K8S_VERSION` in the test-infra ci job definition too right?

**Comment by hakuna-matatah** [comment]
Looks like test run succeeded but it looks like Prow job is stuck in running state - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16701/presubmit-kops-aws-scale-amazonvpc-using-cl2/1818245175466528768

**Comment by BenTheElder** [comment]
> 
Looks like test run succeeded but it looks like Prow job is stuck in running state - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16701/presubmit-kops-aws-scale-amazonvpc-using-cl2/1818245175466528768


that's probably https://github.com/kubernetes-sigs/prow/issues/210

**Comment by BenTheElder** [comment]
> I think we could also facilitate that, but wondering why would we want to do that ? Do we want to run for many different versions ? Or just the latest ?

it's also nice to be explicit in the job config, so we have more confidence that e.g. release-master-informing jobs _actually_ run code from master, though we should always confirm by investigating the uploaded artifacts

**Pull request merged**
