### PR TITLE
WIP: Use Ubuntu 22.04 as the default image for Kubernetes 1.24+

### PR DESCRIPTION
**Pull request by hakman**
As agreed during the 22.04.2022 kOps office hours.

### CODE REVIEW

**Comment by olemarkus** [comment]
I have started using 22.04 and it is not without teething trouble ... I suggest we at least add it to the test grid and run it for a while before making it the default. It is after all using nftables by default etc.

**Comment by zetaab** [comment]
ubuntu 22 uses also cgroupv2 by default. We have seen issues with debian-11 earlier with oldest java projects. Old java versions do not support cgroup v2

**Comment by hakman** [comment]
`nftables by default` - It's been ages since that appeared and it's supported since long time ago by k8s and most CNIs.
`cgroup v2` - Is probably a good point. 
`old java` - Not sure what we can do about workloads using older Java versions and other programming languages. For sure clusters could have a separate IG for such apps.

**Comment by olemarkus** [comment]
We could mount v1 like we mount cgroups for cilium. But not sure this is on us. Can also be solved by daemonset or initcontainers. But they would need to be privileged.

**Comment by olemarkus** [comment]
Seems like ec2-instance-connect is broken on jammy.
```
May 01 07:27:45 ip-172-20-56-12 sshd[7914]: AuthorizedKeysCommand /usr/share/ec2-instance-connect/eic_run_authorized_keys ubuntu SHA256:**** failed, status 2
```

**Pull request closed without merging**
