### PR TITLE
Add weave network encryption secret

### PR DESCRIPTION
**Pull request by kampka**
Adds the possibility to enable weave network encryption as describe in https://www.weave.works/docs/net/latest/tasks/manage/security-untrusted-networks/

The code to lookup the secert an supply it as a template function may not be positioned ideally, I would be happy for pointers on that part.

### CODE REVIEW

**Comment by mikesplain** [comment]
Oh this is very cool. Nice work @kampka! Lets get the tests running first.

/ok-to-test

**Comment by kampka** [comment]
Thanks @mikesplain 

/assign andrewsykim

**Comment by chrisz100** [comment]
Looks good so far! Thanks @kampka 
/lgtm

**Comment by justinsb** [comment]
So I was a little concerned about why this is creating what looks like a new secret type, but on closer inspection I now see that we're creating a new CLI (sub)command.

Idea for future enhancement - we probably don't need the password to be specified (i.e. the `-f` flag doesn't need to be mandatory).  We can just generate one if one isn't provided.  I think `fi.CreateSecret` actually creates one by default - I'm just not sure if it's suitable for weave or if weave has specific requirements.

This looks great - thanks @kampka 

/approve
/lgtm

**Comment by kampka** [comment]
@justinsb good point, totally missed that.
Thanks for the suggestion.
Fixed in #5457

**Comment by bboreham** [comment]
>  if weave has specific requirements [for passwords]

I don't think so.

**Pull request merged**
