### PR TITLE
[WIP] Test network plugins e2e presubmits

### PR DESCRIPTION
**Pull request by hakman**
/cc @rifelpet

### CODE REVIEW

**Comment by rifelpet** [comment]
ref: https://github.com/kubernetes/test-infra/pull/17984/files

the failing jobs report a 404 when downloading the kops assets:

> curl -fsS --retry 3 -o /workspace/kops https://storage.googleapis.com/kops-ci/pulls/pull-kops-e2e-cni-calico/pull-9597c9cf8/linux/amd64/kops
> curl: (22) The requested URL returned error: 404 

that URL is created by [this python function](https://github.com/kubernetes/test-infra/blob/b225e06266269e8a14f7f57bd9e9dd1255cfbffa/scenarios/kubernetes_e2e.py#L255-L267) which defaults the job name to `pull-kops-e2e-kubernetes-aws`. If you replace the kops url with that, it works:

https://storage.googleapis.com/kops-ci/pulls/pull-kops-e2e-kubernetes-aws/pull-9597c9cf8/linux/amd64/kops

So the python function must not be seeing the JOB_NAME env var for some reason.

**Comment by hakman** [comment]
All tests for network plugins pass, new jobs are good to go.
/close

**Pull request closed without merging**
