### PR TITLE
Require kops 1.7.1 (with the CVE fix), recommend kops 1.8.1

### PR DESCRIPTION
**Pull request by justinsb**
We make it recommended in the stable channel, and will test the mandatory
upgrade in the alpha channel.

### CODE REVIEW

**Comment by justinsb** [comment]
WIP because depends on #3586, also because I'm not convinced this is actually working!

**Comment by geojaz** [comment]
/lgtm

should we rebase and get it merged?

**Comment by justinsb** [comment]
Rebased and ready to go I hope

**Pull request merged**
