### PR TITLE
Add missing permissions to aws lbc for irsa

### LINKED ISSUE #13020: AWS LBC cannot delete Security Groups it creates
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master branch. Broken code appears to be in release-1.23 branch as well

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.21.7

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Examine the kops-aws-aws-load-balancer-controller e2e test.

Alternatively:
1. Create a cluster with the AWS Load Balancer controller.
2. Create an Ingress backed by an ALB.
3. Delete the ingress

**5. What happened after the commands executed?**

The ALB controller is unable to delete the "k8s-traffic-" ingress for the ALB due to lack of IAM permissions. This is because the security group is missing the `KubernetesCluster` tag.

**6. What did you expect to happen?**

Security group is tagged with the tags that kOps passed AWS LBC through the `default-tags` flag. LBC is able to delete the security groups it creates.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

Introduced by #12920.

Filed upstream as kubernetes-sigs/aws-load-balancer-controller#2424

### PR DESCRIPTION
**Pull request by olemarkus**
Looks like we are missing a lot of permissions for LBC. 
fixes #13020

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by olemarkus** [comment]
Not sure how we managed to get this test passing before, but the test tries to use create an LB with the cluster name in it. This name contains `.`, which is not allowed by AWS.

**Comment by hakman** [comment]
> Not sure how we managed to get this test passing before, but the test tries to use create an LB with the cluster name in it. This name contains `.`, which is not allowed by AWS.

Seems like a test bug and should be fixed in k/k. Should we skip it for now?

**Comment by olemarkus** [comment]
The tests are from lbc repo, but yeah. we I'll do rebase and push, and then we skip trying to run that test. I'll see if I can fix it in a follow-up.

**Pull request merged**
