### PR TITLE
Don't expose v1alpha3 API

### PR DESCRIPTION
**Pull request by johngmyers**
It's not ready for 1.26.

### CODE REVIEW

**Comment by hakman** [comment]
I think in the previous releases we left it around, just not made it the default yet.
/cc @olemarkus @justinsb

**Comment by olemarkus** [comment]
I believe we did not remove it in 1.25, yes.

**Comment by johngmyers** [comment]
It escaped into 1.25. The 1.26 one is incompatible. Technically we should rename the 1.26 one to v1alpha4 and master branch to v1alpha5. Or we can remove from 1.26 and save some hassle.

**Comment by justinsb** [comment]
If you're OK to remove it from 1.26 (because it constrains your ability to iterate), then I'm in favor of removing it.  We could also feature flag it if that's easier (?).

I don't think we're going to break anyone by removing it, because I don't think we've suggested to anyone to use it and it's not the default / not documented, and we do risk breaking people by leaving it in when we aren't maintaining compatability.

My vote: remove, easy enough to add back if someone is using it, but if they are we should discuss with them that they probably should be sticking with alpha2 for the moment.

**Comment by johngmyers** [comment]
Anyone who used v1alpha3 in 1.25 is going to be broken. We didn't maintain compatibility.

I would prefer we not leave a similar attractive nuisance in 1.26. APIMachinery rules allow removal of alpha apiversions with no deprecation period.

**Review by hakman — APPROVED** [review]

**Pull request merged**
