### PR TITLE
better error messages with docker api

### PR DESCRIPTION
**Pull request by chrislovecnm**
Got `DOCKER_HOST="unix:///var/run/docker.sock" running on my mac.  I do not have the time to try to figure out how to make socket connection, but the error message will help a user.

### CODE REVIEW

**Comment by justinsb** [comment]
Looks like docker changed the default, it is now  https://github.com/docker/engine-api/blob/master/client/client_unix.go  but in the version we're using Darwin is 
```
// DefaultDockerHost defines os specific default if DOCKER_HOST is unset
const DefaultDockerHost = "tcp://127.0.0.1:2375"
```

(unix is `DefaultDockerHost = "unix:///var/run/docker.sock"`)

Probably going to be best to use the Docker CLI throughout :-(

**Comment by chrislovecnm** [comment]
Would be better in mind to use the socket, I would rather now have to have the binary in a k8s hosted kops. Just a thought

**Comment by justinsb** [comment]
Yes, I definitely favor the socket as well.  Except that using the socket means parsing the auth values ourselves, which is a pain.  So we end up using the CLI for push & pull anyway.  I'm thinking we just use the CLI everywhere, for now...

**Comment by justinsb** [comment]
Although this is an improvement on the API path, whether or not we want that long term :-)

/lgtm

**Pull request merged**
