### PR TITLE
upgrade calico to 2.6.12 to fix TTA-2018-001

### PR DESCRIPTION
**Pull request by mechpen**
https://www.projectcalico.org/security-bulletins/#TTA-2018-001

### CODE REVIEW

**Comment by mechpen** [comment]
@KashifSaadat

**Comment by mikesplain** [comment]
@justinsb We should probably cherry pick this into 1.11

**Comment by mechpen** [comment]
I signed it

**Comment by KashifSaadat** [comment]
Bot issues.. will try reopen.

/close

**Comment by mechpen** [comment]
Looks there is a problem with the cla bot?  Should I try close this one and open a new PR?

**Comment by KashifSaadat** [comment]
Yeah that's probably a good idea as it's not recovering by itself oddly. Sorry @mechpen !

**Pull request closed without merging**
