### PR TITLE
Support for using hostPort when using kube-router

### PR DESCRIPTION
**Pull request by andsens**
Enable portmap plugin in the kube-router cni config to support hostPort.  
Similar to #7295 (flannel), #4063 (canal), and #3206 (calico).

### CODE REVIEW

**Comment by johngmyers** [comment]
@andsens Please fix the CLA problem. You might need to ensure your email address is associated with your GitHub account.

**Comment by andsens** [comment]
@johngmyers I am signed up, somethings buggy somewhere. We signed up as an org and my google account is connected as an employee account. It doesn't seem that my github account will connect though.  
When I hit "Sign up as an employee" I get this screen:
Annotation 2020-08-07 083019
which leads me to this screen
Annotation 2020-08-07 083018

And the org is definitely signed up:
Annotation 2020-08-07 083017

Any pointers?

**Comment by rifelpet** [comment]
@andsens is your github email and the author email used in the git commits associated with the org? You may need to use the helpdesk mentioned in the first bot comment above

> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/

**Comment by andsens** [comment]
@rifelpet @johngmyers, fixed. My account at LF was just an administrator and not a contributor.

**Comment by rifelpet** [comment]
The GitHub Actions and Travis failures are because you need to run `make kops-gobindata`. The e2e failure is just a flake.

**Comment by andsens** [comment]
@rifelpet fixed

**Comment by hakman** [comment]
@andsens a few more things:
1. Bump the version here also:
https://github.com/kubernetes/kops/blob/4990b71185cf79c0f6ebca4b11bd96877c496d88/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L842-L846
2. Add `--bgp-graceful-restart=true` to the list of args, same as in [here](https://github.com/cloudnativelabs/kube-router/blob/27857d3a86b015a24bc5b95d8e163c2427d7a56d/daemonset/kubeadm-kuberouter-all-features-hostport.yaml#L64).

Thanks!

**Comment by andsens** [comment]
@hakman I don't understand what that has to do with enabling an unrelated plugin? I'd rather not take ownership of code I don't understand by showing up in git-blame.

**Comment by hakman** [comment]
The parameter is part of the `hostport` example. In any case, will add it with the next upgrade to 1.0.1 someday.
Can you do the version bump?

**Comment by hakman** [comment]
Hey @andsens. Just wanted to check if you are ok with the suggested change to bump the manifest version. It is required for the updates to work properly. Thanks.
https://github.com/kubernetes/kops/blob/4990b71185cf79c0f6ebca4b11bd96877c496d88/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L842-L846

**Comment by andsens** [comment]
@hakman argh, apologies. I saw your mail this morning and planned to do the bump and then immediately forgot all about it.
I will add the change tomorrow and update the PR.

**Comment by hakman** [comment]
Sound good. Thanks @andsens!

**Comment by andsens** [comment]
@hakman done. I enabled BGP graceful restart as well. Had to [read up on it](https://tools.ietf.org/html/rfc4724#section-1) to figure out what it does first though, pretty neat :-)

**Comment by hakman** [comment]
Hehe. Really nice @andsens.
Feel free to open another PR for upgrading kube-router to v1.0.1, if you think that's a good idea.
/lgtm
/approve

**Pull request merged**
