### PR TITLE
rolling-update: if filtering IGs, don't warn if IG not found

### LINKED ISSUE #2000: rolling-update: Found ASG with no corresponding instance group
Got a warning when running `kops rolling-update cluster` with the `--instance-group` option. Guessing it's not a big deal, just that it noticed the nodes ASG that didn't match the specified IG:

```
kops rolling-update cluster  --instance-group=master-us-east-1e --master-interval 10m --yes
Using cluster from kubectl context: us-east-1.domain.com

W0226 00:48:57.209824   27209 rollingupdate_cluster.go:90] Found ASG with no corresponding instance group: "nodes.us-east-1.domain.com"
NAME                    STATUS          NEEDUPDATE      READY   MIN     MAX     NODES
master-us-east-1e       NeedsUpdate     1               0       1       1       1
```

```
kops version
Version 1.5.1 (git-01deca8)
```

### PR DESCRIPTION
**Pull request by justinsb**
Fix #2000

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2001)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
So I think this is not needed.  The edge case we hit we should actually warn.  The edge case that was hit, was where two instances where put into standby in EC2.  This did not allow a rolling-update to occur properly.

**Comment by justinsb** [comment]
On master:

```
kops rolling-update cluster --instance-group nodes
Using cluster from kubectl context: simple.example.com

W0407 22:40:24.346199   17725 rollingupdate_cluster.go:107] Found ASG with no corresponding instance group "master-us-east-1c.masters.simple.example.com"
NAME    STATUS  NEEDUPDATE      READY   MIN     MAX     NODES
nodes   Ready   0               2       2       2       2

No rolling-update required.
```

**Comment by chrislovecnm** [comment]
Sorry that this has been open so long.  Do we need this change?  It seems to be an edge case where someone modified the ig in the aws console.  Please answer with a Yes, and I push the button :)

**Comment by justinsb** [comment]
Yes - did you see the comment above?

**Comment by justinsb** [comment]
Push the LGTM button :-)

**Pull request merged**
