### PR TITLE
chore(sysctls): modify sysctls to improve tcp connections

### PR DESCRIPTION
**Pull request by igorvpcleao**

### CODE REVIEW

**Comment by justinsb** [comment]
@igorvpcleao are you able to sign the CLA?  Also, if you have a reference for where you are taking these settings from, it would be great to know where that is so we can figure out why the values are what they are...

**Comment by blakebarnett** [comment]
This would be great to get in, but I agree we need better documentation on why each setting is needed.

**Comment by justinsb** [comment]
Marking as WIP until CLA bot is happy!

**Comment by justinsb** [comment]
/close

Closing because of lack of CLA; if you are able to sign the CLA we would welcome the contributions!

**Pull request closed without merging**
