### PR TITLE
Cherry pick of #9069 onto release-1.17

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #9069

### CODE REVIEW

**Comment by johngmyers** [comment]
`hack/verify-packages.sh` is failing

**Comment by justinsb** [comment]
Thanks for the heads up!  Hopefully it'll pass this time.  It wasn't a totally clean cherry-pick, e.g. I had to add wellknownusers.

**Comment by johngmyers** [comment]
Yes, I noticed that during review.
/lgtm

**Comment by hakman** [comment]
Any ideas if this change could have affected the containerd periodic e2e?
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-containerd

**Comment by johngmyers** [comment]
I'm seeing that the failed e2e test is having a problem pulling the new sidecar container. Perhaps the e2e test config or somesuch needs to be tweaked to use the locally built container?

**Pull request merged**
