### PR TITLE
Typo fix an->and

### PR DESCRIPTION
**Pull request by AdamDang**
Line 119: "kubectl is downloaded an installed by other tasks"
Typo fix an->and

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks @AdamDang 

/ok-to-test
/lgtm

**Comment by chrislovecnm** [comment]
/lgtm

Let me know if you want to work on writing more docs, like new ones. Appreciate the spelling fixes.

**Comment by AdamDang** [comment]
@chrislovecnm 
Thanks for your invitation! I'd like to work on the document.  I can try a new one.

**Pull request merged**
