### PR TITLE
Update elasticsearch logging to 5.6.4

### PR DESCRIPTION
**Pull request by frankh**
I've picked the versions of everything used by the kubernetes
fluentd-elasticsearch plugin at https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/kibana-deployment.yaml

I'm not sure exactly how versioning for addons is supposed to work. These changes don't depend on any particular version of kubernetes which is what the addon versions seem to be named after.

I've kept it in 1.6.0 for ease of diff/review for now

### CODE REVIEW

**Comment by frankh** [comment]
Update CLA

**Comment by chrislovecnm** [comment]
Can we create a new version of the YAML?  That will allow upgrades.  Not certain we can upgrade cleanly ...  Take a look at how the other addons add a new YAML file and update the addons file https://github.com/frankh/kops/blob/2a47341bd468db3209f039dcc7f32fcb5867dc44/addons/logging-elasticsearch/addon.yaml

**Comment by frankh** [comment]
I've changed to a new yaml file, v1.7.0 -  again, not entirely sure how the versioning system works so not sure if it should match the required kubernetes version? AFAIK it should run on 1.6, same as before

**Comment by frankh** [comment]
I've split this into 2 commits, the first simply copies 1.6.0.yaml to 1.7.0.yaml, which means the diff for the 2nd commit is much easier to follow

**Comment by justinsb** [comment]
/approve
/lgtm

Thanks @frankh - and thanks also for splitting it up into the separate commits

**Pull request merged**
