### PR TITLE
Fix amazon-vpc-routed-eni yaml template

### LINKED ISSUE #6499: amazon-vpc-routed-eni does not apply cleanly
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.11.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.12.0
**3. What cloud provider are you using?**
AWS
**4. What commands did you run?  What is the simplest way to reproduce this issue?**
When bootstraping a brand new cluster with these kops + k8s versions. Resulting channel does not apply cleanly because the yaml is invalid.

```
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Error: error updating "networking.amazon-vpc-routed-eni": error applying update from "networking.amazon-vpc-routed-eni/k8s-1.10.yaml": error running kubectl
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Usage:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   channels apply channel [flags]
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Flags:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -f, --filename strings   Apply from a local file
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -h, --help               help for channel
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --yes                Apply update
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Global Flags:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --alsologtostderr                  log to standard error as well as files
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --config string                    config file (default is $HOME/.channels.yaml)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --log_dir string                   If non-empty, write log files in this directory
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --logtostderr                      log to standard error instead of files (default false)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -v, --v Level                          log level for V logs (default 0)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: error updating "networking.amazon-vpc-routed-eni": error applying update from "networking.amazon-vpc-routed-eni/k8s-1.10.yaml": error running kubectl
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.524930    5693 channels.go:34] apply channel output was: I0216 14:26:45.647059    9206 addons.go:38] Loading addons channel from
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.751640    9206 s3context.go:194] found bucket in region
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.751745    9206 s3fs.go:220] Reading file
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.779034    9206 addons.go:113] Skipping version range "<1.6.0" that does not match current version 1.12.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.779069    9206 addons.go:113] Skipping version range "<1.6.0" that does not match current version 1.12.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.779079    9206 addons.go:113] Skipping version range "<1.7.0" that does not match current version 1.12.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.779087    9206 addons.go:113] Skipping version range ">=1.7.0 <1.8.0" that does not match current version 1.12.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.779096    9206 addons.go:113] Skipping version range ">=1.8.0 <1.10.0" that does not match current version 1.12.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: NAME                                        CURRENT        UPDATE
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: core.addons.k8s.io                        -        1.4.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: networking.amazon-vpc-routed-eni        -        1.3.0-kops.1
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.789615    9206 addon.go:130] Applying update from
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.789645    9206 s3fs.go:220] Reading file
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:45.808993    9206 apply.go:67] Running command: kubectl apply -f /tmp/channel733093387/manifest.yaml
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.327852    9206 channel_version.go:175] sending patch: "{\"metadata\":{\"annotations\":{\"addons.k8s.io/core.addons.k8s.io\":\"{\\\"version\\\":\\\"1.4.0\\\",\\\"channel\\\"
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Updated "core.addons.k8s.io" to 1.4.0
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.336853    9206 addon.go:130] Applying update from
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.336897    9206 s3fs.go:220] Reading file
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.343764    9206 apply.go:67] Running command: kubectl apply -f /tmp/channel535499246/manifest.yaml
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.518964    9206 apply.go:70] error running kubectl apply -f /tmp/channel535499246/manifest.yaml
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: I0216 14:26:46.518998    9206 apply.go:71] clusterrole.rbac.authorization.k8s.io/aws-node unchanged
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: serviceaccount/aws-node unchanged
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: clusterrolebinding.rbac.authorization.k8s.io/aws-node unchanged
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: daemonset.extensions/aws-node unchanged
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: error: error validating "/tmp/channel535499246/manifest.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.names): unknown field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionNames; if you choose to ignore these errors, turn validation off with --validate=false
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Error: error updating "networking.amazon-vpc-routed-eni": error applying update from "networking.amazon-vpc-routed-eni/k8s-1.10.yaml": error running kubectl
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Usage:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   channels apply channel [flags]
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Flags:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -f, --filename strings   Apply from a local file
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -h, --help               help for channel
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --yes                Apply update
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]: Global Flags:
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --alsologtostderr                  log to standard error as well as files
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --config string                    config file (default is $HOME/.channels.yaml)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --log_dir string                   If non-empty, write log files in this directory
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --logtostderr                      log to standard error instead of files (default false)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:   -v, --v Level                          log level for V logs (default 0)
Feb 16 14:26:46 ip-10-102-50-176 docker[5639]:       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

### PR DESCRIPTION
**Pull request by tvi**
Current yaml structure is invalid.
Crosschecked with https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.3/aws-k8s-cni.yaml

Fixes #6499.

### CODE REVIEW

**Comment by tvi** [comment]
ping

**Comment by justinsb** [comment]
Thanks @tvi 

/approve
/lgtm

**Pull request merged**
