### PR TITLE
Upgrade docker/containerd/containeros hashes to SHA256

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by hakman** [comment]
```bash
% VERIFY_HASHES=1 go test -v ./nodeup/pkg/model -run TestContainerdPackageHashes
=== RUN   TestContainerdPackageHashes
--- PASS: TestContainerdPackageHashes (64.95s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.4-1_amd64.deb (3.04s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.10-3_amd64.deb (2.08s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/containerd.io_1.2.10-3_amd64.deb (2.13s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/containerd.io_1.2.10-3_amd64.deb (2.12s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.10-3_amd64.deb (2.37s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm (2.82s)
    --- PASS: TestContainerdPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm#01 (0.15s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.10.linux-amd64.tar.gz (6.51s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.11.linux-amd64.tar.gz (6.59s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.12.linux-amd64.tar.gz (6.45s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.2.13.linux-amd64.tar.gz (6.39s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.3.2.linux-amd64.tar.gz (7.29s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.3.3.linux-amd64.tar.gz (7.08s)
    --- PASS: TestContainerdPackageHashes/https://storage.googleapis.com/cri-containerd-release/cri-containerd-1.3.4.linux-amd64.tar.gz (9.95s)
PASS
ok  	k8s.io/kops/nodeup/pkg/model	65.940s
```
```bash
% VERIFY_HASHES=1 go test -v ./nodeup/pkg/model -run TestDockerPackageHashes
=== RUN   TestDockerPackageHashes
--- PASS: TestDockerPackageHashes (145.13s)
    --- PASS: TestDockerPackageHashes/http://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_17.03.2~ce-0~debian-stretch_amd64.deb (2.81s)
    --- PASS: TestDockerPackageHashes/http://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb (2.19s)
    --- PASS: TestDockerPackageHashes/http://download.docker.com/linux/static/stable/x86_64/docker-17.03.2-ce.tgz (2.74s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm (2.15s)
    --- PASS: TestDockerPackageHashes/http://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_17.09.0~ce-0~debian_amd64.deb (2.37s)
    --- PASS: TestDockerPackageHashes/http://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb (2.75s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.06.2~ce~3-0~ubuntu_amd64.deb (3.78s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb (4.33s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.09.0.ce-1.el7.centos.x86_64.rpm (2.48s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.03.1~ce~3-0~ubuntu_amd64.deb (3.28s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.2~ce~3-0~ubuntu_amd64.deb (4.14s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.06.1~ce~3-0~debian_amd64.deb (3.97s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.06.2~ce~3-0~debian_amd64.deb (4.06s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~debian_amd64.deb (3.90s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.1.ce-3.el7.x86_64.rpm (4.61s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.09.3~3-0~debian-stretch_amd64.deb (3.08s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.2.ce-3.el7.x86_64.rpm (4.56s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb (4.29s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.06.3~ce~3-0~debian_amd64.deb (4.11s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.3.ce-3.el7.x86_64.rpm (4.31s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.3.ce-3.el7.x86_64.rpm#01 (0.21s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.09.9~3-0~debian-stretch_amd64.deb (3.85s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_18.09.9~3-0~debian-buster_amd64.deb (4.67s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_18.09.9~3-0~ubuntu-xenial_amd64.deb (3.50s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_18.09.9~3-0~ubuntu-bionic_amd64.deb (4.07s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.9-3.el7.x86_64.rpm (4.80s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.9-3.el7.x86_64.rpm#01 (0.20s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/static/stable/x86_64/docker-18.09.9.tgz (6.07s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/static/stable/x86_64/docker-19.03.4.tgz (6.84s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_19.03.4~3-0~debian-stretch_amd64.deb (7.25s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_19.03.4~3-0~debian-buster_amd64.deb (6.85s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_19.03.4~3-0~ubuntu-xenial_amd64.deb (7.14s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.4~3-0~ubuntu-bionic_amd64.deb (6.86s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.4-3.el7.x86_64.rpm (6.58s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.4-3.el7.x86_64.rpm#01 (0.34s)
    --- PASS: TestDockerPackageHashes/https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz (5.98s)
PASS
ok  	k8s.io/kops/nodeup/pkg/model	145.830s

```

**Comment by rifelpet** [comment]
@hakman we should make that a make target if it isn’t already. “make verify-hashes” or something, and then find an appropriate place to run it in prow

/approve

**Comment by hakman** [comment]
Good idea @rifelpet. Will create a PR for that.

**Pull request merged**
