### PR TITLE
Add brew install documentation

### PR DESCRIPTION
**Pull request by WillPlatnick**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/989)

### CODE REVIEW

**Comment by WillPlatnick** [comment]
I signed it!

**Comment by WillPlatnick** [comment]
Partially solves https://github.com/kubernetes/kops/issues/912

**Comment by WillPlatnick** [comment]
This should now completely solve https://github.com/kubernetes/kops/issues/912

**Comment by kris-nova** [comment]
@WillPlatnick 

This looks good so far, I think the docs are spot on. And this offers everything I think we need to move forward with homebrew support as a team.

I think some long term goals are going to be getting this automated into our build process, and potentially offering pre built binaries.

This LGTM - but I'll give it to EOD to let the rest of the team take a look.

Thanks again!

**Comment by kris-nova** [comment]
@WillPlatnick I opened up this issue, as there is a bug I found https://github.com/kubernetes/kops/issues/991


Let me know if you want to fix this PR - or - we can merge this in *now*, and we can get another PR out later.

Cheers!

**Comment by justinsb** [comment]
This is awesome @WillPlatnick  - thanks :-)

**Comment by chrislovecnm** [comment]
@WillPlatnick marking this work in progress until we get brew fixed.

**Comment by brandoncole** [comment]
I really like this!  Awesome work @WillPlatnick.

**Comment by WillPlatnick** [comment]
@kris-nova I believe WIP can be removed and this can be merged as per https://github.com/kubernetes/kops/issues/991

**Comment by kris-nova** [comment]
LGTM - Thank you @WillPlatnick!

**Pull request merged**
