### PR TITLE
Update aws-sdk-go to v1.37.33 for kOps 1.20

### PR DESCRIPTION
**Pull request by hakman**
This will allow it to recognize `ap-northeast-3`.

### CODE REVIEW

**Comment by olemarkus** [comment]
I support backporting this.
/lgtm

**Comment by hakman** [comment]
Leaving final decision to @rifelpet and @johngmyers.

**Comment by rifelpet** [comment]
agreed, seems reasonable
/lgtm

**Review by johngmyers — APPROVED** [review]
I'm a bit on the fence. Since it's a patch release, I suppose it can go in.

**Pull request merged**
