### PR TITLE
Workaround for overlay2 vs rhel-family docker bug

### PR DESCRIPTION
**Pull request by justinsb**
Docker 17.x with rhel-family fails to detect overlay2 correctly, and
need us to pass overlay2.override_kernel_check=true for docker to
correctly detect overlay2 support.

### CODE REVIEW

**Comment by zetaab** [comment]
/test pull-kops-e2e-kubernetes-aws
I think this solves problem https://github.com/kubernetes/kops/issues/6348 ?

**Comment by justinsb** [comment]
Ah - nice found @zetaab - that looks like the issue!

**Comment by RAR** [comment]
Hey @justinsb  - Question on this change:

We override storage on our systems to use devicemapper.  Full override is:

``` 
    storage: devicemapper
    storageOpts:
    - dm.thinpooldev=/dev/mapper/docker-docker--pool
    - dm.use_deferred_deletion=true
    - dm.use_deferred_removal=true
    - dm.fs=ext4
```

Docker now fails to start due to:

```
-- The start-up result is done.
Mar 19 14:41:32 ip-10-23-8-22.us-east-2.compute.internal docker[16423]: /usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
Mar 19 14:41:32 ip-10-23-8-22.us-east-2.compute.internal docker[16423]: See '/usr/bin/docker run --help'.
Mar 19 14:41:32 ip-10-23-8-22.us-east-2.compute.internal systemd[1]: protokube.service: main process exited, code=exited, status=125/n/a
Mar 19 14:41:32 ip-10-23-8-22.us-east-2.compute.internal systemd[1]: Unit protokube.service entered failed state.
Mar 19 14:41:32 ip-10-23-8-22.us-east-2.compute.internal systemd[1]: protokube.service failed.
Mar 19 14:41:33 ip-10-23-8-22.us-east-2.compute.internal dockerd[16421]: Error starting daemon: error initializing graphdriver: devmapper: Unknown option overlay2.override_kernel_check
Mar 19 14:41:33 ip-10-23-8-22.us-east-2.compute.internal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 19 14:41:33 ip-10-23-8-22.us-east-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
```

Is there a way to fully remove this addition for my use case without forcing a non 17.* version of docker?

**Pull request merged**
