### PR TITLE
WIP: Add a default RBAC rule to avoid kubernetes/kubernetes#39259

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes kubernetes/kubernetes#39256 (as a quick hack).

Long-term solution is to fix kubernetes/kubernetes#39259

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1286)

### CODE REVIEW

**Comment by liggitt** [comment]
I would rather tolerate a forbidden error in the e2e grant than add this, even temporarily

**Comment by liggitt** [comment]
Also, this shouldn't be tagged for 1.5.0, since the e2e test change that caused it went into the 1.6 branch

**Comment by liggitt** [comment]
(Unless kops uses the 1.5 branch differently than I expect)

**Comment by zmerlynn** [comment]
@liggitt: Then let's talk about reverting several PRs in the main repo. `kops` isn't yet blocking, and I can't make progress there until it is.

**Comment by zmerlynn** [comment]
Nevermind, after looking at testgrid, it really is just the three failures that @cjcullen fixed in kubernetes/kubernetes#39263.

But this increases the urgency for getting this back blocking, if you're working in this area.

**Pull request closed without merging**
