### PR TITLE
Config is deprecated, use PodManifestPath

### PR DESCRIPTION
**Pull request by mtaufen**
This is in preparation for https://github.com/kubernetes/kubernetes/pull/40048

/cc @zmerlynn

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1708)

### CODE REVIEW

**Comment by zmerlynn** [comment]
@mtaufen: How long has `--pod-manifest-path` been live? `kops` at master needs to support 1.4+, at least. (Looking in main repo...)

**Comment by zmerlynn** [comment]
Looks like this worked from 1.4.0 on, should be safe.

**Comment by mtaufen** [comment]
Potential cause of the test failure?
```
W0130 11:10:36.256] W0130 11:10:36.256050     547 executor.go:109] error running task "LaunchConfiguration/nodes.aws-kops-agent-pr-53-0.test-aws.k8s.io" (9m59s remaining to succeed): IAM instance profile not yet created/propagated (original error: Invalid IamInstanceProfile: nodes.aws-kops-agent-pr-53-0.test-aws.k8s.io)
W0130 11:10:36.257] W0130 11:10:36.256117     547 executor.go:109] error running task "LaunchConfiguration/master-us-west-2b.masters.aws-kops-agent-pr-53-0.test-aws.k8s.io" (9m59s remaining to succeed): IAM instance profile not yet created/propagated (original error: Invalid IamInstanceProfile: masters.aws-kops-agent-pr-53-0.test-aws.k8s.io)
W0130 11:10:36.257] I0130 11:10:36.256172     547 executor.go:91] Tasks: 49 done / 53 total; 2 can run
W0130 11:10:37.160] W0130 11:10:37.159472     547 executor.go:109] error running task "LaunchConfiguration/nodes.aws-kops-agent-pr-53-0.test-aws.k8s.io" (9m58s remaining to succeed): IAM instance profile not yet created/propagated (original error: Invalid IamInstanceProfile: nodes.aws-kops-agent-pr-53-0.test-aws.k8s.io)
W0130 11:10:37.161] W0130 11:10:37.159531     547 executor.go:109] error running task "LaunchConfiguration/master-us-west-2b.masters.aws-kops-agent-pr-53-0.test-aws.k8s.io" (9m58s remaining to succeed): IAM instance profile not yet created/propagated (original error: Invalid IamInstanceProfile: masters.aws-kops-agent-pr-53-0.test-aws.k8s.io)
```

**Comment by mtaufen** [comment]
@zmerlynn yup, `PodManifestPath` was added in v1.4

**Comment by mtaufen** [comment]
@k8s-bot aws e2e test this

**Comment by zmerlynn** [comment]
@mtaufen: I believe the issue is that `PodManifestPath` isn't defined. Trying to remember where to stick it right now. (Also, I can't figure out why `cluster/log-dump.sh` is failing, or it would've been obvious in the `protokube` logs.)

**Comment by zmerlynn** [comment]
@mtaufen: It needs to be defined in `pkg/apis/kops/componentconfig.go`, similar to how #1357 handled it.

**Comment by mtaufen** [comment]
Ok I'll fix it up. Just out of curiosity, since you already vendor k8s.io/kubernetes, any reason you don't just include the componentconfig types from there?

**Comment by justinsb** [comment]
LGTM!  Thanks @mtaufen.

The challenges using componentconfig from k8s:

1) we add flag annotations on them so that we can map them back to flags
2) we change some of the types to pointers, so that there's no ambiguity as to whether a flag is set or not
3) when we started componentconfig wasn't as rich as it is now

**Pull request merged**
