### PR TITLE
For dev, don't preload docker images on nodes

### PR DESCRIPTION
**Pull request by justinsb**
If we're not going to use the docker images, we don't need to preload
them - saves a bit off the boot time.

### CODE REVIEW

**Comment by hakman** [comment]
Nice! This saves me a PR.

In the same context, shouldn't the LoadImage task be in the ProtokubeBuilder?
https://github.com/kubernetes/kops/blob/0b52b994be03f143608c11f74a56532edd8cce7b/upup/pkg/fi/nodeup/command.go#L304-L310

**Comment by rifelpet** [comment]
shoot, should have merged this before my mocks update

**Comment by justinsb** [comment]
Also moved the protokube image loading into ProtokubeBuilder - thanks for the suggestion @hakman!

**Pull request merged**
