### PR TITLE
WIP: Support "egress: External" to avoid configuring networking

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Includes #5139, once that merges will be smaller.

The idea here is that we allow a subnet to explicitly opt-out of route configuration.  Where all subnets opt-out, we end up not configuring and routes, route tables or creating an IGW.  (See final commit where I have broken out the change)

cc @chrislovecnm

**Comment by xrl** [comment]
This is interesting. I am going to build this locally and test it out.

**Comment by geojaz** [comment]
@justinsb While this seems to work for me, and I want to get something akin to this into 1.11, I don't love the details.

If we want to 100% let the user manage networking outside of kops, IMO, we should make that an option. In current state, this feels like a secret feature. I don't think this use case really fits the intention of the egress flag but I could be convinced otherwise. I love to configure, but for me, this feature fits best at the top level and with a more relevant name.

I would prefer something like: `createIGW: (true/false)`. And I guess if you wanted to do more granular egress config on a subnet basis, leaving egress off would imply that you wanted to DIY, and `egress: i-123` would do the standard (assuming we were in `createIGW: false` mode. Without trying it out, I'm not even sure how the routing would work in a split scenario like this.

This reminds me... We're starting to have network related stuff all over the cluster spec. Is it time for a crazy refactor and to pull this all into a networking object?

**Comment by justinsb** [comment]
@geojaz ... yes I think it's time to consider an external networking object, particularly with machines API coming :-)

**Comment by dannyg28** [comment]
Any more word on this? Would love to have this functionality

**Comment by moustafab** [comment]
We've forked this repo, to manage 2 of our clusters which are needing external networking and are hoping we can get this into the next release. @justinsb can we update your fork or should we open a new PR based on it?

**Comment by justinsb** [comment]
This is a new feature - we discussed in office hours that we should prioritize bug fixes until we get kops 1.12 released, and that this could help us catch up quickly.

/milestone 1.13

**Comment by drewwells** [comment]
Documentation says that External is support, why is this PR closed if the docs say it is supported?

https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#egress

**Comment by geojaz** [comment]
@drewwells @granular-ryanbonham I think the bulk of this, if not the entire thing was captured in https://github.com/kubernetes/kops/pull/6218 and has been improved on. 

If 6218 does not take care of your use case, please draft a proposal in an issue so can discuss :D

**Pull request closed without merging**
