### PR TITLE
Canal manifest updates for k8s v1.12+

### LINKED ISSUE #5751: Canal MTU does not support jumbo frames
**1. What `kops` version are you running?**
`Version 1.10.0 (git-8b52ea6d1)`

**2. What Kubernetes version are you running?**

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops create cluster with `spec.networking.canal: {}` and `spec.kubelet.networkPluginMtu: 8951`

**5. What happened after the commands executed?**
Cluster functions, but pod to pod and pod to node MTU size is 1500, rather than 9001 or 8951 (depending)

**6. What did you expect to happen?**
Pod to pod networking to leverage MTU size of 8951

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**
I can provide if required.

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**
n/a

**9. Anything else do we need to know?**
pod to self MTU is 65535
pod to pod on same host MTU is 9001
pod to pod on different host MTU is 1500  (this is the problem)

Method:
```
# tracepath -np 9999 100.96.7.3
 1?: [LOCALHOST]                      pmtu 9001
 1:  172.20.132.53                                         0.066ms
 1:  172.20.132.53                                         0.031ms
 2:  172.20.132.53                                         0.034ms pmtu 8951
 2:  100.96.7.0                                            1.172ms
 3:  100.96.7.0                                            1.140ms pmtu 1500
 3:  100.96.7.3                                            1.078ms reached
     Resume: pmtu 1500 hops 3 back 3
```

### PR DESCRIPTION
**Pull request by KashifSaadat**
**Changes:**
- Update Canal manifest to v3.6.1 for Kubernetes v1.12+
- Allow configuring the MTU for Canal, keep default value as 1500 (fixes #5751)

Related docs: https://docs.projectcalico.org/v3.6/networking/mtu#selecting-mtu-size

### CODE REVIEW

**Comment by mikesplain** [comment]
@KashifSaadat we probably shouldn't cherry-pick this into 1.12 but maybe 1.13 or 1.14? Thoughts?

**Comment by KashifSaadat** [comment]
Cheers @mikesplain, good question! There's no specific urgency for bringing it into the v1.12 release so it can wait, but is a reasonably small change either way so shouldn't cause any issues :)

**Comment by mikesplain** [comment]
Great, I'll take care of it in a joint cherrypick

**Pull request merged**
