### PR TITLE
Promote alpha to stable

### PR DESCRIPTION
**Pull request by MoShitrit**
It's been 8 days since #13379 was merged, so we should be good with promoting the latest k8s versions to `stable` at this point.
/cc @hakman @olemarkus

### CODE REVIEW

**Review by hakman — APPROVED** [review]
Thanks @MoShitrit :)

**Comment by MoShitrit** [comment]
@hakman thanks for #13412!
Now that it's merged, should I pull `master` into my branch and push it up? Or does it happen automagically thanks to k8s-ci-bot? 😄

**Comment by hakman** [comment]
@MoShitrit yes, you should rebase. That should fix the tests.
/lgtm cancel until fixing the tests

**Comment by MoShitrit** [comment]
> @MoShitrit yes, you should rebase. That should fix the tests.


@hakman done!

**Comment by hakman** [comment]
👍 
/lgtm

**Comment by hakman** [comment]
@MoShitrit could you rebase instead of merging master?

**Comment by MoShitrit** [comment]
> @MoShitrit could you rebase instead of merging master?

@hakman yep already did.
At first I pulled master into my branch, but then I rebased and force-pushed. Not sure why is this label not being removed. I only see my single commit in this PR right now. Am I missing something?

**Comment by hakman** [comment]
Maybe it's just slow 😆

**Comment by MoShitrit** [comment]
Looks like this isn't going away. I'm going to close that PR and open a new one.
/close

**Pull request closed without merging**
