### PR TITLE
[Issue-12293] Fix json output to keep it consistent for single or multiple objects

### PR DESCRIPTION
**Pull request by srikiz**
A minor fix, tested and works as expected.
For a single cluster you would still return an array as seen below.

```
./kops get clusters -o json | jq .
[
  {
    "kind": "Cluster",
    "apiVersion": "kops.k8s.io/v1alpha2",
    "metadata": {
      "name": "dev***ds.co.in",
      "creationTimestamp": "2022-02-01T14:17:41Z"
    },
    "spec": {
      "channel": "stable",
      "configBase": "do://sri-k***e/de****ds.co.in",
      "cloudProvider": "digitalocean",
      "kubernetesVersion": "1.22.5",
      "subnets": [
        {
          "name": "tor1",
          "zone": "tor1",
          "region": "tor1",
          "type": "Public"
        }
      ],
      "masterPublicName": "ap*****.co.in",
      "topology": {
        "masters": "public",
        "nodes": "public",
        "dns": {
          "type": "Public"
        }
      },
      "nonMasqueradeCIDR": "100.64.0.0/10",
      "sshAccess": [
        "0.0.0.0/0",
        "::/0"
      ],
      "kubernetesApiAccess": [
        "0.0.0.0/0",
        "::/0"
      ],
      "etcdClusters": [
        {
          "name": "main",
          "etcdMembers": [
            {
              "name": "etcd-1",
              "instanceGroup": "master-tor1-1"
            }
          ],
          "memoryRequest": "100Mi",
          "cpuRequest": "200m"
        },
        {
          "name": "events",
          "etcdMembers": [
            {
              "name": "etcd-1",
              "instanceGroup": "master-tor1-1"
            }
          ],
          "memoryRequest": "100Mi",
          "cpuRequest": "100m"
        }
      ],
      "kubeProxy": {
        "enabled": false
      },
      "kubelet": {
        "anonymousAuth": false
      },
      "networking": {
        "cilium": {
          "enableNodePort": true
        }
      },
      "api": {
        "dns": {}
      },
      "authorization": {
        "rbac": {}
      },
      "iam": {
        "legacy": false,
        "allowContainerRegistry": true
      }
    }
  }
]
```

### CODE REVIEW

**Comment by srikiz** [comment]
@olemarkus - please suggest if you see any issues with this. This should keep the `get clusters -o json` consistent to return an array for a single/multiple clusters. However, it also returns an array when using `kops get cluster test.example.com -ojson` as well. I fixed the test for the same, but not sure if we should expect it to return a cluster object instead of an array if a single cluster is specified. 
I still like the existing behavior, so not sure if we really need to modify this pattern here.

**Comment by olemarkus** [comment]
Can you add a small mention in the 1.23 release notes (assume we can cherry-pick this there)

**Comment by srikiz** [comment]
> Can you add a small mention in the 1.23 release notes (assume we can cherry-pick this there)

Okay. Should I do that after this gets merged into master, and when we cherry pick this into 1.23 release branch?

**Comment by olemarkus** [comment]
The docs are served from master only, so add it to this PR please.

**Comment by olemarkus** [comment]
I think you can squash the commits and then this is good.

**Comment by srikiz** [comment]
@olemarkus - Fixed docs as per your suggestion. Also, realized I missed one use-case where we still need to return a single object if `kops get cluster dev.example.com -ojson` is specified. I have fixed that as well. The changes would ensure:

> `kops get clusters -o json` -- will always return a list (irrespective of whether the list contains a single or multiple clusters)
> `kops get cluster dev.example.com -ojson` -- will return a single object.
> `kops get ig -o json` -- will return based on the size of the ig.

**Comment by srikiz** [comment]
> I think you can squash the commits and then this is good.

@olemarkus - Done. Please have a look when you get a chance. Thanks !

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
