### PR TITLE
fix-up staticcheck error

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@justinsb

**Comment by tanjunchen** [comment]
@hwdef

**Comment by tanjunchen** [comment]
@justinsb

**Comment by tanjunchen** [comment]
@justinsb can you help me review it ?   Thank You !

**Comment by justinsb** [comment]
Thanks @tanjunchen - looks good

/approve
/lgtm

**Pull request merged**
