### PR TITLE
Spotinst: integrate AWS instance metadata config to instance groups

### PR DESCRIPTION
**Pull request by yehielnetapp**
add AWS instance metadata v2 support. fix Ocean Capacity in mod SpotinstOceanTemplate .

### CODE REVIEW

**Comment by yehielnetapp** [comment]
@hakman look like PR Update dependencies to K8s v1.27 #15373 : 
  https://github.com/kubernetes/kops/commit/30f84a4f13a4b292efe3d4142404340d38b72555
  overwrite PR Spotinst: bump spotinst-sdk-go to v1.145.0 #15361

**Comment by hakman** [comment]
@yehielnetapp The `CI` tests need manual rebase. They should pass after that.

**Pull request closed without merging**
