### PR TITLE
Add missing OpenStack reference

### PR DESCRIPTION
**Pull request by marsavela**
Add missing OpenStack reference.

### CODE REVIEW

**Comment by marsavela** [comment]
@rifelpet could you move this forward?

**Comment by rifelpet** [comment]
@marsavela I'm only able to `/lgtm` the PR, we will need someone in the approvers list in the `OWNERS` file to `/approve` it which will trigger the merge.

**Comment by marsavela** [comment]
@rifelpet understood, thanks. 

@drekle Since you're the owner of the OS part of this, maybe you can merge this...

**Comment by mikesplain** [comment]
Thanks @marsavela!

/lgtm
/approve

**Pull request merged**
