### PR TITLE
fix static check error in vfssync.go

### PR DESCRIPTION
**Pull request by beautytiger**

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @beautytiger 

/approve
/lgtm
/ok-to-test

**Comment by rdrgmnzs** [comment]
Hi @beautytiger, this looks great. Can you follow the instructions at https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md#updating-the-generated-api-code to re-generate the API code.

Thanks!

**Comment by beautytiger** [comment]
@rdrgmnzs 
Thanks for your instruction.
Rebased and run `make apimachinery && make`, it seems ok.

**Pull request merged**
