### PR TITLE
v1alpha3: remove redundant ConfigStore

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by hakman** [comment]
I would say that ConfigBase is the redundant one. Everything else has the Store suffix...

**Comment by johngmyers** [comment]
Many fewer places use ConfigStore; it only affects ACLs.  As it derives from ConfigBase it is unlikely anyone would set it.

My plan is to change to a `configStore` sub-struct: `configStore.base`, `configStore.keypairs`, and `configStore.secrets`.

**Review by hakman — APPROVED** [review]

**Pull request merged**
