### PR TITLE
Implement Openstack cloudmock, add integration test

### PR DESCRIPTION
**Pull request by rifelpet**
This implements basic CRUD logic for all of the openstack resources, a followup to #9698 

Most of the resource types are pretty straight forward except:
* zones and recordsets live under the same /zones path prefix
* loadbalancer responses have their pools and listener IDs embedded in them
* routers and routerinterfaces live under the same /routers path prefix
* the security group rule's `remote_group_id` query param behaves differently than other filters - if it isn't provided that indicates the rules should not have a remote_group_id field, rather than not filtering on the field at all.
 
Next steps:
* server creation just uses a hardcoded IP address. I can update this to use sequential IPs in their subnet in a followup PR 
* loadbalancers and pools dont have their /members subresource yet. 
* I believe loadbalancer creation creates a VIP automatically but I need to look into the docs more
* I'll need to update this for octavia support
* We'll want a "complex_openstack" integration test that has a more complete `spec.cloudConfig.openstack` 

This is a large PR but most of the file changes are all independent so the "context depth" for reviewing this shouldn't be too bad, but if you want me to break up the first commit further I can do that.

### CODE REVIEW

**Comment by olemarkus** [comment]
The test and the clusterspec looks good. I didn't go through all the mock implementations in detail though. I suspect tweaks are needed anyway once we try to add a more complex spec.

There is no way to go in and verify that e.g dns servers was correctly set on a subnet after the tests has run right? One would need something like Heat or Terraform support to validate that? Which doesn't even guarantee that the direct output works as expected.

/lgtm

**Comment by rifelpet** [comment]
Right, this wont verify that values are set properly. Terraform support would take us a step further since it has input validation, but neither would catch issues like "the wrong IP was used" or "there's a typo in userdata". Those could only be caught by having e2e jobs which would definitely be my preferred route but we've discussed that a few times :) hopefully we can get the infra in place for that sometime.

In the mean time, this integration test will catch issues like:
* nil pointer dereference in openstack models or openstacktasks
* openstacktasks dependency cycles
* inaccurate openstacktasks Find logic
* missing resource types in pgk/resources/openstack

**Comment by xoxbet** [comment]
> This implements basic CRUD logic for all of the openstack resources, a followup to #9698

Hello @rifelpet, are you sure you've mentioned correct issue here?

**Comment by rifelpet** [comment]
@xoxbet oops you're right, that was supposed to be https://github.com/kubernetes/kops/pull/9691. Thanks for catching that

**Pull request merged**
