### PR TITLE
Revert "Deploys dns-controller with default ingress setting (--watch-ingress=true)"

### PR DESCRIPTION
**Pull request by justinsb**
This reverts commit 8c13903ab748567390138cfead667bc376e9fc0c.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2560)

### CODE REVIEW

**Comment by justinsb** [comment]
Per discussion, turning on watch-ingress breaks a lot of people.  We likely want to do something like #2504, but we want to get 1.6.0 out the door first, and #2504 is a bigger change that would probably delay our release clock.

**Comment by justinsb** [comment]
Also, @sethpollack is going to look at using external-dns for ingress :-)  Would be great to start using / recommending it, and I don't _think_ ingress DNS is currently required for API bringup.

**Comment by geojaz** [comment]
@justinsb @chrislovecnm thanks gents! I'm tied up moving from east to west coast for the time being...

**Pull request merged**
