### PR TITLE
GCE tutorial markdown formatting

### PR DESCRIPTION
**Pull request by flaviamissi**
Hi! First of all I'd like to thank you for making this! I'm eager to try it out o/

The current `master` version of the document contains a few formatting issues that makes it hard to read. The proposed changes attempt to make formatting better to read and more concise. Rendering the Github markdown will provide better "before and after" view of the changes.

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks - this does look better!  Out of interest, why do you use the indent style instead of the triple backticks?  I didn't know you could do that!

Are you able to sign the CLA?  It's a bit of a pain the first time, but once you've done so it should be valid across all the kubernetes projects?

**Comment by justinsb** [comment]
Ah - apparently my commenting woke up the CLA bot.  So ignore that :-)

**Comment by justinsb** [comment]
Thanks @flaviamissi ... I do wonder about indent vs backticks and whether there's a reason to go one way or the other, but thank for fixing!

/approve
/lgtm
/ok-to-test

**Comment by flaviamissi** [comment]
Hey @justinsb, sorry for the long delay!

>  Out of interest, why do you use the indent style instead of the triple backticks? I didn't know you could do that!

I have no strong reason to use one or the other. The background for switching to indents in this specific case was that the triple backticks got messy, so it seemed simpler to use the indentation here. Hope the choice wasn't confusing! 

And thanks for getting the patch in! 💪

**Pull request merged**
