### PR TITLE
Update weave to 1.9.7

### PR DESCRIPTION
**Pull request by justinsb**
This includes the hairpin fix

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2704)

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @kris-nova !

**Comment by jordanjennings** [comment]
@justinsb I was working on this same change last week and found an issue with NodePort services, which I reported to weave here:

https://github.com/weaveworks/weave/issues/3011

This definitely affected an upgrade, but I haven't had time to go back and test if it affects newly created clusters. Have you tested this already, and if not could you double check?

cc @chrislovecnm

**Comment by justinsb** [comment]
Thanks @jordanjennings - https://github.com/weaveworks/weave/releases/tag/v1.9.7 has reference to a bug and a fix, and I applied that same fix here (in the second commit - I didn't spot it first time).

With that fix, LoadBalancer services do work, and LoadBalancer services use NodePort.

Want to try with the extra commit on your branch and let me know if that works for you also?

**Comment by jordanjennings** [comment]
@justinsb I diffed the old and new weave files before trying my fix, so I caught both the version number bump as well as the host name fix in my branch. Here's my file for reference:

https://github.com/jordanjennings/kops/blob/weave-upgrade/upup/models/cloudup/resources/addons/networking.weave/k8s-1.6.yaml.template

**Comment by jordanjennings** [comment]
Also - I just diffed the weave yaml on kops master vs my branch and apart from a minor ordering difference they are the same. I would expect to see this issue after upgrades using master, but I can give it a try again today to be sure.

**Comment by jordanjennings** [comment]
Sorry for the flurry of comments, but just to clarify: the issue is that NodePort services work as long as the pod you're trying to hit happens to be on the node you're hitting. I really only caught this issue by luck, because at first try everything seemed to be working great. If the LoadBalancer service is pointing to a DaemonSet (like an ingress controller maybe) or a deployment that happens to be running a pod on each node then everything "appears" to be fine.

**Comment by justinsb** [comment]
Yes - I think the issue is that I was testing with a relatively small cluster, and # of pods > # of nodes.  Reading through the issues now...

**Pull request merged**
