### PR TITLE
add targetRamMb to kubeAPIServer spec

### PR DESCRIPTION
**Pull request by captainkerk**
This PR adds support for setting targetRamMb in the kube apiserver spec

### CODE REVIEW

**Comment by captainkerk** [comment]
The travis build is failing on `make gen-cli-docs`, which is failing on master as well. I'm happy to add it to this PR, though I suppose that deserves its own PR.

**Comment by justinsb** [comment]
Sorry, the `make gen-cli-docs` is because I temporarily broke master trying getting some old docs prs merged - ignore it and I'll force-merge once it's only travis failing.

I'm was just debating how we should name the flag - `Mb` or `MB`.  We haven't been very consistent about resources in flags...

I think Mb is both more correct and more consistent, therefore...

/approve
/lgtm
/ok-to-test

**Comment by justinsb** [comment]
Manually merging because all tests but travis have passed, and travis failure is known problem with master (since resolved).

**Comment by captainkerk** [comment]
Thank you Justin!

**Pull request merged**
