### PR TITLE
Add gen-api-docs target to makefile

### PR DESCRIPTION
**Pull request by justinsb**
Following instructions in docs/apireference/README.md

### CODE REVIEW

**Comment by justinsb** [comment]
Do not merge before #3001; marking as WIP.

@pwittrock - want to take a look at the Makefile - the 4th commit?

**Comment by chrislovecnm** [comment]
Not going to lgtm, because when we move in the merge queue, it will nab it.  I am not sure how to label it so it does not merge it.

**Comment by justinsb** [comment]
Rebased and reworked for instructions & fixes (thanks @pwittrock !).  @pwittrock want to take a look?

**Comment by justinsb** [comment]
Why `do-not-merge` @chrislovecnm ?

**Comment by chrislovecnm** [comment]
@justinsb was making sure that I got the labels correct.  Just testing.  Should merge now :)

**Pull request merged**
