### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by xichengliudui**
Removing unnecessary code saves space

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @xichengliudui - I think it also keeps govet happy!

I think you need to run gofmt though - that's why travis is failing.

Otherwise lgtm

/approve
/lgtm
/ok-to-test

(not that it will merge without gofmt getting fixed!)

**Comment by xichengliudui** [comment]
@justinsb  
Thank you very much for your prompt. I have executed gofmt.

**Comment by mikesplain** [comment]
Thanks @xichengliudui!
/lgtm
/approve

**Pull request merged**
