### PR TITLE
update kube-router to 0.3.1

### PR DESCRIPTION
**Pull request by caraboides**
I updated the kube router to the current version for k8s>=1.11

### CODE REVIEW

**Comment by granular-ryanbonham** [comment]
Thanks for the PR. Are you able to sign the CLA? That is required before we can merge this PR.

Thanks

**Comment by tkoeck** [comment]
Are there any news on that PR?

**Comment by caraboides** [comment]
@granular-ryanbonham I think i have the CLA `You are already authorized to contribute code to this project through your membership with CNCF - Inoio.`
Or did i some thing wrong, sorry i am a little bit confused :-/

**Comment by caraboides** [comment]
see: #7317

**Pull request closed without merging**
