### PR TITLE
Typo fix detaults->defaults

### PR DESCRIPTION
**Pull request by AdamDang**
Typo fix detaults->defaults

### CODE REVIEW

**Comment by justinsb** [comment]
Would you mind squashing the commits please @AdamDang ?

**Comment by AdamDang** [comment]
@justsb Thanks a lot for your kind attention.
I can use only the browser to work with github. I still do not know how to put them together. Can I squash the commits with browser like Chrome?

**Comment by AdamDang** [comment]
/assign @geojaz @justinsb 
Please can you help to squash the commits in this PR? Thanks!

**Comment by justinsb** [comment]
/approve

/lgtm

I'm not sure about the github code editor, and I'd rather have the typo fixes than one commit :-)  Thank you for the fixes @AdamDang

**Pull request merged**
