### PR TITLE
fixed link to topology.md file

### PR DESCRIPTION
**Pull request by mshenhera**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1722)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Can u fill out the CLA?

**Comment by chrislovecnm** [comment]
@mshenhera can you please sign the CLA?

**Comment by chrislovecnm** [comment]
Hi there - can u please sign the cla, or let us know if you cannot

**Comment by mshenhera** [comment]
Hi Chris, I've signed the cla.

**Comment by yissachar** [comment]
@k8s-bot ok to test

**Pull request merged**
