### PR TITLE
Update kOps recommended versions and images

### PR DESCRIPTION
**Pull request by hakman**
/cc @MoShitrit @olemarkus @rifelpet

### CODE REVIEW

**Comment by MoShitrit** [comment]
Hmm, that's odd. I just made a PR to update alpha today and it got merged earlier today. 
Did I miss anything [here](https://github.com/kubernetes/kops/pull/11245) @hakman ?

**Review by MoShitrit — APPROVED** [review]

**Comment by hakman** [comment]
> Hmm, that's odd. I just made a PR to update alpha today and it got merged earlier today.
> Did I miss anything [here](https://github.com/kubernetes/kops/pull/11245) @hakman ?

Nop... that was me missing that part. Thanks for beating me to it.

**Comment by MoShitrit** [comment]
> > Hmm, that's odd. I just made a PR to update alpha today and it got merged earlier today.
> > Did I miss anything [here](https://github.com/kubernetes/kops/pull/11245) @hakman ?
> 
> Nop... that was me missing that part. Thanks for beating me to it.

Thanks!!! 😄

**Review by MoShitrit — APPROVED** [review]

**Comment by MoShitrit** [comment]
@hakman any chance we need `hack/update-expected.sh` here, since we changed the image? I think I've had to do that in the past when I updated it. I guess I _did_ miss checking that part earlier, so thanks for doing that!

**Review by MoShitrit — APPROVED** [review]

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
