### PR TITLE
Update cluster_spec docs with audit logging

### PR DESCRIPTION
**Pull request by Grillz**
Updates docs to reflect https://github.com/kubernetes/kops/pull/1879

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2620)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Can you sign the cla?

**Comment by Grillz** [comment]
@chrislovecnm I did about an hour ago, is it not showing up?

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
It picked it up ;)

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Pull request merged**
