### PR TITLE
Fix typos in docs/getting_started

### PR DESCRIPTION
**Pull request by roim**
Found a typo while going through these docs. I then ran a quick check on everything under `getting_started/` and found another one.

Admins: feel free to patch directly instead of approving the PR.

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
Hi @roim, thanks for fixing these typos. Please sign the CLA to be able to merge it.
/ok-to-test

**Comment by roim** [comment]
Working on that, thanks hakman

**Comment by hakman** [comment]
> Working on that, thanks hakman

Any news? Do you need any help with this?

**Comment by roim** [comment]
@hakman just waiting on a contact from our legal team to ensure there's nothing conflicting with my current contract, but will try to get it in tomorrow

**Comment by hakman** [comment]
Perfect. Thanks!

**Comment by roim** [comment]
I signed it

**Pull request merged**
