### PR TITLE
Rebrand kops to kOps

### PR DESCRIPTION
**Pull request by hakman**
This should make the purpose of the project more clear.
https://deploy-preview-10077--kubernetes-kops.netlify.app

/cc @justinsb @mikesplain 
/hold for feedback

### CODE REVIEW

**Comment by olemarkus** [comment]
This didn't immediately resonate well with me. Does this also change the pronunciation to k-ops?

**Comment by hakman** [comment]
> This didn't immediately resonate well with me. Does this also change the pronunciation to k-ops?

I would say so, but not mandatory.

**Comment by johngmyers** [comment]
I showed the old and suggested logo to someone with graphic design experience and got this feedback:

* The O does not read as capital.
* What is the purpose of the chevron? In the current logo it appears to incorporate a K, but that is not necessary in the new logo.
* What is the purpose of the shading?
* The kerning needs to be adjusted.

What is the typeface? Are there any particular color or design standards we are trying to follow? What are we trying to achieve (other then de-emphasizing the K)?

**Comment by randomvariable** [comment]
+100 on the idea

**Comment by olemarkus** [comment]
After giving this some more thought, I am also 100% on-board with this.

**Comment by hakman** [comment]
Thanks @olemarkus :).
/assign @justinsb

**Comment by geojaz** [comment]
@olemarkus Thanks for confirming, initially i had a similar reaction, but coming back to it, feel like this is the right direction. +1 from me too

**Comment by geojaz** [comment]
@hakman are you specifically waiting for justin's approval? after the discussion in office hours, i'm happy to do it

**Comment by hakman** [comment]
Thanks @geojaz. I think we all agree, so probably should merge and see how the users receive it.
/hold cancel

**Review by geojaz — APPROVED** [review]
I think we're ready to do this one, so i'll push the button... With the understanding that we're all trying to do the best we can with the world we live in. And if and when we need to iterate on this, we will.
/lgtm
Thanks all

**Pull request merged**
