### PR TITLE
add cluster proportional autoscaler for coredns

### PR DESCRIPTION
**Pull request by sethpollack**

### CODE REVIEW

**Comment by justinsb** [comment]
Sorry for the delay.  Do you mind if we tackle this in kops 1.12?  (And we should compare it to https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns-horizontal-autoscaler/dns-horizontal-autoscaler.yaml )

**Comment by sethpollack** [comment]
@justinsb Yes, thats fine. But shouldn't it be compared to https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/kube-dns.addons.k8s.io/k8s-1.6.yaml.template ?

**Comment by justinsb** [comment]
Thanks @sethpollack and I hope you'll hang in there!

We discussed in [office-hours on 3/15](https://www.youtube.com/watch?v=SdW4Y7FgZfI&index=2&list=PL69nYSiGNLP2NcuGKoAzme6ZtZmrJlsaR&t=930s) the need to prioritize bug fixes until we can get 1.12 out (which will hopefully mean we get to everything faster overall), and I believe this is a feature, so I'm going to move this to the next release.

/milestone 1.13

**Pull request closed without merging**
