### PR TITLE
Remove setting oom score since not compatible with 1.6

### PR DESCRIPTION
**Pull request by andrewsykim**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2222)

### CODE REVIEW

**Comment by justinsb** [comment]
Hmmm...  this is from https://github.com/kubernetes/kubernetes/blob/release-1.6/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest#L62

What are you seeing that suggests it is broken?

**Comment by andrewsykim** [comment]
```
I0329 01:25:56.699746       8 server.go:173] setting OOM scores is unsupported in this build
```

Could be a config error on my end though

**Comment by andrewsykim** [comment]
It was a mistake on my end, the full error message was 
```
I0329 01:27:29.394314       7 server.go:173] setting OOM scores is unsupported in this build
invalid configuration: no server found for cluster "local"
```

My nodeup binary was stale so it had a stale kubeconfig file for kube-proxy which was the real reason for crashing, the OOM score message is just a warning before it, not sure if the message has always been there :P

**Comment by justinsb** [comment]
Hmm... that does feel like it might be a separate issue, but thank you for tracking it down!

**Pull request closed without merging**
