### PR TITLE
for whatever reason the import was missing for asset, which caused co…

### PR DESCRIPTION
**Pull request by JuJu227**
…mpile failures for API and examples. Extremely small change; however, is obviously needed for the API to work.  @chrislovecnm @kris-nova

### CODE REVIEW

**Comment by kris-nova** [comment]
This PR seems a bit odd - wondering if we could get : 

1. Replication steps to produce whatever error/problem you are seeing
2. More information on why this PR attempts to solve whatever is broken
3. Does this fix API things? More detail on what it's fixing please

I am just wondering how we are getting compile errors without this one-liner? I personally compile kops all the time - without any issues - but if this is API related you have my interest peaked!

**Comment by JuJu227** [comment]
@kris-nova 

Apologies: should've written an issue for this first. It was a dead simple fix though 
1) The quickest way to recreate this error is to simply run `make examples` which results in 
`
go install k8s.io/kops/examples/kops-api-example/...
k8s.io/kops/upup/models
upup/models/vfs.go:58: undefined: Asset
upup/models/vfs.go:69: undefined: AssetDir
upup/models/vfs.go:94: undefined: AssetDir
make: *** [examples] Error 2
`
2)  From the error above it's obvious, it's just a missing import package.  I initially found this issue when I was attempting to integrate with the API directly.

**Comment by justinsb** [comment]
I'm not seeing the problem; let's see if CI can see it :-)

**Comment by chrislovecnm** [comment]
LGTM

**Comment by kris-nova** [comment]
So I don't think this is an import error.. I think this is an issue with using kops as a library and the dependency manager missing `bindata.go`

Kops will generate a `kops/upup/models/bindata.go` file upon compiling... that file contains the `Asset()` and `AssetDir()` functions needed for the code to run.. 

The fix (IMHO) should have been to generate a `bindata.go` from the same source you plan on using as your library and stick in your dependency manager's copy of kops `kops/upup/models/bindata.go` and recompile the master project


### The error
```
vendor/k8s.io/kops/upup/models/vfs.go:61: undefined: Asset
vendor/k8s.io/kops/upup/models/vfs.go:72: undefined: AssetDir
vendor/k8s.io/kops/upup/models/vfs.go:97: undefined: AssetDir
```
### The fix
```
cp /go/src/k8s.io/kops/upup/models/bindata.go Godeps/_workspace/src/k8s.io/kops/upup/models
```
Can I get a few +1's on this so I can undo the merge please?

**Pull request merged**
