### PR TITLE
Delete route tables, even if untagged, if we are deleting the VPC

### PR DESCRIPTION
**Pull request by justinsb**
The route table cannot exist without a VPC; if we're deleting the VPC we
must delete the route table also.

This will help fix problems when we fail to tag the route-table.

Issue #597

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@kris-nova can u take a peak?

@justinsb - can we add a unit test?

**Comment by chrislovecnm** [comment]
Need a rebase btw

**Comment by justinsb** [comment]
With unit test.

**Comment by chrislovecnm** [comment]
NICE ... LGTM

**Pull request merged**
