### PR TITLE
update instances list with make update-machine-types

### PR DESCRIPTION
**Pull request by rekcah78**
adding : 
m5.8xlarge
m5.16xlarge

m5a.8xlarge
m5a.16xlarge

m5d.8xlarge 
m5d.16xlarge

r5.8xlarge
r5.16xlarge

r5a.8xlarge
r5a.16xlarge

r5d.8xlarge
r5d.16xlarge

### CODE REVIEW

**Comment by mikesplain** [comment]
I'll open cherry-picks for the upcoming releases as well.

**Comment by rekcah78** [comment]
@mikesplain do you think the test failure is due to my PR or the e2e platform ?

**Pull request merged**
