### PR TITLE
Bump nvidia-driver-535 for CUDA 12 support

### PR DESCRIPTION
**Pull request by ddelange**
Close https://github.com/kubernetes/kops/issues/16557

### CODE REVIEW

**Comment by olemarkus** [comment]
Definitely use the `-server` package, which does not bring in the xorg-core deps.

**Comment by hakman** [comment]
@ddelange would you like to continue with this PR? 😄

**Comment by ddelange** [comment]
hey :wave: I'm AFK until beginning July. Feel free to take over if you have the time:)

**Comment by ddelange** [comment]
@hakman ready to merge?

**Comment by hakman** [comment]
Thanks @ddelange. Would you mind also squashing the commits?

**Comment by ddelange** [comment]
done :)

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
