### PR TITLE
Allow disabling warm pool by setting WarmPool.MaxSize to 0

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by olemarkus** [comment]
What is the use case for this? Perhaps if one wants to keep the struct around, but disable the pool, the standard `enabled` flag would be better?

**Comment by johngmyers** [comment]
This would allow us to add a `warmPool` struct at cluster level, providing defaults. Much like we do for `rollingUpdate`.

**Review by olemarkus — APPROVED** [review]
Sounds good

**Pull request merged**
