### PR TITLE
fix: protokube restart always and spawn new containers

### PR DESCRIPTION
**Pull request by MqllR**
The issue is described here https://github.com/kubernetes/kops/issues/7928

TL;DR
The systemd service for protokube enter in an infinity loop and flood new containers.

### CODE REVIEW

**Comment by MqllR** [comment]
CLA signed

**Comment by mikesplain** [comment]
Hi @MqllR! This looks pretty good.  Have you tested this? Were you able to replicate the crashing issue and confirm this protects things (as it should)? 

/ok-to-test

**Comment by MqllR** [comment]
Hi @mikesplain !

I reproduced the issue with sending a sig term to journald. This is how I reproduce:

```
# ps auxw | grep journald                                                                                                                                                                 
root      1441  0.1  0.8 131212 69580 ?        Ss   Oct25  37:03 /usr/lib/systemd/systemd-journald                                                                                                                 
# kill 1441
```

Then, the service protokube will start to flap and create new failing containers:

```
# docker ps -a | grep protokube
700d344a8928        protokube:1.13.2                                                    "/usr/bin/protokube …"   Less than a second ago   Exited (2) Less than a second ago                       jovial_clarke
c2d7092885d8        protokube:1.13.2                                                    "/usr/bin/protokube …"   3 seconds ago            Exited (2) 3 seconds ago                                quizzical_wiles
1d76cd819002        protokube:1.13.2                                                    "/usr/bin/protokube …"   6 seconds ago            Exited (2) 5 seconds ago                                frosty_bell
1d785a37a145        protokube:1.13.2                                                    "/usr/bin/protokube …"   9 seconds ago            Exited (2) 8 seconds ago                                eager_noyce
74c62eb400d1        protokube:1.13.2                                                    "/usr/bin/protokube …"   11 seconds ago           Exited (2) 11 seconds ago                               festive_tesla
21ef746f8178        protokube:1.13.2                                                    "/usr/bin/protokube …"   14 seconds ago           Exited (2) 14 seconds ago                               optimistic_swirle
s
e3d3948b3bad        protokube:1.13.2                                                    "/usr/bin/protokube …"   17 seconds ago           Exited (2) 16 seconds ago                               brave_allen
a5bff6a56c2f        protokube:1.13.2                                                    "/usr/bin/protokube …"   20 seconds ago           Exited (2) 19 seconds ago                               optimistic_benz
ee08c8c82dbf        protokube:1.13.2                                                    "/usr/bin/protokube …"   23 seconds ago           Exited (2) 22 seconds ago                               zealous_sammet
0392c89fda35        protokube:1.13.2                                                    "/usr/bin/protokube …"   25 seconds ago           Exited (2) 25 seconds ago                               competent_volhard
2ebc60f5c327        protokube:1.13.2                                                    "/usr/bin/protokube …"   28 seconds ago           Exited (2) 28 seconds ago                               vigilant_bohr
d1ecdc9c7341        protokube:1.13.2                                                    "/usr/bin/protokube …"   31 seconds ago           Exited (2) 30 seconds ago                               agitated_meninsky
7b9dd9aec196        protokube:1.13.2                                                    "/usr/bin/protokube …"   35 seconds ago           Exited (2) 33 seconds ago                               lucid_wescoff
88a9d5e3f3af        protokube:1.13.2                                                    "/usr/bin/protokube …"   3 weeks ago              Up 3 weeks                                              elegant_chebyshev
```

To test my configuration, I edited the systemd conf and tested it again:

```
# cat /lib/systemd/system/protokube.service 
[Unit]
Description=Kubernetes Protokube Service
Documentation=https://github.com/kubernetes/kops

[Service]
ExecStartPre=/bin/true
ExecStartPre=-/usr/bin/docker stop protokube
ExecStartPre=-/usr/bin/docker rm protokube
ExecStart=/usr/bin/docker run -v /:/rootfs/ -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd --name=protokube ...
Restart=always
RestartSec=2s
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
```

It fixes the issue as expected.

We must test with a full kops deployment but I'm fighting a bit to build the binary.

**Comment by maruina** [comment]
@MqllR can I ask you why the docker command starts with a `-` in the systemd unit file?

**Comment by MqllR** [comment]
> @MqllR can I ask you why the docker command starts with a `-` in the systemd unit file?

Hi @maruina,
I put a `-` because both `stop` and `rm` could failed at the first start (the container is not created). The dash record the event but don't consider the service as failed: https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=

**Comment by maruina** [comment]
Thanks! I learned a new thing :)

**Comment by MqllR** [comment]
Hi @mikesplain,

I've build nodeup and run it to verify the output. It's the expected result.

**Comment by MqllR** [comment]
Since the merge of https://github.com/kubernetes/kops/pull/7986, the change I proposed has been implemented inside... don't sure to see the relation between splitting the CRI/containerd and protokube systemd!

**Pull request closed without merging**
