### PR TITLE
Fix bash commands on "Set up IAM user" section in aws docs.

### PR DESCRIPTION
**Pull request by JisuPark**
Hello there.

I was following [setting-up-a-kops-iam-user](https://github.com/kubernetes/kops/blob/master/docs/aws.md#setting-up-a-kops-iam-user) for create kops user.

But it doesn't work, so I fixed commands properly.

Thanks

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2355)

### CODE REVIEW

**Comment by JisuPark** [comment]
I have signed the CLA, thanks.

**Comment by justinsb** [comment]
Thanks @JisuPark .  But the command in the docs "works for me", using bash.

With the proposed change, I only observe the first arn value.   I think we would have to change the loop to

`for arn in ${arns[@]}; do echo $arn; done`

Which shell are you using?  What error do you see with the version in the docs?

**Comment by JisuPark** [comment]
@justinsb Oh sorry, it's my bad. I use zsh(5.0.8) so I just tested my code only for zsh.
I've checked my changes don't work on bash(3.2.57).

If we run below code for the original one on the zsh

```
for arn in $arns; do echo $arn '1'; done
``` 

I expected

```
arn:aws:iam::aws:policy/AmazonEC2FullAccess 1
arn:aws:iam::aws:policy/AmazonRoute53FullAccess 1
arn:aws:iam::aws:policy/AmazonS3FullAccess 1
arn:aws:iam::aws:policy/IAMFullAccess 1
arn:aws:iam::aws:policy/AmazonVPCFullAccess 1
```

as a result but the actual result is 

```
arn:aws:iam::aws:policy/AmazonEC2FullAccess
arn:aws:iam::aws:policy/AmazonRoute53FullAccess
arn:aws:iam::aws:policy/AmazonS3FullAccess
arn:aws:iam::aws:policy/IAMFullAccess
arn:aws:iam::aws:policy/AmazonVPCFullAccess 1
```

which means array don't work.

That's why I've changed for the zsh.

**Comment by chrislovecnm** [comment]
@JisuPark do we need this PR, if I am reading correctly the changes you made were because of zsh.

**Comment by JisuPark** [comment]
@chrislovecnm Sorry about late reply. You are right. I think we'd better close this PR :D

**Pull request closed without merging**
