### PR TITLE
Bump cilium to 1.7.5

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by rifelpet** [comment]
is there a reason this is targeting release-1.18 and not master? I don't see this change in master nor an open PR for it.

**Comment by olemarkus** [comment]
I am redoing the templates and config on master. See #9295 etc. Aim to use the 1.8 line on master if cilium release it in time (they are in RC phase now)

**Comment by rifelpet** [comment]
ahh got it, thanks for the clarification.

/approve

**Comment by rifelpet** [comment]
though unfortunately we wont have much test coverage of this since the cilium periodic job(s) use the master branch...

**Comment by olemarkus** [comment]
@rifelpet Wouldn't this do? https://testgrid.k8s.io/kops-k8s-1.18#kops-grid-cilium-u2004-k18
doesn't run that frequent though.

**Comment by olemarkus** [comment]
Or they perhaps uses kops master, but that specific release branch?

**Comment by hakman** [comment]
> Or they perhaps uses kops master, but that specific release branch?

👍

**Comment by hakman** [comment]
@rifelpet should we create optional e2e tests for the popular CNIs that we could run on any PR?

**Comment by rifelpet** [comment]
Ah i like that idea a lot. we could even have them run automatically based on changes to each provider's yaml directory.

**Comment by hakman** [comment]
Right, that hashes test should be a pretty good template for this.

**Comment by rifelpet** [comment]
anyone want to volunteer setting those up? We might be able to use them across multiple branches (master and release-*) too.

**Comment by hakman** [comment]
Let's start with master. I think I may have some time tomorrow to copy / paste these jobs, unless someone else beats me to it.

**Pull request merged**
