### PR TITLE
WIP: Repackage weaveworks/mesh, don't use build tags

### PR DESCRIPTION
**Pull request by justinsb**
bazel doesn't play nice with build tags.

### CODE REVIEW

**Comment by justinsb** [comment]
After the awesome work in #4477 , this should let gossip DNS work with a bazel-built protokube

**Comment by mikesplain** [comment]
Awesome! Thanks @justinsb!

/lgtm

**Comment by justinsb** [comment]
Actually this causes messiness because those files don't have the required headers ... sigh.

**Comment by mikesplain** [comment]
Eek! Good catch
/lgtm cancel

**Comment by justinsb** [comment]
We did this via sed statements in the Makefile instead

/close

**Pull request closed without merging**
