### PR TITLE
moving adding a feature docs to development

### PR DESCRIPTION
**Pull request by chrislovecnm**
This been bugging me since it is kinda in the wrong directory 😀

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@zmerlynn any ideas what is up with Jenkins and this?

**Comment by zmerlynn** [comment]
@k8s-bot test this
@chrislovecnm There was a fun test glitch when you opened this PR. Separately, prow is losing webhooks, so never reported it. You can always kick it with `@k8s-bot test this` (in this repo; in the `kubernetes` repo you want `@k8s-bot aws e2e test this` to test kops alone).

**Comment by zmerlynn** [comment]
@k8s-bot test this (mumble, it's still dropping webhooks).

**Comment by justinsb** [comment]
Works for me - thanks!

**Pull request merged**
