### PR TITLE
Remove kubeconfig path from log

### LINKED ISSUE #670: Log message about write config incorrect
I have

```shell
KUBECONFIG=/Users/clove/.kube/config:/Users/clove/.kube/k8s-01.dev.aws-us-west-2.datapipe.io:/Users/clove/.kube/k8s-06.dev.aws-us-west-2.datapipe.io:/Users/clove/.kube/old-config
```

and kops logged

```shell
I1017 16:02:14.502657   50732 create_cluster.go:479] Exporting kubecfg for cluster
Wrote config for clove-k8s.dev.datapipe.io to "/Users/clove/.kube/config:/Users/clove/.kube/k8s-01.dev.aws-us-west-2.datapipe.io:/Users/clove/.kube/k8s-06.dev.aws-us-west-2.datapipe.io:/Users/clove/.kube/old-config"
```

It wrote the config out to `~/.kube/config` but we need log that we wrote it to that.

### PR DESCRIPTION
**Pull request by kris-nova**
- Just removing the `to` part of the log message. I don't think its a huge win to have that in the logs, and was causing problems This closes #670

### CODE REVIEW

**Comment by kris-nova** [comment]
@chrislovecnm - what are we gaining by logging the file we wrote to? I haven't looked at the exact implementation of doing this but imagine it would require some hacking.

Just want to make sure the feature is worth it.

**Comment by chrislovecnm** [comment]
It prints out the location to the ui which is helpful to me as a user.  If it has a path delimiter I believe it is written to the first file, but I do not know. It is a ui / user visible change, that is why I am being picky about it.  Did the path help you when you ran it?

**Comment by kris-nova** [comment]
Will commit a fix for the working file path - thanks for the feedback

**Comment by kris-nova** [comment]
@chrislovecnm - The kubectl config will read from the first element in your kubeconfig path - See https://github.com/kubernetes/kops/pull/701/commits/c12c4aa5d690d224b9866a9b6aae0bd22290b7e3 that addresses this.

**Comment by chrislovecnm** [comment]
Awesomesauce LGTM

**Pull request merged**
