### PR TITLE
Update controller-tools and CRDs

### PR DESCRIPTION
**Pull request by rifelpet**
The `make crds` task is currently broken on master because:

1. `controller-tools` is no longer in the vendor directory after the switch to go mod. The tools.go addition fixes that.
2. [controller-tools 1.1.0](https://github.com/kubernetes/kops/commit/e48cf3635342c665a82a753fd660634a03a98bd3#diff-37aff102a57d3d7b797f152915a6dc16L151) was depending on a conflicting version of the `k8s.io/api` and needed updating to the very latest commit in order to pick up support for 1.15.

Marking WIP because i haven't had a chance to actually test the CRDs yet and do a structural `yamldiff` to look for any unexpected changes.
/hold

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks for doing this.  Two things:

* I think we need https://github.com/kubernetes-sigs/controller-tools/pull/322 in controller-tools, so that the CRDs can then be installed on 1.16 (otherwise we hit https://github.com/kubernetes-sigs/controller-tools/issues/302).  I did `GO111MODULE=on go get -u sigs.k8s.io/controller-tools@76a25b63325ae000dd90099b151b196ac55979ac`  A nice side effect of this is that the CRDs _are_ then recognized as renames and the diff is more comprehensible.

* I'm changing float -> resource.Quantity in the other series of PRs, to avoid the warnings from the generator.  I'm not 100% sure whether they are just warnings i.e. are the fields just ignored.

**Comment by rifelpet** [comment]
Thanks for the suggestions! I'm still fighting some dependency version compatibility issues and for some reason `hack/update-bazel.sh` is regenerating the `BUILD.bazel` files in the vendor directory, but the new CRD yamls are looking much better. I'll try to get the remaining issues addressed soon.

**Comment by rifelpet** [comment]
@justinsb reran the go get and everything worked better this time :) CRD diffs are looking good overall too

/hold cancel

**Comment by justinsb** [comment]
Thanks for doing this!

/approve
/lgtm

**Pull request merged**
