### PR TITLE
Update Calico manifests to better match the latest release

### PR DESCRIPTION
**Pull request by tmjd**
- Adds mounts for Application layer policy https://docs.projectcalico.org/v3.8/security/app-layer-policy/
- Re-organizes manifest to better match (reduce differences) with source
  Calico manifests.
  https://docs.projectcalico.org/v3.8/manifests/calico-etcd.yaml
  https://docs.projectcalico.org/v3.8/manifests/calico.yaml
- Switch install-cni container to initContainer
- Fix critical annotation on kube-controller

### CODE REVIEW

**Comment by tmjd** [comment]
I've tested this out by:
- installing with my changes
- Installing a cluster with kops v1.13 and then updating with my changes.
- Enabling Calico Application Layer Policy https://docs.projectcalico.org/v3.8/security/app-layer-policy/ and verifying by following the tutorial at the link.

**Comment by tmjd** [comment]
I don't want this PR to get too out of date. What is the next step needed here?

**Comment by miguelbernadi** [comment]
This Pr is also very interesting for my case as it adds the PriorityClassName to calico. We recently added PriorityClasses to the cluster for our apps and calico-node got evicted due to receiving the default (lowest) priority. Would be very glad to see it become part of a patch release for 1.13.

**Comment by mikesplain** [comment]
Hey @tmjd sorry for the delay on this, let me dive in a bit and get back to you. I recently did a similar update so I need to make sure these line up right. Also, I really think we should only be updating the v1.12 manifest because we don't run any tests against those old versions and really do not support them any more given our deprecation policy.  That said, I really really appreciate your work on this and the contribution! I'll setup a reminder to look at this later this week when I can give it the time it deserves.

**Comment by hakman** [comment]
@tmjd @mikesplain I think https://github.com/kubernetes/kops/pull/8104 does something similar for latest Calico manifest.

**Comment by mikesplain** [comment]
Since this has been since handled, closing. Sorry for the delay and thanks for the contribution.

/close

**Pull request closed without merging**
