### PR TITLE
Fix typos in kops_upgrade.md

### PR DESCRIPTION
**Pull request by aknuds1**
Fix typos in kops_upgrade.md.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2815)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
Thanks for you PR btw!

**Comment by aknuds1** [comment]
@chrislovecnm Thanks for feedback, I've gone and changed the Go source as you suggested.

**Comment by chrislovecnm** [comment]
Thanks!

**Pull request merged**
