### PR TITLE
dns: Update coredns to v1.11.3

### PR DESCRIPTION
**Pull request by ataut-pai**
fixes https://github.com/kubernetes/kops/issues/16916

### CODE REVIEW

**Comment by hakman** [comment]
@ataut-pai Thanks for the PR! The test failure looks like a flake.
Before we merge this, would you mind squashing your commits?

**Comment by ataut-pai** [comment]
thank you, @hakman, squashed the commits so should be ready for merge 💯 

PS: also, the previous bunch of tests before squash were 🟢

**Comment by hakman** [comment]
> QQ: is there an ETA for the next patch release?

Probably in the next 1-2 weeks.

**Review by hakman — APPROVED** [review]

**Pull request merged**
