### PR TITLE
Verify gofmt as part of build

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1317)

### CODE REVIEW

**Comment by justinsb** [comment]
We're hoping will travis will fail on this one, because gofmt is broken on head, then we can merge #1316, rebase and it should go green :-)

**Comment by aledbf** [comment]
@justinsb why you list each package? why not just use `go list`?

**Comment by justinsb** [comment]
@aledbf I did it that way because `go list` seems to be super-slow.  Instead I create the list of packages, and then CI verifies that the list of packages is up to date, using `go list`: https://github.com/kubernetes/kops/pull/1317/files#diff-7f01cd2a406bfdb00503ee8e0e9b5936R26

**Comment by chrislovecnm** [comment]
WTH is travis not picking this up??

**Comment by justinsb** [comment]
Persuaded travis with a refactor.

It is picking up the bindata.go files though...

**Comment by justinsb** [comment]
Just rebased now that #1316 has merged; should go green

**Comment by chrislovecnm** [comment]
Can you rebase this, as I merged the gofmt fix.  This failed correctly

**Comment by chrislovecnm** [comment]
waiting on e2e

**Comment by justinsb** [comment]
We need a way to skip e2e, although there is value in knowing if it fails on "unrelated" changes I guess

**Comment by justinsb** [comment]
Green; merging :-)

**Pull request merged**
