### PR TITLE
Limit concurrency of asset copy tasks 

### PR DESCRIPTION
**Pull request by johngmyers**
Why: parallelism after a certain point doesn't make things any faster: there's only so much bandwidth. Less parallelism increases the amount of feedback on progress and allows retries of interrupted copies to better avoid recopying by having more completed copies.

How: It uses a buffered channel as a semaphore.

### CODE REVIEW

**Comment by hakman** [comment]
This would deserve a description with why and how it's done. Other than that...
/lgtm

**Comment by johngmyers** [comment]
Why: parallelism after a certain point doesn't make things any faster: there's only so much bandwidth. Less parallelism increases the amount of feedback on progress and allows retries of interrupted copies to better avoid recopying by having more completed copies.

How: It uses a buffered channel as a semaphore.

**Comment by johngmyers** [comment]
@hakman Is there a particular place you wanted that description? How can I move this forward?

**Review by hakman — APPROVED** [review]
Sorry, missed this.
Description was not for me but for anyone looking at this 6 months from now.

**Pull request merged**
