### PR TITLE
Propose awsudo as a workaround for kops mfa

### PR DESCRIPTION
**Pull request by max-lobur**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2791)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@max-lobur are you able to sign our CLA?

**Comment by max-lobur** [comment]
@chrislovecnm just signed! thanks!

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
Thanks @max-lobur

**Pull request merged**
