### PR TITLE
Update versions for romana container images

### PR DESCRIPTION
**Pull request by cgilmour**
This updates the template for romana networking to ship the latest released versions.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Appreciate the PR! 

In order for kops to pick-up the update with existing cluster we need to update https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go with a higher version number.

Thanks

**Comment by cgilmour** [comment]
Thanks Chris. I've updated it to also bump the version in `bootstrapchannelbuilder.go`

**Pull request merged**
