### PR TITLE
Update apiVersion in docs and tests

### PR DESCRIPTION
**Pull request by johngmyers**
Not sure how to update `docs/apireference/build/index.html`

### CODE REVIEW

**Comment by rifelpet** [comment]
/ok-to-test

I wonder if we need to keep at least some of the integration tests using the old apiVersion in order to test backwards compatibility...

**Comment by johngmyers** [comment]
I left the old apiVersion in `kops/tests/integration/conversion/minimal/legacy-v1alpha2.yaml` and `kops/tests/integration/update_cluster/complex/in-legacy-v1alpha2.yaml`

**Comment by rifelpet** [comment]
ah that's right. That sounds sufficient to me

/lgtm

**Pull request merged**
