### PR TITLE
Remove support for Canal and the vxlan Flannel backend

### LINKED ISSUE #8562: 1.17 alpha versions causing regression for kiam?
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Any of the 1.17 alphas so far.

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

seen in 1.17.0-rc.2 through 1.17.3. Works without issue on kops/k8s 1.15 and 1.16 built clusters. ONLY change is bump to 1.17.x.

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Try to install kiam via it's included helm chart onto a kops 1.17.x built-cluster

**5. What happened after the commands executed?**

The kiam-agent daemonsets crashloop

**6. What did you expect to happen?**

No crashloop.

**7. Please provide your cluster manifest. Execute

Will follow up with this if asked for. Main thing applicable here is we are using CoreDNS

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

From the agent logs w/ gRPC debugging enabled:
```
kubectl -n kube-system logs kiam-agent-5z8tt
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9620","time":"2020-02-14T18:13:41Z"}
INFO: 2020/02/14 18:13:41 parsed scheme: "dns"
INFO: 2020/02/14 18:13:46 grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.kiam-server on 100.64.0.10:53: dial udp 100.64.0.10:53: operation was canceled.
WARNING: 2020/02/14 18:13:46 grpc: failed dns A record lookup due to lookup kiam-server on 100.64.0.10:53: dial udp 100.64.0.10:53: operation was canceled.
INFO: 2020/02/14 18:13:46 ccResolverWrapper: got new service config: 
INFO: 2020/02/14 18:13:46 ccResolverWrapper: sending new addresses to cc: []
{"level":"fatal","msg":"error creating server gateway: error dialing grpc server: context deadline exceeded","time":"2020-02-14T18:13:46Z"}
```

**9. Anything else do we need to know?**

Bug also posted with kiam folks here: uswitch/kiam#378

### PR DESCRIPTION
**Pull request by johngmyers**
Due to coreos/flannel#1243

Targeting kops 1.17

Fixes #8562

### CODE REVIEW

**Comment by johngmyers** [comment]
There's activity on the underlying bug, so
/hold

**Comment by joshbranham** [comment]
Yeah this thread also has some activity, the maintainer is referenced as well: https://github.com/coreos/flannel/issues/1245

**Comment by jhohertz** [comment]
It would be great if the flannel folks get this fixed up, but there doesn't seem to be a lot of movement.

**Comment by johngmyers** [comment]
I think I'll asses the state in 2-3 weeks. If no progress by then I'll un-hold.

This should be a 1.17 blocker.

**Comment by gamer22026** [comment]
How does this affect running flannel in AWS ? Even with disabling Source/Destination Check on the nodes, I was not able to get flannel with `host-gw` backend working (k8s 1.16.7) and aws-vpc is a non-starter.

**Comment by johngmyers** [comment]
I don't see any progress.
/hold cancel

**Comment by johngmyers** [comment]
Decision from Kops Office Hours is to defer for two weeks.
/hold

**Comment by johngmyers** [comment]
Decision of kops office hours is to proceed.
/hold cancel

**Comment by andersosthus** [comment]
There's an open PR now to fix this issue at https://github.com/coreos/flannel/pull/1282.
For our part we use Flannel to run Windows Worker nodes, and Flannel is afaik the only supported overlay (https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#networking)

**Comment by justinsb** [comment]
I've also (so far) only been able to reproduce the problem on rhel 7.8 images.

**Comment by justinsb** [comment]
And I actually think that https://github.com/kubernetes/kops/pull/8381/files might be a fix.

**Comment by justinsb** [comment]
I'm trying to get some flannel tests going on "every distro": https://github.com/kubernetes/test-infra/pull/17300/files

**Comment by jhohertz** [comment]
Just a data point, I tried adding the sysctls from the CentOS7 fix to a Flatcar-based cluster and didn't see any change in flannel's behaviour.

Trying to figure out the best way to shoehorn the ethtool/checksum fix in for a test now...

**Comment by hakman** [comment]
Seems that the proper  fix was accepted: https://github.com/kubernetes/kubernetes/issues/88986#issuecomment-620633097. Getting it to already released distros will probably take a long time, if it ever happens.

The [patch comment](http://patchwork.ozlabs.org/project/netfilter-devel/patch/335a95d93767f2b58ad89975e4a0b342ee00db91.1587429321.git.gnault@redhat.com/) says that `the problem seems to be there from day one, although it was probably not visible before UDP tunnels were implemented`. 

For now the best hope for the near future is the https://github.com/coreos/flannel/pull/1282, which will require a new Flannel release.

**Comment by jhohertz** [comment]
I'm not sure the "proper" fix is the whole story here. I rolled a version of flatcar with the cited kernel patch and see no difference in behaviour for flannel vxlan / canal.

**Comment by jhohertz** [comment]
I can however now confirm using ethtool to disable offloading works.

**Comment by hakman** [comment]
@jhohertz just curious, how did you try flatcar with that patch?

**Comment by jhohertz** [comment]
@hakman I forked the manifest and coreos-overlay repositories to add the patch. [Running cork create](https://docs.flatcar-linux.org/os/sdk-modifying-coreos/) for my attempt looks like: ```cork create --manifest-branch viafoura-build-2345.3.1 --manifest-url https://github.com/viafoura/flatcar-manifest.git```. There are additional steps to actually turn the result into an AMI.

The backport had one minor difference for 4.19 in call signatures but otherwise the logic was identical. There might be other differences that need accounting for, but the patch tiny... At any rate, my attempt lives here in the context of the build setup above: https://github.com/viafoura/flatcar-coreos-overlay/blob/viafoura-build-2345.3.1/sys-kernel/coreos-sources/files/4.19/z0004-netfilter-nat-never-update-the-UDP-checksum-when-it-.patch

**Comment by jhohertz** [comment]
Re: the ethtool thing, I'm going to try to adapt [this](https://t.du9l.com/2020/03/kubernetes-flannel-udp-packets-dropped-for-wrong-checksum-workaround/) into a hooks yaml fragment suitable for a cluster spec. Not really used that bit of functionality before, I'll share if I get a working example.

**Comment by jhohertz** [comment]
At first glance, this seems to work in a cluster spec to implement the workaround in a not terrible way. FAR from extensively tested. And of course if this is actually disabling real hardware offload, this isn't an ideal fix, but it may be the best we can get for now.

```
spec:
  hooks:
  - name: flannel-cksum-offload-disable.service
    useRawManifest: true
    roles: [Master, Node]
    manifest: |
      [Unit]
      Description=Turn off checksum offload on flannel.1
      After=sys-devices-virtual-net-flannel.1.device
      [Install]
      WantedBy=sys-devices-virtual-net-flannel.1.device
      [Service]
      Type=oneshot
      ExecStart=/sbin/ethtool -K flannel.1 tx-checksum-ip-generic off

```

**Comment by hakman** [comment]
> Re: the ethtool thing, I'm going to try to adapt [this](https://t.du9l.com/2020/03/kubernetes-flannel-udp-packets-dropped-for-wrong-checksum-workaround/) into a hooks yaml fragment suitable for a cluster spec. Not really used that bit of functionality before, I'll share if I get a working example.

@jhohertz That is not such a bad idea. May be something to think about adding in Kops as a workaround until a new version of Flannel is released.

**Comment by johngmyers** [comment]
Closing in favor of #9074

**Pull request closed without merging**
