### PR TITLE
Enable NTH capacity rebalance handling by default

### PR DESCRIPTION
**Pull request by johngmyers**
Since (I believe) capacity rebalance recommendations need to be explicitly enabled, this is a more sensible default. Why would someone enable rebalance recommendations if they don't want some sort of action taken on them?

### CODE REVIEW

**Comment by olemarkus** [comment]
Rebalance recommendations in itself is not a feature one toggles on or off. But one can configure autoscaling to respond to them: https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-capacity-rebalancing.html

We have discussed the use of rebalance recommendations together with NTH in slack extensivelty, and several spot+NTH users have strongly discouraged using this feature as rebalance recommendations happens far more frequently than actual spot interruptions. So when cordoning is enabled, the cluster will be left with dozens of cordoned nodes. With draining enabled, it will lead to dozens of unnecessary interruptions although karpenter/CAS can reap the nodes in this case (given that they are fully drained).

**Comment by johngmyers** [comment]
And yet in Queue Processor mode we drain on rebalance recommendations with no option to turn it off? I'm failing to see how that makes sense.

**Comment by olemarkus** [comment]
In queue processor mode, we hardcoded the values for rebalance recommendations to false, I think. Enabling it in the cluster spec only took effect on the daemonset.

**Comment by johngmyers** [comment]
Queue processor mode has it hardcoded to drain on rebalance recommendations. I've submitted #14771, which will cause existing queue processor users to have this turned off unless they configure otherwise.
/close

**Pull request closed without merging**
