### PR TITLE
check does iface has associations

### LINKED ISSUE #12231: nodeup crashes in kops 1.22 beta 1 in debian 11
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops 1.22 beta 1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

I am running rolling update to cluster from kops 1.21 -> kops 1.22 beta 1 (k8s version 1.22.1)

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

kops update cluster && rolling-update

**5. What happened after the commands executed?**

I can see following in logs

```
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: [Unit]
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: Description=Kubernetes Protokube Service
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: Documentation=https://kops.sigs.k8s.io
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: [Service]
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: ExecStart=/opt/kops/bin/protokube --bootstrap-master-node-labels=true --channels=s3://foo/kops122testaws.k8s.local/addons/bootstrap-channel.yaml --cloud=aws --containerized=false --dns-internal-suffix=internal.kops122testaws.k8s.local --dns=gossip --initialize-rbac=true --manage-etcd=false --master=true --node-name=ip-10-124-36-41.eu-north-1.compute.internal --remove-dns-names=etcd-a.internal.kops122testaws.k8s.local,etcd-b.internal.kops122testaws.k8s.local,etcd-c.internal.kops122testaws.k8s.local,etcd-events-a.internal.kops122testaws.k8s.local,etcd-events-b.internal.kops122testaws.k8s.local,etcd-events-c.internal.kops122testaws.k8s.local --v=4
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: EnvironmentFile=/etc/sysconfig/protokube
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: Restart=always
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: RestartSec=3s
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: StartLimitInterval=0
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: [Install]
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: WantedBy=multi-user.target
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: I0831 11:16:56.324827    6886 task.go:110] testing task "Service"
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: I0831 11:16:56.324835    6886 task.go:110] testing task "File"
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: I0831 11:16:56.324850    6886 task.go:110] testing task "File"
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: I0831 11:16:56.326855    6886 request_logger.go:45] AWS request: ec2/DescribeInstances
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x20fbb0d]
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: goroutine 1 [running]:
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/upup/pkg/fi/cloudup/awsup.GetInstanceCertificateNames(0xc000834ee0, 0xc0004be6e0, 0xc000834ee0, 0x0, 0x0, 0x0)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011upup/pkg/fi/cloudup/awsup/aws_cloud.go:2103 +0x1cd
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/nodeup/pkg/model.(*KubeletBuilder).kubeletNames(0xc00000e3d0, 0x3eb6808, 0x4, 0xc0007f9601, 0x1582b8e, 0xc0007f97d8)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011nodeup/pkg/model/kubelet.go:633 +0x36f
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/nodeup/pkg/model.(*KubeletBuilder).buildKubeletServingCertificate(0xc00000e3d0, 0xc000956020, 0x0, 0x0)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011nodeup/pkg/model/kubelet.go:566 +0x18e
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/nodeup/pkg/model.(*KubeletBuilder).Build(0xc00000e3d0, 0xc000956020, 0x0, 0x0)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011nodeup/pkg/model/kubelet.go:63 +0x50
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/upup/pkg/fi/nodeup.(*Loader).Build(0xc0007f9ce8, 0xc000557200, 0x20, 0x20)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011upup/pkg/fi/nodeup/loader.go:39 +0x344
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: k8s.io/kops/upup/pkg/fi/nodeup.(*NodeUpCommand).Run(0xc0007f9f40, 0x43f83a0, 0xc00000e018, 0x0, 0x0)
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011upup/pkg/fi/nodeup/command.go:314 +0x248f
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: main.main()
Aug 31 11:16:56 ip-10-124-36-41 nodeup[6886]: #011cmd/nodeup/main.go:117 +0x1013
Aug 31 11:16:56 ip-10-124-36-41 systemd[1]: kops-configuration.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 31 11:16:56 ip-10-124-36-41 systemd[1]: kops-configuration.service: Failed with result 'exit-code'.
Aug 31 11:16:56 ip-10-124-36-41 systemd[1]: Failed to start Run kOps bootstrap (nodeup).
Aug 31 11:16:56 ip-10-124-36-41 systemd[1]: kops-configuration.service: Consumed 2.020s CPU time.
Aug 31 11:16:56 ip-10-124-36-41 cloud-init[711]: W0831 11:16:56.381778    5650 executor.go:139] error running task "Service/kops-configuration.service" (1m41s remaining to succeed): error doing systemd restart kops-configuration.service: exit status 1
Aug 31 11:16:56 ip-10-124-36-41 cloud-init[711]: Output: Job for kops-configuration.service failed because the control process exited with error code.
Aug 31 11:16:56 ip-10-124-36-41 cloud-init[711]: See "systemctl status kops-configuration.service" and "journalctl -xe" for details.
```

master fails to bootstrap

**6. What did you expect to happen?**

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

### PR DESCRIPTION
**Pull request by zetaab**
fixes #12231

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by ArchangelX360** [comment]
Is this planned to be released in a `v1.22-beta.2` by any chance?

**Comment by olemarkus** [comment]
Yes, it has been merged into the 1.22 branch.

**Comment by ArchangelX360** [comment]
Awesome! Do you have an ETA on the release of a `1.22.0-beta.2` by any chance? We are benchmarking something on our end so it would be awesome to have a `1.22` cluster up and ready :D!

**Comment by olemarkus** [comment]
Well .. you can always do something like 
```
export KOPS_BASE_URL="$(curl -s https://storage.googleapis.com/k8s-staging-kops/kops/releases/markers/release-1.22/latest-ci.txt)
wget "$KOPS_BASE_URL/$(go env GOOS)/$(go env GOARCH)/kops"
./kops create ...
```

**Comment by ArchangelX360** [comment]
Oh indeed, that would do to unblock my testing while I wait patiently for the stable release. Thanks for the tip ☺️!

**Comment by ArchangelX360** [comment]
I get:
```
Error: cannot determine hash for "https://artifacts.k8s.io/binaries/kops/1.22.0-beta.2+v1.22.0-beta.1-113-g63f1d9490c/linux/amd64/nodeup" (have you specified a valid file location?)
```

I suppose some assets are not published by the CI run so the workaround does not work?
Or am I doing something wrong?

**Comment by olemarkus** [comment]
That nodeup url looks wrong. It should be
```
https://storage.googleapis.com/k8s-staging-kops/kops/releases/1.22.0-beta.2+v1.22.0-beta.1-113-g63f1d9490c/linux/amd64/nodeup
```

**Pull request merged**
