### PR TITLE
Update AWS test scenarios

### PR DESCRIPTION
**Pull request by hakman**
/cc @johngmyers @olemarkus

### CODE REVIEW

**Comment by rifelpet** [comment]
I dont think the aws-ebs-csi scenario is used at all, we might be able to remove it

**Comment by hakman** [comment]
> I dont think the aws-ebs-csi scenario is used at all, we might be able to remove it

I think it's used in https://github.com/kubernetes-sigs/aws-ebs-csi-driver PRs.

**Review by johngmyers — APPROVED** [review]

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
