### PR TITLE
Add documentation for updating CRDs when making API changes

### PR DESCRIPTION
**Pull request by rifelpet**
~I explicitly chose not to include the commits from #7634 so we can verify that the job fails if this script fails. Once that is merged the job can be reran and should succeed.~

~This means that any API changes will need `make crds` ran in addition to `make apimachinery`. I've updated the docs to reflect that.~

Now that we have a new verify-generated prow job, this updates the documentation on how to keep the CRDs up to date.

### CODE REVIEW

**Comment by justinsb** [comment]
This looks great.  I approved/lgtmed the other PR, so hopefully that'll merge soon and then this one will pass.  I don't think travis rebases though, so you'll have to rebase.

But have an approve & lgtm anyway!

/approve
/lgtm

**Comment by justinsb** [comment]
/test pull-kops-verify-gomod

The failure with go 1.11 in travis is more interesting ... I guess we should pull this validation out of travis into prow.

**Comment by justinsb** [comment]
Sent https://github.com/kubernetes/test-infra/pull/14637 which I imagine could end up validating all generated code on PRs.  But then I found the existing script `hack/verify-generate.sh` which seems to be pretty similar to `verify-crds`.  Should we merge them?

A valid reason not to merge them is that I imagine we'll put more generation into `verify-generate.sh`.  So if we wanted to just verify that the CRDs had been generated, we could split them.  But ... would people want to just verify that CRD generation was correct, but not check other generated code?

**Comment by rifelpet** [comment]
I can't think of a reason someone would only want to verify a subset of generated code, given that master will now always have up-to-date generated code. Once the test-infra PR is merged I can reduce this PR down to just the docs update and add a mention of the hack script.

**Comment by rifelpet** [comment]
@justinsb Updated to only include a docs update

**Comment by mikesplain** [comment]
This looks great! Thanks @rifelpet!

/lgtm
/approve

**Pull request merged**
