### PR TITLE
Always infer gossip DNS from cluster name

### PR DESCRIPTION
**Pull request by hakman**
/cc @olemarkus @justinsb

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by rifelpet** [comment]
@hakman I think this is causing some e2e failures:

https://testgrid.k8s.io/kops-misc#kops-aws-external-dns

https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-fqdn

**Comment by hakman** [comment]
Thanks @rifelpet. Looks like #14377 fixed the issue: https://testgrid.k8s.io/kops-misc#kops-aws-external-dns.

**Pull request merged**
