### PR TITLE
Cache ASGs, LCs, and AMIs

### PR DESCRIPTION
**Pull request by hobosteaux**
A proposal for #7111

The core problem is that to fetch a single ASG / LC, we must fetch all of them in pages of 50. This quickly results in backoffs from aws. For a ~230 ASG cluster, this PR reduces the time for `kops update cluster` from ~30 min to ~15 seconds.

There are two current issues with this PR:
1. All changes to items are in the W side of an RWMutex, forcing them to be serial now instead of parallel
2. When fetching ASGs / LCs, there is a race condition that can occur if a modification happens between warming the cache and R locking for using the cache

I have never touched the kops codebase before, so am looking for input on if there are other approaches to doing this and if there are other ideas on how to be more thread-safe.

cc: @mikesplain

### CODE REVIEW

**Comment by hobosteaux** [comment]
This is failing because of the following error:
```
W0611 23:55:47.038] Starting local Bazel server and connecting to it...
W0611 23:55:48.921] INFO: Options provided by the client:
W0611 23:55:48.922] Inherited 'common' options: --isatty=0 --terminal_columns=80
W0611 23:55:48.925] INFO: Reading rc options for 'build' from /etc/bazel.bazelrc:
W0611 23:55:48.925] 'build' options: --experimental_remote_spawn_cache --remote_local_fallback --remote_http_cache=http://bazel-cache.default.svc.cluster.local.:8080/kubernetes/kops,0ca5b989e63c411e51f762535c5c2319 --remote_local_fallback --remote_http_cache=http://bazel-cache.default.svc.cluster.local.:8080/kubernetes/kops,0ca5b989e63c411e51f762535c5c2319
W0611 23:55:48.926] ERROR: Unrecognized option: --experimental_remote_spawn_cache
W0611 23:55:48.936] make: *** [bazel-build] Error 2
W0611 23:55:48.937] Run: ('/workspace/./test-infra/jenkins/../scenarios/../hack/coalesce.py',)
I0611 23:55:48.970] Makefile:668: recipe for target 'bazel-build' failed
I0611 23:55:48.970] Bazel remote cache is enabled, generating .bazelrcs ...
E0611 23:55:48.970] Command failed
```

I have tried to reproduce it locally, but the instructions seem stale for that:
```
➜ docker run -it -v /home/eball/repos/kops/src/k8s.io/kops:/go/src/k8s.io/kops golang bash
Unable to find image 'golang:latest' locally
latest: Pulling from library/golang
6f2f362378c5: Pull complete
494c27a8a6b8: Pull complete
7596bb83081b: Pull complete
372744b62d49: Pull complete
0658c6765517: Pull complete
dbd5b1749350: Pull complete
ca642e59c356: Pull complete
Digest: sha256:f6b9f5d9da411dd88772b0829d8f382113c6b34f1a54aac5867dd2471afc6512
Status: Downloaded newer image for golang:latest
root@4dd4a9da4e87:/go# cd src/k8s.io/kops/
root@4dd4a9da4e87:/go/src/k8s.io/kops# make ci
cd /go/src/k8s.io/kops; /go/src/k8s.io/kops/.build/local/go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
go vet ./...
hack/verify-gofmt.sh
xargs: bazel: No such file or directory
Makefile:528: recipe for target 'verify-gofmt' failed
make: *** [verify-gofmt] Error 127
```

Any suggestions on how to tackle this? The diff to master doesn't look to have any build changes (in the repo at least) and other PRs don't seem to be failing with the same issues.

**Comment by jaredallard** [comment]
@hobosteaux Assuming this is ready, @justinsb it'd be awesome if we could get some movement on this PR.

Happy to help contribute in anyway I can as well.

**Comment by m0rganic** [comment]
The go modules are probably out of date because it's been sitting here for so long. This should be a simple test to resolve, right?

**Pull request closed without merging**
