### PR TITLE
Scaleway support in protokube

### PR DESCRIPTION
**Pull request by Mia-Cross**
The goal of this PR is to add support for Scaleway in protokube. This step will complete the bootstrapping of new nodes. For the time being, only gossip DNS is supported but a custom DNS will soon come in a next PR.

### CODE REVIEW

**Comment by Mia-Cross** [comment]
@hakman I tried adding ScalewaySpec to the ClusterSpec in v1alpha2 as you suggested in my previous PR (#14322), but I was not sure where since I didn't see any cloud provider spec. It caused errors in the CI so I eventually removed it. It seems like the [CloudProviderSpec](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/cluster.go#L58) included in v1alpha2 references [this one](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/cluster.go#L231) where ScalewaySpec is already present.

**Review by remyleone — APPROVED** [review]

**Review by hakman — CHANGES_REQUESTED** [review]
Thanks @Mia-Cross. This looks really nice. 👍 
Please squash the commits and see a few nits and comments below:

> I tried adding ScalewaySpec to the ClusterSpec in v1alpha2...

No worries, please ignore that.

> For the time being, only gossip DNS is supported but a custom DNS will soon come in a next PR.

DNS part may be need more time and attention. With this in mind, you may want to switch to the cloud resources provisioning instead and come back to DNS once you have a working cluster.

**Review by hakman — APPROVED** [review]
Thanks @Mia-Cross! 😄

**Pull request merged**
