### PR TITLE
Drop support for Weave as of k8s 1.23

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by johngmyers** [comment]
Once this goes in I will pin the Weave e2e tests to k8s 1.22.

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
Did you mean to squash commits?
/hold

**Comment by johngmyers** [comment]
Yup.
/hold cancel

**Comment by raffis** [comment]
Is there any context for this? Is weave support dropped because weave seems kinda unmaintained? (last release over one year ago).

**Comment by olemarkus** [comment]
Weave stopped working as of k8s 1.23 (nodes cannot reach each other) and upstream seems dead so we do not expect any fix.

**Pull request merged**
