### PR TITLE
Implemented Nvidia DevicePlugin GPU Support on AWS

### PR DESCRIPTION
**Pull request by dcwangmit01**
* Supports DevicePlugin GPU Mode AND Legacy Accelerators GPU Mode

===
Rendered Readme Found Here
https://github.com/dcwangmit01/kops/tree/gpu-device-plugins-3/hooks/nvidia-device-plugin

Related Issues:
* https://github.com/kubernetes/kops/issues/4591
* https://github.com/kubernetes/kops/issues/5135
* https://github.com/kubernetes/kops/issues/4591

Related Pull Requests:
* https://github.com/kubernetes/kops/pull/4971

### CODE REVIEW

**Comment by dcwangmit01** [comment]
Tagging those who reviewed/commented on prior GPU PR https://github.com/kubernetes/kops/pull/4971.

This PR adds Kops GPU support for kubernetes >= 1.11.0 via DevicePlugins.

@115100, @bhack, @chrislovecnm, @erez-rabih, @faheem-cliqz, @flx42, @justinsb, @KashifSaadat, @mikesplain, @mindprince, @richardbrks, @rtluckie

**Comment by bhack** [comment]
Is cuda mandatory?

**Comment by dcwangmit01** [comment]
@bhack Cuda is not mandatory, but included here to follow the same practice as the other GPU hook images.

**Comment by bhack** [comment]
@dcwangmit01 ok but I suppose this will duplicate the node storage consumption when we use pod with image derived from nvidia/cuda like Tensorflow etc..

**Comment by bhack** [comment]
I.e. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu#L1

**Comment by bhack** [comment]
@flx42 Yes but I meant that in 90% of the cases the next command is to apt-get cuda-*

**Comment by flx42** [comment]
I agree CUDA toolkit libraries shouldn't be part of a driver install.

**Comment by faheem-cliqz** [comment]
Tested and works as expected. Awesome work thanks.

**Comment by justinsb** [comment]
This is purely additive, so I'm going to merge it in :-)

I've added myself a TODO item to build the docker image as part of the kops release and repoint it, so we won't be relying on your docker images @dcwangmit01 !

Thank you so much @dcwangmit01 

/approve
/lgtm

**Pull request merged**
