### PR TITLE
fix-up gosimple check error

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@hwdef

**Comment by hwdef** [comment]
/ok-to-test
Thank you!

**Comment by hwdef** [comment]
/ok-to-test
/lgtm
Thank you!

**Comment by tanjunchen** [comment]
@justinsb

**Comment by justinsb** [comment]
Thanks @tanjunchen 

I think the verify-generated issue was a problem we were having with the test, so

/retest

And then if it passes tests...
/approve
/lgtm

**Pull request merged**
