### PR TITLE
Bump Travis versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
Appears the formatting requirements are contradictory between 1.10 and 1.11. So not sure how to easily fix that.

**Comment by chrisz100** [comment]
The easiest way to fix it probably is run go fmt in a docker container running go 1.10 and commit the changes.

**Comment by HaraldNordgren** [comment]
@chrisz100 Hmm, doing that brings the file formatting back it currently is on `master`, which will break 1.11.

**Comment by chrisz100** [comment]
We are just building on 1.10 as of now and that’s also what we Test against. 1.11 will be a global thing for I believe kops version 1.12

**Comment by HaraldNordgren** [comment]
@chrisz100 I'm sure what you are saying, but unless there is an easy fix for this I guess we can close the PR.

**Comment by HaraldNordgren** [comment]
@chrisz100 Updated the build to only run the fmt linter for 1.11.x. Do you think this is mergeable in it's current state?

**Comment by rdrgmnzs** [comment]
@HaraldNordgren we build kops with the same version of go as the k8s release uses. So we will not be using go 1.11 until Kops 1.13 (Which is the version k8s is targeting to adopt golang 1.12), this means that we only want travis builds to verify the formatting against go 1.10, so reverting the formatting to as it is currently on master is the correct path.

**Comment by HaraldNordgren** [comment]
Fair enough.

**Pull request closed without merging**
