### PR TITLE
Use Calico v3.23 for Kubernetes 1.22+

### PR DESCRIPTION
**Pull request by hakman**
Ref: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#supported-versions
> We test Calico v3.23 against the following Kubernetes versions.
> * v1.21
> * v1.22
> * v1.23

### CODE REVIEW

**Comment by hakman** [comment]
Looks like the Calico upgrade is more complicated.
/hold cancel

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
