### PR TITLE
[heapster] Create v1.3.0.yaml

### PR DESCRIPTION
**Pull request by blackstar257**
Upgrade heapster to 1.3.0 and addon-resizer to 1.7

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2356)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
ith @k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by blackstar257** [comment]
@chrislovecnm made the 2 changes.

**Pull request merged**
