### PR TITLE
moving chrisz100 to approver level

### PR DESCRIPTION
**Pull request by chrisz100**
Hi all, as discussed with @mikesplain I'd love to move the ranks and be allowed to approve in the future.

### CODE REVIEW

**Comment by chrisz100** [comment]
Whoops... 
/assign @chrislovecnm

**Comment by chrislovecnm** [comment]
Aws tests are busted because of the testing account.

@mikesplain he has met the needed amount of PR reviews and PRs?

**Comment by mikesplain** [comment]
According to devstats, yes @chrisz100 has completed the required reviews to be bumped to an approver.

I think Chris is a strong asset to the project and it would be great get his help keeping up the recent velocity we've achieved.

**Comment by justinsb** [comment]
Yes, I concur!  @chrisz100 remember that with great power comes great responsibility, and ... welcome!

/approve
/lgtm

**Pull request merged**
