### PR TITLE
Pass 2: k8s GCR vanity URL

### PR DESCRIPTION
**Pull request by thockin**
Will eventually have a presubmit.  Please try to stick to the new URL before the old one breaks :)

### CODE REVIEW

**Comment by justinsb** [comment]
For kube-apiserver, kube-proxy, this is actually a deliberate decision for older clusters:

```
// The k8s.gcr.io prefix is an alias, but for CI builds we run from a docker load,
// and we only double-tag from 1.10 onwards.
// For versions prior to 1.10, remap k8s.gcr.io to the old name.
// This also means that we won't start using the aliased names on existing clusters,
// which could otherwise be surprising to users.
```

IIRC the breaking issue is that the older k8s CI builds, where we `docker load` the images, don't have the new name (the comment suggests 1.9 breaks).

There's also the case of a non-CI build, for people running e.g. k8s 1.7.  There we keep the old name, because we don't like to change configuration on existing clusters unless we have to.  If those names ever stopped working I think it would break people not using kops as well, so I don't know if/how we're planning on breaking the name.

I'm happy to take this on and figure out how to tweak the rules so they work for CI and older cluster versions etc, if that's easier for you @thockin

**Comment by thockin** [comment]
help is welcome

**Comment by justinsb** [comment]
I think this is only the metrics-server.  Will tackle in kops 1.11

**Comment by justinsb** [comment]
Extracted just the non-backwards compatible changes, into #6623

**Pull request closed without merging**
