### PR TITLE
Default ClusterDNS appropriately when NodeLocalDNS is enabled

### PR DESCRIPTION
**Pull request by johngmyers**
/cc @olemarkus

### CODE REVIEW

**Comment by olemarkus** [comment]
Thanks for this. I think this does make things simpler for users.
If this goes in, we'd want this backported to 1.18 too.

/lgtm

**Comment by johngmyers** [comment]
One question is whether `ClusterDNS` should default to `NodeLocalDNS.LocalIP` for all cases when `NodeLocalDNS` is enabled, not just the ones where it doesn't work otherwise.

**Comment by olemarkus** [comment]
An earlier PR I had of this did that. I suspect there may be other cases where you need localIP. For example calico in BPF (kubeproxy-free) mode.

**Comment by johngmyers** [comment]
/assign @rifelpet 
It would be good to get this into 1.18 branch soon.

**Comment by rifelpet** [comment]
👍 
/approve

**Pull request merged**
