### PR TITLE
Enable weave network encryption for k8s 1.6

### PR DESCRIPTION
**Pull request by Andrey9kin**

### CODE REVIEW

**Comment by Andrey9kin** [comment]
Trying to get CLA singed. Waiting for verification email from Linux Foundation

**Comment by Andrey9kin** [comment]
@kampka I followed your commit where you updated k8s-1.7 yaml. Could you please take a look

**Comment by kampka** [comment]
For what its worth:

/lgtm

:)

**Comment by chrisz100** [comment]
/ok-to-test
/lgtm

Thanks for the contribution!

**Comment by justinsb** [comment]
This makes sense; if the user doesn't enable weave encryption it should be a no-op, so I'd argue it's just confusing that it doesn't do anything on k8s 1.6.

I would suggest upgrading to a newer version of k8s though @Andrey9kin  - we are contemplating stopping support in kops for older versions of k8s, because technically k8s itself doesn't get security patches etc.  I'm not sure if you're actually running an older version of k8s or if this is just for consistency?

In any case, thank you for the PR @Andrey9kin 

/approve
/lgtm

**Comment by Andrey9kin** [comment]
@justinsb we are still running 1.6.13 and planning to upgrade within in a couple of months (hopefully) but for a time being it would be great to avoid dealing with an in-house build of kops where this patch is included

**Comment by justinsb** [comment]
Didn't mean to remove approved!

/approve

**Pull request merged**
