### PR TITLE
[WIP] Add missing permissions to AWS CCM for ELB

### PR DESCRIPTION
**Pull request by hakman**
/cc @olemarkus @rifelpet

### CODE REVIEW

**Comment by justinsb** [comment]
Could we get the AWS CCM to tag these?  i.e. is this something we will be able to revert at some stage in the future?  If so, it might be nice to put them into their own section e.g.

```
// ELBs are not currently tagged, but the AWS CCM should tag them.
p.unconditionalAction.Insert(
  "elasticloadbalancing:ConfigureHealthCheck",
  "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
  "elasticloadbalancing:ModifyLoadBalancerAttributes",
  "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
```

Of course, if the tags don't work or can't work then ignore this suggestion!

**Comment by olemarkus** [comment]
/hold

I have been testing this thoroughly earlier on when I did e.g https://github.com/kubernetes/cloud-provider-aws/pull/293

Let me have a look over the weekend what is happening if someone can point me to what tests are failing because of this.

**Comment by rifelpet** [comment]
FWIW I still see the access denied errors in the newer AWS CCM:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13626/pull-kops-e2e-kubernetes-aws/1524010242340294656/artifacts/cluster-info/kube-system/aws-cloud-controller-manager-9rq8w/logs.txt


`E0510 13:22:28.302375       1 controller.go:310] error processing service deployment-2723/test-rolling-update-with-lb (will retry): failed to ensure load balancer: Unable to update load balancer attributes during attribute sync: "AccessDenied: User: arn:aws:sts::768319786644:assumed-role/aws-cloud-controller-manager.kube-system.sa.e2e-pr13626.p-nlvlmo/1652188946267749829 is not authorized to perform: elasticloadbalancing:ModifyLoadBalancerAttributes on resource: arn:aws:elasticloadbalancing:ap-northeast-2:768319786644:loadbalancer/aed2827de90eb4174a8a1e06a66203b8 because no identity-based policy allows the elasticloadbalancing:ModifyLoadBalancerAttributes action\n\tstatus code: 403, request id: a42ed2f9-c1c2-4322-8225-b24ab854b033"`

**Comment by olemarkus** [comment]
Isn't this error only transient? Looks like the LB is ensured after a while.

**Comment by rifelpet** [comment]
You're right, ELB `aed2827de90eb4174a8a1e06a66203b8` does eventually reconcile:

First failures soon after creation:

`I0510 13:23:04.427116       1 aws_loadbalancer.go:1212] Updating load-balancer attributes for "aed2827de90eb4174a8a1e06a66203b8"`
`E0510 13:23:04.433330       1 controller.go:310] error processing service deployment-2723/test-rolling-update-with-lb (will retry): failed to ensure load balancer: Unable to update load balancer attributes during attribute sync: "AccessDenied: User: arn:aws:sts::768319786644:assumed-role/aws-cloud-controller-manager.kube-system.sa.e2e-pr13626.p-nlvlmo/1652188946267749829 is not authorized to perform: elasticloadbalancing:ModifyLoadBalancerAttributes on resource: arn:aws:elasticloadbalancing:ap-northeast-2:768319786644:loadbalancer/aed2827de90eb4174a8a1e06a66203b8 because no identity-based policy allows the elasticloadbalancing:ModifyLoadBalancerAttributes action\n\tstatus code: 403, request id: e2333ede-349f-4e1b-98f7-11d662b13660"`


And eventually no errors when those same Info lines are logged:

`I0510 13:25:05.182400       1 aws_loadbalancer.go:1185] Creating additional load balancer tags for aed2827de90eb4174a8a1e06a66203b8`
`I0510 13:25:05.208323       1 aws_loadbalancer.go:1212] Updating load-balancer attributes for "aed2827de90eb4174a8a1e06a66203b8"`

I think we can close this after all

**Pull request closed without merging**
