### PR TITLE
Bumping stable channel to k8s 1.4.6

### PR DESCRIPTION
**Pull request by chrislovecnm**
Have not done integration testing. Will test and move out of [WIP] when I do.  This will close https://github.com/kubernetes/kops/issues/978

### CODE REVIEW

**Comment by zmerlynn** [comment]
@chrislovecnm: Playing with the PR builder on this side. Please don't let it gate you on merging, though.

@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this (forgot to update `prow`)

**Comment by zmerlynn** [comment]
@k8s-bot test this (needed another tweak)

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by chrislovecnm** [comment]
Play away ;)

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
Ha, this PR is an amusing case where the change is actually a no-op the PR builder currently, which is a little sad. Because of https://github.com/kubernetes/test-infra/pull/1191, until v1.5 moves into stable, the PR builder is going to override the version anyways.

**Comment by kris-nova** [comment]
@chrislovecnm 

Assigning back to you, please assign to me when you guys are done testing so I can review/merge

**Comment by chrislovecnm** [comment]
There is zero way for me to test this until we merge.  Not the best design, something we need to figure out.  Probably self hosted resources would help.

@kris-nova waiting on you.

**Comment by chrislovecnm** [comment]
@zmerlynn if you want to merge :)

**Comment by zmerlynn** [comment]
Once the PR builder in this repo is no longer overriding the kubernetes version, this PR could be tested that way. But I'm okay with just biting the bullet.

**Pull request merged**
