### PR TITLE
Use AWS metadata to retrieve local-hostname in nodeup

### PR DESCRIPTION
**Pull request by bwagner5**
Cloud Provider: AWS

This PR changes nodeups method of looking up an instance private DNS name from a DescribeInstances call to an instance metadata lookup. DescribeInstances is prone to throttling with large clusters and can cause significant delays when a node is trying to join a cluster.

### CODE REVIEW

**Comment by rifelpet** [comment]
This would break clusters with IMDS disabled. I think it would be reasonable to try IMDS first and fallback to DescribeInstances.

**Comment by hakman** [comment]
> This would break clusters with IMDS disabled. I think it would be reasonable to try IMDS first and fallback to DescribeInstances.

Can / should a kOps cluster work without IMDS?

**Comment by hakman** [comment]
Thanks @bwagner5. Seems like a good improvement from my point of view.
@rifelpet Leaving this to you for the final review.
/lgmt

**Comment by bwagner5** [comment]
>> This would break clusters with IMDS disabled. I think it would be reasonable to try IMDS first and fallback to DescribeInstances.

> Can / should a kOps cluster work without IMDS?
Previous implementation also used IMDS to get metadata://aws/meta-data/instance-id.

There's some other places that use IMDS in nodeup as well so it might be worth going through and figuring out if it's reasonable to perform a fallback if IMDS is disabled everywhere. But it's almost impossible to do really large scale-ups if you're not using IMDS on node bootstrap so I'd lean towards getting rid of the API calls and requiring IMDS. 

I have a version of nodeup that does zero API calls and relies only on IMDS and OS calls for node info rather than DescribeInstanceTypes.  I may try to PR some of those after they're cleaned up.

**Comment by johngmyers** [comment]
Don't you have to use IMDS to get the instance role credentials to authenticate to kops-controller? I don't think it's going to be possible to bootstrap without IMDS.

**Comment by hakman** [comment]
> There's some other places that use IMDS in nodeup as well so it might be worth going through and figuring out if it's reasonable to perform a fallback if IMDS is disabled everywhere. But it's almost impossible to do really large scale-ups if you're not using IMDS on node bootstrap so I'd lean towards getting rid of the API calls and requiring IMDS.

In any case one would need instance ID, which is pretty hard to get without IMDS, right?

> I have a version of nodeup that does zero API calls and relies only on IMDS and OS calls for node info rather than DescribeInstanceTypes. I may try to PR some of those after they're cleaned up.

That would be very nice.
I think there are also some places where metadata api is called directly instead of using vfs to read it. It may be worth a PR to change all to use vfs.

**Comment by olemarkus** [comment]
> In any case one would need instance ID, which is pretty hard to get without IMDS, right?

Instances with RBN enabled can just get this from `os.hostname` :)

**Review by rifelpet — APPROVED** [review]
It sounds like IMDS is required at this point then. This lgtm and I agree with proposed follow up PRs.

**Comment by rifelpet** [comment]
Should we remove eco:DescribeInstances from the node IAM policy? Users may be depending on it for other workloads though, and having them add it back makes the policy size larger since it would become its own statement.

**Comment by johngmyers** [comment]
Doesn't kubelet require `DescribeInstances`?

**Comment by olemarkus** [comment]
We can remove it from the nodeup function (if it is there). Kubelet still needs it if the in-tree CCM is used, but it should be a part of the CCM function too.

**Pull request merged**
