### PR TITLE
add cluster-autoscaler.sh

### PR DESCRIPTION
**Pull request by sdarwin**
Create a more complete cluster-autoscaler installation script based on https://github.com/kubernetes/autoscaler/issues/110 which will automate the installation of the IAM Policy.

### CODE REVIEW

**Comment by sdarwin** [comment]
Received email "You just signed CNCF Individual Contributor License Agreement"

**Comment by chrisz100** [comment]
@sdarwin can you please add the license header to your script? Thanks!

**Comment by sdarwin** [comment]
> please add the license header 

@chrisz100  , done.

**Comment by chrisz100** [comment]
Thank you @sdarwin ! 
/lgtm

**Comment by justinsb** [comment]
This looks great - thanks @sdarwin !

/approve
/lgtm

**Pull request merged**
