### PR TITLE
Added documentation for vSphere support status.

### PR DESCRIPTION
**Pull request by prashima**
This documentation contains details about current status of vSphere support in kops.

- Priority-wise list of bugs, features and testing tasks.
- Existing support in vSphere in terms kops commands.

Please feel free to suggest formatting changes to make markdown look and read better.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2800)

### CODE REVIEW

**Comment by prashima** [comment]
Addressed comments from @chrislovecnm as per kops office hours discussion.

- Moved vsphere-dev.md and vsphere-development-status.md to kops/docs
- Added appropriate links in README.md

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
Looks good, but will rebase and merge as #2850

**Comment by justinsb** [comment]
Merged as #2850 - thanks @prashima

**Pull request closed without merging**
