### PR TITLE
Set nodeSelector and command to null

### LINKED ISSUE #13646: Upgrade issues with kOps to old clusters (earlier than 1.24.0 alpha 4)
/kind bug

Using latest master:

1. dns-controller deployment contains `command` section which should be removed manually (applies both AWS & openstack)
2. dns-controller deployment contains `nodeSelector` which should be removed manually (applies both AWS & openstack)
3. ebs-csi-controller deployment contains `nodeSelector` which should be removed manually (applies AWS)
4. openstack-cloud-provider daemonset contains `nodeSelector` which should be removed manually (applies openstack)
5. kops-controller daemonset contains `command` section which should be removed manually (applies AWS & openstack)
6. kops-controller daemonset contains `nodeSelector` section which should be removed manually (applies AWS & openstack)

7. new normal nodes not joining to cluster (AWS) (because kops-controller not working)

result:

openstack
```
% kubectl get nodes
NAME                   STATUS   ROLES                  AGE    VERSION
master-espsti-puuw2p   Ready    control-plane,master   36m    v1.24.0
master-esptnl-a1w4kr   Ready    control-plane,master   21m    v1.24.0
master-helpa-jpamzg    Ready    control-plane          16m    v1.24.0
nodes-espsti-x27fug    Ready    node                   10m    v1.24.0
nodes-esptnl-5nca1z    Ready    node                   5m6s   v1.24.0
nodes-helpa-jdwmdd     Ready    node                   36s    v1.24.0
```

works pretty fine, master role in control-plane might be coming from ccm?

aws:

```
% kubectl get nodes
NAME                                              STATUS   ROLES           AGE   VERSION
i-05f12a6579380dc1e                               Ready    control-plane   84m   v1.24.0
i-0c3235d129cc4b5ec                               Ready    control-plane   71m   v1.24.0
i-0f092c39e5906a068                               Ready    control-plane   78m   v1.24.0
ip-10-124-101-122.eu-central-1.compute.internal   Ready    node            17d   v1.23.6
ip-10-124-32-191.eu-central-1.compute.internal    Ready    node            17d   v1.23.6
ip-10-124-92-94.eu-central-1.compute.internal     Ready    node            17d   v1.23.6
```

cannot get working cluster. Creating new AWS cluster works fine, but I cannot update existing cluster.

### PR DESCRIPTION
**Pull request by zetaab**
fixes #13646

### CODE REVIEW

**Comment by zetaab** [comment]
@olemarkus this looks like its fixing the issue

**Comment by olemarkus** [comment]
Can you add to the rest of the addons that needs this too? Or specify in the title/commit which addons you are doing, and I can fix the remainder.

**Comment by zetaab** [comment]
I think this has now all nodeSelector changes to addons and 2 command changes (dns & kops controllers)

**Review by olemarkus — APPROVED** [review]
At least all I know about are fixed with this. Thanks a lot.

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
