### PR TITLE
etcd-manager: Update to 3.0.20190513

### PR DESCRIPTION
**Pull request by justinsb**
In particular, we are picking up the fix for #6098.

### CODE REVIEW

**Comment by granular-ryanbonham** [comment]
/test pull-kops-e2e-kubernetes-aws. 
Rerunning now that kube-deploy PR was approved

**Comment by justinsb** [comment]
/retest

Instances launched but not enough ... quota?

**Comment by justinsb** [comment]
Guess who didn't update the credentials on the build machine after the dockerhub issue, so the push was broken...

I suspect this run will fail, but the next one should be OK!

**Comment by granular-ryanbonham** [comment]
Looks like it passed..

**Pull request merged**
