### PR TITLE
Add node monitor flags

### PR DESCRIPTION
**Pull request by so0k**
To improve quicker detection of a node being down, allow users to set 

- kubelet's `node-status-update-frequency` flag
- controller manager `node-monitor-*` and `pod-eviction-timeout` flags

Ref [Improving Kubernetes reliability: quicker detection of a node down](https://fatalfailure.wordpress.com/2016/06/10/improving-kubernetes-reliability-quicker-detection-of-a-node-down/)

### CODE REVIEW

**Comment by so0k** [comment]
/assign @geojaz 

I'm not sure what else I need to do for this change?

**Comment by chrislovecnm** [comment]
Take a look at https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

You need to update the two other files and generate the code with apimachinery

**Comment by so0k** [comment]
should I create a separate PR for adding evicted pods garbage collection flags for controller manager - see: [evicted pods issue](https://github.com/kubernetes/kubernetes/issues/55051#issuecomment-364912371)

**Comment by so0k** [comment]
@chrislovecnm let me know if I missed anything out

**Comment by chrislovecnm** [comment]
This looks good, I am checking to see if we are still merging code since we are close to the 1.9 release

**Comment by so0k** [comment]
maybe I should a README on how to apply what's in the article (or I can do this in a separate PR?)

**Comment by justinsb** [comment]
/lgtm

No user-facing impact => ok to merge :-)

**Pull request merged**
