### PR TITLE
apimachinery: Enable round-trip tests now we have two versions in play

### PR DESCRIPTION
**Pull request by justinsb**
Will help us catch problems where values don't convert correctly.

### CODE REVIEW

**Comment by justinsb** [comment]
/assign @johngmyers 

Looks like it might be catching some things :-)

**Comment by johngmyers** [comment]
```
         - 				ExternalPolicies:   &nil,
        + 				ExternalPolicies:   nil,
 ```

Not really worried about `&nil`. Perhaps it should be `map` instead of `*map`?

         - 						Provider:              "Ǚ頻蓊ż$č!Ťp\u00ad屳`lʒň琐*",
        + 						Provider:              "",

         - 						LeaderElectionTimeout: s"&Duration{Duration:-1869857h12m53.878519543s,}",
        + 						LeaderElectionTimeout: nil,

Unused fields deliberately omitted from new API.

         - 					Hosts:        []string{},
        + 					Hosts:        nil,

Not worried about the distinction. Don't know why the test even cares.

         - 					NodeLabels:                  map[string]string{"z": `H騦TǟBȓŘ;硲#+ĳ楀\K~鿣`},
        + 					NodeLabels:                  nil,

Not admin configurable, thus ignored, thus deliberately omitted from new API.

         - 					LyftVPC:   &kops.LyftVPCNetworkingSpec{},
        + 					LyftVPC:   nil,

         - 					Legacy:                 true,
        + 					Legacy:                 false,

If set causes API validation error, thus deliberately omitted from new API.

**Comment by justinsb** [comment]
Right, I think the printing might be over-printing here, so not sure that all the differences that are printed "count" as failures.

I think this is what we likely need to figure out: "Unused fields deliberately omitted from new API."  I know what we've done elsewhere is to map an unused field `spec.foo` -> `spec.deprecatedFoo`.  But at some point those are dropped, and I think if we are happy with dropping values of `foo` (which I think we are), then we don't need to introduce `deprecatedFoo`.  What I haven't found yet is how to tell the fuzzer that some fields are "special".  I think having a table of these fields in our code would end up being super-useful - not sure if we would generate docs from them, but I suspect once we have it we'll find more uses (e.g. automatically logging warnings in v1alpha2 if the field is used?)

**Comment by johngmyers** [comment]
There are some fields which, if used, cause an API validation error. There is a much larger set of others which have been ignored for a long time.

**Pull request closed without merging**
