### PR TITLE
Switch from glog to klog

### PR DESCRIPTION
**Pull request by justinsb**
We have to do this as part of 1.13 (and it's a good idea anyway)

### CODE REVIEW

**Comment by justinsb** [comment]
Looks like this relies on #6860

**Comment by rdrgmnzs** [comment]
@justinsb can you rebase now that #6860 landed.

**Comment by justinsb** [comment]
Well this is a mess... if we call klog.InitFlags before we've switched to k8s 1.13 we get a duplicate flag error; if we start using klog but don't call InitFlags we won't get all the log output.

The latter is the lesser of the two evils, so not calling InitFlags yet, but we can put the InitFlags call into the 1.13 PR.

**Comment by justinsb** [comment]
OK - so the InitFlags approach worked :-)  1.13 update is in #6857

**Comment by justinsb** [comment]
/test pull-kops-e2e-kubernetes-aws

Prow just went on holiday

**Comment by rdrgmnzs** [comment]
Thanks for all the work @justinsb!

/lgtm

**Pull request merged**
