### PR TITLE
Automated cherry pick of #7992: Add CloudControllerConfigArgv template function, Expose

### PR DESCRIPTION
**Pull request by DavidSie**
Cherry pick of #7992 on release-1.15.

#7992: Add CloudControllerConfigArgv template function, Expose

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks @DavidSie, I think we should hold off on 1.15 and focus on 1.16 and 1.17.

**Comment by DavidSie** [comment]
Hi @mikesplain,  I manage to shrink  this PR.

**Comment by DavidSie** [comment]
@robinpercy  and @granular-ryanbonham  please add ok-to-test

**Comment by zetaab** [comment]
As we are stable already in 1.15 I do not see why we should merge this. Instead like mike said: we should make these kind of modifications in 1.16 and 1.17 (and master). Only bug fixes are allowed in stable releases

**Pull request closed without merging**
