### PR TITLE
use iptables legacy mode when using buster

### LINKED ISSUE #7379: Debian buster iptables not compatible with k8s
Debian buster has iptables 1.8.2 (nftables) which is too new for k8s. https://github.com/kubernetes/kubernetes/issues/71305. It means that kube-proxy does not work which leads to situation that cluster does not work.

Temporary solution is available here https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-509394152 after running those commands I can run kops cluster fine with debian buster.

This is not yet critical bug, but we should find solution for this quite fast (before buster images are uploaded to AWS). 

/kind bug

### PR DESCRIPTION
**Pull request by zetaab**
fixes #7379 

There are two ways to do this: nodeup OR insert in imagebuilder. However, at least I would like to have support in all buster images - that is why I implemented it to nodeup. Imagebuilder does not support platforms like openstack.

/assign @justinsb 
/kind bug

### CODE REVIEW

**Comment by zetaab** [comment]
This needs cherrypick to 1.14 and 1.13.

**Comment by zetaab** [comment]
@justinsb could you check this PR before doing next 1.14 beta release. This is needed there

**Comment by zetaab** [comment]
/assign @mikesplain 

could you Mike check this?

**Comment by justinsb** [comment]
As I commented on the issue, this is indeed problematic.

I do wonder whether nodeup runs in time.  It's presumably possible for something to beat nodeup and run some iptables commands (for example, if docker was preinstalled), which based on reading the k8s issue would result in problems also.

Going to seek clarification on the k8s issue (https://github.com/kubernetes/kubernetes/issues/71305)...

**Comment by zetaab** [comment]
I actually have been using buster image by adding these commands to IG additionalUserData. I think additionalUserData is executed earlier than this file?

**Comment by zetaab** [comment]
@justinsb any progress in this?

**Comment by nvanheuverzwijn** [comment]
@zetaab 
This might be interesting : https://github.com/kubernetes/test-infra/pull/14812
In these tests, he seems to only use `iptables-legacy` and `ip6tables-legacy`, not `arptables-legacy` or `ebtables-legacy` because "these are not installed" (see https://github.com/kubernetes/test-infra/pull/14813) so maybe we should be careful with arptables and ebtables.

**Comment by hakman** [comment]
I did some testing using the official Debian images from https://wiki.debian.org/Cloud/AmazonEC2Image/Buster.
The `arptables` and `ebtables` packages were not installed by default.

May be a good idea to also make sure that `arptables` and `ebtables` are installed during setup.

**Comment by zetaab** [comment]
/hold

it might be that this is not needed anymore in kube 1.16 https://github.com/kubernetes/kubernetes/pull/82966

**Comment by olemarkus** [comment]
Cilium has no plans for supporting nftables anytime soon. So cilium users will need something like this anyway. Would be nice if this one goes in, but perhaps add an API field controlling if legacy or nft iptables should be used.

**Pull request closed without merging**
