### PR TITLE
bump k8s versions in alpha following May releases

### PR DESCRIPTION
**Pull request by moshevayner**
**What this PR does / why we need it**:
Bumping k8s versions in Alpha following recent releases

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
- https://github.com/kubernetes/kubernetes/releases/tag/v1.24.14
- https://github.com/kubernetes/kubernetes/releases/tag/v1.25.10
- https://github.com/kubernetes/kubernetes/releases/tag/v1.26.5
- https://github.com/kubernetes/kubernetes/releases/tag/v1.27.2

### CODE REVIEW

**Comment by hakman** [comment]
Hi @moshevayner. I needed to quickly fix a runc related issue and did this a few days ago in https://github.com/kubernetes/kops/pull/15427. Sorry for not tagging you there.

**Comment by moshevayner** [comment]
> Hi @moshevayner. I needed to quickly fix a runc related issue and did this a few days ago in #15427. Sorry for not tagging you there.

@hakman Ohh whoops! I didn't even realized that I bumped them up too high 🤦🏼 
Thanks for double checking that!

I did notice that we're still running 1.27.0 though - should we at least bump that one?

**Comment by hakman** [comment]
> Thanks for double checking that!

No worries. Mostly my mistake for not tagging you. 😄 

> I did notice that we're still running 1.27.0 though - should we at least bump that one?

Not sure where you mean that, `requiredVersion` refers to the kOps version to use for that version.

**Comment by moshevayner** [comment]
> > Thanks for double checking that!
> 
> No worries. Mostly my mistake for not tagging you. 😄
> 
> > I did notice that we're still running 1.27.0 though - should we at least bump that one?
> 
> Not sure where you mean that, `requiredVersion` refers to the kOps version to use for that K8s version.

LOL wow, that 0 for 2 for me 🙈 
Sorry about that!
Closing my PR since it's irrelevant. 

/close

**Comment by hakman** [comment]
I appreciate you taking the time to do it though. Cya next time.

**Pull request closed without merging**
