### PR TITLE
Cherrypick etcd-manager support for openstack 

### PR DESCRIPTION
**Pull request by zetaab**
original PR #7395 

openstack support is still under alpha, so I think its ok to cherrypick this to 1.14?

### CODE REVIEW

**Comment by justinsb** [comment]
Yes, this is indeed fine, as also we haven't (quite) released 1.14.0, although you can probably see that I'm trying to get it done today!

**Comment by justinsb** [comment]
I think this needs #7426 to land first, to get the proxy package in there

**Comment by zetaab** [comment]
@justinsb can you add lgtm to this?

**Pull request merged**
