### PR TITLE
Ignore tags files generated by Exhuberant Ctags

### PR DESCRIPTION
**Pull request by relaxdiego**
For anyone that uses ctags for quickly navigating the code (e.g. Vim
users), ignoring the various tags files generated all over the place
will be helpful. As I've found, a tags file needs to be generated for
certain subdirectories to avoid confusing ctags. For example, if I
run `ctags -R .` from the project root and I attempt to jump to the
definition of Execute from `cmd/kops/main.go`, I'm taken to the file
`channels/cmd/channels/root.go` instead of `cmd/kops/root.go`.
Maintaining one tags file for `cmd/kops`, however, doesn't produce the
same problem. This is why all tags files need to be ignored.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1306)

### CODE REVIEW

**Comment by relaxdiego** [comment]
I signed it!

**Comment by justinsb** [comment]
Thanks @relaxdiego .  LGTM.  Just going to find out if we can bypass e2e for a PR that doesn't need it

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kops/1306)*

**Comment by chrislovecnm** [comment]
@justinsb this is new ... blocked by reviewable app now?

**Comment by chrislovecnm** [comment]
Never mind

**Pull request merged**
