### PR TITLE
Align website and readme file

### PR DESCRIPTION
**Pull request by sxt90128**
Fixes: #13226

### CODE REVIEW

**Comment by hakman** [comment]
@sxt90128 Would you mind updating the commit message to match the PR title?

**Comment by sxt90128** [comment]
> @sxt90128 Would you mind updating the commit message to match the PR title?

@hakman It has been changed.

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
Thanks @sxt90128. :)

**Pull request merged**
