### PR TITLE
[DigitalOcean] use ubuntu-22-04 as the default node image

### PR DESCRIPTION
**Pull request by srikiz**
Minor update to use `ubuntu-22-04` as a base image going forward.
Also realized we no longer use the e2e scenarios for running tests, but have them explicitly specified in `test-infra` repo. So deleting this file for clarity.

FYI - @timoreimann @rifelpet

### CODE REVIEW

**Comment by hakman** [comment]
@srikiz We are planning to move to 22.04 soon, but there is no decision yet. Would you mind waiting a little with this change?

**Comment by srikiz** [comment]
Oh okay. How about updating to ubuntu-21-10-x64 for now?

**Comment by hakman** [comment]
We only use Ubuntu LTS by default. Any special reason you want to move to 22.04?

**Comment by hakman** [comment]
@srikiz Would it be ok for you to switch back to 22.04 and I will have an answer about the timeline for the merge soon.

**Comment by srikiz** [comment]
> @srikiz Would it be ok for you to switch back to 22.04 and I will have an answer about the timeline for the merge soon.

Sure @hakman - I wasn't aware that we use Ubuntu LTS by default. I am okay to close this PR if we need to be on LTS.

**Comment by hakman** [comment]
Sorry, but I forgot to give you an update @srikiz.
Seems that there's still no consensus about upgrading. Switching to cgroupv2 is especially risky as there isn't yet that much adoption. https://github.com/kubernetes/kops/issues/14140 will be used to track the upgrade to 22.04 in the future.

**Comment by hakman** [comment]
Closing this until there is an agreement about https://github.com/kubernetes/kops/issues/14140.

**Pull request closed without merging**
