### PR TITLE
YouTube tutorial

### PR DESCRIPTION
**Pull request by vfarcic**
I'm not sure what is the policy about adding videos to the docs/tutorials. Please let me know if such a thing is welcome and, if it is, whether that is the correct place.

### CODE REVIEW

**Comment by gambol99** [comment]
cc @justinsb @chrislovecnm

**Comment by KashifSaadat** [comment]
Apologies I missed this! It is a helpful tutorial for new users starting out creating a Cluster with kops, however I'm not sure about linking out to videos outside of the org. @chrislovecnm what do you think?

**Comment by vfarcic** [comment]
Apologies in advance for a silly question... What is the "org"?

As a side note, I created four more kops videos that might be useful to newbies.

https://www.youtube.com/watch?v=r-c6GoG75uc&t=6s
https://www.youtube.com/watch?v=9FNCSm7FmZc&t=7s
https://www.youtube.com/watch?v=W88tLLMMik4&t=2s
https://www.youtube.com/watch?v=zi9kGlqKzwA&t=12s

**Comment by KashifSaadat** [comment]
No worries I should've clarified, was just referring to the Kubernetes Github Organization.

That's great, will take a look through them :)

**Comment by chrislovecnm** [comment]
@KashifSaadat I really have no idea.

**Comment by KashifSaadat** [comment]
Ah right no worries. @justinsb any idea?

**Comment by justinsb** [comment]
I'll ask around.  I'd guess it won't be a problem as long as we link to the videos and not to the channel, but I'll see...

Thanks for making them @vfarcic

**Comment by justinsb** [comment]
Just a progress report - I'm trying to get our YouTube channel set up :-)

**Comment by justinsb** [comment]
/remove-lifecycle rotten

Going to move this to the next milestone, as I'm burning down the remaining 1.11 issues for beta release, and this wouldn't be compiled in to a release, so shouldn't impact the timelines.

**Comment by chrisz100** [comment]
/remove-lifecycle rotten 

@justinsb how’s YouTube doing! :-)

**Comment by chrisz100** [comment]
@justinsb do we have an update here?

**Pull request closed without merging**
