### PR TITLE
Release notes for 1.18.0-alpha.3

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by hakman** [comment]
@justinsb @rifelpet I think the release notes from the github release page differ from those in the master branch.

**Comment by rifelpet** [comment]
hm whats different exactly? https://github.com/kubernetes/kops/releases/tag/v1.18.0-alpha.3

**Comment by hakman** [comment]
Check the significant changes section:
https://github.com/kubernetes/kops/blob/master/docs/releases/1.18-NOTES.md#significant-changes

**Comment by rifelpet** [comment]
ah, thank you. i just updated the release's significant changes to match whats in 1.18-NOTES.md

**Comment by rifelpet** [comment]
and the breaking changes and deprecations sections.

**Pull request merged**
