### PR TITLE
Enhancement in Ubuntu or debian apt-get and CI issue fix

### PR DESCRIPTION
**Pull request by Rajpratik71**
This PR is clean version of #8681  as requested 

Major Changes No 1 : debian package manager tweaks

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Major Changes No 2 : added packages apt-utils ca-certificates

Because Github CI build is 

1.  Slow and in log it is showing because "apt-utils" not installed 

2. to avoid CI build to exits with error without having certificate

### CODE REVIEW

**Comment by Rajpratik71** [comment]
@hakman @rifelpet @mikesplain  requesting review , new PR as per changes asked in #8681

**Comment by Rajpratik71** [comment]
@robinpercy  @joshbranham requesting review

**Comment by johngmyers** [comment]
The commit messages have a lot of repeated text. Please remove the duplicate text.

**Comment by Rajpratik71** [comment]
> The commit messages have a lot of repeated text. Please remove the duplicate text.

done as requested

**Comment by Rajpratik71** [comment]
@johngmyers please review , done as requested

**Comment by Rajpratik71** [comment]
@robinpercy  requesting review

**Comment by johngmyers** [comment]
@Rajpratik71 you will need to rebase on top of master. We no longer allow merge commits in PRs.

**Comment by Rajpratik71** [comment]
> @Rajpratik71 you will need to rebase on top of master. We no longer allow merge commits in PRs.

done as requested

**Comment by johngmyers** [comment]
It looks like this makes a test data file executable. Please remove that change.

**Comment by Rajpratik71** [comment]
> It looks like this makes a test data file executable. Please remove that change.

fixed

**Comment by hakman** [comment]
@Rajpratik71 this PR needs to be rebased for the tests to work.
Also, check the files and make sure that *only* the changes you want are there: https://github.com/kubernetes/kops/pull/8687/files.

**Pull request merged**
