### PR TITLE
Use correct `kops rolling-update` command

### PR DESCRIPTION
**Pull request by bjarkevad**

### CODE REVIEW

**Comment by bjarkevad** [comment]
I signed it!

**Comment by chrislovecnm** [comment]
We need yah to sign the linuxfoundation CLA as well please

**Comment by bjarkevad** [comment]
I already did, the mail I got says it was signed on 11/09/2016 09:06. 
Did I do something wrong?

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
