### PR TITLE
update README to note current, stalled status

### PR DESCRIPTION
**Pull request by zapman449**
Per @rdrgmnzs in https://kubernetes.slack.com/archives/C3QUFP0QM/p1535049142000100

### CODE REVIEW

**Comment by zapman449** [comment]
the linux foundation tests should be resolved at this point.

**Comment by mikesplain** [comment]
Hi @zapman449, can you make sure you followed the directions above and used the same email for the CLA as your commit? I know it can be a pain but you only have to do this once for all Kubernetes org contributions.

Thanks!

**Comment by justinsb** [comment]
This looks good - if you wanted to add a positive note, you could say "but we have some work in progress to rebase on CRDs, which is looking like a much simpler path forwards"

Sorry about the CLA battles!  If you `git log -p` you can see the email address you used in your commit - it it different from the CLA bot email @zapman449 ?

**Comment by justinsb** [comment]
Oh - reading the "details" above, it looks like maybe you need to add that email to github?  https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/  That's a new requirement if that's the case...

**Pull request closed without merging**
