### PR TITLE
Add possibility to prepend additional user data scripts

### PR DESCRIPTION
**Pull request by ArchangelX360**
Before this patch, AdditionalUserData scripts will only be placed
after `nodeup.sh`.
We needed to have a script running before to workaround issues that are inherent to `nodeup.sh`, such as https://github.com/kubernetes/kops/issues/12041

### CODE REVIEW

**Comment by hakman** [comment]
@ArchangelX360 Did you try naming your additional scripts with a digit in front? If I remember correctly, they run in alphabetical order.

**Comment by ArchangelX360** [comment]
@hakman I did not try, but that seems very unlikely given the code of `AWSNodeUpTemplate`, `nodeup.sh` will always be always placed first see https://github.com/kubernetes/kops/blob/master/pkg/model/resources/nodeup.go#L192.

Then, AWS executes sequentially the scripts in userdata in the order provided by the operator (I tried moving manually the script before `nodeup.sh` and it worked).

**Comment by hakman** [comment]
Can you try the naming? We had same issue in the past and different names for the scripts helped.
See this for example:
https://github.com/kubernetes/kops/pull/7381#issuecomment-521878286

**Comment by ArchangelX360** [comment]
> Then, AWS executes sequentially the scripts in userdata in the order provided by the operator (I tried moving manually the script before nodeup.sh and it worked).

I was wrong, naming does work! AWS will run then in alphabetical order, e.g. it works if I configure:

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
// ...
spec:
  // ...
  additionalUserData:
    # prefixed a_ to be sure to run before nodeup, script are executed in alphabetical order
    - name: a_useradd_workaround.sh
      type: text/x-shellscript
      content: |
        #!/bin/bash
        set -o errexit
        set -o nounset
        set -o pipefail

        # `kops` assumes those users are not existing and `kops-configuration.service` will fail with both:
        #  - "useradd: UID 10011 is not unique"
        #  - "useradd: UID 10012 is not unique"
        # Those two UIDs are already attached to some users in our setup.
        # So we are forcing a local user creation with `--non-unique`, so that `kops` does not try to create them
        echo "Applying 'kops' UID workaround"
        sudo /usr/sbin/useradd --non-unique -u 10011 -s /sbin/nologin -o kops-controller
        sudo /usr/sbin/useradd --non-unique -u 10012 -s /sbin/nologin -d /etc/kubernetes/kube-apiserver-healthcheck/secrets kube-apiserver-healthcheck
```

Thank you so much @hakman!

**Pull request closed without merging**
