### PR TITLE
Extend examples of subnet parameter

### PR DESCRIPTION
**Pull request by dictvm**
The parameter `subnets` isn't well named in my opinion. I was expecting it to require the name of a AWS subnet until I checked the configuration of the already existing default-InstanceGroup. Only then I noticed that `subnets` was meant to be the availability zone or a list of AZs. This change is supposed to make that more obvious.

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @dictvm thanks for the contribution! 

The file you changed is actually auto generated by from https://github.com/kubernetes/kops/blob/master/cmd/kops/create_ig.go#L101.

Please follow these steps:

1. Update the go file
2. Run make gen-cli-docs
3. Check in the results

Thanks again!

**Comment by mikesplain** [comment]
@dictvm Any update on this? We always love new contributors so keep us updated! Thanks!

**Comment by dictvm** [comment]
I'm sorry, I'm not sure if I've done this correctly. I have now updated the docs and the code, tested it locally and I have pushed everything into the branch `patch-1`. If I had known earlier that the docs are derived from the CLI code, I wouldn't have bothered to just edit the file on Github. Sorry for the confusion, I'll pay more attention next time.

**Comment by mikesplain** [comment]
@dictvm Hey no worries! Looks good, only issue now is your odd second commit. Would you mind squashing these commits?

**Comment by dictvm** [comment]
@mikesplain I tried to fix this today, but my git-foo wasn't strong so I ended up with two broken local (detached) branches and merge conflicts. Not sure what went wrong there. I'll try again tomorrow.

I really screwed this up.

**Comment by mikesplain** [comment]
@dictvm Oh no! That's no fun, remember to rebase you'll have to git push --force to your fork, unless you're using a tool to hide it.  Others may have an easier workflow but mine is:
```
# 2 is the number of commits to modify
git rebase -i @~2
# In the editor swap the second commit from pick to fixup
git push --force <your fork>
```

**Comment by dictvm** [comment]
Alright, thanks for your help @mikesplain, I hope this is correct now.

**Comment by mikesplain** [comment]
Thanks @dictvm! 
/lgtm

**Pull request merged**
