### PR TITLE
add EnableNodeAuthorization in the list of experimental features

### PR DESCRIPTION
**Pull request by rekcah78**

### CODE REVIEW

**Comment by chrisz100** [comment]
/ok-to-test 
/lgtm 

Thanks for adding this and helping us with the docs! Much appreciated @rekcah78

**Comment by chrisz100** [comment]
/assign @mikesplain 
As it's docs only shouldn't be release-relevant or blocking.

**Comment by rekcah78** [comment]
@chrisz100 problem with the CI ?

**Comment by chrisz100** [comment]
There is a little glitch in the test infrastructure right now... @justinsb opened a ticket against it already.

**Pull request merged**
