### PR TITLE
updating CI in hack script

### PR DESCRIPTION
**Pull request by chrislovecnm**
fixing missing `CI=1` in the hack script.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2079)

### CODE REVIEW

**Comment by faraazkhan** [comment]
Just tried this locally, still fails with
```
W0309 16:38:17.012908   64564 executor.go:109] error running task "LaunchConfiguration/nodes.<cluster-name>" (7s remaining to succeed): error rendering AutoScalingLaunchConfiguration UserData: error opening resource: error executing template "nodeup": template: nodeup:123:3: executing "nodeup" at <KubeEnv>: error calling KubeEnv: cannot determine hash for http://kops-devel.s3.amazonaws.com/kops/1.5.1/images/protokube.tar.gz (have you specified a valid KubernetesVersion?)
```
@chrislovecnm

**Comment by faraazkhan** [comment]
Turns out the above was because the hack script uses `http` instead of `https` in the `KOPS_BASE_URL` env var. There is also the additional issue with https://github.com/kubernetes/kops/issues/2098 that needs to resolved for the script to work fully.

**Comment by chrislovecnm** [comment]
Making more tweaks - WIP

**Comment by justinsb** [comment]
Is this still WIP?

**Comment by chrislovecnm** [comment]
@justinsb yes still WIP

**Pull request merged**
