### PR TITLE
Squash patch versions of old release notes

### PR DESCRIPTION
**Pull request by hakman**
A different approach to solve https://github.com/kubernetes/kops/pull/8372.

Preview:
* https://deploy-preview-9770--kubernetes-kops.netlify.app/releases/1.6-notes/
* https://deploy-preview-9770--kubernetes-kops.netlify.app/releases/1.7-notes/
* https://deploy-preview-9770--kubernetes-kops.netlify.app/releases/1.8-notes/

### CODE REVIEW

**Comment by rifelpet** [comment]
This seems reasonable to me. Maybe our theme supports having submenu items on the left where we could hide some of the oldest releases behind an "archives" section. Something to consider for a followup

/lgtm

**Comment by johngmyers** [comment]
Ah, so you deleted the dead link.
/lgtm

**Comment by hakman** [comment]
> Ah, so you deleted the dead link.

Yes, this way the notes are kept as is, but the scripts and the link are gone.

**Pull request merged**
