### PR TITLE
Update aws.md

### PR DESCRIPTION
**Pull request by kmaris**
Fix grammar.

### CODE REVIEW

**Comment by kmaris** [comment]
/assign @chrislovecnm 

Hope I'm doing this right. First commit to this project, glad it's a small docs related one!

**Comment by mikesplain** [comment]
Hey @kmaris thanks so much for the PR! Small docs fixes are what make the world go round (or at least the kops world!).  Anyway keep 'em coming if you find more, feel free to group them if you find lots (and there probably are).

/area documentation
/ok-to-test
/lgtm

**Comment by KashifSaadat** [comment]
/approve

Thanks @kmaris :)

**Comment by kmaris** [comment]
@mikesplain I'll definitely group them together going foward, this was a nice test for me to get contributions pre-reqs going :) Thanks again.

**Pull request merged**
