### PR TITLE
Add support for MemorySwap

### PR DESCRIPTION
**Pull request by tomesm**
This PR adds support for `MemorySwapConfiguration` based on the following logic:

- If `memorySwapConfiguration.swapBehavior` is not set, there will be no change to the kubelet configuration.
- If `memorySwapConfiguration.swapBehavior` is set to an empty string, kubelet config will contain `memorySwap: ""`.
- If `memorySwapConfiguration.swapBehavior` is set to `"UnlimitedSwap"`, kubelet config will contain `memorySwap: UnlimitedSwap`.

Fixes: #14950

### CODE REVIEW

**Comment by jan-kantert** [comment]
@hakman @zetaab is there anything missing to get this merged? this feature makes certain usecases much more economic (i.e. most java workloads)

**Comment by hakman** [comment]
@tomesm If you have time to go through the review, please let me know and I will try to review this PR.

**Comment by hakman** [comment]
Thanks, @tomesm for the inspiration and sorry for the delay in review.
I created a [slightly simpler](https://github.com/kubernetes/kops/pull/15632) version of it which will be part of kOps 1.27.0.

**Comment by tomesm** [comment]
Hey @hakman , your version looks better. Im glad I inspired you :)

**Comment by hakman** [comment]
I hope you try again @tomesm. I would be happy to review your PRs. 👍

**Pull request closed without merging**
