### PR TITLE
Add support for bastion aws user-data

### LINKED ISSUE #4444: Bastions role additionalUserData not available?
Hi

 Thanks for this tools, works great :)

1. I'm currently using additionalUserData for nodes and masters to install SaltStack and setup users and a few minor things we apply to all instances. I'm trying to do the same for bastions groups, but even when I edit bastions IG nothing changes and kops doesn't detect any change.

Here is what I do

```
kops edit instancegroup bastions
```

I add the example present in Instance Group for this feature

```
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2018-02-13T15:43:08Z
  labels:
    kops.k8s.io/cluster: mycluster.company.com
  name: bastions
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      echo "Hello World.  The time is now $(date -R)!" | tee /root/output.txt
  image: ami-965e6bf3
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-us-east-2a
  - utility-us-east-2b
  - utility-us-east-2c
```

I don't get a message like **kops edit does not update the cloud resources, to apply the changes use "kops update cluster"** like I get when editing nodes IG.

Running update/rolling-update cluster doesn't change anything. I also checked Launch Configuration for this group and user-data is empty.

2. Feel free to provide a design supporting your feature request.

The same approach used for all other instances, like nodes and master?

Thanks.

### PR DESCRIPTION
**Pull request by duboisf**
Fixes #4444

### CODE REVIEW

**Comment by duboisf** [comment]
So in the integration tests I added selective validation of terraform data files.... I'm not sure this is a great idea!

I added validation for the bastion launch config since the content is simple, but to make sure I didn't break something I added also the nodes launch config. The thing is the nodes launch config contains the nodeup script which is pretty involved, I'm not sure it will be stable? Meaning that as the master branch evolves, might the produced terraform data for the nodes launch config change? In that case might want to remove that once and only keep the bastion launch config check.

**Comment by justinsb** [comment]
I was concerned that this would be a behavioural change, but it looks like we don't have any extra fields that will suddenly be applied to the bastion with this change (beyond additionalUserData on the bastion, which - if the user specifies - we should honor).  I'm not missing something, am I?

I'll think about testing.  I like having the script under test coverage but I thought we already had it covered?

**Comment by duboisf** [comment]
Indeed didn't have to add any fields. When we updated our bastion IG with `additionalUserData` there were no errors but the user data was not being added to the bastion's launch config. This is why we were confused (as was @abednarik in #4444).

The tests only validated that the list of created data filenames matched the expected list, it didn't validate the content.

I think that validating the content of `data/aws_launch_configuration_bastion.bastionuserdata.example.com_user_data` is good because it _only_ depends on the `additionalUserData` field of the bastion IG.

But for the nodes launch config (`data/aws_launch_configuration_nodes.bastionuserdata.example.com_user_data`) I don't know if the launch config content _only_ depends on `in-v1alpha2.yaml`...

Worst case I remove the nodes launch config validation from the test?

**Comment by duboisf** [comment]
Will test some more

**Comment by duboisf** [comment]
@justinsb ok removed the `data/aws_launch_configuration_nodes.bastionuserdata.example.com_user_data` test data because if the nodeup template changes then the test will fail, which will suck for the poor soul who has to modify the nodeup template...

I left the bastion data file since it entirely depends on only the bastion instance group yaml and it's good to test that it matches the actual output.

**Comment by duboisf** [comment]
@justinsb do you need anything else from me?

**Comment by justinsb** [comment]
/ok-to-test

/lgtm

Thanks @duboisf  :-)

**Comment by duboisf** [comment]
/retest

Seemed like a transient error `Temporary failure resolving 'deb.debian.org'`

**Pull request merged**
