### PR TITLE
Set the tcp_rmem sysctl in bootstrap script

### PR DESCRIPTION
**Pull request by justinsb**
This ensures that we're using our settings for downloading nodeup
itself and any assets that nodeup downloads.  This is a workaround for
reported problems with the initial download on some kernels otherwise.

Issue #10206

### CODE REVIEW

**Comment by olemarkus** [comment]
This looks good.

Do we know if there is any kernel issue worth tracking? I suspect it won't hit older distros like Debian 9 anyway though.

**Comment by hakman** [comment]
Seems there was some discussion around the patch and workaround, but no conclusion:
https://lore.kernel.org/netdev/CANn89iL48fnjMQ=rt7oGRC_cejhuwfvcyy5JcUs=k5Cet+-Vwg@mail.gmail.com/

**Comment by justinsb** [comment]
Removed the WIP, based on feedback (thanks @olemarkus  and @hakman ), and a similar workaround described here: https://github.com/kubernetes/kops/issues/10206#issuecomment-766852332

The sysctls might be setting up larger windows that we should by default, but we can tackle that separately.

**Pull request merged**
