### PR TITLE
nodeup: Use https for docker download

### PR DESCRIPTION
**Pull request by rata**
Both domains support https, so we can just use it.

I've tried to download all files via https and it works fine. I used,
with this commit as HEAD, this simple script:

	for i in $( git show | grep https | awk ' { print $3 }' | tr -d '",' | grep ^https:\/\/ )
	do
		echo $i; timeout 3 wget  $i
	done

Then, just compared the number of downloaded files and URLs used in the
for loop (there is one file, docker-ce_17.09.0~ce-0~debian_amd64.deb.1,
created with a ".1" instead as ".deb" because the distribution is not in
the filename for those).

So, besides this should work, I've tried for all those files and it
works :)

### CODE REVIEW

**Comment by mikesplain** [comment]
Hi @rata thanks for the PR.  I'm not sure why these are in HTTP but it's worth getting these tests fixed up, assuming no one has issues with the change it's self.

You'll need to updated the tests as well, and squash into your previous commit e.g. https://github.com/kubernetes/kops/blob/c6e84ffd5508d5d591dd7da5ce4bbfd5860cc44e/nodeup/pkg/model/tests/dockerbuilder/simple/tasks.yaml#L219

**Comment by rata** [comment]
@mikesplain thanks a lot for the quick review and pointer to the failing tests. Now all tests are green. Let me know if something else is needed for merge :)

**Comment by mikesplain** [comment]
@rata great! Looks good to me.  Lets get some other eyes on this since, I imagine there's a reason it was http, (maybe some distro's didn't ship with certs?). 

@andrewsykim @justinsb @chrislovecnm any ideas why this might be?

**Comment by thomaschaaf** [comment]
Is this really desired? https://whydoesaptnotusehttps.com/

**Comment by mikesplain** [comment]
That's some great points @thomaschaaf, very much agreed with.

**Comment by rata** [comment]
@thomaschaaf oh, didn't know about that, it's interesting. Thanks!

But I think this isn't installed using an APT repository. This assumption might be wrong (so all that follows will be wrong too). I didn't read the code for that, but seems reasonable as it points to a file over HTTP, not an APT repo. Also, I've checked and there is no such repository on an already installed VM, so I'd guess that it is not used as an APT repository. If you know more about this (i.e. know the code :)), can you please confirm?

If it doesn't use an APT repository, then mostly that stuff doesn't apply here. I'd guess that it just downloads the deb file (or downloads and checks the hash) instead of using an apt repository. So,  there is no signature for the apt repository, because we are not using one, etc. And https is better than plain http, in that case.

So, I think this is relevant as it is just a download over HTTP. Not using an APT repository.

**Comment by justinsb** [comment]
We download over http but we check the hash - so it's not a security issue (an attacker would have to force a hash collision).

I think originally we downloaded over http because it's a little faster, a little easier to proxy.  I don't have any real objection to switching to https, but my concern is that we'd have to think about how it interacts with people that have an http proxy for egress.

@DerekV - you wrote much of our proxy support (thank you!) - what do you think?  Is it OK to switch to https, or do some people only have http proxies?

I'm inclined to say we shouldn't switch to https, for the same reason that apt repos primarily use http.  But I'm open to any arguments in favor.

In any case it could have subtle behaviours, so I'm going to target this to our next major release - 1.11

**Comment by rata** [comment]
@justinsb I'm not against leaving this as it is, though. I don't see a reason not to change it and that's why I opened the PR.

But if you guys prefer HTTP for some mirrors (and https for others), I'm okay with it. Just thought it was not on purpose :)

**Comment by rata** [comment]
@mikesplain @andrewsykim @justinsb @DerekV any thoughts on this?

I don't have much more to add to what I already said, but that `download.docker.com` **is already returning a redirect to** `https` and `https` is already being used for some URLs.

So, maybe using https only for download.docker.com makes more sense for you? Or not using https for *any* URL? But the current mix of URLs doesn't help. In my case, I thought it was a mistake and that is why I opened the PR.

In any case, I don't mind if the PR is closed. But in that case, maybe a comment in the code would help to avoid someone else just looking at it, thinking it was a typo and opening a similar PR.

**Comment by justinsb** [comment]
I'm not entirely clear how we should proceed - let's tackle in 1.12.

**Comment by justinsb** [comment]
I think I have a way forward ... there are some other patches that will hopefully land in 1.12, such that we will download everything by hash, and can have multiple source locations.  So we can support both http and https, so we could have one as a fallback.

I'm also hoping we can have mirrors!

**Comment by rata** [comment]
@justinsb cool, thanks! Should I close this, then?

**Comment by justinsb** [comment]
Let's let the mirror support land in 1.12, and then implement this via mirroring in 1.13

**Pull request closed without merging**
