### PR TITLE
Feature/4920 add authorization mode flag

### PR DESCRIPTION
**Pull request by chrisz100**
Kubelet allows and makes use of authorization-mode flags on the service definition. Added this to the kubelet model.

### CODE REVIEW

**Comment by chrisz100** [comment]
I can't really reproduce this error on Mac - is this test that fails runtime related? 
Test: TestLifecycleMinimal
On Mac with go 1.9 specifically.

**Comment by mikesplain** [comment]
@chrisz100 looks like you should be good go go now!

**Comment by chrisz100** [comment]
Great, so from my side nothing to be added.

**Comment by mikesplain** [comment]
/lgtm We'll likely wait on 1.9 before merging this in though.

Thanks for the contribution!

**Comment by justinsb** [comment]
/approve

No real reason to delay on mapping the flag.  For actually setting the flag we have to be much more careful :-)

**Pull request merged**
