### PR TITLE
Pass `S3_*` env vars to nodes when using Gossip

### PR DESCRIPTION
**Pull request by hakman**
Closes https://github.com/kubernetes/kops/issues/15684

### CODE REVIEW

**Review by johngmyers — COMMENTED** [review]
Can we suppress the credentials entirely when the cloud provider has an instance role or equivalent?

We should be moving the non-credential stuff to the cluster spec.

**Comment by hakman** [comment]
> Can we suppress the credentials entirely when the cloud provider has an instance role or equivalent?
> We should be moving the non-credential stuff to the cluster spec.

Not sure what you mean, but closing this for now. It should not be needed.

**Pull request closed without merging**
