### PR TITLE
Update containerd to v1.7.7

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
LGTM

Thanks for adding the runc hashes

**Comment by hakman** [comment]
@upodroid Any idea if what would make the failing jobs not be able to download the build artifacts?
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/16043/pull-kops-e2e-cni-cilium/1716060340745146368/artifacts/18.246.161.222/cloud-init-output.log
```
Cloud-init v. 23.2.2-0ubuntu0~22.04.1 running 'modules:config' at Sun, 22 Oct 2023 12:10:55 +0000. Up 17.55 seconds.
Cloud-init v. 23.2.2-0ubuntu0~22.04.1 running 'modules:final' at Sun, 22 Oct 2023 12:10:56 +0000. Up 18.44 seconds.
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 87380 16777216
== nodeup node config starting ==
All downloads failed; sleeping before retrying
```

**Comment by upodroid** [comment]
that is weird, seems to be specific to aws tests except pull-kops-e2e-cni-amazonvpc. The build was uploaded successfully to GCS.

/retest

**Comment by hakman** [comment]
@upodroid I found the problem:
```
NODEUP_URL_AMD64=https://storage.googleapis.com/k8s-staging-kops/pulls/pull-kops-e2e-cni-calico/pull-f7a52388b66079ae2487a2a1af4fe8d55549e1ee/1.29.0-alpha.2+v1.29.0-alpha.1-167-g6b543cd2f7/linux/amd64/nodeup
NODEUP_HASH_AMD64=f46b20a651727d81b1bdf625648f53a9564325610b1446cb292c0253f34e84b5
NODEUP_URL_ARM64=
NODEUP_HASH_ARM64=
```

**Pull request merged**
