### PR TITLE
Adding troubleshooting documentation

### PR DESCRIPTION
**Pull request by kris-nova**
This closes https://github.com/kubernetes/kops/issues/382

### CODE REVIEW

**Comment by kris-nova** [comment]
How I wish I could `@k8s-ci-robot ok to test` to get this through... :( 

Assigning to @chrislovecnm - can we also look at getting me robot rights please?

**Comment by chrislovecnm** [comment]
Travis does the build. The bots do e2e ;)

**Comment by chrislovecnm** [comment]
Can we try to recreate this issue? Good exercise for one of the new guys ;)

**Comment by kris-nova** [comment]
Recreate what issue? The one the PR is referencing? Or the bot things?

**Comment by chrislovecnm** [comment]
Recreate the issue that @justinsb has only seen once

**Comment by kris-nova** [comment]
Closed - @justinsb suggested another mitigation path

**Pull request closed without merging**
