### PR TITLE
[WIP] Cloud Implementation 

### PR DESCRIPTION
**Pull request by kris-nova**
### This is a **WIP** do not merge

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2487)

### CODE REVIEW

**Comment by geojaz** [comment]
@geojaz just watching your magic

**Comment by chrislovecnm** [comment]
You want to drop the azure deps  into another PR?

**Comment by blakebarnett** [comment]
@kris-nova still planning to get this in?

**Comment by chrislovecnm** [comment]
@kris-nova can we close this?

**Pull request closed without merging**
