### PR TITLE
Update Weave Net to version 2.5.2

### PR DESCRIPTION
**Pull request by murali-reddy**
https://github.com/weaveworks/weave/releases/tag/v2.5.2

### CODE REVIEW

**Comment by hadrianvalentine** [comment]
Greetings,
Is there any update on the status of this PR?

**Comment by ReillyBrogan** [comment]
/approve

I don't know if this will work with me drive-by reviewing this but it's worth a shot. I've been using Weave Net 2.5.2 with my kops clusters for the last month and haven't hit any issues.

**Comment by hairyhenderson** [comment]
@zetaab Any possibility to get this merged? Would be great to get this ugprade!

**Comment by itskingori** [comment]
I would like to recommend that we test this a little further. We upgraded to this version after a bunch of weave pods got OOM'd at 200MB during scaling. As part of that upgrade we increased the limit to 300MB and out cluster was very very unstable on 2.5.2. We've rolled back to 2.5.1 but kept the 300MB limit change and it's been working well for the past hour or so (with scaling). With 2.5.2 we had to remove cluster-autoscaler because the cluster would slowly fall apart as weave state became inconsistent.

**Comment by murali-reddy** [comment]
@itskingori 

> We upgraded to this version after a bunch of weave pods got OOM'd at 200MB during scaling.

> As part of that upgrade we increased the limit to 300MB and out cluster was very very unstable on 2.5.2. 

2.5.2 is bug fix release. I dont see any possible reasons why 2.5.2 would cause your cluster to be unstable compared to 2.5.1

Its possible you may run into the issue on 2.5.1 as well (https://github.com/weaveworks/weave/issues/3650).

To me its best to understand the root cause for the memeory leak before coming to conculsion on 2.5.2

**Comment by itskingori** [comment]
@murali-reddy I'm still monitoring our setup. There a two issues here:

> 2.5.2 is bug fix release. I dont see any possible reasons why 2.5.2 would cause your cluster to be unstable compared to 2.5.1

We were equally surprised. But our tests have been consistent since Saturday that when we're running 2.5.2 we get weave pods with different states after a while ... it's not immediate (and memory usage is not rising up to the point we get OOMs). This is a different issue. Memory usage went down slightly but we would have issues eventually (inconsistent ipam lists) as long as we had cluster-autoscaler scaling ... to cope we would remove and run a fixed number of nodes.

> Its possible you may run into the issue on 2.5.1 as well ([weaveworks/weave#3650](https://github.com/weaveworks/weave/issues/3650)).

Yes, I've hit that issue and that is what made us upgrade after reading the CHANGELOG. I consider both these issues separate. The only connection is that I thought 2.5.2 would address the OOM issue. 

> To me its best to understand the root cause for the memeory leak before coming to conculsion on 2.5.2

Agreed. I'll refrain from posting until I have memory heap of a pod that's getting to/past 200MB.

**Comment by itskingori** [comment]
FYI. There's https://github.com/weaveworks/weave/issues/3659#issuecomment-514773808 where @sferrett confirms that's 2.5.2 is working for him.

**Comment by hairyhenderson** [comment]
For what it's worth, we've been running 2.5.2 in 9 different clusters for over 2 weeks and haven't seen any of the error rates that we were seeing with 2.5.1 or 2.5.0.

**Comment by itskingori** [comment]
My colleague (@zacblazic) has done extensive testing with this version and he has posted the results in https://github.com/weaveworks/weave/issues/3677.

**Comment by rifelpet** [comment]
It looks like we can close this as #7444 was a duplicate and merged into master and cherry-picked into 1.14.

**Comment by murali-reddy** [comment]
> It looks like we can close this as #7444 was a duplicate and merged into master and cherry-picked into 1.14.

@rifelpet thanks for informing. Closing this PR.

**Pull request closed without merging**
