### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by AdamDang**
Line 1601: typo fix "defailt"->"default"

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@AdamDang this is auto generated documentation :) . We need to fix the generator.

**Comment by justinsb** [comment]
Thanks for spotting!

If you `git grep defailt` you should see:

```
> git grep defailt
docs/apireference/build/index.html:<td>LogDriver is the defailt driver for container logs (default &#34;json-file&#34;)</td>
pkg/apis/kops/dockerconfig.go:  // LogDriver is the defailt driver for container logs (default "json-file")
pkg/apis/kops/v1alpha1/dockerconfig.go: // LogDriver is the defailt driver for container logs (default "json-file")
pkg/apis/kops/v1alpha2/dockerconfig.go: // LogDriver is the defailt driver for container logs (default "json-file")
pkg/openapi/openapi_generated.go:                                                               Description: "LogDriver is the defailt driver for container logs (default \"json-file\")",
pkg/openapi/openapi_generated.go:                                                               Description: "LogDriver is the defailt driver for container logs (default \"json-file\")",
```

The `pkg/apis/kops` are the source changes.  And then I believe you run `make gen-cli-docs gen-api-docs`

**Comment by AdamDang** [comment]
Thanks for your help! @justinsb
I'm tring my best to get skilled in GIT.

**Comment by chrislovecnm** [comment]
That make target is busted since dep @justinsb. And I cannot get dep to work locally.

**Pull request closed without merging**
