### PR TITLE
fixing some links in the readme page

### PR DESCRIPTION
**Pull request by cpanato**
Fixing some links in the readme docs pages

### CODE REVIEW

**Comment by dj80hd** [comment]
dup of #7901 ?

**Comment by dj80hd** [comment]
Linking directly to the subsection (not having to scroll) may provide an even better user experience: e.g.
https://github.com/kubernetes/kops/pull/7901/files#diff-e70100059cc3a7376740bbe9751a082eL62

**Comment by geojaz** [comment]
@cpanato I chose #7901 over this one of your links was broken and @dj80hd got there first. thanks!

**Comment by cpanato** [comment]
sure no problem, i did not see that one

**Pull request closed without merging**
