### PR TITLE
Update aws-sdk-go to 1.12.55

### PR DESCRIPTION
**Pull request by leeeboo**
To add support for cn-northwest-1.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@leeeboo the only thing I am seeing for this update is the Route53 updates?  Is that why we need this?

**Comment by leeeboo** [comment]
@chrislovecnm this commit update the aws adk. Aws launched cn-northwest-1 last month. The old sdk doesn’t support it.

**Comment by chrislovecnm** [comment]
Where is it listing this n the release notes for the API? Did you specific —cloud aws? Also this is not passing CI

**Comment by leeeboo** [comment]
@chrislovecnm I am not sure why it can not pass the ci. I build it on my mac and it works.
The aws sdk must be update because the old one can not pass the Region "cn-northwest-1" valid on function "validateRegion" in file "kops/util/pkg/vfs/s3context.go".

**Comment by leeeboo** [comment]
@chrislovecnm and I just follow the step in "https://github.com/kubernetes/kops/blob/7bdf854db226c35316294e7fc25ca21fc9ce6de7/docs/development/dependencies.md".

**Comment by leeeboo** [comment]
I will close this pr and do again

**Pull request closed without merging**
