### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by justinsb** [comment]
/lgtm

/ok-to-test

Thanks @asifdxtreme !

**Comment by justinsb** [comment]
Ah - actually, these doc cli files are automatically generated (https://github.com/kubernetes/kops/pull/3220/files#diff-bb864714b86caf85949ac3c69c68d0f9R2 )

I think you change it here: https://github.com/kubernetes/kops/blob/master/cmd/kops/validate.go#L34 and then you run `make gen-cli-docs`, this should then fix both this and 3219.

I'm going to close 3219 as a dup of this, therefore :-)

**Comment by chrislovecnm** [comment]
@justinsb going to remove the lgtm since we need changes

**Comment by chrislovecnm** [comment]
/lgtm cancel 

@asifdxtreme let us know if you have any questions

**Comment by chrislovecnm** [comment]
/approver cancel 

Any update?

**Pull request closed without merging**
