### PR TITLE
create_cluster.go: Allow specifying etcd version to use for cluster.

### PR DESCRIPTION
**Pull request by jpds**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@jpds we already have this functionality hiding in the code.

**Comment by chrislovecnm** [comment]
It is hiding deliberately for a couple of reasons. Sorry that is is hiding 

Look at overrides

Here is why it is hiding

1. We were designing a capability to access more of the api options and the design was not final
2. You have the capability to use a manifest and define the etcd version. I highly recommend using manifests.
3. We have a PR I think inbound which has a patch like functionality, but really want a true patch like function.

Does the existing functionality work for you?

**Comment by jpds** [comment]
> You have the capability to use a manifest and define the etcd version. I highly recommend using manifests.

We've been doing this for now and when you create multiple clusters a day (for dev/test purposes). It gets really frustrating to do `create cluster`, `edit cluster`. find the lines, etc.

**Comment by jpds** [comment]
Ah, I've just discovered the `--override "cluster.spec.etcdClusters[*].version=3.1.11"` option - this should be better documented.

**Comment by chrislovecnm** [comment]
@jpds I mentioned why it is not documented :)  Alpha feature.

Can we close this PR?

**Comment by jpds** [comment]
Sounds good to me, thanks.

**Pull request closed without merging**
