### PR TITLE
Fix typo in docker healthcheck

### PR DESCRIPTION
**Pull request by TristanPeers**

### CODE REVIEW

**Comment by TristanPeers** [comment]
CLA completed/signed

**Comment by geojaz** [comment]
@TristanPeers it looks like there may be some issue with your CLA? maybe double check the email on these commits vs the email that you signed the CLA on?

in the meantime...
/ok-to-test

**Comment by TristanPeers** [comment]
@geojaz - thanks. CLA issue now resolved.

**Pull request merged**
