### PR TITLE
Don't hash parts of the cluster name for e2e

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by justinsb** [comment]
Looks good, but can we add a comment (either to the commit or the code itself) about why we're not hashing.  It does feel like we were trying to fit into a size limit before, but maybe we don't have that limit any more?

**Comment by olemarkus** [comment]
Added to commit

**Comment by justinsb** [comment]
Thanks @olemarkus 

/approve
/lgtm

**Pull request merged**
