### PR TITLE
use the latest version of 1.22 golang

### PR DESCRIPTION
**Pull request by upodroid**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by upodroid** [comment]
@rifelpet ^

The IAM change has been applied.

**Comment by rifelpet** [comment]
This job creates the final artifacts used in releases. Do we lose reproducibility of our artifacts by not pinning the Go patch version?

**Comment by upodroid** [comment]
We can pin the go patch version if we don't forget to bump it

**Comment by rifelpet** [comment]
Replaced by https://github.com/kubernetes/kops/pull/16661

/close

**Pull request closed without merging**
