### PR TITLE
fixed the sentence mistake

### PR DESCRIPTION
**Pull request by abhijitio**
change jessie to stretch

### CODE REVIEW

**Comment by abhijitio** [comment]
I have signed a Contributor License Agreement (CLA). Please check.

**Comment by mikesplain** [comment]
Ahh yes good catch @abhijitio! Thanks for the contribution!

/ok-to-test
/area documentation
/lgtm
/approve

**Comment by mikesplain** [comment]
Can you make sure your branch is up to date with master? Not sure why travis would think you need to run `make apimachinery` with this change.

**Comment by justinsb** [comment]
It's one of our scripts not recognizing 2019 (see #6288).  Will merge manually as it's just travis!

Thanks for the fix @abhijitio

**Pull request merged**
