### PR TITLE
GCE integration test: verify TF output

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Builds on #3391

**Comment by chrislovecnm** [comment]
This PR is pretty big, I think it include some stuff on a pr that was just approved. Let's see if it needs a rebase

**Comment by justinsb** [comment]
Rebased - and much smaller now - PTAL @chrislovecnm

**Comment by chrislovecnm** [comment]
I think I just lgtm some of this code, will probably need a rebase shortly.

**Comment by justinsb** [comment]
Awesome - thank you @chrislovecnm, you LGTM-ed 3435 which has this as its first commit.  If that merges I'll close this one!

**Pull request closed without merging**
