### PR TITLE
Docs updates to clarify and fix typos in rolling-update cmd.

### PR DESCRIPTION
**Pull request by jlaswell**
Helps with https://github.com/kubernetes/kops/issues/3441; tried to keep the same voicing, but feel free to revert/update as desired of course.

### CODE REVIEW

**Comment by jlaswell** [comment]
Happy to make the appropriate changes to get CI passing w/ a little insight into where I should start.

**Comment by chrislovecnm** [comment]
@jlaswell we had another PR that came in that broke ci ... can you rebase and see if that helps?

**Comment by jlaswell** [comment]
Trying to re-trigger the cncf-cla label.

/joke

**Comment by chrislovecnm** [comment]
/joke

bot listens to members :) and people with a CLA :(

**Comment by chrislovecnm** [comment]
Random comment about CLA ... bot??

@jlaswell you may want to reach out to the email address.  Good news is that you only have to jump through this once.

**Comment by jlaswell** [comment]
I've been recommended to reopen a new PR to see if that'll solve the issue; thanks for your patience.

**Pull request closed without merging**
