### PR TITLE
Update Calico to v3.4.0

### PR DESCRIPTION
**Pull request by vietwow**
Updating to Calico v3.4.0

### CODE REVIEW

**Comment by vietwow** [comment]
Hi @chrisz100 @rdrgmnzs I have just signed CLA, so how to update this pull ? Thanks

**Comment by mikesplain** [comment]
Hi @vietwow, it looks like your commit isn't setup properly. If you do a `git log` on your branch you'll see your commit author as `Author: Viet Nguyen <vietwow@Temp-MacBook-Pro.local>`.  This needs to match the email address that you used to sign the CLA.  You can search google how to edit a commit author but that's most likely the issue with the bot 😉

**Comment by mikesplain** [comment]
@vietwow Thanks for the update, looks like the cla still isn't passing, can you remove the merge commit? Something like this should make it doable: https://sethrobertson.github.io/GitFixUm/fixup.html

**Comment by justinsb** [comment]
Looks like this was done in #6263 

Thanks for the PR @vietwow , and sorry this one didn't get merged.

**Pull request closed without merging**
