### PR TITLE
Require all HasLifecycle tasks to have lifecycle set

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by johngmyers** [comment]
Actually, it looks like the e2e-gce failures are now in line with previous runs.

**Comment by johngmyers** [comment]
@olemarkus I believe this is ready to go in.

**Review by olemarkus — APPROVED** [review]

**Comment by johngmyers** [comment]
Will open as new PR.

**Comment by hakman** [comment]
When this happens, a force push with a changed commit message does the trick.

**Pull request closed without merging**
