### PR TITLE
Document etcd-manager backups retention settings

### PR DESCRIPTION
**Pull request by hakman**
Followup for https://github.com/kopeio/etcd-manager/pull/322

### CODE REVIEW

**Comment by rifelpet** [comment]
Maybe this should go in the etcd backup/restore page? 
https://kops.sigs.k8s.io/operations/etcd_backup_restore_encryption/

**Comment by hakman** [comment]
Thanks @rifelpet

**Comment by caiohasouza** [comment]
Great job @hakman!

What kops versions this feature will be released?

**Pull request merged**
