### PR TITLE
Automated cherry pick of #15916: Configure Karpenter resources.

### PR DESCRIPTION
**Pull request by danports**
Cherry pick of #15916 on release-1.28.

#15916: Configure Karpenter resources.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by danports** [comment]
Darn, I missed 1.28.0 by a few hours! 😵‍💫

**Comment by hakman** [comment]
@danports Please cherrypick #15935 and #15957 at the same time (same command), in this order.

**Comment by danports** [comment]
Cherrypick this PR rather than the original 1.29 PR? Sure, I'll give it a try.

**Comment by danports** [comment]
All set: #15958

**Pull request closed without merging**
