### PR TITLE
Update containerd to v1.6.16

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Review by zetaab — APPROVED** [review]

**Comment by zetaab** [comment]
ideas why the tests are failing?

**Comment by hakman** [comment]
@zetaab https://github.com/kubernetes/kops/pull/15071#issuecomment-1407573368

**Comment by hakman** [comment]
@zetaab Let's make the IPv6 jobs optional for now.
https://github.com/kubernetes/test-infra/pull/28580

**Pull request merged**
