### PR TITLE
v1alpha3: Remove no-longer-used topology fields

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by clayrisser** [comment]
Why was nodes and controlPlane topology fields removed? How can I configure controlPlane to have a public topology now?

**Comment by johngmyers** [comment]
The topology fields didn't do much of anything. You configure the topology by specifying the subnets for the particular instance groups.

**Comment by clayrisser** [comment]
Ok, thanks. Got it to work!

https://gitlab.com/bitspur/rock8s/rock8s-cluster

Sorry haven't updated the code here yet.
https://github.com/clayrisser/rock8s-cluster

**Pull request merged**
