### PR TITLE
Removing duplicate AMI entry from Documentation

### PR DESCRIPTION
**Pull request by AlexLast**
- Removing duplicate AMI entry from spectre/meltdown advisory

### CODE REVIEW

**Comment by AlexLast** [comment]
@justinsb

**Comment by mikesplain** [comment]
Good eye! Thanks @AlexLast, mind filling out the CLA above so we can get this in?

Thanks again!

**Comment by AlexLast** [comment]
@mikesplain Sorry - missed that step. I've completed the CLA now.

**Comment by chrislovecnm** [comment]
/ok-to-test
/lgtm

Thanks for catching my copy pasta typo!

**Comment by mikesplain** [comment]
Looks like @chrislovecnm may have accidentally removed his approval?  

Thanks again for this @AlexLast!

/lgtm

**Comment by mikesplain** [comment]
This is having issues due to the aws testing bug, I'll kick it once more.  Hopefully we'll get lucky soon ;)
/retest

**Pull request merged**
