### PR TITLE
Remove babysit-daemons flag from 1.7

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2447)

### CODE REVIEW

**Comment by justinsb** [comment]
cc @mtaufen 

https://github.com/kubernetes/kubernetes/issues/44248

https://github.com/kubernetes/kubernetes/pull/44230

**Comment by mtaufen** [comment]
Woohoo! Sorry I've been behind on my reviews/issue follow up. This is great!

**Comment by mtaufen** [comment]
LGTM

**Comment by mtaufen** [comment]
@justinsb someone with write access needs to approve.
@mikedanese can you do it?

**Comment by chrislovecnm** [comment]
I can be the merge bot ;)

**Comment by kinghajj** [comment]
I just tried to bring up a cluster with Kops 1.7 & K8s 1.7.3, and see this in the syslog: `kubelet[11289]: unknown flag: --babysit-daemons`. Any ideas?

**Comment by justinsb** [comment]
@kinghajj are you definitely running kops 1.7 & k8s 1.7.3?  If you do `ps -ef | grep kubelet` do you see the `babyset-daemons` flag?  (Or you could try `ps -ef | grep babysit`).  If you do, please open an issue!

**Pull request merged**
