### PR TITLE
Remove all traces of utils.tar.gz

### PR DESCRIPTION
**Pull request by hakman**
With support for CoreOS gone, utis.tar.gz is not needed anywhere anymore. See also:
* https://github.com/kubernetes/kops/pull/8978
* https://github.com/kubernetes/kops/pull/9065

### CODE REVIEW

**Comment by johngmyers** [comment]
Does ContainerOS not need this either?

Please also remove from docs/aws-china.md

**Comment by hakman** [comment]
> Does ContainerOS not need this either?

ContainerOS has the binaries bundled, I did a quick test o GCP. No idea if there is a reference with the installed packages there.

**Comment by hakman** [comment]
Rebased after https://github.com/kubernetes/kops/pull/8922

**Pull request merged**
