### PR TITLE
Fix minor docs typos

### PR DESCRIPTION
**Pull request by JamesJJ**
Fixes some minor docs typos

### CODE REVIEW

**Comment by hakman** [comment]
Thanks for taking the time to send a PR for these.
Please sign the CLA so that we can accept the changes.

**Comment by JamesJJ** [comment]
> Thanks for taking the time to send a PR for these.
> Please sign the CLA so that we can accept the changes.

ok, I signed it

**Comment by hakman** [comment]
Perfect. Thanks again.
/lgtm
/approve

**Comment by JamesJJ** [comment]
> @JamesJJ: The following test **failed**, say `/retest` to rerun all failed tests:

/retest

(previous failure due to transient failure in curl connection?)

**Pull request merged**
