### PR TITLE
Add a v1.7.0 storage addon resource.

### LINKED ISSUE #3298: Wrong api version in addons/storage-aws.addons.k8s.io/v1.6.0.yaml
Then trying to create new cluster I see flowing error on master nodes:

```
(storage.k8s.io/v1beta1) does not match the expected API version (storage.k8s.io/v1)
```

Full log:

```
 docker[1630]: I0828 11:01:10.989964      95 addon.go:129] Applying update from "s3://state-store/kube-test.[omitted]//v1.6.0.yaml"
 docker[1630]: I0828 11:01:10.990005      95 s3fs.go:173] Reading file "s3://state-store/kube-test.[omitted]/addons/.yaml"
 docker[1630]: I0828 11:01:11.080461      95 apply.go:66] Running command: kubectl apply -f /tmp/channel344250621/manifest.yaml
 docker[1630]: I0828 11:01:11.426661      95 apply.go:69] error running kubectl apply -f /tmp/channel344250621/manifest.yaml
 docker[1630]: I0828 11:01:11.426684      95 apply.go:70] Error from server (BadRequest): error when creating "/tmp/channel344250621/in the data (storage.k8s.io/v1beta1) does not match the expected API version (storage.k8s.io/v1)
 docker[1630]: Error from server (BadRequest): error when creating "/tmp/channel344250621/manifest.yaml": the API version in the data ( match the expected API version (storage.k8s.io/v1)
 docker[1630]: Error: error updating "storage-aws.addons.k8s.io": error applying update from "storage-aws.addons.k8s.io/v1.6.0.yaml": error 
 docker[1630]: Usage:
 docker[1630]: channels apply channel [flags]
 docker[1630]: Flags:
 docker[1630]: -f, --filename stringSlice   Apply from a local file
 docker[1630]: --yes                    Apply update
 docker[1630]: Global Flags:
 docker[1630]: --alsologtostderr                  log to standard error as well as files
 docker[1630]: --config string                    config file (default is $HOME/.channels.yaml)
 docker[1630]: --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
 docker[1630]: --log_dir string                   If non-empty, write log files in this directory
 docker[1630]: --logtostderr                      log to standard error instead of files (default false)
 docker[1630]: --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
 docker[1630]: -v, --v Level                          log level for V logs (default 0)
 docker[1630]: --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
 docker[1630]: error updating "storage-aws.addons.k8s.io": error applying update from "storage-aws.addons.k8s.io/v1.6.0.yaml": error running 
 docker[1630]: I0828 11:01:11.436833       1 channels.go:50] apply channel output was: I0828 11:01:10.222741      95 addons.go:37] Loading addons m-state-store/kube-test.[omitted]/addons/bootstrap-channel.yaml"
 docker[1630]: I0828 11:01:10.620835      95 s3context.go:159] Found bucket "state-store" in region "us-east-1"
 docker[1630]: I0828 11:01:10.620883      95 s3fs.go:173] Reading file "s3://state-store/kube-test.[omitted]/addons/
 docker[1630]: I0828 11:01:10.969253      95 addons.go:112] Skipping version range "<1.6.0" that does not match current version 1.7.2
 docker[1630]: I0828 11:01:10.969309      95 addons.go:112] Skipping version range "<1.6.0" that does not match current version 1.7.2
 docker[1630]: NAME                                CURRENT        UPDATE
 docker[1630]: storage-aws.addons.k8s.io        -        1.6.0
 docker[1630]: I0828 11:01:10.989964      95 addon.go:129] Applying update from "s3://state-store/kube-test.[omitted]//v1.6.0.yaml"
 docker[1630]: I0828 11:01:10.990005      95 s3fs.go:173] Reading file "s3://state-store/kube-test.[omitted]/addons/.yaml"
 docker[1630]: I0828 11:01:11.080461      95 apply.go:66] Running command: kubectl apply -f /tmp/channel344250621/manifest.yaml
 docker[1630]: I0828 11:01:11.426661      95 apply.go:69] error running kubectl apply -f /tmp/channel344250621/manifest.yaml
 docker[1630]: I0828 11:01:11.426684      95 apply.go:70] Error from server (BadRequest): error when creating "/tmp/channel344250621/in the data (storage.k8s.io/v1beta1) does not match the expected API version (storage.k8s.io/v1)
 docker[1630]: Error from server (BadRequest): error when creating "/tmp/channel344250621/manifest.yaml": the API version in the data ( match the expected API version (storage.k8s.io/v1)
 docker[1630]: Error: error updating "storage-aws.addons.k8s.io": error applying update from "storage-aws.addons.k8s.io/v1.6.0.yaml": error 
 docker[1630]: Usage:
 docker[1630]: channels apply channel [flags]
 docker[1630]: Flags:
 docker[1630]: -f, --filename stringSlice   Apply from a local file
 docker[1630]: --yes                    Apply update
 docker[1630]: Global Flags:
 docker[1630]: --alsologtostderr                  log to standard error as well as files
 docker[1630]: --config string                    config file (default is $HOME/.channels.yaml)
 docker[1630]: --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
 docker[1630]: --log_dir string                   If non-empty, write log files in this directory
 docker[1630]: --logtostderr                      log to standard error instead of files (default false)
 docker[1630]: --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
 docker[1630]: -v, --v Level                          log level for V logs (default 0)
 docker[1630]: --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
 docker[1630]: error updating "storage-aws.addons.k8s.io": error applying update from "storage-aws.addons.k8s.io/v1.6.0.yaml": error running 
 docker[1630]: W0828 11:01:11.436884       1 kube_boot.go:149] error applying channel "s3://state-store/kube-test.[omitted]/addons/bootstrap-channel.yaml": error running channels: exit status 1
```

kops version 1.7.0
k8s version 1.7.2

Cluster was created with flowing command:
```
kops create cluster --zones us-west-2a ${NAME}
```

### PR DESCRIPTION
**Pull request by mikesplain**
Took a stab at fixing this for both!  Haven't tested it yet though.

Fixes #3298

### CODE REVIEW

**Comment by mikesplain** [comment]
I may have found an issue, marking WIP

**Comment by mikesplain** [comment]
When testing this I ran into https://github.com/kubernetes/kops/issues/3694, I don't think it's related.

**Comment by chrislovecnm** [comment]
You tested with 1.6 and 1.7?

**Comment by chrislovecnm** [comment]
K8s versions

**Comment by mikesplain** [comment]
@chrislovecnm Yep. Tested on v1.6.8 and v1.7.8

**Pull request merged**
