### PR TITLE
Upgrade DO CSI controller to 4.2.0

### LINKED ISSUE #14004: DigitalOcean CSI E2E Test Failures
/kind bug

the DigitalOcean e2e job has a few CSI StatefulSet test failures: 

https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico

The statefulset pods are failing to be created:

```
STEP: Creating statefulset ss in namespace statefulset-6052
Jul 18 21:16:18.031: INFO: Default storage class: "do-block-storage"
STEP: Saturating stateful set ss
Jul 18 21:16:18.132: INFO: Waiting for stateful pod at index 0 to enter Running
Jul 18 21:16:18.229: INFO: Waiting for pod ss-0 to enter Running - Ready=false, currently Pending - Ready=false
Jul 18 21:16:28.328: INFO: Waiting for pod ss-0 to enter Running - Ready=false, currently Pending - Ready=false
...
```

the [kube-scheduler logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-do-calico/1549135514714509312/artifacts/cluster-info/kube-system/kube-scheduler-10.106.0.3/logs.txt) report:

`I0718 21:16:18.099175      11 scheduler.go:351] "Unable to schedule pod; no fit; waiting" pod="statefulset-6052/ss-0" err="0/5 nodes are available: 5 pod has unbound immediate PersistentVolumeClaims. preemption: 0/5 nodes are available: 5 Preemption is not helpful for scheduling."`

and the [CSI Controller logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-do-calico/1549135514714509312/artifacts/cluster-info/kube-system/csi-do-controller-0/logs.txt) report:

`I0718 21:16:49.114169       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"statefulset-6052", Name:"datadir-ss-0", UID:"2010fb26-1eae-40fe-b4a0-36af33161d20", APIVersion:"v1", ResourceVersion:"15317", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "do-block-storage": rpc error: code = OutOfRange desc = invalid capacity range: required (1) can not be less than minimum supported volume size (1Gi)`

The e2e test [creates a volume claim template with a storage request](https://github.com/kubernetes/kubernetes/blob/b52705ae3edd5fa3ed5af472ab223c0a31111314/test/e2e/framework/statefulset/fixtures.go#L107) of literally `1` (byte).

For reference, the AWS equivalent test passes based with these [controller logs](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-cni-calico/1549171250700488704/artifacts/cluster-info/kube-system/ebs-csi-controller-7c54df765c-8mdjt/logs.txt):

```
I0718 23:36:23.449330       1 connection.go:184] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.ebs.csi.aws.com/zone":"ap-southeast-1a"}}],"requisite":[{"segments":{"topology.ebs.csi.aws.com/zone":"ap-southeast-1a"}}]},"capacity_range":{"required_bytes":1},"name":"pvc-c72f1ca3-65dd-4056-bfb5-5e765f3a72a9","parameters":{"csi.storage.k8s.io/pv/name":"pvc-c72f1ca3-65dd-4056-bfb5-5e765f3a72a9","csi.storage.k8s.io/pvc/name":"datadir-ss-0","csi.storage.k8s.io/pvc/namespace":"statefulset-5710","encrypted":"true","type":"gp3"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
...
I0718 23:36:26.815328       1 connection.go:186] GRPC response: {"volume":{"accessible_topology":[{"segments":{"topology.ebs.csi.aws.com/zone":"ap-southeast-1a"}}],"capacity_bytes":1073741824,"volume_id":"vol-0648af63ddb05af0c"}}
...
I0718 23:36:26.815872       1 controller.go:858] successfully created PV pvc-c72f1ca3-65dd-4056-bfb5-5e765f3a72a9 for PVC datadir-ss-0 and csi volume name vol-0648af63ddb05af0c
```

The `"required_bytes": 1` in the request and `"capacity_bytes":1073741824` (1GB) in the response seem to suggest that the AWS controller just uses the default minimum EBS volume size for claims that request fewer bytes than that. I'm wondering if the DO controller should do the same.

/cc @srikiz @timoreimann if you prefer to track this in the CSI driver repo, I'm happy to open one there.

### PR DESCRIPTION
**Pull request by rifelpet**
Fixes #14004

Sourced from https://github.com/digitalocean/csi-digitalocean/tree/master/deploy/kubernetes/releases/csi-digitalocean-v4.2.0

### CODE REVIEW

**Review by srikiz — APPROVED** [review]
LGTM !
Thank you for putting this change !

**Comment by hakman** [comment]
Failures are unrelated and should be fixed by https://github.com/kubernetes/test-infra/pull/26850.

**Comment by srikiz** [comment]
The errors here seem to be unrelated. I see `nfs-server` pod starting okay  - blob:https://prow.k8s.io/dba76ef4-99ea-496b-b518-2c5071fa10d9  but the mount failed.
```
[BeforeEach] [sig-storage] PersistentVolumes
  test/e2e/framework/framework.go:187
ï¿½[1mSTEPï¿½[0m: Creating a kubernetes client
Jul 19 05:33:41.243: INFO: >>> kubeConfig: /root/.kube/config
ï¿½[1mSTEPï¿½[0m: Building a namespace api object, basename pv
ï¿½[1mSTEPï¿½[0m: Waiting for a default service account to be provisioned in namespace
ï¿½[1mSTEPï¿½[0m: Waiting for kube-root-ca.crt to be provisioned in namespace
[BeforeEach] [sig-storage] PersistentVolumes
  test/e2e/storage/persistent_volumes.go:114
[BeforeEach] NFS
  test/e2e/storage/persistent_volumes.go:131
ï¿½[1mSTEPï¿½[0m: creating nfs-server pod
ï¿½[1mSTEPï¿½[0m: locating the "nfs-server" server pod
Jul 19 05:33:47.567: INFO: Running '/home/prow/go/src/k8s.io/kops/_rundir/9cf1adf4-0721-11ed-b09a-5ecaca227ace/kubectl --server=https://api.e2e-b284d3e83b-4c77c.test-cncf-do.k8s.io --kubeconfig=/root/.kube/config --namespace=pv-2101 logs nfs-server nfs-server'
Jul 19 05:33:47.762: INFO: stderr: ""
Jul 19 05:33:47.762: INFO: stdout: "Serving /exports\nrpcinfo: can't contact rpcbind: : RPC: Unable to receive; errno = Connection refused\nStarting rpcbind\nNFS started\n"
Jul 19 05:33:47.762: INFO: nfs server pod IP address: 100.110.136.80
```

```
Jul 19 05:41:05.072: INFO: At 2022-07-19 05:33:49 +0000 UTC - event for pvc-tester-79wxc: {kubelet 10.108.0.5} FailedMount: MountVolume.SetUp failed for volume "nfs-2d796" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 100.110.136.80:/exports /var/lib/kubelet/pods/b261f550-43a6-48e1-85fa-8d3a47015120/volumes/kubernetes.io~nfs/nfs-2d796
Output: mount: /var/lib/kubelet/pods/b261f550-43a6-48e1-85fa-8d3a47015120/volumes/kubernetes.io~nfs/nfs-2d796: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

**Pull request merged**
