### PR TITLE
Fix Sirupsen/logrus submodule path error

### PR DESCRIPTION
**Pull request by liranp**
Since the renaming of Sirupsen dependency to sirupsen (https://github.com/kubernetes/kops/commit/5905aa251d07dae2691b1ff1d48cfd91fe059f42) I'm getting the following error:

```
$ git submodule init
fatal: No url found for submodule path '_vendor/github.com/Sirupsen/logrus' in .gitmodules
```

### CODE REVIEW

**Comment by liranp** [comment]
CNCF Corporate CLA signed.

**Comment by chrislovecnm** [comment]
Your cla is not showing up. Are you using the correct username and email address with you git setup?

**Comment by liranp** [comment]
@chrislovecnm Yeah, not sure why it's not working. Trying to figure it out.

```
$ git config user.name
Liran Polak

$ git config user.email
liran@spotinst.com
```

**Comment by chrislovecnm** [comment]
You may want to email helpdesk@rt.linuxfoundation.org

**Comment by liranp** [comment]
@chrislovecnm Somehow it's working now.

**Comment by justinsb** [comment]
Closing and reopening to kick travis

**Pull request merged**
