### PR TITLE
Include terraform init command for initialising the AWS provider/pluging

### PR DESCRIPTION
**Pull request by eggsy84**
Submitting this PR in response to issue #3347

### CODE REVIEW

**Comment by eggsy84** [comment]
Have registered on CLA

**Comment by KashifSaadat** [comment]
Hey @eggsy84, thanks for the contribution!

The CLI docs file you've updated is actually auto-generated. Please could you update your PR and make the change here: https://github.com/kubernetes/kops/blob/master/cmd/kops/rollingupdatecluster.go#L51

You can then update the docs cli file by running `make gen-cli-docs`.

Thanks!

**Comment by chrislovecnm** [comment]
@eggsy84 did you register the CLA with the same GitHub user/email address that you pushed the SHA with?  Your CLA is not taking.

**Comment by eggsy84** [comment]
Hey @chrislovecnm I thought I did but I did register my organisation instead of personal - wonder if thats caused an issue?

**Comment by eggsy84** [comment]
Thanks @KashifSaadat I'll make those changes

**Comment by chrislovecnm** [comment]
@eggsy84 not certain.  I would probably email helpdesk@rt.linuxfoundation.org

**Comment by chrislovecnm** [comment]
Any word on the cla?

**Comment by eggsy84** [comment]
Hi both, I'll close this PR and re-submit from my org github account to ensure the CLA is in place.

**Pull request closed without merging**
