### PR TITLE
WIP scale-test: Testing

### PR DESCRIPTION
**Pull request by hakman**
/cc @hakuna-matatah @torredil @rifelpet

### CODE REVIEW

**Comment by torredil** [comment]
:(

```
Test started today at 6:36 AM error after 4h43m24s. ([more info](https://prow.k8s.io/spyglass/lens/metadata/iframe?req=%7B%22artifacts%22%3A%5B%22finished.json%22%2C%22podinfo.json%22%2C%22prowjob.json%22%2C%22started.json%22%5D%2C%22index%22%3A0%2C%22src%22%3A%22gs%2Fkubernetes-jenkins%2Fpr-logs%2Fpull%2Fkops%2F16240%2Fpresubmit-kops-aws-scale-amazonvpc-using-cl2%2F1745046713195827200%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16240/presubmit-kops-aws-scale-amazonvpc-using-cl2/1745046713195827200&lensIndex=0#))

Job execution failed: Pod got deleted unexpectedly
```

/test presubmit-kops-aws-scale-amazonvpc-using-cl2

**Comment by hakuna-matatah** [comment]
>Test started today at 6:36 AM error after 4h43m24s. ([more info](https://prow.k8s.io/spyglass/lens/metadata/iframe?req=%7B%22artifacts%22%3A%5B%22finished.json%22%2C%22podinfo.json%22%2C%22prowjob.json%22%2C%22started.json%22%5D%2C%22index%22%3A0%2C%22src%22%3A%22gs%2Fkubernetes-jenkins%2Fpr-logs%2Fpull%2Fkops%2F16240%2Fpresubmit-kops-aws-scale-amazonvpc-using-cl2%2F1745046713195827200%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/16240/presubmit-kops-aws-scale-amazonvpc-using-cl2/1745046713195827200&lensIndex=0#))

>Job execution failed: Pod got deleted unexpectedly

this issue is being tracked [here](https://github.com/kubernetes/test-infra/issues/31459)

**Comment by torredil** [comment]
@hakuna-matatah Thanks for the heads up 

/test presubmit-kops-aws-scale-amazonvpc-using-cl2

**Comment by hakman** [comment]
@hakuna-matatah can you do a PR for 30?

**Comment by hakuna-matatah** [comment]
> @hakuna-matatah can you do a PR for 30?

Yes, will do that.

**Pull request closed without merging**
