### PR TITLE
doc_fix: fixing update cluster command

### PR DESCRIPTION
**Pull request by swagftw**

### CODE REVIEW

**Review by hakman — APPROVED** [review]
/ok-to-test

**Comment by hakman** [comment]
Thanks @swagftw. Please sign the CLA to merge the PR.

**Comment by swagftw** [comment]
I also got deprecation warnings for `sshpublickey` create and delete command. But we can discuss those and I can make changes again to that :)

**Comment by swagftw** [comment]
@hakman EasyCLA Auth is done.. :)

**Pull request merged**
