### PR TITLE
Add option to create an internal load balancer for the bastion

### PR DESCRIPTION
**Pull request by dezmodue**
Attempt to address https://github.com/kubernetes/kops/issues/12147

### CODE REVIEW

**Comment by olemarkus** [comment]
Looks good to me in general. I am a bit uncertain if this is worth a new CLI flag though.

**Comment by dezmodue** [comment]
I don't mind either way - I can remove it if that's preferred

**Comment by olemarkus** [comment]
I suggest you remove it then. it can always be added later.

**Comment by dezmodue** [comment]
Removed the CLI flag as suggested @olemarkus

**Review by olemarkus — APPROVED** [review]

**Comment by dezmodue** [comment]
For what I can see the logs show that the job was unable to reach the terraform registry:

│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: could not connect to registry.terraform.io: Failed to
│ request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": net/http: TLS
│ handshake timeout

Am I reading the logs right? 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/12321/pull-kops-verify-terraform/1440983009762217984

**Comment by olemarkus** [comment]
Yeah. Terraform has some issues. All our PRs are blocked by this.

**Pull request merged**
