### PR TITLE
"Force" k8s 1.11.10 in stable channel

### PR DESCRIPTION
**Pull request by justinsb**
Bringing this from the alpha channel (#7423) to the stable channel.

As discussed in office hours, and from the notes on #7423:

Even 1.11 and 1.12 are technically unsupported, but this should get users
off the very oldest unsupported versions of k8s.

Users that want to stay on those versions can pass the
KOPS_RUN_OBSOLETE_VERSION env var.

### CODE REVIEW

**Comment by justinsb** [comment]
This required updating a lot of tests that were using really old k8s versions, that is in the final commit.

This also includes #7594 and #7595 which I'm hoping will merge shortly (and I'll rebase if github doesn't automatically prune it down)

**Comment by rifelpet** [comment]
here we go
/lgtm

**Pull request merged**
