### PR TITLE
Only list the latest coreos stable image

### PR DESCRIPTION
**Pull request by gianrubio**
It's a bit confused for the users to "choose" the right ami

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2689)

### CODE REVIEW

**Comment by WillemMali** [comment]
`/lgtm` but not a contributor.

I verified the account ID stays the same and I like this addition because it's more specific in a useful way ("this is how you find the latest image for X") and is transparent (to me) how to make it less specific ("list all images").

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
/lgtm

Waiting on CI

**Comment by justinsb** [comment]
I like the `"Name=name,Values=CoreOS-stable*"` filter, but it looks like the order is not guaranteed so `[-1]` does not give the latest image.  It currently gives me `CoreOS-stable-1235.9.0-hvm`, but `CoreOS-stable-1298.5.0-hvm` is available.

**Comment by gianrubio** [comment]
Indeed, it's not sorting. What about this filter

```
$ aws ec2 describe-images --region=us-east-1 --owner=595879546273 --filters \
"Name=virtualization-type,Values=hvm" "Name=name,Values=CoreOS-stable*" \
 --query 'sort_by(Images,&CreationDate)[-1].{id:ImageLocation}'

{
    "id": "595879546273/CoreOS-stable-1353.8.0-hvm"
}
```

**Comment by chrislovecnm** [comment]
@justinsb I am going to merge, if we need more tweaks we can iterate.

**Pull request merged**
