### PR TITLE
Migrate to registry.k8s.io

### LINKED ISSUE #13365: migrate to registry.k8s.io
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**

Migrate future releases of kOps to `registry.k8s.io` which is a replacement of `k8s.gcr.io` (and currently for the moment redirect to `k8s.gcr.io`)

**2. Feel free to provide a design supporting your feature request.**

/kind feature
/sig k8s-infra

### PR DESCRIPTION
**Pull request by hakman**
Fixes #13365

/cc @justinsb @olemarkus
/hold for feedback

### CODE REVIEW

**Comment by hakman** [comment]
Looks ready now. @justinsb could you take a look?
/hold cancel

**Comment by ameukam** [comment]
@hakman is the revert easy in case we see some unexpected behaviors on the new endpoint ?

**Comment by hakman** [comment]
@ameukam Revert should be pretty easy.

**Comment by ameukam** [comment]
> @ameukam Do we have a plan to make the new endpoint GA?

We are currently working on make it GA in the incoming weeks. In his current shape, it's usable for the community. We are more focused on scalability.

**Comment by hakman** [comment]
> > @ameukam Do we have a plan to make the new endpoint GA?
> 
> We are currently working on make it GA in the incoming weeks. In his current shape, it's usable for the community. We are more focused on scalability.

Sounds good @ameukam. As long as it's GA in the next few months I don't see any issues.

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
