### PR TITLE
Bump retries up to ~6m for a request

### LINKED ISSUE #900: Retry 500s
See [1389](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1389/) (failed teardown) and [1390](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-kops-aws/1390/) (failed cluster up).

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes #900

### CODE REVIEW

**Comment by zmerlynn** [comment]
In an ideal world, this gets in before https://github.com/kubernetes/test-infra/pull/1015, but it's not the end of the world (I suspect the PR builder isn't actually as thundering-herd as I was testing).

**Comment by chrislovecnm** [comment]
`const ClientMaxRetries = 13` ... omg ...

**Comment by chrislovecnm** [comment]
LGTM ... waiting on build

**Comment by zmerlynn** [comment]
The trap is green, merging!

**Comment by justinsb** [comment]
Thanks @zmerlynn  :-)

**Pull request merged**
