### PR TITLE
Update alpha channel k8s 1.16 to 1.16.15 and Ubuntu image to latest available

### PR DESCRIPTION
**Pull request by MoShitrit**
https://github.com/kubernetes/kubernetes/releases/tag/v1.16.15

### CODE REVIEW

**Comment by hakman** [comment]
@MoShitrit could you also update the ubuntu image?

**Comment by MoShitrit** [comment]
> @MoShitrit could you also update the ubuntu image?

Sure @hakman , 
So [1.16 image](https://github.com/kubernetes/kops/blob/master/channels/alpha#L44) should be changed to this as well? 
`099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200716`

**Comment by hakman** [comment]
Meant that ubuntu has a newer image which we should update for 1.18 :).

**Pull request merged**
