### PR TITLE
Automated cherry pick of #16363: Update Calico to v3.27.3

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #16363 on release-1.29.

#16363: Update Calico to v3.27.3

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by justinsb** [comment]
Looks good, but have we reached a conclusion on #16363 ?

**Comment by hakman** [comment]
> Looks good, but have we reached a conclusion on #16363 ?

@justinsb https://github.com/kubernetes/kops/pull/16363 is unrelated to the failure.
See: https://github.com/kubernetes/kops/pull/16363#issuecomment-2031886140.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
