### PR TITLE
cloudbuild: Try uploading our binaries to the staging bucket also

### PR DESCRIPTION
**Pull request by justinsb**
Adding build & upload of our binaries to the staging bucket, from the
trusted builder.

### CODE REVIEW

**Comment by justinsb** [comment]
cc @rifelpet .... honestly I don't know if this is going to work, but I don't know of a better way than to actually just try it!

**Comment by rifelpet** [comment]
Agreed! The kops-controller image is successfully getting pushed:

https://console.cloud.google.com/gcr/images/k8s-staging-kops/GLOBAL/kops-controller?gcrImageListsize=30

but because [we default to the KOPS_CONTROLLER_TAG variable if it is set](https://github.com/kubernetes/kops/blob/6b4b00395470b2488a4c0bb33c361461ea38f80a/tools/get_workspace_status.sh#L74-L77) and the [Makefile has it hardcoded](https://github.com/kubernetes/kops/blob/6b4b00395470b2488a4c0bb33c361461ea38f80a/Makefile#L61), we're constantly overwriting the same `1.18.0-alpha.2` image tag rather than the [VERSION tag we try to pass](https://github.com/kubernetes/kops/blob/6b4b00395470b2488a4c0bb33c361461ea38f80a/cloudbuild.yaml#L10). I wasn't sure the best way to solve that. Perhaps set `KOPS_CONTROLLER_TAG=$_GIT_TAG` in cloudbuild.yaml and have the Makefile check for a variable before assigning its current value as default?

Regardless,
/lgtm

**Comment by rifelpet** [comment]
It looks like bazel failed, possibly an oom issue or maybe theres a timeout on the job?

```
Step #1: [501 / 720] GoCompilePkg vendor/google.golang.org/api/compute/v0.beta/windows_amd64_pure_stripped/go_default_library%/k8s.io/kops/vendor/google.golang.org/api/compute/v0.beta.a; 9s linux-sandbox
Step #1: [601 / 720] GoCompilePkg vendor/google.golang.org/api/compute/v0.alpha/windows_amd64_pure_stripped/go_default_library%/k8s.io/kops/vendor/google.golang.org/api/compute/v0.alpha.a; 11s linux-sandbox
Step #1:
Step #1: Bazel caught terminate signal; shutting down.
Step #1:
Step #1: ERROR: build interrupted
Step #1: INFO: Elapsed time: 248.538s, Critical Path: 58.31s
Step #1: INFO: 640 processes: 640 linux-sandbox.
Step #1: FAILED: Build did NOT complete successfully
Step #1: FAILED: Build did NOT complete successfully
Step #1: make: *** [bazel-crossbuild-kops] Error 8
Step #1: Makefile:656: recipe for target 'bazel-crossbuild-kops' failed
TIMEOUT
ERROR: context deadline exceeded
```

side note, it'd be great if the `builder` image surfaced these logs into the prow job output rather than having to poke around the GCS bucket

**Comment by justinsb** [comment]
Thanks @rifelpet 

* I'm not entirely sure how best to avoid overwriting every time either.  It's difficult when using dockerhub because then the versions need to match, and so we'd need to inject versions into the manifests.  Maybe we pursue the option of using KOPS_BASE_URL more broadly - it's _supposed_ to be the case that if you use KOPS_BASE_URL you shouldn't pull from dockerhub any more, so the dockerhub version can just be a fallback.

* Good news on the log front; if you click into the prow results, there's an artifacts link at the top, then click `artifacts`, then `build.log` - that's the GCB log I think.

* The log suggests a timeout, and it does look like the job itself took 22m.  We should probably look at using a bigger instance type than the default (the default is pretty small).

**Comment by justinsb** [comment]
It might be as simple as adding a `machineType` to our options block: https://cloud.google.com/cloud-build/docs/build-config#options

**Comment by rifelpet** [comment]
Trying out machineType here:  https://github.com/kubernetes/kops/pull/8520

A bit strange that the default timeout is 10m but our job timed out after 22m: https://cloud.google.com/cloud-build/docs/build-config#timeout_2

**Comment by rifelpet** [comment]
Looks like upping the machineType worked:

```
gsutil ls -lr gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/
gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/:

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/darwin/:

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/darwin/amd64/:
 123032760  2020-02-11T02:18:18Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/darwin/amd64/kops
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/darwin/amd64/kops.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/darwin/amd64/kops.sha256

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/:
  28227273  2020-02-11T02:18:17Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/dns-controller.tar.gz
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/dns-controller.tar.gz.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/dns-controller.tar.gz.sha256
  26723192  2020-02-11T02:18:17Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/kops-controller.tar.gz
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/kops-controller.tar.gz.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/kops-controller.tar.gz.sha256
 179935569  2020-02-11T02:18:19Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/protokube.tar.gz
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/protokube.tar.gz.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/images/protokube.tar.gz.sha256

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/:

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/:
 124370057  2020-02-11T02:18:18Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/kops
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/kops.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/kops.sha256
  78001509  2020-02-11T02:18:18Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/nodeup
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/nodeup.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/nodeup.sha256
    554287  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/utils.tar.gz
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/utils.tar.gz.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/linux/amd64/utils.tar.gz.sha256

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/windows/:

gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/windows/amd64/:
 123886080  2020-02-11T02:18:18Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/windows/amd64/kops.exe
        41  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/windows/amd64/kops.exe.sha1
        65  2020-02-11T02:18:16Z  gs://k8s-staging-kops/kops/releases/v20200211-1.18.0-alpha.2-45-g3166d31da/windows/amd64/kops.exe.sha256
TOTAL: 24 objects, 684731575 bytes (653.01 MiB)
```

**Comment by justinsb** [comment]
Awesome - thanks @rifelpet ... and we do have a 1200 second timeout on line 2 :-)

**Pull request merged**
