### PR TITLE
AssetBuilder does not use Phase; removing

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Follow on with nits to #3254

**Comment by chrislovecnm** [comment]
We use phase in the builder 

    if a.Phase == "assets" && file.CanonicalFileURL

**Comment by justinsb** [comment]
In a temporal warp, this depends on #4100

**Comment by chrislovecnm** [comment]
/hold 

see comment on dependant PR, this breaks a use case that we have.

**Pull request closed without merging**
