### PR TITLE
toolbox dump: include AWS route table objects

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
This "can't" be the fix, but #16072 passed with this included.  I think the cloud-init change is more likely to be the cause (though that doesn't make a lot of sense), but this can serve as our "control"

/test pull-kops-e2e-cni-calico-ipv6

**Comment by justinsb** [comment]
/wip so that it doesn't merge, I don't think it's particularly time-critical

**Comment by justinsb** [comment]
This turned out not to be related, but I think we should be dumping all these objects.  Debating whether we should just default the Dump function, but as we still have to set object I though a bit of repetition here wasn't the end of the world.

**Review by hakman — APPROVED** [review]

**Pull request merged**
