### PR TITLE
Update machine_types.go to support T3 family

### LINKED ISSUE #5680: Add support of new T3 family
Feature request to add support of newly launched T3 family. [aws-blog-link](https://aws.amazon.com/blogs/aws/new-t3-instances-burstable-cost-effective-performance/)

### PR DESCRIPTION
**Pull request by wanghanlin**
close #5680 
cpu baseline ref https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-credits-baseline-concepts.html

### CODE REVIEW

**Comment by Globegitter** [comment]
I think it would be really amazing if there could be a cherry-pick for kops 1.10.0 /  a kops 1.10.1 release - it seems like a small thing but I think a lot of people would be happy to get the t2 unlimited functionality as well as the money savings.

**Comment by mitpwd** [comment]
KOPS should not hardcode any AWS instance types in the first place.

**Comment by justinsb** [comment]
You're right @mitpwd except that there isn't a convenient API for instance types.  I think @mikesplain and @sethpollack are actually working on putting a file somewhere where all of kubernetes-on-aws components could consume it (i.e. creating an API for instance type attributes).

**Comment by tomaszkiewicz** [comment]
> You're right @mitpwd except that there isn't a convenient API for instance types. I think @mikesplain and @sethpollack are actually working on putting a file somewhere where all of kubernetes-on-aws components could consume it (i.e. creating an API for instance type attributes).

I've searched aws-sdk-go for new instance types and it looks like there's a file with API model:

https://github.com/aws/aws-sdk-go/blob/master/models/apis/ec2/2016-11-15/api-2.json

The file seems to be used to generate API with the generator included in the repo:

https://github.com/aws/aws-sdk-go/blob/f26268b77ea9619d95b1d04b6f3e3c5a03b61110/private/model/cli/gen-api/main.go

And the file is updated frequently, so probably it's very up-to-date. When you use JSON path .shapes.InstanceType.enum you can extract all possible instance types :)

I don't know how kops is up-to-date with dependency on aws-sdk-go but maybe it's a good point to start a discussion :)

Best regards

Łukasz Tomaszkiewicz

**Pull request merged**
