### PR TITLE
Expose metrics port when PrometheusMetricsEnabled set to true in Calico

### PR DESCRIPTION
**Pull request by avdhoot**
Problem:
Currently `PrometheusMetricsEnabled` only start servings metrics on `PrometheusMetricsPort` . But Prometheus can not scrape it. This PR will expose that service so Prometheus can scrape it. 
Sample config for Prometheus-operator
```apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: calico-node
    monitoredBy: prometheus-infra
  name: calico-node
  namespace: kube-system
spec:
  podMetricsEndpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: calico-node

### CODE REVIEW

**Comment by hakman** [comment]
@avdhoot In the Calico docs I see that the ports are exposed with a service. Should this be added here also?
https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics#creating-a-service-to-expose-felix-metrics

**Comment by avdhoot** [comment]
@hakman we are using Prometheus [pod](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod)  discovery mechanism. I do not think we should create service only to expose metrics.

**Comment by hakman** [comment]
Thanks for the explanation and the contribution. I think will be appreciated by users.
/lgtm
/approve

**Pull request merged**
