### PR TITLE
Cherry pick of #6420 onto release-1.14

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #6420

### CODE REVIEW

**Comment by justinsb** [comment]
This feels optional, but cherry-picking because otherwise I am worried we'll get conflicts on future PRs which we do require.

**Comment by rdrgmnzs** [comment]
@justinsb can you rebase this when you have some time.

**Comment by mikesplain** [comment]
Closing this since this was included in https://github.com/kubernetes/kops/pull/6937 since it's required for https://github.com/kubernetes/kops/pull/6878

/cole

**Pull request closed without merging**
