### PR TITLE
Update document for GPU support

### PR DESCRIPTION
**Pull request by yujunz**
The current guide is created two years ago and the content is out
of date.

### CODE REVIEW

**Comment by KashifSaadat** [comment]
Thanks @yujunz !

/area documentation
/ok-to-test
/lgtm

**Comment by yujunz** [comment]
Thanks @KashifSaadat . Who should I ask for the `approved` label?

**Comment by KashifSaadat** [comment]
Sorry missed that!

/approve

**Comment by yujunz** [comment]
Is the failure related to this patch? @KashifSaadat 

/retest

**Comment by KashifSaadat** [comment]
@yujunz there is a failure with the e2e tests unrelated to your PR, it's currently affecting all PRs it seems

**Pull request merged**
