### PR TITLE
fixing the service name for demo-app-v2

### PR DESCRIPTION
**Pull request by ravicm**

### CODE REVIEW

**Comment by andrewsykim** [comment]
/ok-to test 

please sign the CLA :)

**Comment by chrisz100** [comment]
something was missing there...
 /ok-to-test 

CLA is missing still. @ravicm can you sign that please?

**Comment by chrisz100** [comment]
something was missing there...
 /ok-to-test 

CLA is missing still. @ravicm can you sign that please?

**Comment by chrisz100** [comment]
something was missing there...

/ok-to-test 

CLA is missing still. @ravicm can you sign that please?

**Pull request closed without merging**
