### PR TITLE
Add a BAZEL_CONFIG Makefile arg to bazel commands

### PR DESCRIPTION
**Pull request by fejta**
Intend to change CI jobs from `make bazel-build` to `make bazel-build BAZEL_CONFIG=--config=ci`

https://github.com/kubernetes/test-infra/blob/4db0b31df68e72c01edfe6eeb450d6cccd4f1615/config/jobs/kubernetes/kops/kops-config.yaml#L22-L23

Note that `bazel test --config=ci` is required (`bazel --config=ci test # unrecognized flag`)

### CODE REVIEW

**Comment by fejta** [comment]
Ready for review!

Do ya'll know about https://gubernator.k8s.io/pr? (or https://gubernator.k8s.io/pr/USERNAME) It gives you a filter of PRs waiting for your response (aka its your turn to review someone's PR and/or its your turn to address review comments on your own PR)

You probably already do, but if not its super duper handy!

**Comment by rifelpet** [comment]
Thanks!
/lgtm

**Comment by justinsb** [comment]
Thanks @fejta 

/approve
/lgtm

**Pull request merged**
