### PR TITLE
Use github.com/go-viper/mapstructure/v2

### PR DESCRIPTION
**Pull request by ameukam**
Update mapstructure with a maintained fork.

See:
  - https://github.com/mitchellh/mapstructure/issues/349

### CODE REVIEW

**Comment by hakman** [comment]
Great success @ameukam! 😄 
/lgtm
/approve

**Comment by ameukam** [comment]
@hakman I think we need figure out remaining jobs (mostly presubmits/periodics for upgrades tests) post kubecon.

**Pull request merged**
