### PR TITLE
Upgrade bazel gazelle

### PR DESCRIPTION
**Pull request by mikesplain**
We haven't upgraded the vendored version of bazel, it turns out. This fixes that and a few other inconsistencies.

### CODE REVIEW

**Comment by justinsb** [comment]
I've learned that the trick is to turn off bazel's protobuf magic, in WORKSPACE:

```
+# gazelle:prefix k8s.io/kops
+# gazelle:proto disable_global
 gazelle(
     name = "gazelle",
     command = "fix",
     external = "vendored",
-    prefix = "k8s.io/kops",
 )
```

That means that it won't use the internal versions of the protobuf libraries, but will instead use the versions in vendor, which means the build is more compatible with `go build`.

I think with that this PR should work!

**Comment by mikesplain** [comment]
ooOOoo! Great find @justinsb! Thanks for that. Pushing a fix with that now.

**Comment by justinsb** [comment]
Thanks @mikesplain !

/approve
/lgtm

**Pull request merged**
