### PR TITLE
WIP Support IPv6 in AWS VPC CNI

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by rifelpet** [comment]
The dns-controller pod logs show that it correctly updated the AAAA api dns record but `validate cluster` timed out waiting for the ipv4 placeholder IP to be updated, and `delete cluster` output shows the A record being deleted as well:

```
route53-record		api.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.									ZEMLNXIIWQ0RV/A/api.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.
route53-record		api.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.									ZEMLNXIIWQ0RV/AAAA/api.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.
route53-record		api.internal.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.								ZEMLNXIIWQ0RV/AAAA/api.internal.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.
route53-record		kops-controller.internal.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.						ZEMLNXIIWQ0RV/AAAA/kops-controller.internal.e2e-09c66f4ca2-eb1ce.test-cncf-aws.k8s.io.
```

**Comment by johngmyers** [comment]
The daemonset pod refused to start because it didn't like the combination of environment variable settings.

**Comment by johngmyers** [comment]
```
{"level":"error","ts":"2021-11-01T04:56:43.777Z","caller":"entrypoint.sh","msg":"Setting WARM_PREFIX_TARGET = 0 is not supported while WARM_IP_TARGET/MINIMUM_IP_TARGET is not set. Please configure either one of the WARM_{PREFIX/IP}_TARGET or MINIMUM_IP_TARGET env variables"}
```

**Comment by johngmyers** [comment]
The pull-kops-e2e-ipv6-amazonvpc job is failing due to a panic when cleaning up from a previous failed run. It looks like the deployer's dumplogs panics on missing files. @rifelpet this looks like a recent change of yours.

The pull-kops-e2e-ipv6-amazonvpc-irsa job appears to be failing due to a kube-proxy regression caused by #12664. Or it could be something else which is causing aws-node to exit with an error.

My local test cluster, which is on Ubuntu instead of Debian 11 and uses k8s 1.22.2, brings up more things. But the service network `fd00:5e4f:ce::` isn't routing.

**Comment by rifelpet** [comment]
The kubetest2 and kube-proxy issues should be fixed in https://github.com/kubernetes/kops/pull/12668 and https://github.com/kubernetes/kops/pull/12667 respectively.

**Comment by johngmyers** [comment]
...and I'll have to try Debian 11 in my next local test cluster.

**Comment by johngmyers** [comment]
It's assigning IPv4 `podIP`s.

**Comment by johngmyers** [comment]
Ah, IPv6 support was added in the 1.10 branch.

**Comment by johngmyers** [comment]
Filed aws/amazon-vpc-cni-k8s#1725 on the IPv4 failure.

The IPv6 test's ipamd looks okay, but the node doesn't think the CNI initialized. I need to track down where that's supposed to happen.

**Comment by johngmyers** [comment]
For IPv6, GRPC health probes to 127.0.0.1:50051 are somehow failing.

**Comment by johngmyers** [comment]
In the IPv6 case, the `aws-node` pod is hanging on this block of code, between starting ipamd and starting the CNI plugin:

```
#NodeIP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
get_node_primary_v4_address() {
    while :
    do
        NODE_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
        if [[ "${NODE_IP}" != "" ]]; then
            return 0
        fi
        # We sleep for 1 second between each retry
        sleep 1
    done
}
```

The curl to the metadata is failing with:

```
sh-4.2# curl -v http://169.254.169.254/latest/meta-data/local-ipv4
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/local-ipv4 HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Date: Sat, 06 Nov 2021 01:00:52 GMT
< Server: EC2ws
< Connection: close
< Content-Type: text/plain
< 
* Closing connection 0
```

This also fails when run from outside the container. Maybe it's an IMDSv2 issue?

**Comment by johngmyers** [comment]
This is aws/amazon-vpc-cni-k8s#1727

**Comment by hakman** [comment]
Good news :)
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.10.0

**Comment by johngmyers** [comment]
That version of AWS VPC CNI is busted on instances with IMDSv2 enabled. Reference issue above.

With my testing so far, it is not routing Kubernetes services in IPv6. I'll have to cross-check the IAM requirements.

**Comment by hakman** [comment]
That is quite sad, but I guess we can hack kOps to not enable IMDSv2, at least to see that it works.

**Comment by johngmyers** [comment]
I'm testing with an image I compiled with a cherrypicked fix.

**Comment by MoShitrit** [comment]
Hey guys! @hakman @johngmyers by looking at the progress here, I suppose we should hold off with bumping the AWS CNI version for now?

**Comment by johngmyers** [comment]
Yes, AWS VPC CNI 1.10.0 is DOA.

**Comment by johngmyers** [comment]
AWS VPC CNI v1.10.1 has a fix for the IMDSv2 bug. We can proceed with bumping it to that version.

**Comment by johngmyers** [comment]
Filed aws/amazon-vpc-cni-k8s#1750

**Pull request closed without merging**
