### PR TITLE
[Unit Tests] Add unit tests for create_kubecfg file

### PR DESCRIPTION
**Pull request by srikiz**
Hi - Please find the first pull request for KOPS.
I added a new unit test file for testing building kube config file for different scenarios - A public DNS cluster, gossip cluster, a cluster with no master public name etc.

Please have a look and let me know if you have any questions.

### CODE REVIEW

**Comment by srikiz** [comment]
/help Not sure why the Travis CI is failing. Can anyone help?

**Comment by mikesplain** [comment]
Hi @srikiz, since you made a change you'll need to run `make bazel-gazelle` to regenerate bazel's buildfiles. Let me know if you need help with that!

**Comment by mikesplain** [comment]
So we need to make those outputs a bit better and I've removed this test in travis: https://github.com/kubernetes/kops/pull/6841

**Comment by srikiz** [comment]
Thanks @mikesplain - That went through well. It looks like the pull-kops-verify-gofmt is failing now. Can you please suggest how to go about on this issue.

**Comment by mikesplain** [comment]
That should be fixed via `make gofmt`. Checkin the results and you should be good to go.

**Comment by chrisz100** [comment]
/lgtm 
/approve

Great that you have motivation to work on the test coverage! Love that, keep it up :-)

**Pull request merged**
