### PR TITLE
Improve Addon Update Check

### PR DESCRIPTION
**Pull request by granular-ryanbonham**
Hash Manifest for Addons and compare hashes to ensure we pickup any manifest changes.

### CODE REVIEW

**Comment by rifelpet** [comment]
It sounds like this will address #5697 and its related issues.

**Comment by OrlinVasilev** [comment]
is there a workaround for this one until that is released?

**Comment by mikesplain** [comment]
This looks pretty good, I need to take some more time to read through it and I'd like to get @justinsb's take on it since he's more in tune with the intricacies of addons.  Hashing the manifest is a great solution and I look forward to getting this in.

That said, I do think we should hold off on putting this in 1.12.  In theory we should be rolling 1.13 and 1.14 soon once 1.12 is released. At this point, I think we should only be cherry picking critical fixes in so we can get 1.12 cut (maybe even this week?).  I'm going to label this as a cherry pick and 1.13 for now.

/assign @justinsb

**Comment by granular-ryanbonham** [comment]
Justin and I discussed a change to this last night. I have some rework to do. marking back as WIP for now.

**Comment by granular-ryanbonham** [comment]
@justinsb  This is ready for you to look over again.

**Comment by mikesplain** [comment]
This looks really good! Thanks for all the hard work @granular-ryanbonham! Would you mind squashing your commits a bit? They don't all need to disappear but I bet you could clean it up a little to make future merges a little easier?

**Comment by granular-ryanbonham** [comment]
/close
Closing in favor of https://github.com/kubernetes/kops/pull/7133

**Pull request closed without merging**
