### PR TITLE
[WIP] - Update Lyft CNI Default to 0.6.3

### PR DESCRIPTION
**Pull request by gjtempleton**
Marking as WIP whilst double checking the new version internally.

Brings in a number of Lyft CNI improvements:

* [Handling unavailability of AWS limits](https://github.com/lyft/cni-ipvlan-vpc-k8s/pull/80)
* [Garbage collection of links and IPTables rules](https://github.com/lyft/cni-ipvlan-vpc-k8s/pull/83)
* [Improved bulk allocation](https://github.com/lyft/cni-ipvlan-vpc-k8s/pull/84)

### CODE REVIEW

**Comment by hakman** [comment]
@gjtempleton maybe when you get this figured out you could help me and @rifelpet to make the periodic e2e work.

**Comment by gjtempleton** [comment]
Looks like this'll require a change to the CNI config file as well. We're still testing exactly what changes are required.

See https://github.com/lyft/cni-ipvlan-vpc-k8s/pull/85

**Comment by gjtempleton** [comment]
More complicated than I thought unfortunately, this'll require a minimum k8s version of 1.16 as per: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#changed-1

I'll do some more work on adding some k8s version based logic to allow this.

**Comment by hakman** [comment]
@gjtempleton If you need any help with this, please let me know.

**Pull request closed without merging**
