### PR TITLE
Remove Zone from spec field

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
Issue: #14710 
Hello, I am a beginner and I am trying to slove good first issue. This pr is about letting cloud provide decide the zone instead of user. So i simply remove zone from the spec field. Lat me know if further changes required.

### CODE REVIEW

**Comment by Sajiyah-Salat** [comment]
why my test failed? can anyone help me pass my test?

**Comment by olemarkus** [comment]
Hey @Sajiyah-Salat. The change you have made fixes the test, but doesn't implement the change. So now you need to start looking at the code :)

**Comment by Sajiyah-Salat** [comment]
I got your point but I am a beginner. So looking in the code base will be a hard time on me.

**Comment by olemarkus** [comment]
The references issue contains quite a few clues. I'd look at the code mentioned there and understand how it works.

**Comment by Sajiyah-Salat** [comment]
I will try to understand the same

**Comment by Sajiyah-Salat** [comment]
Hello @olemarkus any updates? have you look in a code?

**Comment by olemarkus** [comment]
Hi. This is an exercise for you as contributor to this feature :)

**Comment by Sajiyah-Salat** [comment]
Ohk great, can you give some details about how can I start my work?

**Pull request closed without merging**
