### PR TITLE
Switch to golang 1.11.5

### PR DESCRIPTION
**Pull request by justinsb**
For cherry-picking to 1.13

https://github.com/kubernetes/kubernetes/blob/release-1.13/build/build-image/cross/Dockerfile

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
@justinsb we’ll need to remove the 1.10 tests and run gofmt against the existing code base to deal with the formatting changes that were introduced in 1.11

**Comment by justinsb** [comment]
Working on fixing the gofmt test job, it's currently locked on a particular go version

**Comment by justinsb** [comment]
pull-kops-verify-gofmt job change was merged upstream, so...

/retest

**Comment by rdrgmnzs** [comment]
Just food for thought, would it be more maintainable to install Bazel in the Travis image using before_install like in https://github.com/bazelbuild/rules_go/blob/master/.travis.yml instead of having a separate CI test for it instead?

**Comment by justinsb** [comment]
@rdrgmnzs I did think about it, but it's pretty slow to download bazel every time, and I think generally I'd rather move testing _out_ of travis, and into prow.  I can see where we end with is that travis is primarily testing that kops itself builds on osx & linux (& windows?), on multiple go versions.  That's much harder to do in prow.

**Comment by rdrgmnzs** [comment]
Makes sense, thanks @justinsb !

/lgtm

**Pull request merged**
