### PR TITLE
Move net mode log after it is known in create

### LINKED ISSUE #4293: "networking mode=" log message in `create cluster` doesn't shows default kubenet
As in the title, `networking mode` is logged before it's set based on `networking` flag.

### PR DESCRIPTION
**Pull request by nebril**
fixes #4293

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/approve

thanks, @mikesplain - you tracking the number of reviews?

**Comment by mikesplain** [comment]
@chrislovecnm Certainly! Easy enough to figure out with filters.

**Pull request merged**
