### PR TITLE
Update calico manifest version

### PR DESCRIPTION
**Pull request by justinsb**
By doing this, we can update existing kops clusters also.

cc @heschlie

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1857)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/lgtm

Dumb question of the year ... wth is 2.0.2 in the manifest??

**Comment by heschlie** [comment]
@justinsb this LGTM, but I am unsure as to how this helps update existing clusters (mostly just not sure how this all ties together) will this somehow alert existing clusters to trigger an update when they do a cluster upgrade the next time being there is a version difference?

**Comment by chrislovecnm** [comment]
@heschlie since we are running daemonsets I wonder about the upgrade as well.   But this is the versioning that we should use regardless.  With a rolling update this would cause an upgrade to fire off regardless.

**Pull request merged**
