### PR TITLE
LBC has to run on the control plane, so set replicas accordingly

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by johngmyers** [comment]
Any particular reason we shouldn't deploy on worker nodes if using IRSA?

(And I noticed that `deployOnWorkersIfExternalPermissons` misspells "permissions".)

**Comment by olemarkus** [comment]
The problem is that LBC without IMDS need `--vpc-id` specified. And it is really tricky to get the actual VPC ID into the templates. I have asked LBC if it is possible to use tag-based discovery of VPC as well, like they do for subnets.

**Pull request merged**
