### PR TITLE
Fix -ldflags incompatibility in go1.10

### LINKED ISSUE #4491: Failed to propagate VERSION environment variable to protokube
1. What `kops` version are you running? The command `kops version`, will display
 this information.

8d5da313af16a4374199faf983f9742b7d72abfd
Version 1.7.0

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

3. What cloud provider are you using?
AWS

4. What commands did you run?  What is the simplest way to reproduce this issue?

```
time make kops-install upload S3_BUCKET=s3://${S3_BUCKET_NAME} VERSION=dev; echo $?
kops -v10 create cluster --zones us-west-1a --networking amazon-vpc-routed-eni  --kubernetes-version 1.8.0 name.k8s.local
kops update cluster name.k8s.local —yes
```

5. What happened after the commands executed?
protokube gets downloaded correctly from S3 and imported to docker.
However it fails to start on all nodes because its tagged correctly with `dev` but the system is trying to spin up version 1.7.0 for some reason.

```
Feb 22 01:23:37 ip-172-20-57-24 dockerd[1389]: time="2018-02-22T01:23:37.934691720Z" level=error msg="Handler for POST /v1.26/containers/create returned error: No such image: protokube:1.7.0"
Feb 22 01:23:37 ip-172-20-57-24 docker[17766]: Unable to find image 'protokube:1.7.0' locally
Feb 22 01:23:38 ip-172-20-57-24 dockerd[1389]: time="2018-02-22T01:23:38.747212111Z" level=error msg="Handler for POST /v1.26/images/create returned error: repository protokube not found: does not exist or no pull access"
Feb 22 01:23:38 ip-172-20-57-24 systemd[1]: protokube.service: main process exited, code=exited, status=125/n/a
```
```
$ sudo docker images
REPOSITORY                                                    TAG                  IMAGE ID            CREATED             SIZE
protokube                                                     dev                  ce7b8cdb68ea        7 hours ago         273 MB

```

6. What did you expect to happen?
Cluster should start normally.

9. Anything else do we need to know?
Nope.

I think this is root cause of #2785.

### PR DESCRIPTION
**Pull request by tvi**
Fixes #4491 and maybe #2785 as well.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Thanks for the PR!  Go 1.10 is not supported by upstream as of yet, so I am uncertain on the best path for this PR.  I think it is ok, but I am going to get @justinsb opinion.

/assign @justinsb

**Comment by chrislovecnm** [comment]
I think you are fixing a bug that a bunch of developers are hitting ...

**Comment by chrislovecnm** [comment]
@justinsb just helped a new developer with this problem, so either we need to force the use of a specific version of go, or support 1.10.

**Comment by tvi** [comment]
I think this is best of both worlds, because kops is still being built in docker by 1.9 because GOVERSION, this change just proactively protects in case system go is 1.10 during bootstrap.

**Comment by chrislovecnm** [comment]
Since multiple people are hitting this

/approve

**Pull request merged**
