### PR TITLE
openstack: Upgrade to Gophercloud v2

### PR DESCRIPTION
**Pull request by pierreprinetti**
Gophercloud v1 is frozen and lacks a few improvements that can be found in the v2 branch. This patch bumps Gophercloud to the current v2 branch and makes the required modifications to the kops code.

Essentially:

* Add a context argument to Gophercloud functions
* Refactor scheduler hints for server creation

Incidentally, Gophercloud also got stricter in the accepted response codes. I have changed the mocked `servers.Create` call to return `202` instead of `201`: [docs](https://docs.openstack.org/api-ref/compute/?expanded=restore-soft-deleted-instance-restore-action-detail#create-server)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Despite the huge LOC change count, this patch should be relatively straightforward, as it’s almost exclusively the same regex applied all over. Let me know if I can help with the review @zetaab @olemarkus.

**Comment by hakman** [comment]
> Despite the huge LOC change count, this patch should be relatively straightforward, as it’s almost exclusively the same regex applied all over. Let me know if I can help with the review @zetaab @olemarkus.

Thank you @pierreprinetti, the review seems pretty straightforward.
I will wait for @zetaab's final approval, as we don't have any e2e tests for OpenStack.
/lgtm

**Review by zetaab — APPROVED** [review]
/approve

**Pull request merged**
