### PR TITLE
WIP Use droplet ID for node names in DO

### PR DESCRIPTION
**Pull request by hakman**
/cc @rifelpet

### CODE REVIEW

**Comment by rifelpet** [comment]
Whats the advantage of using the droplet ID over the IP address for the node name? I suppose it matches AWS' instance ID node names, any other benefits?

**Comment by hakman** [comment]
> Whats the advantage of using the droplet ID over the IP address for the node name? I suppose it matches AWS' instance ID node names, any other benefits?

See https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/getting-started.md#--provider-iddigitaloceandroplet-id

**Pull request closed without merging**
