### PR TITLE
Correct all the word "cluster" to be in lowercase

### PR DESCRIPTION
**Pull request by AdamDang**
In the main text of this doc, We can see "cluster" "Cluster" "clusters" "Clusters".
My suggestion: in lowercase.

### CODE REVIEW

**Comment by justinsb** [comment]
The distinction I was aiming for here is between a Cluster object and the cluster.  Honestly I'm not sure either way ... I'll think :-)

**Comment by rdrgmnzs** [comment]
What about leaving Cluster capitalized and adding "object" after every mention to emphasize that it is an object. InstanceGroup already has "objects" on most mentions but we should ensure the rest of the mentions also specify "objects" to create a clear distinction.

**Comment by justinsb** [comment]
That's a great suggestion @rdrgmnzs - what do you think @AdamDang ?

**Comment by AdamDang** [comment]
@justinsb Good idea! I've modified as that.

**Pull request merged**
