### PR TITLE
etcd admin doc

### PR DESCRIPTION
**Pull request by sdarwin**
Document for https://github.com/kubernetes/kops/issues/8400

### CODE REVIEW

**Comment by rifelpet** [comment]
Thanks @sdarwin  this looks great. We'll need to add this new page to [this file](https://github.com/kubernetes/kops/blob/master/mkdocs.yml) to get it in the docs site's menu.

**Comment by sdarwin** [comment]
@rifelpet, updated mkdocs.yml

**Comment by rifelpet** [comment]
the [preview looks good](https://deploy-preview-8729--kubernetes-kops.netlify.com/operations/etcd_administration/). thanks!
/lgtm
/approve

**Comment by sdarwin** [comment]
hmm, interesting..  That preview wasn't rendering numbered lists. 
It showed "1 1 1 1" instead of "1 2 3 4".  

I have changed the markup to the following, which seems to fix it.

```
1\. 
2\. 
3\.
```

**Pull request merged**
