### PR TITLE
Allow configuring OpenStack CCM networking options

### PR DESCRIPTION
**Pull request by ederst**
This will allow to configure the [OpenStack CCM networking options](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#networking).

### CODE REVIEW

**Review by zetaab — APPROVED** [review]
looks ok, but just wondering can this be used with kops? kops does not add multiple interfaces to single instance?

**Comment by ederst** [comment]
@zetaab no kops does not allow multiple openstack interfaces, but this can be beneficial when:
* interfaces get attached afterwards, via a controller or other provisioning logic
* when using subnets where a ipv6 is automatically attached, and no ipv6 should be reported to the k8s node resource
* using subnets where occm deems it is public and the net should be handles as private (or vice versa)

**Pull request merged**
