### PR TITLE
Fixes issue #1005

### LINKED ISSUE #1005: Improve cli help documents and command line help
Appropriate the https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/templates code so that we can do cool stuff like:

```golang
var (
	apply_long = templates.LongDesc(`
		Apply a configuration to a resource by filename or stdin.
		This resource will be created if it doesn't exist yet.
		To use 'apply', always create the resource initially with either 'apply' or 'create --save-config'.

		JSON and YAML formats are accepted.

		Alpha Disclaimer: the --prune functionality is not yet complete. Do not use unless you are aware of what the current state is. See https://issues.k8s.io/34274.`)

	apply_example = templates.Examples(`
		# Apply the configuration in pod.json to a pod.
		kubectl apply -f ./pod.json

		# Apply the JSON passed into stdin to a pod.
		cat pod.json | kubectl apply -f -`)
)

func NewCmdApply(f cmdutil.Factory, out io.Writer) *cobra.Command {
	var options ApplyOptions

	cmd := &cobra.Command{
		Use:     "apply -f FILENAME",
		Short:   "Apply a configuration to a resource by filename or stdin",
		Long:    apply_long,
		Example: apply_example,
		Run: func(cmd *cobra.Command, args []string) {
			cmdutil.CheckErr(validateArgs(cmd, args))
			cmdutil.CheckErr(cmdutil.ValidateOutputArgs(cmd))
			cmdutil.CheckErr(validatePruneAll(options.Prune, cmdutil.GetFlagBool(cmd, "all"), options.Selector))
			cmdutil.CheckErr(RunApply(f, cmd, out, &options))
		},
	}
}
```

### PR DESCRIPTION
**Pull request by robertojrojas**
Improved cli command line help by adding k8s templates, i18n, and examples. Fixes #1005

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2443)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
Waiting on e2e - this is a PR that was already opened and reviewed

**Comment by geojaz** [comment]
👍 thanks gents!

**Pull request merged**
