### PR TITLE
Update controller-runtime to v0.8.2 for kOps 1.20

### PR DESCRIPTION
**Pull request by hakman**
... and k8s.io/* to v0.20.4

`kops-controller` changed the leader election mechanism from ConfigMaps locking to Lease API, so new permissions are needed. Logs for `kops-controller` show that things are working correctly in the [e2e test](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/10967/pull-kops-e2e-kubernetes-aws-1-20/1366995504935735296/artifacts/ip-172-20-44-115.ap-southeast-2.compute.internal/kops-controller-p4z5z.log).
```diff
--- a/upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
+++ b/upup/models/cloudup/resources/addons/kops-controller.addons.k8s.io/k8s-1.16.yaml.template
@@ -160,8 +160,10 @@ rules:
   - create
 - apiGroups:
   - ""
+  - coordination.k8s.io
   resources:
   - configmaps
+  - leases
   resourceNames:
   - kops-controller-leader
   verbs:
@@ -175,8 +177,10 @@ rules:
 # We can't restrict creation of objects by name
 - apiGroups:
   - ""
+  - coordination.k8s.io
   resources:
   - configmaps
+  - leases
   verbs:
   - create
```

One thing I am not sure about is the context changes:
```diff
--- a/cmd/kops-controller/controllers/node_controller.go
+++ b/cmd/kops-controller/controllers/node_controller.go
@@ -69,8 +69,7 @@ type NodeReconciler struct {
 
 // +kubebuilder:rbac:groups=,resources=nodes,verbs=get;list;watch;patch
 // Reconcile is the main reconciler function that observes node changes.
-func (r *NodeReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
-       ctx := context.Background()
+func (r *NodeReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
        _ = r.log.WithValues("nodecontroller", req.NamespacedName)
 
        node := &corev1.Node{}
```

/cc @bmelbourne @olemarkus

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by bmelbourne** [comment]
> ... and k8s.io/* to v0.20.4
> 
> /cc @bmelbourne @olemarkus

I didn't think we'd want to go to the latest versions of k8s.io modules hence the `replace` directives. I'll update my recent PR sometime today.

**Comment by hakman** [comment]
> > ... and k8s.io/* to v0.20.4
> > /cc @bmelbourne @olemarkus
> 
> I didn't think we'd want to go to the latest versions of k8s.io modules hence the `replace` directives. I'll update my recent PR sometime today.

Maybe do that first in a PR and the look into `controller-runtime` upgrade. It requires a little more work with permissions at least.

**Comment by bmelbourne** [comment]
@hakman @olemarkus 
PR #10965 is ready for review and just focuses on bumping up the k8s.io Go modules to `v0.20.4`.

**Comment by hakman** [comment]
@olemarkus Could you do the final review? Thanks!

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
