### PR TITLE
Handle disappearing LBs during tear-down

### PR DESCRIPTION
**Pull request by johngmyers**
Found in https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-upgrade-k126-kolatest-to-klatest-kolatest/1615188933384081408/build-log.txt

Handle the case where a load balancer in the account is deleted between the time we list it and the time we query it for tags.

### CODE REVIEW

**Comment by justinsb** [comment]
I assume this happens if there is a concurrent deletion operation.  Can we add a log message so people know why it's switching behaviours (e.g. if they notice the slowdown)?

An alternative strategy could be simply to retry any list operation if the error is one of a set of candidate errors?

**Comment by johngmyers** [comment]
This could be for any LB in the account, possibly one for a different cluster. I think any logging would be noise; it's just switching tactics for the 20 LBs in the page of results.

It is a good question whether we should try to address these piecemeal or whether we should have a retry loop over the whole "list resources and delete" process.

**Comment by justinsb** [comment]
In office hours, I think we said we were going to look at retrying all list operations and see if that was in fact easier.

Not sure if you've had time @johngmyers - I don't think there's anything wrong with this PR as-is, so we can merge as-is, or I can just have a go at the list handling if that's helpful.

But no rush, I don't think this happens very often (currently) ... just going through the recent PRs!

**Comment by johngmyers** [comment]
Will address this at a higher level

**Pull request closed without merging**
