### PR TITLE
Clarify MixedInstancePolicy instance group docs

### PR DESCRIPTION
**Pull request by gjtempleton**
Improved consistency of rest of InstanceGroup docs

Cleans up MDLint errors throughout.

Attempt to resolve Travis failing to report status of #8818

### CODE REVIEW

**Comment by hakman** [comment]
@gjtempleton I have the same problem with Travis failing pretty much 100% of time. If you find a solution, please let me know also.

**Comment by rifelpet** [comment]
still no luck :( i see this PR and the last attempt had identical commits. Maybe travis isn't treating the PRs differently because they contain the same commit hashes? maybe you can open a new PR with some trivial change that changes the commit hash? thats my only idea at this point...

**Comment by gjtempleton** [comment]
Lets try a force push of a new commit first. If that still fails to see the status I'll give opening a new PR with fresh commits a try.

**Comment by rifelpet** [comment]
:(

**Comment by gjtempleton** [comment]
Still nope, attempt no. 4 on its way.

**Pull request closed without merging**
