### PR TITLE
Always generate kops-controller certs

### PR DESCRIPTION
**Pull request by hakman**
This is a quick simple fix, but can be easily be reverted and a better one added later.

Fixes: #10704

### CODE REVIEW

**Comment by justinsb** [comment]
Yes, I concur with this fix; it is consistent with our always labelling with the pki label!

Thanks @hakman!

**Comment by hakman** [comment]
Thanks @justinsb. I guess now all blockers for 1.19.1 are fixed?

**Comment by justinsb** [comment]
I think we also want to figure out the kubenet + containerd thing... I borrowed your trick and am trying to get that to pass...  They all pass on GCE somehow (https://k8s-testgrid.appspot.com/google-gce#gce-containerd)

I'm generally double-checking the list...  we should probably also check this fix against the two reported scenarios  (at least mentally run through the scenarios!)

**Pull request merged**
