### PR TITLE
Bump nvidia device plugin to 0.11 and nvidia driver to 510

### PR DESCRIPTION
**Pull request by olemarkus**
This will also make it possible to use gpu + arm. That combination requires jammy AMIs.

### CODE REVIEW

**Comment by rifelpet** [comment]
should we add a release note and update the docs regarding the AMI requirement?

**Comment by olemarkus** [comment]
Good idea. Added.

**Review by rifelpet — APPROVED** [review]

**Comment by ddelange** [comment]
fyi nvidia has [stopped](https://hub.docker.com/r/nvidia/k8s-device-plugin) CD to docker hub and moved here:
`nvcr.io/nvidia/k8s-device-plugin:v0.12.0`

**Comment by olemarkus** [comment]
@ddelange thanks. would really appreciate if you could do a PR updating this.

**Pull request merged**
