### PR TITLE
Automated cherry pick of #7992: Add CloudControllerConfigArgv template function, Expose

### PR DESCRIPTION
**Pull request by DavidSie**
Cherry pick of #7992 on release-1.17.

#7992: Add CloudControllerConfigArgv template function, Expose

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by zetaab** [comment]
quite heavy changes? why +10k? 1.16 have less than 1k

**Comment by DavidSie** [comment]
@zetaab  big part comes from running `make gomod`.  I'm not sure why it is changing order in modules.txt

**Comment by mikesplain** [comment]
Agreed with @zetaab, we need to figure out why all those changes appear here... It seems like something is wrong.

**Comment by mitch000001** [comment]
So we're not going to pick it into 1.17?

**Comment by DavidSie** [comment]
I'm working on it. there is another pr https://github.com/kubernetes/kops/pull/8166 which is much smaller, but it fails at the moment.

**Pull request closed without merging**
