### PR TITLE
Clarify ignoring AssociatePublicIP message

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1624)

### CODE REVIEW

**Comment by kris-nova** [comment]
Why don't we want this in 1.5? This looks fine

**Comment by chrislovecnm** [comment]
If it is not a bug fix I would like to hold till 1.5.1

**Comment by justinsb** [comment]
I think that's taking the freeze too far.  We know we have to fix things, and I thought this message was confusing and a user mentioned it as well (though we also have the root cause to fix too, which is that we shouldn't be marking private zones with AssociatePublicIPs=true)

**Comment by chrislovecnm** [comment]
Thanks guys ... merging :)

**Comment by chrislovecnm** [comment]
I will close the code freeze ish, please tag with the 1.5.0 release, and I will review and merge :)

**Pull request merged**
