### PR TITLE
Docs: Fix some broken development links

### PR DESCRIPTION
**Pull request by gjtempleton**
Couple of minor link fixes to development related docs/images

Also cleans up the lists under issues and pull requests headings in `welcome/contributing.md` and lists in `welcome/office_hours.md`

### CODE REVIEW

**Comment by rifelpet** [comment]
Awesome! the preview site really makes reviewing these changes easier.

/approve
/lgtm

**Comment by mikesplain** [comment]
Glad to hear it! Thanks @gjtempleton for catching these!

**Comment by gjtempleton** [comment]
Yep, definitely makes things far simpler for these PRs, thanks again for the hard work in getting it up and running @mikesplain !

**Pull request merged**
