### PR TITLE
Test of model to terraform

### PR DESCRIPTION
**Pull request by justinsb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1116)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
"kubectl": executable file not found in $PATH <- Travis goes boom

**Comment by kris-nova** [comment]
@chrislovecnm @justinsb 

> "kubectl": executable file not found in $PATH <- Travis goes boom

How do we plan on getting the binary into our build? There is a small part of me that wants to keep it up in S3 like we do with our other things.. and just pull it down for tests.. so we can easily add new versions without breaking the build.. just a thought

**Comment by justinsb** [comment]
I'll make it so we don't need kubectl.  We're only using it to write kubecfg.

In this particular case, I don't think we want to be writing kubecfg at all.

**Comment by justinsb** [comment]
(The dnsprovider hack is actually the blocker here...)

**Comment by chrislovecnm** [comment]
```
integration_test.go:178: terraform output differed from expected
```
^ travis still not happy

**Comment by justinsb** [comment]
Tests failed because we changed the TF output :-)  Tests working as designed, I'd say!

I opened https://github.com/kubernetes/kubernetes/pull/38590 and manually applied it for now.  We should notice if a version bump obliterates it before the PR is accepted, because our code won't compile (or our tests will fail!).

Marked as P0 because this is on the critical path to getting API machinery up and running.  Once we have this I can start making bigger changes.

**Comment by justinsb** [comment]
Hooray - finally gone green!

**Pull request merged**
