### PR TITLE
Add hint how to determine mount path of etcd data

### PR DESCRIPTION
**Pull request by FuriKuri**
Hi,

I've added a hint, how to determine the mount paths of the etcd directories. I think most people know how to get the correct path, but if you go through such a risky procedure, you'll be more comfortable with such information.

### CODE REVIEW

**Comment by rifelpet** [comment]
Thanks @FuriKuri!

/ok-to-test
/lgtm
/area documentation

**Comment by justinsb** [comment]
Thanks for this @FuriKuri 

/approve
/lgtm

**Pull request merged**
