### PR TITLE
Add live-restore flag to docker config

### PR DESCRIPTION
**Pull request by marciorodrigues87**
More info: https://github.com/kubernetes/kops/issues/4160

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Please follow the instructions here: https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

Also, what version of k8s does this api apply to?

**Comment by gkope** [comment]
@chrislovecnm Kubernetes `1.7.11`

**Comment by chrislovecnm** [comment]
@marciorodrigues87 nudging you on this.  We need to have all three api files updates, and the api machinery generated. We probably should validate that this is only used with k8s 1.7+ I think is correct?

here are some docs on making the api changes: https://github.com/kubernetes/kops/blob/master/docs/development/api_updates.md

**Comment by marciorodrigues87** [comment]
@chrislovecnm Thanks for the help! And sorry about the late answer! I did the missing things to add the field to the API... 
The flag is related to `dockerd` running on cluster nodes, so I think that it'll work on all kubernetes versions. I can validate if using this flag on a docker version that doesn't have the flag will break and so we can put some validation to accept the flag only starting from docker version `1.12`.
Please take a look on the flags documentation: https://docs.docker.com/config/containers/live-restore/

**Comment by chrislovecnm** [comment]
@marciorodrigues87 we can merge this, can we get a squash first?  It would be good to add some validation for the API value so that versions of k8s without support don't use this flag.  You can do a follow-up PR if you like.

**Comment by justinsb** [comment]
/lgtm

Thanks @marciorodrigues87

**Pull request merged**
