### PR TITLE
Detect AWS region for S3 inside containers

### PR DESCRIPTION
**Pull request by hakman**
AWS detection assumes that `/sys/devices/virtual/dmi/id/product_uuid` is readable. This is not the case inside containers like `kops-controller`. If there is an error reading the file, AWS api should be queried anyway as a fallback.

Fixes: #9856

### CODE REVIEW

**Comment by johngmyers** [comment]
Another possibility would be to set `AWS_REGION` in the manifest.

**Comment by hakman** [comment]
> Another possibility would be to set `AWS_REGION` in the manifest.

This is a more generic fix that will work in any container and I don't think it has any downside.

**Comment by johngmyers** [comment]
Some security systems block access to AWS metadata from pods in order to deny them use of the node's IAM roles.

**Comment by hakman** [comment]
> Some security systems block access to AWS metadata from pods in order to deny them use of the node's IAM roles.

Ok, I would still leave this as is and create a new PR that adds AWS_REGION to env vars. Sounds reasonable?

**Comment by hakman** [comment]
@johngmyers any thoughts on merging this?

**Comment by ryan-dyer-sp** [comment]
Can we get this back ported to 1.18?  without this change the ability to use kops to deploy to aws govcloud regions is broken; at least without needing to manually update the kops-controller DS to include the AWS_REGION env.

**Comment by hakman** [comment]
@ryan-dyer-sp already cherry-picked into 1.18, will take another 2-4 for a new release. I hope this is ok for you.

**Pull request merged**
