### PR TITLE
Update kube-dns addon configuration to match the latest

### PR DESCRIPTION
**Pull request by bowei**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1997)

### CODE REVIEW

**Comment by bowei** [comment]
These changes are needed for a main kubernetes PR to pass: https://github.com/kubernetes/kubernetes/pull/41826

**Comment by bowei** [comment]
@chrislovecnm -- I'm happy to create a new file, what should the yaml be named and how will it chosen for the kops e2e job?

**Comment by chrislovecnm** [comment]
1.5.3 to match the next kops version. I can run the e2e once you make the changes. Any Kubernetes org member can fire off the e2e.

**Comment by chrislovecnm** [comment]
I understand you question. I am on mobile so I cannot find the. Ode, but there is code that specifies the. Erosion of the yaml file. If you look for the weave cni PRs I think it is the same go file that gets updated.

**Comment by bowei** [comment]
@chrislovecnm -- should the version match the Kubernetes version (1.6) or kops version (1.5.3)? I see a wide mix of version numbers among the addons. How is the version chosen when running the Kops driven e2e tests that are part of the main Kubernetes repository?

I'm trying to get kubernetes/kubernetes#41826 to pass and it requires kops + the main repo to be in sync.

**Comment by justinsb** [comment]
@bowei the problem is that we have no numbering scheme in kubernetes!

The missing piece is that bootstrapchannelbuilder.go needs to be updated with the version number.

If this is something that you are going to backport to 1.4 and 1.5, we can just update the version.  Otherwise we need to switch based on the cluster KubernetesVersion, enabling only for 1.6 and above.  (In general, this is probably a good idea anyway if the PR hasn't been backported yet).

See for example:

**Comment by bowei** [comment]
@justinsb -- how does one choose the manifest to use from the BuildOptions() method? 

I'm not familiar with the flow of code in kops, but the BuildOptions() seems to be setting some template substitutions for the manifest file. I would prefer to switch the entire manifest file based on Kubernetes version rather than chopping it into a kube version independent manifest and version specific template substitutions...

**Comment by bowei** [comment]
@chrislovecnm @justinsb -- would love to get this sorted out. This is blocking updates to kube-dns.

**Comment by justinsb** [comment]
@bowei it is absolutely fine to create a second yaml template - v1.6.0.yaml.template, and you just need to switch out this line https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L88 based on the KubernetesVersion.

There are a few templates variables, but they are substituted for you - you don't need to set them up etc.

So you just want to do something like this:

```
sv, err := util.ParseKubernetesVersion(b.Cluster.KubernetesVersion)
if err != nil {
  return nil, fmt.Errorf("unable to determine kubernetes version from %q", b.Cluster.KubernetesVersion)
}
version := "1.6.0"
if kubernetesVersion.Major == 1 && kubernetesVersion.Minor <= 5 {
	version = "1.5.1"
}
```

**Comment by bowei** [comment]
@chrislovecnm feedback? This is blocking kubernetes/kubernetes#41826

**Pull request merged**
