### PR TITLE
Revert "Temporarily disable cluster-autoscaler in many-addons test"

### PR DESCRIPTION
**Pull request by olemarkus**
This reverts commit a64ae909e13f6d8abaa72912838dfc201cef0a92 (PR #14934).

Issue should be fixed by #14952

### CODE REVIEW

**Comment by hakman** [comment]
I think the test takes too long now.
/test pull-kops-e2e-aws-upgrade-126-ko126-to-klatest-kolatest-many-addons

**Review by johngmyers — APPROVED** [review]

**Comment by johngmyers** [comment]
The hold was to let the many-addons test complete.

**Pull request merged**
