### PR TITLE
Automated cherry pick of #10913: Honor OS update policy at InstanceGroup level too

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #10913 on release-1.20.

#10913: Honor OS update policy at InstanceGroup level too

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by rifelpet — APPROVED** [review]

**Comment by seh** [comment]
Thank you, @hakman!

**Comment by johngmyers** [comment]
This inverted the sense of UpdatePolicy on Debian. It now installs unattended-upgrades and performs upgrades if the policy is "external" and does nothing if it is set to "automatic" (or "").

**Comment by seh** [comment]
I had noted confusion in this area in https://github.com/kubernetes/kops/pull/10913#pullrequestreview-596656071.

**Comment by johngmyers** [comment]
Yeah, it's busted in 1.20 as well.

**Comment by seh** [comment]
[This Slack thread](https://kubernetes.slack.com/archives/C3QUFP0QM/p1614094895070000?thread_ts=1614031129.048800&cid=C3QUFP0QM) from the "kops-users" channel may also be of interest.

**Pull request merged**
