### PR TITLE
Headers 2016->2017

### PR DESCRIPTION
**Pull request by kris-nova**
Updating the script for the new year! Woo 🎉

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1258)

### CODE REVIEW

**Comment by justinsb** [comment]
I guess we wait before merging this?

**Comment by chrislovecnm** [comment]
Marking this WIP for merge in 2017

**Comment by kris-nova** [comment]
The year of the Rooster has arrived.. merge please?

**Comment by justinsb** [comment]
I can't merge without the status check from travis :-(

@zmerlynn any ideas how to kick travis?

@kris-nova maybe rebase and repush?

**Comment by chrislovecnm** [comment]
rebase pretty please.  Travis is not happy.

**Pull request merged**
