### PR TITLE
Fix log rotation of apiserver audit logs

### PR DESCRIPTION
**Pull request by ottoyiu**
Fixed an oops I created in #2494 where log rotation done by the kube-apiserver does not function
as expected.

The kube-apiserver first has to rename the existing audit log prior to a new one
being created. Renaming is not possible when the audit file is mounted
directly as the host path. kube-apiserver will return a 'Device or
resource busy' error when it tries to do so. So instead, we mount the
directory of the path instead of the file itself. Also remove the
creation of an empty audit log file as that is no longer necessary for
Docker to mount a directory.

"If an audit log file already exists, Kubernetes appends new audit logs
to that file. Otherwise, Kubernetes creates an audit log file at the
location you specified in audit-log-path. If the audit log file exceeds
the size you specify in audit-log-maxsize, Kubernetes will rename the
current log file by appending the current timestamp on the file name
(before the file extension) and create a new audit log file. Kubernetes
may delete old log files when creating a new log file; you can configure
how many files are retained and how old they can be by specifying the
audit-log-maxbackup and audit-log-maxage options."

Source: https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

Tested this on Kubernetes 1.6 and with an audit log path specified to
be:
/var/log/kube-apiserver-audit.log

The kube-apiserver container has this mounted:
/dev/xvda1 on /var/log type ext4 (rw,relatime,data=ordered)

Tested to make sure /var/log/kube-apiserver.log's host path continues to function.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2670)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
In regard to testing:

1. Private and public topology need to be tested with an application that uses internal and lb services.
2. Please test 1.5 and 1.6 or we need to just release for 1.6 and document this.

**Comment by ottoyiu** [comment]
Tested this on 1.5.7 as well with the private topology. I will test both using a public topology on Monday.

**Comment by chrislovecnm** [comment]
@ottoyiu I missed typed the stuff about testing.  No need to test on different network setups with this PR.  We good to merge?

**Comment by ottoyiu** [comment]
@chrislovecnm yes :)

**Comment by chrislovecnm** [comment]
Sorry to be a pain about this, but why was this not made a task? Maybe I am miss reading the code, but it no longer appears to be a task

**Comment by ottoyiu** [comment]
@chrislovecnm Naw, definitely appreciate you spending the time to code review :)

By default, Docker will create a directory if the path you specified to be a host mount does not exist. To circumvent that, a task is added so that prior to the spin up of the apiserver, the file path is touch'ed first, so that Docker won't create a directory in the location you specified to be a file. Now that I actually want to mount a directory for the apiserver to properly manage the audit logs, the default behaviour of Docker is the desired one.

**Pull request merged**
