### PR TITLE
Use etcd v3.5.0 for Kubernetes 1.22+

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Comment by olemarkus** [comment]
Maybe we should do a k8s upgrade test for this PR as well.

**Comment by hakman** [comment]
> Maybe we should do a k8s upgrade test for this PR as well.

@olemarkus I agree, we should try it. Should be pretty much fine, as it's tested in the etcd-manager integration tests.

**Review by johngmyers — APPROVED** [review]

**Pull request merged**
