### PR TITLE
Update Calico to v3.21.1

### PR DESCRIPTION
**Pull request by hakman**
https://docs.projectcalico.org/archive/v3.21/release-notes/

### CODE REVIEW

**Comment by hakman** [comment]
@lwr20 any thoughts on why the `[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]` test will fail with Calico v3.21.0?

**Comment by lwr20** [comment]
Sadly that's a bug.  
@caseydavenport put this up to fix: https://github.com/projectcalico/libcalico-go/pull/1544  
We expect to release v3.21.1 with that fix in shortly.

**Comment by hakman** [comment]
Thanks @lwr20. Sounds good to me :).

**Comment by hakman** [comment]
Ready for review now that v3.21.1 is out.
/cc @johngmyers @olemarkus @rifelpet

**Review by johngmyers — APPROVED** [review]

**Pull request merged**
