### PR TITLE
Apply cloud labels into ELB

### LINKED ISSUE #2048: cloudLabels for API ELB
It seems cloudLabels is not putting TAG on API ELB's.
kops create cluster --v=3 --state=s3://ewe-kubernetes-dev --cloud=aws \
    --name=kubetnets.us-west-2.dev.expedia.com \
    --ssh-public-key=~/.ssh/kube_aws_rsa.pub \
    --master-size=t2.medium \
    --cloud-labels="Team=CAT" \
    --master-zones=us-west-2c,us-west-2a,us-west-2b \
    --network-cidr=10.4.0.0/16 \
    --vpc=vpc-030e8f64 \
    --node-count=3 \
    --node-size=t2.micro \
    --topology private \
    --networking weave \
    --zones=us-west-2c,us-west-2a,us-west-2b \
    --channel=alpha

Result : k8 API ELB's dont have AWS TAG mentioned in cloud-labels.

### PR DESCRIPTION
**Pull request by wingyplus**
Fixes #2048

### CODE REVIEW

**Comment by wingyplus** [comment]
@k8s-ci-robot /check-cla

**Comment by KashifSaadat** [comment]
Thanks for the fix @wingyplus, looks good :)

/lgtm
/approve

**Comment by wingyplus** [comment]
@KashifSaadat Thanks :)

**Comment by gambol99** [comment]
This is a dangerous one to added as i've just encounter. Beforehand the cloud tags were not added but now they are and expected in the 'find' of the fi tasks .. This cause's a number of resources which was not presently tagged (vpc, subnets, routing tables etc) by a previous kops binary not to be found and be marked as creating on the kops apply. Also we use dynamic tags (i.e. gitsha's and release version) which would never work ... Thankfully it was in testing .. @mikesplain @justinsb ..

**Comment by justinsb** [comment]
So this had to be reverted - if you're still interested in pursuing it, I think you need to plumb through the additional tags here: https://github.com/kubernetes/kops/blob/c55b03262e8698f52ed5b01182023e24ac1fd37f/pkg/model/awsmodel/api_loadbalancer.go#L117

i.e. specifically in the ELB, not generally at the cloud level.

The problem is that tags at the cloud level act as a filter.  Another option would be to have tags at the cloud level that are added, but don't act as a filter - that would be the spirit of what you've done in this PR.

**Pull request merged**
