### PR TITLE
Drop kops-ci references

### PR DESCRIPTION
**Pull request by ameukam**
Ref:
  - https://github.com/kubernetes/k8s.io/issues/2625

### CODE REVIEW

**Comment by ameukam** [comment]
cc @hakman @rifelpet

**Comment by hakman** [comment]
To merge this I think we have to merge https://github.com/kubernetes/kops/pull/16755 first and skip all failing tests...
/cc @justinsb @rifelpet 
/lgtm

**Comment by hakman** [comment]
@justinsb Can you give it a try?

**Pull request merged**
