### PR TITLE
Use Cilium 1.11 as default

### PR DESCRIPTION
**Pull request by olemarkus**
Cilium 1.11 released today: https://isovalent.com/blog/post/2021-12-release-111
Not sure we want this one in 1.23 or wait. Or maybe upgrade cilium based on k8s version.

Either way, this is the first version that formally supports 1.23 (although 1.10 should work fine as well).

### CODE REVIEW

**Comment by olemarkus** [comment]
/test pull-kops-e2e-cni-cilium

This failing test may be a new one with cilium.

**Comment by olemarkus** [comment]
on the failures:
xref https://github.com/cilium/cilium/issues/18241

**Comment by xmulligan** [comment]
@olemarkus  thanks for keeping Cilium up to date in kops! would you mind adding kops to the Cilium adopters list? https://github.com/cilium/cilium/blob/master/USERS.md

We need this for when we apply to graduate at the CNCF

**Review by hakman — APPROVED** [review]

**Pull request merged**
