### PR TITLE
Docs cleanup / mkdocs migration

### PR DESCRIPTION
**Pull request by mikesplain**
This PR starts a cleanup move to mkdocs. There's quite a bit of work still to be done here but here is the first pass.

Preview (via netlify): https://kops.mikespla.in/

Todos:
- [x] Reduce number of tabs
- [x] Split up pages that make sense to be separated
- [x] Clean up operations pages
- [x] Clean up duplication
- [x] ~Remove netlify make command before merging~ We will likely use netlify so leaving as is.
(Additional todos moved to #7636)

Things to know
* Final location will likely be ~github pages, published by travis~ netlify via cncf account.

There is definitely tons more to go but I wanted to get the docs into a state that is publishable... We can have plenty of follow up PRs to reorder or cleanup additional docs.

### CODE REVIEW

**Comment by mikesplain** [comment]
/hold
To allow others to take a look!

**Comment by rifelpet** [comment]
Looks good to me but i'll give a chance for others to chime in. Thanks for doing this!

**Comment by joshbranham** [comment]
I like this alot (like `ingress-nginx` does among others). Will make it more friendly for people getting started, and for discovery of some of the more advanced concepts and customizations as people look for those.

/lgtm

**Comment by bittopaz** [comment]
I'm considering contributing, this is indeed helpful. Thanks!

**Comment by rifelpet** [comment]
/test pull-kops-verify-generated

@mikesplain thoughts on unholding this?

**Comment by tanjunchen** [comment]
@mikesplain  

> @mikesplain thoughts on unholding this?

Agree

**Comment by mikesplain** [comment]
I'm planning to do one last update with doc changes since I've updated this then get this merged.

Sorry for the delays!

**Comment by mikesplain** [comment]
I'm going to let this merge now and follow up with some additional smaller PRs.  I'll request a site asap.

**Comment by taraslayshchuk** [comment]
@mikesplain This PR breaks [documentation URLs](https://github.com/kubernetes/kops/blob/master/permalinks/upgrade_k8s.md#1.11.10).

**Comment by mikesplain** [comment]
Thanks @taraslayshchuk!  Fixed in #7836!

**Pull request merged**
