### PR TITLE
[Fixes #2466] Creates .kube dir at /home/admin with group/owner as admin

### LINKED ISSUE #2466: owner incorrectly set on ~/.kube folder
root is the owner of the ~/.kube folder on the master.  admin or the base user for the image type should be the owner.

You get the following error when installing a manifest from the master:

```
error: error validating "STDIN": error validating data: mkdir /home/admin/.kube/schema: permission denied; if you choose to ignore
```

kops version:
```
$ kops version
Version 1.6.0-alpha.2 (git-083b78939)
```

k8s version:
```
admin@ip-172-20-20-7:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

I believe this is a nodeup issue, as we need to `chown admin: ~admin/kube`.

### PR DESCRIPTION
**Pull request by dolftax**
Signed-off-by: Jaipradeesh Janarthanan <jaipradeesh@gmail.com>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2523)

### CODE REVIEW

**Comment by dolftax** [comment]
I signed it.

**Comment by chrislovecnm** [comment]
CLA is not happy. Is you git user setup with the email address that you signed the cla with?

**Comment by dolftax** [comment]
Commit:
```
Signed-off-by: Jaipradeesh Janarthanan <jaipradeesh@gmail.com>
```

Cross checked CNCF's email address. Same. I had signed the agreement long back. I did sign-up with Github.

When I hit this URL - https://identity.linuxfoundation.org/node/285/individual-signup, I get `Access Denied`. But Project membership says `CNCF`. Email is same. Github has been added as well. I had pinged @foxish and Linux Foundation support on the same.

**Comment by dolftax** [comment]
@chrislovecnm Logged into hellosign and found the doc. :D

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by dolftax** [comment]
`.kube` folder isn't created on master (or) nodes. It exists in the machine from where `kops` is executed. And the permission looks fine.

Without this patch
```
ls -la /home/admin | grep kube

drwxr-xr-x 2 admin admin        20 May 11 11:27 .kube
```

```
ls -la /home/admin/.kube

-rw------- 1 admin admin 5663 May 11 11:27 config
```

@chrislovecnm Try to use the following executable and see if you can replicate the issue.

https://s3-ap-southeast-1.amazonaws.com/dev-doselect/kops+(1)

**Pull request merged**
