### PR TITLE
[WIP] Stop generating unused cluster_spec.yaml config file for nodes

### PR DESCRIPTION
**Pull request by hakman**
/cc @johngmyers @justinsb @olemarkus

### CODE REVIEW

**Comment by rifelpet** [comment]
Maybe worthy of a release note if folks are utilizing this file themselves?

**Comment by hakman** [comment]
```
jgmyers: I think it's there to make sure that cluster spec changes cause rolling update.
jgmyers: What we want to axe is the cluster completed.
```

**Comment by rifelpet** [comment]
Would reducing it to a hash in the userdata be sufficient?

**Comment by hakman** [comment]
We already have it as a hash in the userdata. But if we want to axe cluster completed instead...

**Comment by johngmyers** [comment]
It should at least show up somewhere in the integration test output

**Pull request closed without merging**
