### PR TITLE
Expose the --fail-swap-on flag for kubelet

### LINKED ISSUE #4123: FailSwapOn kubelet option is not exposed by Kops
Kubelet config is defined in pkg/apis/kops/componentconfig.go and many other files. FailSwapOn is not part of any of these files. In K8s >= 1.8.0, this options defaults to 'true', and there is no way to set it to 'false'.

-- edit below with additional info --

Kops is missing the `--fail-swap-on` config option for Kubelet. In kubernetes/kubelet version <1.8.0, kubelet uses the flag `--experimental-fail-swap-on` which defaults to `false`. In kubernetes/kops >=1.8.0, kubelet uses the flag `--fail-swap-on`, and it defaults to `true`. 

If `--fail-swap-on` is set to `true`, kubelet will error out and never start if the system has swap enabled. If try to use latest kops with kubernetes >= 1.8.0, a system that has swap enabled will never join the cluster because kubelet will never start, and there is no way to  change the `--fail-swap-on` option to `false`.

Kops allows you to specify multiple configuration options for Kubelet. These configuration options can be found [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), among a couple other places. If the config option you are trying to affect is not in this model, then it will not get passed to kubelet.

Like I said, there are many places that the kubelet model shows up: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/componentconfig.go#L22), [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha1/componentconfig.go#L22), and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/componentconfig.go#L22). There also appears to be some generated code that affects the kubelet options as well, for instance these files: [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/v1alpha2/zz_generated.conversion.go) and [here](https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/zz_generated.deepcopy.go).

### PR DESCRIPTION
**Pull request by wannabesrevenge**
Closes #4123 

This change exposes the "--fail-swap-on" flag for kubelet. This means that in the cluster config yaml, you can set `failSwapOn: true | false` under the kubelet config. More info on this option can be found in the referenced issue (#4123), in the kubernetes docs [here](https://kubernetes.io/docs/reference/generated/kubelet/), and in the kubernetes github issue [here](https://github.com/kubernetes/kubernetes/pull/47181).

I made this change by adding the `FailSwapOn` field to the kubelet config structs in the 3 componentconfig.go files. Then I ran `make apimachinery` to generate the rest of the changes you see. 

The changes involving `ImagePullProgressDeadline`, reordering some import statements, and changing the copyright to 2018 are the result of running `make apimachinery`. They are unintended. I can undo some or all of these unintended changes if needed.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Holy crap, we got 2018 all over the place.  We should probably break that update into another PR :(

**Comment by wannabesrevenge** [comment]
i'll get rid of those pesky 2018's and update this thing

**Comment by chrislovecnm** [comment]
@wannabesrevenge you want to do a 2018 PR?  I will merge it quickly.  Ping me on Slack if you put it in.

**Comment by wannabesrevenge** [comment]
@chrislovecnm can do

**Comment by wannabesrevenge** [comment]
Everything is wrapped and ready for scrutiny

**Pull request merged**
