### PR TITLE
Docs - Add the new feature table to various feature sections

### PR DESCRIPTION
**Pull request by rifelpet**
Also cleaning up some creationTimestamps from yaml examples.

It'd be great if someone could double check these versions or even suggest any minimum k8s versions that I left out here.

followup to #9555

### CODE REVIEW

**Comment by rifelpet** [comment]
FYI @MoShitrit I see that the table's shadow is still the full width on FireFox so the fix you provided might have only worked in Chrome

image

**Comment by MoShitrit** [comment]
> FYI @MoShitrit I see that the table's shadow is still the full width on FireFox so the fix you provided might have only worked in Chrome
> 
> image

Huh, you're right!
Apparently, seems like it's the only browser that doesn't handle that well. I checked in Safari and Chrome and both show it properly. I wonder why is FF different. 
Any idea, @mikesplain ?

**Comment by mikesplain** [comment]
Interesting. I'll open a up a PR fix.

**Comment by mikesplain** [comment]
I believe this should take care of that issue: https://github.com/kubernetes/kops/pull/9592

**Pull request merged**
