### PR TITLE
Add hashes for containerd v1.6.7

### PR DESCRIPTION
**Pull request by hakman**
Ref: https://github.com/containerd/containerd/releases/tag/v1.6.7

/cc @olemarkus

### CODE REVIEW

**Comment by olemarkus** [comment]
This release seems bust: https://github.com/containerd/containerd/issues/7255

The relnotes also mentions requiring runc 1.2, which does not exist yet.

**Comment by hakman** [comment]
Switched to just adding the hashes, if anyone wants to try it.

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
