### PR TITLE
Updated security docs to display API secret token correctly

### LINKED ISSUE #2234: Unable to access API bearer token with `kops get secrets`
I created a new private cluster and attempted to access the master API bearer token using instructions here: https://github.com/kubernetes/kops/blob/master/docs/security.md#api-bearer-token

```
$ kops get secrets admin -oplaintext
Using cluster from kubectl context: <...>

secret type SSHPublicKey cannot (currently) be exported as plaintext
```

Workaround: ssh to the master and `sudo cat /srv/kubernetes/known_tokens.csv`.

Slack discussion: https://kubernetes.slack.com/archives/C3QUFP0QM/p1490821908710785

### PR DESCRIPTION
**Pull request by four43**
Fixes #2234

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2532)

### CODE REVIEW

**Comment by four43** [comment]
Updated cncf-cla

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
waiting on e2e

**Pull request merged**
