### PR TITLE
Adding feature stability table to docs and including one example for encryption support in cilium

### LINKED ISSUE #9151: [Documentation Clarity] Please clarify when specific fields are added to the configuration schemas
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.16.2

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.16.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

N/A

**5. What happened after the commands executed?**

Silent dropping of configuration. See below

**6. What did you expect to happen?**

At least an error message

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

See below

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

N/A

**9. Anything else do we need to know?**

We're in the middle of a cluster upgrade to Kops 1.16.2 and nearly suffered an outage because we tried to add fields like `InstanceGroup.spec.sysctlParameters` and `Cluster.spec.networking.amazonvpc.envVars` that are documented in the `master` branch, not accepted in `1.16.2`, and are silently dropped by `1.16.2` instead of throwing an error about unknown configuration.

I understand that `master` reflects the newest state of development rather than the version of the documentation that is tied to a specific release, and that version-controlling the documentation in this way is beneficial precisely because it does allow me to see what the precise state of the documentation is for the version that I'm installing. Nevertheless, it is *extremely easy* to forget to set the tag on GitHub when viewing the documentation and presume that I am looking at the "correct" version of the documentation for what is the latest stable / certified / production-ready version of Kops. In many projects, the latest recommended version for installation is generally sufficiently close to if not identical to `master` that the documentation drift does not present a problem in practice; in Kops, this is not the case, particularly as the manifest version is set to `api/v1alpha2` and not changed when fields are added or changed.

My recommendation is to adopt a similar standard as that found in the main Kubernetes user-facing documentation, which, even for the latest versions, clearly indicates in which version various features were made available. This ensures, for instance, that Kubernetes 1.16 users do not attempt to work with [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/). As such, as a user, I would be able to see from reading the docs in `master` that various features are not yet available for the version of Kops that I am trying to install.

### PR DESCRIPTION
**Pull request by MoShitrit**
Fixes #9151 
To get started, I also added this table to the `cilium` docs for a feature I previously added. This can provide an example for additional features to which we would like to add this table.
Example output of the table when rendered:

image

/cc @rifelpet @olemarkus

### CODE REVIEW

**Comment by MoShitrit** [comment]
I might be missing something, but following the failure output of `hack/verify-boilerplate.sh` I ran `hack/update-header.sh` but nothing happens, it doesn't seem to change anything in `mkdocs_macro.py`.
If I read that script correctly, I _think_ it looks for the copyright block, so I tried adding that manually and it still didn't work.

What am I missing?
```
mosheshitrit:kops mosheshitrit$ hack/verify-boilerplate.sh
FAIL: Boilerplate header is wrong for: /Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/mkdocs_macros.py
FAIL: Please execute ./hack/update-header.sh
mosheshitrit:kops mosheshitrit$ hack/update-header.sh
mosheshitrit:kops mosheshitrit$ hack/verify-boilerplate.sh
FAIL: Boilerplate header is wrong for: /Users/mosheshitrit/src/kubernetes/kops/src/k8s.io/kops/mkdocs_macros.py
FAIL: Please execute ./hack/update-header.sh
```

**Comment by MoShitrit** [comment]
OK found it.
Apparently `hack/update_header.sh` doesn't have a config for `.py` files even though it _does_ exist under `hack/boilerplate` folder. Adding a commit to address that.

**Comment by olemarkus** [comment]
/lgtm

Why did the netlify deploy cancel though?

**Comment by hakman** [comment]
> Why did the netlify deploy cancel though?

@olemarkus Most likely because last commit was on a something not tracked by config file:
https://github.com/kubernetes/kops/blob/8c3b4e4f430914b8a95bfa2f571dc273979f6d1d/netlify.toml#L5

@MoShitrit any chance `mkdocs_macros.py` can be moved to the `scripts` dir?

**Comment by MoShitrit** [comment]
> > Why did the netlify deploy cancel though?
> 
> @olemarkus Most likely because last commit was on a something not tracked by config file:
> 
> https://github.com/kubernetes/kops/blob/8c3b4e4f430914b8a95bfa2f571dc273979f6d1d/netlify.toml#L5
> 
> @MoShitrit any chance `mkdocs_macros.py` can be moved to the `scripts` dir?

@hakman Yeah, sure. I think it'll involve some additional config to the plugin but I can do that.
By the `scripts` dir- do you mean I should create one and put it there? Or is it the `hack` dir? 
I tried to find a dir named `scripts` but couldn't find any.

**Comment by hakman** [comment]
@MoShitrit you are right, meant `hack`. Thanks!

**Comment by MoShitrit** [comment]
@hakman 
Okay, so after re-reading their [docs about the location of the module](https://mkdocs-macros-plugin.readthedocs.io/en/latest/python/#location-of-the-module), I think it might work out better to have a dedicated python package under the root directory, if we don't want to have the file located in the same path as `mkdocs.yml`. So I'm thinking probably creating a python package called `mkdocs_macros/` and moving the `.py` file to this folder. Then we'll have to change the plugin config to point to that directory and that should do it.
WDYT? Is it worth the effort? Or should we just keep it as it is now?
If we _do_ want to use the `hack` dir, we'll have to convert it to a python package (by adding a `__init__.py` file as well there. I'm okay with taking that approach as well, but I'm not sure if we _should_ do it, since most of the files there aren't python and aren't really used by `mkdocs` at all.

**Comment by hakman** [comment]
Thanks for checking @MoShitrit . I don't think it's worth the extra work, but let's see if @rifelpet and @mikesplain have some feedback also.

**Comment by rifelpet** [comment]
I think I'd lean towards moving mkdocs_macros.py into the hack directory and add a `hack/__init__.py` that way we avoid yet another file in the repo root. I think if you squash your commits, the netlify job will not be cancelled and we'll be able to check it out in the browser.

**Comment by MoShitrit** [comment]
Created a new package under `hack` called `mkdocs_macros` and updated `mkdocs.yml` to point to the new package as the module for `Mkdocs-macros` plugin.
I see that the netlify deploy preview worked this time, so we can see an example of the table [here](https://deploy-preview-9555--kubernetes-kops.netlify.app/networking/cilium/#enabling-encryption-in-cilium)

**Comment by mikesplain** [comment]
This looks great, thanks so much for your work on this @MoShitrit!

My only comment is more of a nit, looks like the table goes full with rather than ending at the second column.  Any way we can clean this up?

Screen Shot 2020-07-14 at 9 20 46 AM

Other than that, I think this is a great start!

**Comment by MoShitrit** [comment]
Thanks, @mikesplain !
So I tried to look into that table alignment/padding thing, but I think it's more of how Mkdocs renders every custom block (tables, code etc.). I have a strong feeling this comes from the `Mkdocs-material` theme we're using.
I confirmed that by finding another table in our docs which doesn't use the `macros` plugin at all, and it looks exactly the same - https://kops.sigs.k8s.io/welcome/releases/#compatibility-matrix
I tried to do some html styling to change that, but it kinda broke it. 😖 
I tried to look a little bit a the [material theme docs](https://squidfunk.github.io/mkdocs-material/) but couldn't find a straightforward answer on how to change that (we can maybe apply some external css, but I feel like it could be a little bit out of scope for this PR and it could take me good bit of time to figure this out, lol)
WDYT?

**Comment by mikesplain** [comment]
Hmm gotcha, you should be able to change `max-width: 100%;` to `max-width: fit-content;` on the table object, which worked for me at least.  You would likely need to wrap the table in a div with a new class like `class=kops_feature_table`, then add an override css to [extra.css](https://github.com/kubernetes/kops/blob/master/docs/extra.css) like 

```
.kops_feature_table table {
    max-width: fit-content;
}``` 

But to your point, this is easily fixed in a separate PR if someone spends the time on it. I'm fine without it for now. Thanks for the hard work on this, it's great!

**Comment by MoShitrit** [comment]
> Hmm gotcha, you should be able to change `max-width: 100%;` to `max-width: fit-content;` on the table object, which worked for me at least. You would likely need to wrap the table in a div with a new class like `class=kops_feature_table`, then add an override css to [extra.css](https://github.com/kubernetes/kops/blob/master/docs/extra.css) like
> 
> ```
> .kops_feature_table table {
>     max-width: fit-content;
> }
> ```
> 
> But to your point, this is easily fixed in a separate PR if someone spends the time on it. I'm fine without it for now. Thanks for the hard work on this, it's great!

Yas!!! Got it now. I had to do it with a subclass, but your pointer took me to where I needed 😄 

image
 
Pushing up the commit now so you can see the code change.

Thanks for that, @mikesplain ! 🙇‍♂️

**Comment by MoShitrit** [comment]
Updated example with the fixed table width: https://deploy-preview-9555--kubernetes-kops.netlify.app/networking/cilium/#enabling-encryption-in-cilium

**Comment by MoShitrit** [comment]
Looking to get a 👍 whenever anyone has a free cycle

**Comment by MoShitrit** [comment]
Looking to get a 👍 whenever anyone has a free cycle
@mikesplain @rifelpet

**Comment by hakman** [comment]
@MoShitrit could you also add the `hack/` dir to this list to trigger docs updates on modules changes?
https://github.com/kubernetes/kops/blob/8c3b4e4f430914b8a95bfa2f571dc273979f6d1d/netlify.toml#L5

**Comment by MoShitrit** [comment]
@hakman done! 🚀 😄  https://github.com/kubernetes/kops/pull/9555/commits/d43c9b5169aab580feef0456c87134343cf9141b

**Comment by rifelpet** [comment]
looks great, thanks again! hopefully we can get this setup with all the other feature docs too.

/approve

**Pull request merged**
