### PR TITLE
Add support for containerd v1.4.0

### PR DESCRIPTION
**Pull request by hakman**
https://github.com/containerd/containerd/releases/tag/v1.4.0

### CODE REVIEW

**Comment by johngmyers** [comment]
Typo: "contained"

**Comment by hakman** [comment]
> Typo: "contained"

Hehe. Thanks. Fixed.

**Comment by hakman** [comment]
New `pull-kops-e2e-k8s-containerd` test passing 3 times in a row. I think this is good to go.
https://prow.k8s.io/pr-history/?org=kubernetes&repo=kops&pr=9777

**Comment by rifelpet** [comment]
Is k/k 1.19 defaulting to containerd 1.4.0 ?

**Comment by hakman** [comment]
k/k is testing against containerd master. There is no guideline yet for release versions and containerd.

**Pull request merged**
