### PR TITLE
Re-add inadvertently-dropped deprecation notices

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
@johngmyers Seems that something is broken with kubelet, probably when populating the API server URL:
```
E1119 02:45:17.151948    6143 run.go:74] "command failed" err="failed to run Kubelet: failed to initialize kubelet client: host must be a URL or a host:port pair: \"https://\""
```

**Comment by johngmyers** [comment]
I have not been able to reproduce this in my own environment.

**Comment by hakman** [comment]
> I have not been able to reproduce this in my own environment.

I have been able to reproduce, but don't understand why it happens yet. On new nodes, `/var/lib/kubelet/kubeconfig` has `clusters[0].cluster.server: https://`.

**Comment by johngmyers** [comment]
I think it's running a kops built off of the branch against a nodeup built off of the presumed merge or vice versa.

**Comment by hakman** [comment]
Seems similar to what I managed to find. Let's see if manual rebase helped.

**Comment by johngmyers** [comment]
#14566 was able to bring the cluster up after a rebase.

**Comment by hakman** [comment]
Maybe something is broken with automated rebase?

**Comment by johngmyers** [comment]
I suspect pull-kops-build is misconfigured.

**Comment by hakman** [comment]
If it would be misconfigured, manual rebase would not help use the correct nodeup binary.
/lgtm

**Comment by johngmyers** [comment]
It could be that a rebase causes pull-kops-build to rerun and update nodeup, whereas another PR landing on master doesn't.

**Comment by hakman** [comment]
`pull-kops-build` doesn't actually push things (or at least it's not supposed to).

**Comment by johngmyers** [comment]
Okay, I'm not sure what uploads nodeup to the bucket.

**Comment by hakman** [comment]
Each job uploads its own build to the bucket, diferent dirs. Not very optimal, but works ok.

**Pull request merged**
