### PR TITLE
Release 1.12.0-alpha.1

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Still thinking through the strategy here, but I think...

* For the current alpha series, we don't branch yet (to avoid too many cherry-picks)
* Once we do a beta, we cut the release branch
* We do alphas much earlier in the process and more frequently (as discussed)
* We split up the release process; currently I create this commit, build, push and tag all in one.
* I actually think that the dnscontroller is going to have a problem here, but we'll see.  Likely we should be using CI builds for dns-controller anyway (or we should extract dns-controller entirely / switch to external-dns)
* The committers can discuss whether we're ready for the release, and if so we merge it.
* CI should build the commit as normal
* I think we can then extract the particular release and "promote it".  I think that'll work - but we can try with 1.12.0-alpha.1!
* Maybe we can use a signed git tag, but they may also be more trouble than it is worth.

**Comment by mikesplain** [comment]
Thanks @justinsb!

/lgtm
Pending hold

**Comment by mikesplain** [comment]
Great bullets! I like it, thanks @justinsb!
/lgtm remove

**Comment by justinsb** [comment]
@mikesplain I think now that this is green if you're able to give it lgtm I can try to figure out how to release from the CI build (and that it works as expected!)

**Comment by justinsb** [comment]
Thanks @mikesplain 

Let's see if this works!

/hold cancel

**Comment by rdrgmnzs** [comment]
Not Mike, but this looks great! Thanks @justinsb !

/lgtm

**Comment by mikesplain** [comment]
Missed this! Thanks so much @justinsb!!

/lgtm
/approve

**Comment by Benjamin-Dobell** [comment]
Should this have triggered a nodeup build?

It seems that https://kubeupv2.s3.amazonaws.com/kops/1.12.0-alpha.1/linux/amd64/utils.tar.gz does not exist.

**Comment by gtpgi** [comment]
To add on @Benjamin-Dobell comment it looks like other files like protokube.tar.gz and nodeup are also missing from https://kubeupv2.s3.amazonaws.com/kops/1.12.0-alpha.1/. At the moment, I cannot create a cluster due to the missing files.

**Pull request merged**
