### PR TITLE
Reduce size of images using debian-base

### PR DESCRIPTION
**Pull request by aledbf**
replaces #1355

### CODE REVIEW

**Comment by aledbf** [comment]
@chrislovecnm ping

**Comment by chrislovecnm** [comment]
e2e failed

**Comment by aledbf** [comment]
@chrislovecnm how can we test the protokube image? 
From the error log `image library/protokube:pull-ef3f77b not found`

**Comment by aledbf** [comment]
Just in case I started a cluster using the `hack/dev-build.sh` script without issues.

**Comment by justinsb** [comment]
Looks good other than the fact that e2e is not happy

**Comment by chrislovecnm** [comment]
@aledbf ping me on slack if you like, but how are you testing?  The e2e cluster is not starting.

**Comment by justinsb** [comment]
Looks like the protokube image needs systemctl (to start kubelet):

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/2885/pull-kops-e2e-kubernetes-aws/2128/artifacts/ec2-34-203-245-131.compute-1.amazonaws.com/protokube.log

`W0713 16:12:07.392453       1 kube_boot.go:141] error ensuring kubelet started: error starting kubelet: exec: "systemctl": executable file not found in $PATH`

**Comment by aledbf** [comment]
@justinsb fixed

**Comment by chrislovecnm** [comment]
Nutty question, but shouldn't we be using the images systemctl and not the containers?

**Comment by chrislovecnm** [comment]
@justinsb 1.7.0 or 1.7.2 for this?

**Comment by aledbf** [comment]
> Nutty question, but shouldn't we be using the images systemctl and not the containers?

Yes but that's could be done in another PR? (just because of the scope of the changes)

**Comment by justinsb** [comment]
Thanks @aledbf

**Pull request merged**
