### PR TITLE
New cloud provider: Spotinst

### PR DESCRIPTION
**Pull request by liranp**
This PR adds a new (and virtual) cloud provider, [Spotinst](https://spotinst.com/).

---

The implementation replaces AWS Auto Scaling groups (and in the future also GCE Instance Groups) with Spotinst Elastigroups, so the only part that is different from the AWS/GCE implementation is the compute part. For example, creating an IAM role using the Spotinst provider is exactly the same as creating it using the AWS provider, behind the scenes the role is created by `awsup.AWSCloud` in both implementations.

Currently, this implementation duplicates all AWS tasks and replaces every `cloud.(awsup.AWSCloud)` with `cloud.(*spotinst.SpotinstCloud).CloudProvider().(awsup.AWSCloud)` which implemented as follows:

```go
type SpotinstCloud struct {
    Cloud   fi.Cloud // awsup.AWSCloud or gce.GCECloud
    Service elastigroup.Service
}

func NewSpotinstCloud(cluster *kops.Cluster) (*SpotinstCloud, error) {
    cloudProviderID := GuessCloudFromClusterSpec(&cluster.Spec)
    if cloudProviderID == "" {
        return nil, fmt.Errorf("spotinst: unable to infer cloud provider from spec")
    }

    var cloud fi.Cloud
    var err error

    switch cloudProviderID {
    case kops.CloudProviderAWS, kops.CloudProviderGCE:
        cloud, err = buildCloud(cloudProviderID, cluster)
        if err != nil {
            return nil, err
        }
    default:
        return nil, fmt.Errorf("spotinst: unknown cloud provider: %s", cloudProviderID)
    }

    ...
    ...
    ...

    return &SpotinstCloud{
        Cloud:   cloud,
        Service: elastigroup.New(session.New(config)),
    }, nil
}

func (c *SpotinstCloud) CloudProvider() fi.Cloud {
    return c.Cloud
}

...
...
...
```

This is done in order to overcome the reflection error raised by `cloud.(awsup.AWSCloud)` while the concrete value held by the `fi.Cloud` interface is actually `*spotinst.SpotinstCloud`.

I'm not sure whether there is a better way to implement this, but I had to do it since all tasks (except for Spotinst Elastigroups) need to receive `awsup.AWSCloud` while the `fi.Cloud` built by kops when using `--cloud spotinst` is actually `*spotinst.SpotinstCloud`.

Do you have an idea how can I improve this approach?

---

Once the cluster is created and nodes are spawned, there is no need to run Spotinst as a `cloud-controller-manager` cause the underlying cloud provider is either AWS or GCE, which is already handled by the current implementation of the existing `kube-controller-manager`. Since the cloud provider defined in `Cluster.Spec` doesn't match to the cloud provider defined in some components I had to change the validation code so this conflict won't fail the validation:

```go
...
if c.Spec.Kubelet != nil && (strict || c.Spec.Kubelet.CloudProvider != "") {
    if c.Spec.Kubelet.CloudProvider != "external" && k8sCloudProvider != c.Spec.Kubelet.CloudProvider && kops.CloudProviderID(c.Spec.CloudProvider) != kops.CloudProviderSpotinst {
        return field.Invalid(fieldSpec.Child("Kubelet", "CloudProvider"), c.Spec.Kubelet.CloudProvider, "Did not match cluster CloudProvider")
    }
}
...
```

### CODE REVIEW

**Comment by liranp** [comment]
Signed CNCF Corporate CLA.

**Comment by chrislovecnm** [comment]
When you have a chance if you could reach out. Love to get a better solution for your users.

**Comment by rjkernick** [comment]
@liranp Any updates on when this pull request will be worked on?

**Comment by liranp** [comment]
We did some work to improve this implementation. I'll submit a new PR later today.

**Comment by asobrien** [comment]
see: #5195

**Pull request closed without merging**
