### PR TITLE
Update copyrights for 2020

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by tanjunchen** [comment]
/ok-to-test
why not consider update all copyright?

**Comment by johngmyers** [comment]
I don't understand the question. This is the result of `make apimachinery`, needed for anything to pass CI.

**Comment by tanjunchen** [comment]
> I don't understand the question. This is the result of `make apimachinery`, needed for anything to pass CI.

ok i get it

**Comment by hakman** [comment]
@johngmyers I think this should go also to 1.15. I bet there would be at least one more release for it soon.

**Pull request merged**
