### PR TITLE
replace behavior for @aws hostnameOverride

### PR DESCRIPTION
**Pull request by jacksontj**
Potential fix for #7172

### CODE REVIEW

**Comment by jacksontj** [comment]
The failures now seem to be related to bazel; but I don't see docs anywhere on what I should be updating to make bazel happy with the new imports :/

**Comment by jacksontj** [comment]
@mikesplain tests are passing now :)

**Comment by jacksontj** [comment]
cc @KashifSaadat and @rdrgmnzs (since they are marked as reviewers)

This unblocks usage of NodeAuthorizer in AWS VPCs with DHCP options set.

**Comment by jacksontj** [comment]
cc @gambol99 (since it seems that you own the NodeAuthorizer stuff) :)

**Comment by jacksontj** [comment]
Interesting, I just squashed the commits and now the tests are failing.. have to look into this but I expect some issue with the testing harness

**Comment by justinsb** [comment]
Thanks for tracking down the project @jacksontj ... I'm inclined to go with this fix as it matches the aws cloudprovider code.  It's a new EC2 call, but it's only one, and we should have the IAM role anyway because kubelet needs it.

It should be no-change in the case of users not using a custom DHCP domain.

(We probably should also clean up the code duplication here!)

/lgtm
/retest

**Comment by jacksontj** [comment]
> (We probably should also clean up the code duplication here!)

I agree, I just figured we should get the fix in sooner rather than later (especially since the duplication was already there ;) )


Also seems that tests are passing now, so ready to merge :) Once this is merged I'll open backports for this like my other patches.

**Comment by justinsb** [comment]
We talked about this in office-hours ...

/approve

**Pull request merged**
