### PR TITLE
Run CSI controller in masters

### LINKED ISSUE #13425: CSI provisioning does not work for GCE
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.23.5

**3. What cloud provider are you using?**

GCE

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I created new cluster and after that I deployed application that uses PVC. 

**5. What happened after the commands executed?**

```
% kubectl get pvc -n monitoring
NAME                                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-k8s-db-prometheus-k8s-0   Pending                                      standard-csi   4m29s
prometheus-k8s-db-prometheus-k8s-1   Pending                                      standard-csi   3m50s
```

I see following in csi provisioner logs

```
% kubectl logs csi-gce-pd-controller-7cc567ddc9-9cqfn -c csi-provisioner
...
Reason: forbidden, Message: Required 'compute.disks.create' permission for 'projects/x/zones/europe-north1-a/disks/pvc-91238f39-a327-4004-8fc8-613809d13ecd'
Reason: forbidden, Message: Required 'compute.disks.setLabels' permission for 'projects/x/zones/europe-north1-a/disks/pvc-91238f39-a327-4004-8fc8-613809d13ecd'
```

So I think we are missing some permissions from GCE service account. Seems that CSI controller is running in nodes, so is it using node service account? There can be also other permissions that are missing, I think we could allow compute.disks.*?

### PR DESCRIPTION
**Pull request by zetaab**
fixes #13425

I tested creating new pvcs, resizing them and deleting. Everything works smoothly now.

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]
Until we support pod identities on GCP

**Comment by zetaab** [comment]
@olemarkus can you readd lgtm, I updated the expected test files

**Pull request merged**
