### PR TITLE
chore(channels): update alpha k8s and ubuntu ami versions

### PR DESCRIPTION
**Pull request by moshevayner**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by moshevayner** [comment]
@hakman looks like we have another failing test (seems unrelated to my change) - the `e2e-scenarios-bare-metal` is also failing, looks like it can't find the s3 bucket? Is that a known issue?

**Pull request merged**
