### PR TITLE
Add support for Kubenet with containerd

### PR DESCRIPTION
**Pull request by hakman**
Docker generates the a conflist file for Kubenet when needed.
containerd has a different approach:
https://github.com/containerd/cri/blob/master/docs/config.md#cni-config-template

At some point, Kubenet will migrate to CNI and this workaround can be removed. Until then, this is the default in Kops and should be added, if possible.
https://github.com/kubernetes/kubernetes/issues/38890

CNI config template is based on:
https://github.com/containerd/cri/blob/master/hack/install/install-cni-config.sh

### CODE REVIEW

**Comment by hakman** [comment]
Test results with containerd enabled:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/9104/pull-kops-e2e-kubernetes-aws/1260139702028079105

**Comment by hakman** [comment]
Test results with containerd enabled:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/9104/pull-kops-e2e-kubernetes-aws/1260139702028079105

**Comment by hakman** [comment]
Test results with containerd enabled:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/9104/pull-kops-e2e-kubernetes-aws/1260139702028079105

**Comment by hakman** [comment]
Test results with containerd enabled:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/9104/pull-kops-e2e-kubernetes-aws/1260139702028079105

**Comment by hakman** [comment]
@olemarkus maybe you can have a look at this. Seems somehow related to the work you are doing in CNI plugins reorg. Thanks!

**Comment by olemarkus** [comment]
Looks good. Just generally look use `components.UsesKubenet` as this will then also work with other networking providers that uses kubenet, GCE in particular.

**Comment by hakman** [comment]
Thanks @olemarkus hopefully at some point this will be simplified.

**Pull request merged**
