### PR TITLE
Add best practices to getting started with GCE docs

### PR DESCRIPTION
**Pull request by danielvegamyhre**
The purpose of these changes is to document some best practices when using kOps to create and administer a k8s cluster in GCP. For each best practice, I included a description of why it is considered a best practice, as well as example kops commands to utilize it.

Currently the best practices I have included are:
- Using spot instances to reduce cost for fault-tolerant workloads
- Using a multi-zonal cluster to ensure high availability in the event of an datacenter/rack/server outage

I tested these changes using `make live-docs` to view my changes locally.

Let me know if there are additional best practices we should add and I will be happy to do so.

### CODE REVIEW

**Review by justinsb — APPROVED** [review]

**Comment by justinsb** [comment]
Awesome, thank you @danielvegamyhre 

I like the idea of guiding users a bit more as to "things they should be doing", in addition to describing all the things they can do!

/ok-to-test
/approve
/lgtm

**Comment by justinsb** [comment]
I'll have a look at why these tests are suddenly failing, it's surprising and I can't see how it could relate to a docs PR :-)

**Comment by hakman** [comment]
@justinsb We noticed something similar on other PRs. Somehow it seems like rebase doesn't work well.

**Comment by justinsb** [comment]
The problem looks to be this from kubelet:

```
E1122 01:21:31.667344    3391 run.go:74] "command failed" err="failed to run Kubelet: failed to initialize kubelet client: host must be a URL or a host:port pair: \"https://\""
```

I think the issue is that we build from source, but then when we upload we might not run with the matching nodeup, because we don't always upload it:

From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/14569/pull-kops-e2e-k8s-aws-calico/1594860036918611968/build-log.txt

```
...
== Uploading kops ==
gsutil -h "Cache-Control:private, max-age=0, no-transform" -m cp -n -r /home/prow/go/src/k8s.io/kops/.build/upload/kops/* gs://kops-ci/pulls/pull-kops-e2e-k8s-aws-calico/pull-84a7c3abb9d71cacca2159b3e43d6a3f4b18fceb
Skipping existing item: gs://kops-ci/pulls/pull-kops-e2e-k8s-aws-calico/pull-84a7c3abb9d71cacca2159b3e43d6a3f4b18fceb/1.26.0-alpha.2+v1.26.0-alpha.1-417-g60386cc0de/linux/amd64/protokube
Skipping existing item: gs://kops-ci/pulls/pull-kops-e2e-k8s-aws-calico/pull-84a7c3abb9d71cacca2159b3e43d6a3f4b18fceb/1.26.0-alpha.2+v1.26.0-alpha.1-417-g60386cc0de/linux/amd64/channels
Skipping existing item: gs://kops-ci/pulls/pull-kops-e2e-k8s-aws-calico/pull-84a7c3abb9d71cacca2159b3e43d6a3f4b18fceb/1.26.0-alpha.2+v1.26.0-alpha.1-417-g60386cc0de/linux/amd64/kops.sha256
Skipping existing item: gs://kops-ci/pulls/pull-kops-e2e-k8s-aws-calico/pull-84a7c3abb9d71cacca2159b3e43d6a3f4b18fceb/1.26.0-alpha.2+v1.26.0-alpha.1-417-g60386cc0de/linux/amd64/kops
...
```

We should fix this, but probably not in this PR.  I'm going to merge this one manually.

**Comment by hakman** [comment]
> The problem looks to be this from kubelet:

The kubeconfig has an empty server. Using a locally built nodeup binary, I don't see this issue. Rebasing a PR would also fix the issue.

**Pull request merged**
