### PR TITLE
Run some scenarios on ARM

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
@olemarkus Any thoughts on these failures in `pull-kops-e2e-aws-load-balancer-controller` ?

**Comment by olemarkus** [comment]
The test clones the master branch, so it could be that a bump will solve this. I'll have a look.

**Comment by hakman** [comment]
Should we just make the test optional for now?

**Comment by johngmyers** [comment]
It is optional, I opted to run it because I'm changing the test to arm. I believe the test or it's infra is broken because I have an LBC PR that is also failing to merge on E2E tests.

**Comment by johngmyers** [comment]
The LBC pull test is failing on master, so I'm not going to run it for this PR.

**Pull request merged**
