### PR TITLE
ineffectual assignment to

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@zetaab

**Comment by tanjunchen** [comment]
@zetaab

**Comment by tanjunchen** [comment]
@robinpercy

**Comment by tanjunchen** [comment]
@justinsb   @chrislovecnm

**Comment by tanjunchen** [comment]
@joshbranham

**Comment by tanjunchen** [comment]
@mikesplain How about this?

**Comment by tanjunchen** [comment]
@robinpercy  can you  review it?

**Comment by tanjunchen** [comment]
@rdrgmnzs  can you review it? THX

**Comment by tanjunchen** [comment]
@justinsb

**Comment by justinsb** [comment]
Thanks @tanjunchen 

/approve
/lgtm

**Pull request merged**
