### PR TITLE
bump dns-controller to adopt the aws china region support

### PR DESCRIPTION
**Pull request by qqshfox**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
A custom version is what I was attempting to type

**Comment by qqshfox** [comment]
how about tagging dns-controller the same way as other assets? so we can bump `dns-controller` along with kops.

**Comment by justinsb** [comment]
Sorry - this is my fault.

I actually already did this, as part of 1.7.0-beta.1

But ... I didn't cherry-pick back to master; I'll send a PR now

**Comment by justinsb** [comment]
PR is #3005

**Comment by qqshfox** [comment]
closed as #3005 got merged

**Pull request closed without merging**
