### PR TITLE
Backport rename of service-account key to 1.20

### PR DESCRIPTION
**Pull request by johngmyers**
Addresses #11370

### CODE REVIEW

**Comment by justinsb** [comment]
Like #11390, this looks good, but I propose we get an upgrade e2e periodic test in asap

/hold

**Comment by hakman** [comment]
@justinsb should be covered by @rifelpet's new upgrade test:
https://testgrid.k8s.io/kops-misc#kops-aws-kops-upgrade

I see this in logs, which I am not sure if it's the expected change:
```
  Keypair/service-account
  	Signer              	 id:cn=service-account -> <nil>
  	LegacyFormat        	 true -> false
```

**Comment by johngmyers** [comment]
@hakman The LegacyFormat change is saying that it will upgrade the format (by copying it from the "master" slot to "service-account". For the "Signer" field, `nil` means "self-signed" so it is not an actual change.

**Comment by johngmyers** [comment]
For an upgrade from 1.18 or earlier, the signer would change from "ca" to being self-signed.

**Comment by justinsb** [comment]
Reproducing #11390 is non-trivial (which is a good thing, as it means this isn't _as_ critical as it first appears)!

/hold cancel

/approve
/lgtm

**Pull request merged**
