### PR TITLE
Validate at most one networking option chosen

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by olemarkus** [comment]
Great work. Really appreciate these CNI specific functions.

**Comment by rifelpet** [comment]
Do you think it is worth adding a test that covers specifying two CNI providers and ensuring an error is returned? otherwise it looks good to me

**Comment by johngmyers** [comment]
I considered a test, but in order to be even remotely effective it would have to exercise all combinations of two providers chosen from all other than Classic. It seemed to have too little benefit for the cost, especially given the current state of the api validation code.

**Comment by rifelpet** [comment]
I agree the benefit from a test is not worth the effort.

/lgtm
/approve

**Pull request merged**
