### PR TITLE
Initial Amazon Linux 2023 support

### PR DESCRIPTION
**Pull request by rifelpet**
This is untested, I'll add an e2e job once this merges. I'll update docs once we confirm its working.

### CODE REVIEW

**Comment by rifelpet** [comment]
Actually, since we create a new presubmit job, i can iterate on AL2023 support on this PR. Marking this as WIP and we can merge the test-infra PR first: https://github.com/kubernetes/test-infra/pull/29072

**Comment by hakman** [comment]
Time to check if we still need to install these in general? 😁 
https://github.com/kubernetes/kops/blob/ed8cf86d7c3e9ff3f3261062b9fe1e7c1ef1b93c/nodeup/pkg/model/miscutils.go#L47-L51

**Comment by hakman** [comment]
I vote for "altogether in kops 1.27" + release note.

**Comment by rifelpet** [comment]
This is ready to go, that was surprisingly easy

**Comment by hakman** [comment]
> This is ready to go, that was surprisingly easy

Yep, it usually is these days.

/lgtm
/approve

**Comment by hakman** [comment]
@rifelpet Do you want to also add entry in docs and release note for it?

**Review by hakman — APPROVED** [review]

**Pull request merged**
