### PR TITLE
Add "m4.16xlarge" type

### PR DESCRIPTION
**Pull request by ryanlitalien**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2359)

### CODE REVIEW

**Comment by ryanlitalien** [comment]
Signed CNCF CLA

**Comment by geojaz** [comment]
@k8s-bot ok to test

**Comment by geojaz** [comment]
@ryanlitalien I kicked off the e2e testing, but it looks like you need to run `go fmt ` to get your formatting cleaned up. It runs as part of `make ci` in the main kops repo and it's a good idea to run it pre-commit. 

Otherwise, LGTM. Clean up your formatting, get the testing to work, and I'll merge. Thanks for your contribution!

**Comment by justinsb** [comment]
LGTM also once gofmt is happy :-)

**Comment by ryanlitalien** [comment]
@geojaz @justinsb Hey guys, Github seemed to add an extra invisible spacer in the first attempt. You should be able to squash and merge. Thanks!

**Pull request merged**
