### PR TITLE
Bump cilium to 1.13

### PR DESCRIPTION
**Pull request by olemarkus**
/hold until cilium 1.13 is GA

### CODE REVIEW

**Comment by johngmyers** [comment]
Does Cilium support upgrading directly from 11 to 13? They haven't supported two-minor-version upgrades before.

This newer approach of only supporting one minor version of Cilium at a time means that users won't be able to skip kops minor versions. I don't think we've made that clear in our documentation.

**Comment by olemarkus** [comment]
If we want multiple cilium versions support, I want those other versions in the grid though. Sometimes RBAC and other things change in minor versions, or there can be other things we do outside of cilium (e.g distro change) that needs testing.

**Comment by johngmyers** [comment]
The [Cilium upgrade documentation](https://docs.cilium.io/en/stable/operations/upgrade/#version-specific-notes) only makes assertions about single-minor-version upgrades between 1.9 and 1.12. There's no information about 1.13 yet.

**Comment by anthonyhaussman** [comment]
Cilium `1.13` is out now :tada:

**Comment by zadjadr** [comment]
@olemarkus can we reopen this ? I believe 1.14.0 is not out, while Kops is still on 1.12.0

**Comment by hakman** [comment]
Should be addressed by https://github.com/kubernetes/kops/pull/15730.

**Pull request closed without merging**
