### PR TITLE
Update aws-sdk-go to 1.12.56

### PR DESCRIPTION
**Pull request by leeeboo**
The aws-sdk-go must be update for the new region in China cn-northwest-1.
Because the old on can not pass the function "validateRegion" in file "util/pkg/vfs/s3context.go".

### CODE REVIEW

**Comment by leeeboo** [comment]
I follow the step https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md to update the  dependenc. Why it can not pass the ci?
I can build and run an my mac.

**Comment by leeeboo** [comment]
Or some one can help me to upgrade the aws sdk so that we can use the next kops release version to manage kubernetes on cn-northwest-1. Thanks!

**Comment by chrislovecnm** [comment]
@leeeboo with this update they have changed the interface.  Please run `make test` or `make ci`, and you will see the error.  

The error is also in the travis logs see https://travis-ci.org/kubernetes/kops/jobs/326239351

if you can also update the bazel files as well, it would require you to install bazel and run the bazel make target.

**Comment by leeeboo** [comment]
@chrislovecnm Thank you for your reply. But I can not figure out the error from `make ci OR make test`. I just start use kops to manage my kubernetes and not very understand on it....
Can you help me? Thanks!

**Comment by leeeboo** [comment]
@chrislovecnm I found the error. In package `mockec2` in folder `k8s.io/kops/cloudmock/aws/`. But I don' t know how to edit it.

If the next version of kops want to support cn-northwest-1, the aws-sdk-go must be updated.
But the aws sdk changed some interface, so that the project can not pass the test.

**Comment by leeeboo** [comment]
@chrislovecnm Maybe I found the problem. I will pr agion. Thanks.

**Pull request closed without merging**
