### PR TITLE
Update kops_validate.md

### PR DESCRIPTION
**Pull request by orrchen**
changed typo in validate command - kops instead of kubernetes

### CODE REVIEW

**Comment by orrchen** [comment]
Contributor License is signed

**Comment by chrislovecnm** [comment]
Thanks for the PR!

This documentation is actually generated from go code, so you would need to make the update in the go code. See  https://github.com/kubernetes/kops/blob/master/cmd/kops/validate.go

Once that is done please run the make target gen-cli-docs, and check in the go and md files.  Sorry about the confusion, we added a note to the md files, but I guess that is not enough :(

**Comment by orrchen** [comment]
Thanks @chrislovecnm  , I would be happy to do this change, but struggling with first compiling the project to build it for the PR. Is there a guide to it? Couldn't find it.

**Comment by orrchen** [comment]
OK, got it to guild and generated the docs with `make gen-cli-docs` . However the `docs/cli/kops_validate.md` is being generated without the fix... Am I missing something? output of the make command:
`go build  -ldflags "" -o ${MY_GOPATH}/bin/go-bindata k8s.io/kops/vendor/github.com/jteeuwen/go-bindata/go-bindata
cd ${MY_GOPATH}/src/k8s.io/kops; ${MY_GOPATH}/bin/go-bindata -o upup/models/bindata.go -pkg models -ignore="\\.DS_Store" -ignore="bindata\\.go" -ignore="vfs\\.go" -prefix upup/models/ upup/models/...
cd ${MY_GOPATH}/src/k8s.io/kops; ${MY_GOPATH}/bin/go-bindata -o federation/model/bindata.go -pkg model -ignore="\\.DS_Store" -ignore="bindata\\.go" -prefix federation/model/ federation/model/...
go install  -ldflags "-X k8s.io/kops.Version=1.7.0 -X k8s.io/kops.GitVersion=794286972 " k8s.io/kops/cmd/kops/...
KOPS_STATE_STORE= \
	KOPS_FEATURE_FLAGS= \
	${MY_GOPATH}/bin/kops genhelpdocs --out docs/cli`

I have replaced the real printed GOPATH with ${MY_GOPATH}

**Pull request closed without merging**
