### PR TITLE
Set default master size for ca-central-1 and eu-west-2

### LINKED ISSUE #1455: Default AWS instances for master (m3.medium) is not available in all aws regions.
In newer regions, for example `ca-central-1`, there are no options for m3 instances.
In fact the only medium instance that you can request is a `t2.medium`.

If `t2.medium` is acceptable it should be the default. If not I think you need to move to an `m4.large`

Or at the very least add a warning to the readme...

### PR DESCRIPTION
**Pull request by justinsb**
These newer regions don't support the m3 family; a c4.large is the
cheapest non-burstable instance.

Fix #1455

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1461)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Does K8s support the regions now?

**Comment by justinsb** [comment]
k8s supports ca-central-1 in 1.5.2, london missed the cut

**Comment by chrislovecnm** [comment]
CI is not happy ;(

**Pull request merged**
