### PR TITLE
Bump AWS CNI to 1.12.2

### PR DESCRIPTION
**Pull request by moshevayner**
https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.12.2

### CODE REVIEW

**Review by hakman — APPROVED** [review]
Thanks @moshevayner. 😉

**Comment by moshevayner** [comment]
> /hold for fixing the `pull-kops-e2e-k8s-aws-calico` test

@hakman did the PR break something? Or is this a hold for fixing the flaky test?

**Comment by hakman** [comment]
The PR is OK. There is a problem with how systemd restarts during packages upgrades.

**Comment by moshevayner** [comment]
Gotcha. Thanks for clarifying!

**Comment by moshevayner** [comment]
Hey @hakman !
Any luck so far? 🥺

**Comment by hakman** [comment]
I think we are good now. 🤠 
/unhold

**Pull request merged**
