### PR TITLE
Switch to 1.11.1

### PR DESCRIPTION
**Pull request by mikesplain**
Since k/k now uses go 1.11.1 we should probably test and suggest users
do the same?

https://github.com/kubernetes/kubernetes/blob/8c0542dcf126222481390cd0606e3b7f43830a64/hack/lib/golang.sh#L385

### CODE REVIEW

**Comment by mikesplain** [comment]
Thoughts @justinsb? 

/assign @justinsb

**Comment by mikesplain** [comment]
This may require https://github.com/kubernetes/kops/pull/6144

**Comment by chrisz100** [comment]
Sounds reasonable.

**Comment by rdrgmnzs** [comment]
Looks like that is targeted for k/k 1.13. The 1.12 branch is still using go1.10  .2 https://github.com/kubernetes/kubernetes/blob/release-1.12/hack/lib/golang.sh#L363

**Comment by mikesplain** [comment]
I would support that @rdrgmnzs! Makes sense to me... that said, if we're branching 1.12 soon, we can hold this for use in master soon after.

**Comment by justinsb** [comment]
Yes, I think we can't do this until 1.13 (which is annoying, I know - particularly the gofmt changes!)

I did put on today's agenda a discussion of whether to actually release kops 1.12 alpha.1, 1.13 alpha.1 and maybe even 1.14 alpha.1...

/milestone 1.13

**Comment by chrisz100** [comment]
Makes sense to push this some time now, but i see a lot of changes required before Travis passes this

**Comment by mikesplain** [comment]
Ahh yeah thanks, I’ll revisit

**Comment by rdrgmnzs** [comment]
/close

Closing as the changes to bump the go version were merged in a different PR.

**Pull request closed without merging**
