### PR TITLE
Add additional config for node local dns

### PR DESCRIPTION
**Pull request by zetaab**

### CODE REVIEW

**Comment by zetaab** [comment]
no idea why that upgrade test fails

**Comment by hakman** [comment]
> no idea why that upgrade test fails

Unrelated, etcd upgrade fails.

**Comment by hakman** [comment]
@justinsb The only question here is which is preferred `ExtraConfig` or `AdditionalConfig`?

**Comment by hakman** [comment]
@zetaab Based on the chat I had with @justinsb yesterday, I think it would be preferable to use `AdditionalConfig` instead of  `ExtraConfig`. Does it sound reasonable to you?

**Comment by zetaab** [comment]
yeah I can change that

**Comment by zetaab** [comment]
blah, I need to fix this with time. rebase did not went quite well

**Comment by zetaab** [comment]
fixed

**Review by hakman — APPROVED** [review]

**Pull request merged**
