### PR TITLE
[Fixes #2514] s/kopeio/kopeio-vxlan when parsing from config file

### LINKED ISSUE #2514: kopeio vs kopeio-vxlan
When creating a cluster, the following works:

```
		--networking "kopeio-vxlan" \
```

However when editing the cluster yaml file, the following won't work (it reverts back to kubenet):

```yaml
  networking:
    kopeio-vxlan: {}
```

This works however:

```yaml
  networking:
    kopeio: {}
```

It would be less confusing if we stuck to one name, either `kopeio` OR `kopeio-vxlan`.

### PR DESCRIPTION
**Pull request by dolftax**
Signed-off-by: Jaipradeesh Janarthanan <jaipradeesh@gmail.com>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2525)

### CODE REVIEW

**Comment by dolftax** [comment]
I signed it.

**Comment by chrislovecnm** [comment]
This is an API change, not sure if we want this.  Changing the json, changes our clusterspec.

**Comment by justinsb** [comment]
I agree we should address the issue, but changing the API is a big deal - it would break everyone's existing clusters.

We have some validation for invalid properties on a `kops edit`; we probably need similar logic for `kops create` and `kops replace`.

We can also recognize kopeio for `kops create cluster`, which would be more consistent.  We should recognize both `kopeio` and `kopeio-vxlan`.

The intention here is that kopeio networking can also support ipsec / gre and other modes.  vxlan is the currently supported option by kops.

**Comment by dolftax** [comment]
https://github.com/kubernetes/kops/pull/2525#issuecomment-300571350

**Pull request closed without merging**
