### PR TITLE
Spotinst: Upgrade the Spotinst controller to version 1.0.57

### PR DESCRIPTION
**Pull request by liranp**
This PR upgrades the Spotinst controller to version 1.0.57 and aligns all resources with the corresponding Helm [chart](https://github.com/spotinst/spotinst-kubernetes-helm-charts).

### CODE REVIEW

**Comment by rifelpet** [comment]
:( we rely on ifconfig.co to get our public ip address in e2e jobs. @hakman has an improvement for this here: https://github.com/kubernetes/test-infra/pull/16834 that we'll need merged. I suppose we can periodically retry this e2e job too.

**Comment by liranp** [comment]
@rifelpet Thank you so much for reviewing this!

**Pull request merged**
