### PR TITLE
create encrypted volume during initiation cluster

### PR DESCRIPTION
**Pull request by pronix**
in PR https://github.com/kubernetes/kops/pull/398 added option encrypt volume by editing yaml after initialisation cluster. I added option to do it on first step ``` --encrypt-volume``` and cluster has encrypted volume - user friendly :)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2271)

### CODE REVIEW

**Comment by pronix** [comment]
@justinsb hello. any recommendations ?

**Comment by pronix** [comment]
hello
i need feedback for improve code or merge.
my current project should use kops with encrypted network and ebs. 
other way it will required support fork

**Comment by justinsb** [comment]
Sorry this one fell through the cracks @pronix 

Can I suggest we have a flag `--encrypt-etcd-storage=true`, or `--encrypt-etcd-storage=aws`.  Because then we can also pass the kms key, with the same flag but a different value?

BTW, we have so far deliberately chosen not to expose every option through the CLI, on the grounds that at some stage power users will likely find just creating the cluster directly though yaml more convenient.  If you're going to specify everything in flag anyway, might as well specify it in yaml.  But this flag seems reasonable :-)

**Comment by pronix** [comment]
thanks @justinsb . i will update pr today.

**Comment by pronix** [comment]
hello @justinsb 
flag is changed. check please.

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Pull request merged**
