### PR TITLE
Automated cherry pick of #10048: Install container runtime packages as assets

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #10048 on release-1.19.

#10048: Install container runtime packages as assets - Main

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by johngmyers** [comment]
Holding for #10122

**Comment by hakman** [comment]
@johngmyers #10122 is just a question of building some new kope.io images and @justinsb said he will do that soon. Waiting for that to merge will most likely add conflicts.
Also, there is an easy way around this by using the official Debian image `379101102735/debian-stretch-hvm-x86_64-gp2-2020-07-20-58035`.

**Comment by hakman** [comment]
Thans @johngmyers :)

**Pull request merged**
