### PR TITLE
Adding equal resource requests/limits to flannel for guarenteed QoS

### PR DESCRIPTION
**Pull request by mihok**
Pretty straightforward, [according to docs](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md) setting the resource limits and requests the same it guarentees QOS for the pod.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2010)

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
I'm a little surprised this isn't in the upstream flannel manifest, but I agree that we should have it - in fact that we probably should have it for all our critical pods!

The other thing we need to be careful of is that we don't overallocate CPU, and that we can still fit on a single-core machine.  But I think we should be OK, based on docs/development/instancesizes.md

**Comment by mihok** [comment]
Agreed @justinsb, I'll probably be making a PR on that side as well, at the very least It will allow me to find out why its not there.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Pull request merged**
