### PR TITLE
fix validation for master kubelet api server

### PR DESCRIPTION
**Pull request by yancl**

### CODE REVIEW

**Comment by yancl** [comment]
I signed it!

**Comment by kris-nova** [comment]
Thanks for the PR @yancl!

Will keep an eye on this and get it in ASAP

**Comment by chrislovecnm** [comment]
Need you to sign the linux foundation cla :)

**Comment by yancl** [comment]
Thanks:)

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
