### PR TITLE
WIP: Does CI allow bindata.go to get out of sync?

### PR DESCRIPTION
**Pull request by johngmyers**

### CODE REVIEW

**Comment by justinsb** [comment]
Hmmm... you raise a good point!

**Comment by johngmyers** [comment]
And I raised it in #8584 well prior to its being merged.

**Comment by rdrgmnzs** [comment]
Did not realize #8584 had been merged. Have been busy with a few things and did not get a chance to get back to it. Let me work on adding a verify-bindata script.

**Comment by justinsb** [comment]
And sorry, I got confused because the verify test kept posting results so it looked like it was enabled, but now I'm not sure if they were in fact new results.

**Comment by rdrgmnzs** [comment]
Tested that the new verify-bindata script will fail if bindata is out of sync in #8881

**Pull request closed without merging**
