### PR TITLE
Update Go to v1.16

### PR DESCRIPTION
**Pull request by bmelbourne**
**What this PR does / why we need it**:
Upgrade Go to **v1.16**.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
Support for `GOPATH` mode will be deprecated in Go 1.17 and `GO111MODULE` environment variable will be ignored, 

https://blog.golang.org/go116-module-changes

### CODE REVIEW

**Comment by bharath-123** [comment]
Have submitted a similar PR https://github.com/kubernetes/kops/pull/10864 which got closed....

**Comment by olemarkus** [comment]
Thanks for this. I think we want to hold this one waiting for some of our larger deps to upgrade. at least the other kubernetes libs.

/hold

**Comment by bmelbourne** [comment]
ok no probs. I did a search for any open PRs before raising this hence why I missed the closed PR.

Happy to hold until the other Kubernetes and other dependencies are updated.

As already mentioned in Slack, I'm going to raise new PRs to cover upgrades to other Go module dependences.

**Comment by hakman** [comment]
We should wait for https://github.com/kubernetes/kubernetes/pull/98572 to merge and for 1.12.1 beta.1 to be released at least.

**Comment by olemarkus** [comment]
I think the test above should pass if `make gomod` is run with golang1.16 now.

**Comment by bmelbourne** [comment]
> I think the test above should pass if `make gomod` is run with golang1.16 now.

It certainly did last week, but I'm just waiting for Kubernetes to create the next `v1.21.0-beta.1` release, and then I'll do some further testing locally and do a final rebase.

**Comment by rifelpet** [comment]
I think the go upgrade is independent of any kubernetes release and our use of the kubernetes dependencies. 

I bumped the go versions in the go.mod files to 1.16 and running `make gomod` gave me the same go.mod and go.sum changes that the failing verify-gomod is expecting. Perhaps rebasing and committing the those changes can get this to succeed? All PRs are now blocked on this issue, so I would lean towards getting this merged sooner rather than later.

**Comment by hakman** [comment]
Tried it also and worked as @rifelpet described. Would be nice to get this in soon.

**Comment by bmelbourne** [comment]
> We should wait for [kubernetes/kubernetes#98572](https://github.com/kubernetes/kubernetes/pull/98572) to merge and for 1.12.1 beta.1 to be released at least.

@hakman @olemarkus @rifelpet 
If the general consensus is _not_ to wait for the next Kubernetes release built on Go v1.16, then I'll start working on the final rebase and local testing tonight and hopefully, all going well, it'll be ready for approval soon.

**Comment by hakman** [comment]
No worries, we all agreed that it's ok to merge now and upgrade the deps to 1.21-beta.1 next week.

**Review by hakman — APPROVED** [review]

**Comment by hakman** [comment]
Thanks @bmelbourne! 👍 
/retest

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
