### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by mycapatin**
Fix typo.

### CODE REVIEW

**Comment by mikesplain** [comment]
@mycapatin Thanks for the contribution! Good catch! Thanks so much!
/ok-to-test
/lgtm

**Comment by mycapatin** [comment]
@mikesplain Thanks for your reply!

**Comment by mycapatin** [comment]
assign @chrislovecnm

**Comment by justinsb** [comment]
/approve

Though kogs is a good name ;-)

Thanks @mycapatin

**Pull request merged**
