### PR TITLE
Fail when unable to mount etcd volumes

### PR DESCRIPTION
**Pull request by johanneswuerbach**
When the old master instance took some time to terminate the EBS volumes aren't mountable yet. Fail hard to ensure etcd and the kubelet are not starting before the volume is mounted.

Potentially fixes https://github.com/kubernetes/kops/issues/4128

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Sorry @mikesplain I changed it to actually return an error, which is handled more gracefully then just crashing.

If an error is returned here, protokube will revisit the mount code in its boot loop until all volumes have been mounted.

**Comment by mikesplain** [comment]
@johanneswuerbach No worries, that's why I figured it'd be best to just let the tests run before a review 😉  Thanks!

**Comment by justinsb** [comment]
So I'm not sure how the behaviour really changes here - we do try to mount volumes in a loop.  AFAICT the real change here is that if one volume fails to mount, we will immediately exit, but previously we would process the volumes we did mount.

Can you please clarify the reasoning behind the change for me @johanneswuerbach ?

**Comment by johanneswuerbach** [comment]
@justinsb following the code further I see how this works now and you are right.

In our cluster we had some cases when during a cluster rolling an old master server took a really long time to terminate, the replacement master booted already and the cluster was somehow marked as healthy without actually being able to unmount and remount the etcd EBS volumes from the old master to new master as they were still in-use.

The rolling proceeded afterwards and another master was killed causing an etcd quorum loss. Sadly I wasn't able to debug this further, but you are saying that shouldn't happen, correct?

**Comment by johanneswuerbach** [comment]
Looks like https://github.com/kubernetes/kops/pull/5446 is the actual cause of this issue, closing until I see the happening again.

**Pull request closed without merging**
