### PR TITLE
Use Ubuntu 20.04 as the default image for Kubernetes 1.18+

### LINKED ISSUE #9163: Debian 10 (Buster) or Ubuntu 20.04 (Focal)
Debian 9 (Stretch) is pretty old and will be replaced as base for the default image in Kops 1.18.

Debian 10 (Buster):
* Linux kernel 4.19
* more tested in the Kubernetes world
* natural upgrade from Debian 9
* defaults to iptables NFT (not supported by most CNI plugins)

Ubuntu 20.04 (Focal):
* Linux kernel 5.4
* has fixes for all known kernel bugs at this time (including conntrack ones)
* defaults to iptables Legacy (supported by most CNI plugins)
* very similar to Debian, so most custom hooks and user scripts should still work

There may be some other considerations that I am missing. If so, please add a commoent.

For those interested, plase add a vote:
❤️   - Debian 10 (Buster)
🚀 - Ubuntu 20.04 (Focal)

### PR DESCRIPTION
**Pull request by hakman**
As discussed in Kops Office Hours from Jun 5, 2020. 

Fixes #9163

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
Thanks @hakman !

/lgtm
/approve

**Comment by Moshem123** [comment]
If my Kubernetes version is v1.15.12, is it problem to use the Ubuntu 20.04 image?

**Comment by hakman** [comment]
@Moshem123 there should be no problem to use Ubuntu 20.04 with older versions of k8s, but you will have to use a newer version of kOps that supports it and set the k8s version manually to 1.15.x.

**Comment by Moshem123** [comment]
> @Moshem123 there should be no problem to use Ubuntu 20.04 with older versions of k8s, but you will have to use a newer version of kOps that supports it and set the k8s version manually to 1.15.x.

I'm using kOps latest (1.18.2) with kubernetes 1.15.12.
Thanks for confirming @hakman !!!

**Pull request merged**
