### PR TITLE
Adding DescribeTags to masters

### LINKED ISSUE #2681: aws-iam: Add autoscaling:DescribeTags
Latest versions of the cluster-autoscaler can automatically detect the ASG used by the nodes, but it requires that  `autoscaling:DescribeTags` rights are added to the AWS IAM policy.

### PR DESCRIPTION
**Pull request by robinpercy**
/fixes #2681

### CODE REVIEW

**Comment by gambol99** [comment]
hi @robinpercy ...CI isn't happy ... i believe you need to update the 
```shell
$ ls tests/integration/update_cluster/{additional_user-data,minimal-cloudformation}
tests/integration/update_cluster/additional_user-data:
cloudformation.json  cloudformation.json.extracted.yaml  id_rsa.pub  in-v1alpha2.yaml

tests/integration/update_cluster/minimal-cloudformation:
cloudformation.json  cloudformation.json.extracted.yaml  id_rsa.pub  in-v1alpha2.yaml
```

to fix the TestMinimalCloudformation and TestAdditionalUserData

**Comment by robinpercy** [comment]
Thanks @gambol99. Not sure how I missed those.

**Comment by justinsb** [comment]
Works for me :-)

**Comment by felipejfc** [comment]
is this included in kops 1.8.1? I've just updated a cluster with it and my master's role is yet without DescribeTags

**Comment by dobesv** [comment]
Seems like this didn't make it into the 1.8 releases of kops, based on what I see in that branch.  I am adding that privilege manually but I'm not sure if kops will undo my change later if I update the cluster again.

**Comment by dobesv** [comment]
Looks like it will roll back the change if I update the cluster again with kops 1.8.  However, if I update kops to 1.9 it adds the new permissions when I update my cluster.

**Pull request merged**
