### PR TITLE
Add support for c5a aws ec2 instance types

### LINKED ISSUE #265: master should be labeled
Now that master nodes are schedulable (yay! thank you!), they should have a label on them that is stable across autoscale events.

This allows things like EIP controllers to be scheduled on the master only in fairly obvious way.

Currently, if the master is labeled, and it autoscales, the label does not persist.

### LINKED ISSUE #9281: Add Support for new c5a AWS instance types
- Add c5a AWS instance types to the supported list.

I can help with a PR if you like but I wouldn't know where to start to test and validate the change.  The code does look trivial to update.

### PR DESCRIPTION
**Pull request by coolstang**
Closes #9281

### CODE REVIEW

**Comment by johngmyers** [comment]
How did a vendored file get updated without also updating go.mod/go.sum? And how did that change pass CI?

**Comment by coolstang** [comment]
> How did a vendored file get updated without also updating go.mod/go.sum? And how did that change pass CI?

I checked those files out before I committed as I didn't think they were related to the changes I did.  How can I re-generate them?  Clean build and test doesn't seem too.

**Comment by johngmyers** [comment]
Please take the vendor file change out.

**Comment by coolstang** [comment]
> Please take the vendor file change out.

Removed the vendor file

**Comment by rifelpet** [comment]
Thanks for the contribution!

/lgtm
/approve

**Pull request merged**
