### PR TITLE
Release 1.11.0

### PR DESCRIPTION
**Pull request by justinsb**
Creating the commit, will tag as part of the release process.  (I think that's automatable, but we'll see!)

Holding for last few cherry-picks

/hold

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks @justinsb!

/lgtm
Pending hold

**Comment by justinsb** [comment]
Merged this one manually

**Comment by justinsb** [comment]
Ended up merging manually onto the 1.11 branch.  1.12.0-alpha.1 should hopefully be smoother sailing with the more automated process!

**Pull request closed without merging**
