### PR TITLE
Automated cherry pick of #8757: Update lyft CNI to 0.6.0

### PR DESCRIPTION
**Pull request by gjtempleton**
Cherry pick of #8757 on release-1.16.

#8757: Update lyft CNI to 0.6.0

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by hakman** [comment]
@gjtempleton I think you should cherry-pick this to 1.17 also to not forget about it.

**Comment by rifelpet** [comment]
you'll probably need to close this and open a new PR with a new commit just like the other one

**Comment by gjtempleton** [comment]
Closing to open a new one with new commits for Travis.

**Pull request closed without merging**
