### PR TITLE
Improvements to codegen: header-check & golint

### PR DESCRIPTION
**Pull request by justinsb**
Improve the fitask codegen so it includes a valid header and does better on golint.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1118)

### CODE REVIEW

**Comment by justinsb** [comment]
What's the typo?  The double quotes?

**Comment by chrislovecnm** [comment]
We can file an issue on it if you like.  No big deal

**Comment by justinsb** [comment]
`DO NOT EDIT` is probably clear enough for now :-)  It's like a "if you need to ask..."

I'll fix the typo if you tell me what it is

**Comment by kris-nova** [comment]
I have no idea what the typo is - assuming it's the double quote `""` ¯\_(ツ)_/¯

**Comment by chrislovecnm** [comment]
LGTM

**Comment by chrislovecnm** [comment]
I am outvoted on typo :P

**Comment by kris-nova** [comment]
.. I still don't know what the typo was?

**Pull request merged**
