### PR TITLE
Update documentation and validation for Cilium

### PR DESCRIPTION
**Pull request by johngmyers**
/assign @olemarkus

### CODE REVIEW

**Comment by olemarkus** [comment]
Should we add something to the release notes as well?

**Comment by johngmyers** [comment]
What would we add to the release notes?

**Comment by olemarkus** [comment]
That cilium eni is now considered stable.

**Comment by johngmyers** [comment]
That change was done by #14622, not this PR.

**Comment by olemarkus** [comment]
Yeah, most of this should probably have been a part of that PR. But it's in the same vein as https://github.com/kubernetes/kops/pull/14676/files#diff-664156d0f9d53d9d867cf3470ef83bfc1a7965e7ced8f0e61df746b8f9021786R113

But happy to lgtm if you feel this should be a separate PR.

/lgtm

**Pull request merged**
