### PR TITLE
Update OWNERS files

### PR DESCRIPTION
**Pull request by hakman**
/cc @justinsb @johngmyers @olemarkus @rifelpet @zetaab 
/assign @justinsb

### CODE REVIEW

**Comment by johngmyers** [comment]
None of the owners being removed or moved to emeritus (not counting the top-level owner only being removed from lower level files) has performed more than one review or one approval in the period `2021-09-25..2022-09-25`.

All owners being retained have performed at least five reviews and five approvals within that period.

**Comment by justinsb** [comment]
As discussed in office hours, it's good to steer PRs to people that are most active.  We thank all the new emeritus folk for their contribution and they're always welcome if/when they have more time :-)

/approve
/hold cancel

**Pull request merged**
