### PR TITLE
WIP: Migrate to dep

### PR DESCRIPTION
**Pull request by aledbf**
- [ ] update development.md
- [ ] add note about the go-bindata module (only remaining git module)
- [ ] fix federation build

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/assign @justinsb

I know you reached out to him on this one

**Comment by aledbf** [comment]
@justinsb ping

**Comment by chrislovecnm** [comment]
Is it actually working? I am impressed

**Comment by chrislovecnm** [comment]
How are we going to not run into problems like this?

I am only trying to add aws go sdk to test infra, and they are using bazel and dep together.  https://github.com/kubernetes/test-infra/pull/6086  - it is a mess.

I am wondering if we need to wait for go_rules to mature a bit with dep.  

Thoughts?

**Comment by aledbf** [comment]
> How are we going to not run into problems like this?

I don't know. 
That being said I can commit (long term) to fix any issue with dep in this repository.

> I am only trying to add aws go sdk to test infra, and they are using bazel and dep together. kubernetes/test-infra#6086 - it is a mess.

I cannot event use the current code from master
```
aledbf@me:~/go/src/k8s.io/test-infra$ planter/planter.sh bazel build //...
planter/planter.sh: 58: planter/planter.sh: UID: parameter not set
```

> I am wondering if we need to wait for go_rules to mature a bit with dep.

Right, but removing 6 millions of lines from this repository and almost every git module is a huge win (personal opinion)

**Comment by chrislovecnm** [comment]
It is a huge win if we can still use bazel, otherwise let sleeping dogs lie until bazel and dep start playing nicer together. I am not a fan of the submodules, but it works, and is stable.

Having bazel broken is a HUGE loss for me, so if we can get them working together nicely I would be open to this. Touching out build system makes me a tad nervous. We still have some makefile issues fr the last set of changes.

**Comment by aledbf** [comment]
> Dep is a huge win if we can still use bazel, otherwise let sleeping dogs lie until bazel and dep start playing nicer together. I am not a fan of the submodules, but it works, and is stable.

Which tasks require bazel? (just to make sure it works)

**Comment by chrislovecnm** [comment]
Require bazel none. We do have bazel build and test targets. Admittedly it is the work flow that I am nervous about ... Investigating in the #bazel channel as well.

@juatinsb thoughts?

**Comment by aledbf** [comment]
@chrislovecnm as this is a WIP :wink: the last commit starts the process to fix the dep <-> bazel issues
```
make bazel-gazelle
gazelle update-repos -from_file Gopkg.lock
gazelle update -external vendored
make bazel-build
```

**Comment by justinsb** [comment]
That looks better than the approach I've been using - I'll have to check out your trick @aledbf 

One thing we want to be sure of is that the versions don't change - I created a script `hack/dep.py` which cross-checks `dep status` against the k8s Godeps.  I used the k8s release-1.9 branch and there were a lot of diffs.  I think we want to lock almost of all our dependencies, which in practice means we're not really using `dep` package resolution - but that is not necessarily a bad thing!

That script is #4152

**Comment by chrislovecnm** [comment]
Talking with the infra-test folks dep has some bugs, especially with prune.

I think we should discuss this on next office hours.

**Comment by chrislovecnm** [comment]
@aledbf / @justinsb we did not discuss this during office hours, meant to.  This PR is going to be in rebase hell shortly.  I am kinda on the fence about this one, but I will trust your guy's judgment. 

What are the final thoughts on this? Go or no GO?

**Comment by aledbf** [comment]
> What are the final thoughts on this? Go or no GO?

I take this as an experiment. Not sure if make sense to merge this PR.
Can we leave this open just as a WIP until I can solve the bazel - dep issues?

**Comment by justinsb** [comment]
Thanks for getting us to do this @aledbf :-)

**Pull request closed without merging**
