### PR TITLE
trying to fix the broken list items for ECR permissions

### PR DESCRIPTION
**Pull request by NorseGaud**
Screenshot 2022-12-08 at 5 38 39 PM

*PLEASE NOTE* Before you approve, can someone show me how to see if this works before it's merged in? In my md preview, it looks fine, but it also looked fine before.

### CODE REVIEW

**Comment by NorseGaud** [comment]
@hakman , any recommendations on seeing if this fixed the issue? Is there a way to preview the docs?

**Comment by johngmyers** [comment]
@NorseGaud look at the "Details" link of the "deploy/netlify" GitHub check.

**Comment by johngmyers** [comment]
It's now a bulleted list, but the URLs are not links.

**Comment by johngmyers** [comment]
Thanks!

/ok-to-test
/lgtm
/approve

**Pull request merged**
