### PR TITLE
AWS: Delete old LaunchConfigurations

### LINKED ISSUE #329: "GC" old launch configurations
We probably want to keep them around while instances still use them, but we should eventually remove old launch configurations as part of a rolling-upgrade

### PR DESCRIPTION
**Pull request by justinsb**
We delete old AWS LaunchConfigurations when we see that we have more
than 3.  We add a feature flag KeepLaunchConfigurations to disable this
functionality, for backwards compatability.

Fixes #329

Done in collaboration with @mikesplain

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks for this @justinsb! Been waiting awhile for it! Tested on a few of my clusters and worked well.

**Comment by mikesplain** [comment]
@justinsb just a reminder, you'll need to re-run gazelle for this.

**Comment by justinsb** [comment]
Thanks @mikesplain for working on it with me!  Hoping to post the video soon.  And thanks for the bazel reminder :-)

**Comment by justinsb** [comment]
Updated - figured out the test issue was due to overly fast timeouts in our tests

**Comment by mikesplain** [comment]
Oh nice, good fixes!

**Comment by justinsb** [comment]
@rdrgmnzs or @chrislovecnm can you take a look & lgtm?  @mikesplain and I worked on it together, so we shouldn't be LGTMing it.

It also has the start of the 1.10 release notes...

**Comment by rdrgmnzs** [comment]
@justinsb @mikesplain couple of questions around the PR.

What is the reasoning behind modifying the existing behavior and setting the default to only keep 3 launch configs vs. leaving the default behavior and letting a user choose how many configs to keep if they chose to delete old ones?

Also how do you guys feel about having `export KOPS_FEATURE_FLAGS=KeepLaunchConfigurations` be an actual part of the configuration. The reason I ask, is because if you are managing a large number of clusters or even just a few setting that ENV var every time gets tedious and if you miss doing so even once the old launch configs would be gone.

Otherwise the PR looks great.

**Comment by mikesplain** [comment]
@rdrgmnzs So @justinsb and I talked about it a bit while working through it... Kops doesn't currently support "Rollback", in terms of swapping the current LaunchConfig for a previous one.  It simply will create a new LaunchConfig no matter what.  

So why keep old ones around in the first place? It certainly can help with debugging, as I'm sure many of us have had to do... e.g. what did that old config look like compared to this one.  "Most" people I've talked to rarely look back at old LaunchConfigs and only realize we don't clean up any when they hit their limit.  I roll over a few clusters a day generally so I have to clean them up every few weeks manually.  

Personally, I don't have a strong feeling on the number except for keeping it >= 2  since I feel strongly that we should keep the current template and the previous, especially while nodes using the previous still exist.

I also don't feel too strongly about the flag, I'm fine with either way. If we're going to allow it as a config in cluster config or something, it's probably best to just allow setting the number of LaunchConfigs in the config.  That said, I think it could be an enhancement down the road but I imagine most people will use as is.  Thoughts?

**Comment by rdrgmnzs** [comment]
@mikesplain thanks for the explanation on both accounts. Just wanted to be clear on the reasoning.

Would love to have this added to the config, even if it's not a flag. I feel like the ENV vars are very esoteric and the fact that if you forget to set them you could cause inadvertent consequences (even if not major) scares me. But as you said this is something we can improve in a future PR.

/lgtm

**Comment by pho-enix** [comment]
@justinsb: Could you please link https://github.com/kubernetes/kops/issues/3604 as a duplicate of this?

Great to see that this will be fixed by 1.10 :)

**Pull request merged**
