### PR TITLE
Update to aws-sdk-go to v1.42.37

### PR DESCRIPTION
**Pull request by jinhong-**
Support for new regions, specifically ap-southeast-3 (Jakarta)

### CODE REVIEW

**Comment by jinhong-** [comment]
cla signed

**Comment by hakman** [comment]
@jinhong- Please rebase the PR to remove the `do-not-merge/contains-merge-commits` label.

**Comment by jinhong-** [comment]
@hakman done

**Review by hakman — APPROVED** [review]
Thanks @jinhong-! 👍

**Pull request merged**
