### PR TITLE
Bump kubernetes dashboard version to 1.8.1

### PR DESCRIPTION
**Pull request by stuffandthings**
Bump the version to 1.8.1 in docs

### CODE REVIEW

**Comment by chrislovecnm** [comment]
You mind signing the cla?

**Comment by stuffandthings** [comment]
not at all, been disconnected for some days and just catching up with things!

**Comment by stuffandthings** [comment]
Just signed the CLA! sorry about the delay.

**Comment by mikesplain** [comment]
Thanks for the contribution @stuffandthings! Good catch!

/lgtm

**Pull request merged**
