### PR TITLE
Update calico to 2.1.5 for k8s 1.6+ bugfixes

### PR DESCRIPTION
**Pull request by blakebarnett**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2536)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by ottoyiu** [comment]
This change should also be supported by Kubernetes 1.5 I believe; should we bump up the version numbers for pre-k8s-1.6?

**Comment by blakebarnett** [comment]
Sure, I'll do that as well

**Comment by stevenpall** [comment]
Hi there,

What is the recommended way to apply this update? Update the Calico `DaemonSet` images directly as per https://docs.projectcalico.org/v2.0/getting-started/kubernetes/upgrade? Or is there something more integrated into Kops?

Thanks!

**Pull request merged**
