### PR TITLE
Fixes Issue#2681

### PR DESCRIPTION
**Pull request by magnusboman**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2682)

### CODE REVIEW

**Comment by magnusboman** [comment]
CLA Signed

**Comment by chrislovecnm** [comment]
CLA seems to not be happy. Ensure that you are using they same email on the git commit / git user you signed up with. Also please respond to the bot with the words without quotes on a single line: "I signed it"

**Comment by justinsb** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@magnusboman any luck with the CLA?  Let me know if you want me to merge this into a bigger PR that I have.

**Comment by magnusboman** [comment]
@chrislovecnm Go ahead and merge it. I don't really know what email address I submitted this patch with (probably something @localhost). I signed the CLA as captain.magnus@gmail.com

**Comment by justinsb** [comment]
Hi @magnusboman ... I'm afraid we can't merge without the CLA :-(

I think the commands should be

```
git rebase -i HEAD^^
# Change second line to squash, e.g. https://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one
git commit --amend --author="Magnus Bowman <captain.magnus@gmail.com>"
git push --force
```

**Comment by magnusboman** [comment]
It's only a one liner anyway. I'll close this and you can write add it to your PR.

**Pull request closed without merging**
