### PR TITLE
Add verify-staticcheck script

### PR DESCRIPTION
**Pull request by rifelpet**
I copied this from kubernetes/kubernetes and inlined some of the function definitions and variables that get sourced from other files.

The same process applies as [described here](https://groups.google.com/forum/#!searchin/kubernetes-dev/staticcheck%7Csort:date/kubernetes-dev/XKBtVRE_d_Q/76cNLhMCBAAJ). There is a list of packages containing existing failures in hack/.staticcheck_failures. As we fix them we can remove them from the list and then any new failures will require fixing.

An easy way to test a static check failure is to add this to any function not in the list of packages with existing failures:
```go
	if !!true {
		return nil
	}
``` 

generates this:
```
Errors from staticcheck:
pkg/commands/set_cluster.go:40:5: negating a boolean twice has no effect; is this a typo? (SA4013)
```

I didn't add it to any of the existing make tasks triggered in CI, I wanted to get a review of it first and then we can enable it but if we think its safe to enable out of the gate I'm happy to get that added to this PR.

### CODE REVIEW

**Comment by justinsb** [comment]
This is a great idea!  Let's discuss in office hours tomorrow, but I think we should do this.

**Comment by mikesplain** [comment]
Thanks for doing this @rifelpet!  I'm happy to approve this once you fix the merge conflicts above!  Great job!

/assign @mikesplain

**Comment by mikesplain** [comment]
Looks great! Thanks @rifelpet!

/lgtm
/approve

**Pull request merged**
