### PR TITLE
Delete the function keyword to prevent shellcheck from failing

### PR DESCRIPTION
**Pull request by xichengliudui**

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks for thinking about this!  I ran shellcheck and got a lot of warnings about lack of quoting 

e.g.

```
In hack/make-gendocs.sh line 52:
cp ${WORK_DIR}/go/bin/client-gen ${GOPATH}/bin/
   ^-- SC2086: Double quote to prevent globbing and word splitting.
                                 ^-- SC2086: Double quote to prevent globbing and word splitting.
```

But I didn't see any errors complaining about the use of `function` - and I would have thought that using function was correct.

What error are you getting from shellcheck?

**Comment by xichengliudui** [comment]
@justinsb Is there any file in kop that is wrong to retrieve shecllcheck? The function keyword error I encountered in k8s repo looks like this: 
```
function cleanup {
^-- SC2113: 'function' keyword is non-standard. Use 'foo()' instead of 'function foo'.
Ref: https://www.shellcheck.net/wiki/SC2113 -- 'function' keyword is non-standar...
```
If you don't need this pr I can turn it off.

**Comment by xichengliudui** [comment]
Also, if kop has tools for retrieving scripts, can I fix them?

**Comment by xichengliudui** [comment]
here.

**Comment by justinsb** [comment]
I appreciate the change, so let's merge it.  Would be great to get shellcheck actually working against our repo.  How do you run shellcheck?

/approve
/lgtm

**Pull request merged**
