### PR TITLE
[Fixes #2501] Includes cluster name in `cluster deleted` log

### LINKED ISSUE #2501: Odd message when a cluster is deleted
## kops version

```console
$ kops version
Version 1.6.0-beta.1 (git-77f222d)
```

## recreate

Create a cluster and then delete it:

```console
$ kops delete -f $DIR/kops/cluster.yaml --yes
```

We are outputing:

```
subnet:subnet-9fb94ec5	ok
internet-gateway:igw-6f77af09	ok
security-group:sg-16e23868	ok
route-table:rtb-40fb0f38	ok
vpc:vpc-5bdb3922	ok
dhcp-options:dopt-44b24022	ok
Deleted kubectl config for us-east-1.aws.k8spro.com

Cluster deleted

cluster "us-east-1.aws.k8spro.com" not found
```

The last message is kinda odd in my mind.  We somehow are getting back to here - https://github.com/kubernetes/kops/blob/master/cmd/kops/root.go#L258

I would think that last statement should be:

```
Cluster "us-east-1.aws.k8spro.com" deleted
```

### PR DESCRIPTION
**Pull request by dolftax**
Signed-off-by: Jaipradeesh <jaipradeesh@gmail.com>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2516)

### CODE REVIEW

**Comment by dolftax** [comment]
@k8s-ci-robot CLA signed.

**Comment by geojaz** [comment]
@dolftax I think you may need to just say- "I signed the CLA!" to get the bot to pick it up. I can't seem to find the magic commands right now :/

@k8s-ci-robot ok to test

**Comment by geojaz** [comment]
@k8s-ci-robot ok to test

**Comment by dolftax** [comment]
I signed the CLA!

**Comment by chrislovecnm** [comment]
Just type: "I signed it" also Travis failed

**Comment by chrislovecnm** [comment]
@dolftax I edited your comment, but the robot did not like it. Please just type only the words

I signed it

In a comment. Just those three words. Appreciate your patience. Also, the git sha / user needs to be the email you signed up with.

**Comment by dolftax** [comment]
I signed it

**Comment by dolftax** [comment]
@chrislovecnm https://github.com/kubernetes/kops/issues/2501#issuecomment-299784458

**Comment by dolftax** [comment]
I signed it.

**Comment by chrislovecnm** [comment]
@dolftax maybe the problem is with `kops delete -f mycluster.yaml --yes` command.  I like this PR regardless but may not fix my bug.

**Comment by chrislovecnm** [comment]
@dolftax travis is failing.  

https://travis-ci.org/kubernetes/kops/jobs/229420538

If you client on the details button, you will see the error.  CLA is not happy on this PR.

**Comment by dolftax** [comment]
gofmt is throwing error. That's because of bad indentation. Let me try to delete cluster via a file.

**Comment by justinsb** [comment]
@dolftax we have the `make gofmt` command, which should fix the formatting.

**Comment by dolftax** [comment]
@justinsb Yeah. But I have to fix one more bug in the same PR. Didn't get time to replicate it. Do not merge this PR. Will add a commit in couple of days.

**Comment by chrislovecnm** [comment]
@dolftax I am marking as WIP

**Comment by justinsb** [comment]
@dolftax this LGTM to me now - is it OK to merge?

Closing & reopening to trigger tests.

**Comment by chrislovecnm** [comment]
This does not fix the issue btw.  We have a bug in delete -f, that I need to track down.  A lot of the times `kops delete -f` is exiting with an error code, even though it was successful.  We seem to be looking up a cluster.  @dolftax, when you tested it, did you have multiple clusters in your state store?  I am wondering if the bug is when you only have one cluster in your state store.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by dolftax** [comment]
@chrislovecnm I tested with single cluster setup.

**Comment by justinsb** [comment]
I checked out the needed rebase, and it looks like this was incorporated into #2772.  I'm going to close this PR therefore; if that's not right please rebase & reopen or comment to that effect!

Thank you for the contribution though @dolftax

**Pull request closed without merging**
