### PR TITLE
Automated cherry pick of #8757: Update lyft CNI to 0.6.0

### PR DESCRIPTION
**Pull request by gjtempleton**
Cherry pick of #8757 on release-1.16.

#8757: Update lyft CNI to 0.6.0

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by hakman** [comment]
@gjtempleton I got this from TravisCI support and seems to work for me. You may also want to give it a try:
```
1- Please logout from travis-ci.org
2- Remove Travis CI for Open Source from the list of Authorized OAuth Apps from the page https://github.com/settings/applications
3- Re-login to travis-ci.org and approve the permission for your accounts
4- Go to your account page https://travis-ci.org/account/repositories and Sync your account.
```

**Comment by gjtempleton** [comment]
@hakman Thanks! Have tried that and pushed up a no-op amended commit to see if that resolves it for good.

**Comment by rifelpet** [comment]
still no luck. i just opened a cherry-pick myself here: https://github.com/kubernetes/kops/pull/8851 we'll see if travis works I guess

**Comment by hakman** [comment]
Hmm... strange. I seem to still have problems myself on some PRs, but new ones look ok. I guess we should do something about this in next weeks's office hours.

**Comment by gjtempleton** [comment]
We definitely should, it's becoming a pain, and I certainly can't see anything on my side that should cause this.

**Comment by hakman** [comment]
@gjtempleton just got a status update from Travis support. I hope it is fixed now.
```
Thank you for your patience on this issue.
Our Engineering Team has just deployed a fix about this issue and it seems like your GitHub status is back on your PR.
Please let us know if you have any other issues related to our product.
```

**Comment by gjtempleton** [comment]
Ah, brilliant, thanks for the update @hakman - lets see what happens next time I need to raise a PR in that case.

**Comment by hakman** [comment]
I think I was too quick to celebrate. Nothing changed for me: https://github.com/kubernetes/kops/pull/8898#issuecomment-612165800.

**Pull request closed without merging**
