### PR TITLE
Automated cherry pick of #9465: Update the service manifest for Docker

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #9465 on release-1.18.

#9465: Update the service manifest for Docker 

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by johngmyers** [comment]
Does this really need to get into 1.18? It's a fairly big set of changes.

**Comment by hakman** [comment]
@johngmyers Except for the vendoring of `github.com/blang/semver/v4`, this change is pretty small and limited to Docker manifest rendering.
Some of it is needed. If there are concerns, I can strip a large part of it.

**Comment by hakman** [comment]
I think that should do it @johngmyers .

**Comment by rifelpet** [comment]
can you explain why the semver vendoring wasn't needed? that was to conditionally add containerd as a dependency in the mainfest right? doesn't 1.18 support containerd?

**Comment by hakman** [comment]
> can you explain why the semver vendoring wasn't needed? that was to conditionally add containerd as a dependency in the mainfest right? doesn't 1.18 support containerd?

You are correct. The docker - containerd service dependency is nice to have, but not mandatory. Services will be started independently, but they sync without much trouble.

**Comment by rifelpet** [comment]
👍 
/approve

**Comment by hakman** [comment]
Thanks @rifelpet :)

**Pull request merged**
