### PR TITLE
Make AWS EBS CSI Driver default as of k8s 1.22

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Review by rifelpet — APPROVED** [review]

**Comment by michaelajr** [comment]
Hey @olemarkus - want to point out that the Cluster Spec comments still says this disabled by default. https://pkg.go.dev/k8s.io/kops/pkg/apis/kops#AWSEBSCSIDriver

**Comment by olemarkus** [comment]
Thanks. Any chance you would be able to do a PR to fix that? Would be much appreciated.

**Pull request merged**
