### PR TITLE
Delete kubectl config when deleting cluster

### PR DESCRIPTION
**Pull request by yissacharcw**
Fixes https://github.com/kubernetes/kops/issues/287

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1218)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Thanks for the work btw ... This is awesome!!

**Comment by yissachar** [comment]
Not sure how we would test this. We're basically just calling kubectl commands. We're not deleting inadvertently, we are deleting advertently ;)

**Comment by chrislovecnm** [comment]
Can you mock a config file and perform the delete on it? We are using a command cli blindly. If the cli changes we have zero manner to verify the behavior of the cli. A user would be very unpressed if a kubectl config got deleted improperly.

**Comment by chrislovecnm** [comment]
Btw thanks, we need this, I just want to try our best to not have this impact a user.

**Comment by yissachar** [comment]
@chrislovecnm I don't think a mock will help us here.

We are blindly trusting kubectl, but I think we have to do that, short of reimplementing the functionality ourselves (and I'd trust kubectl over attempting that).

We can do a backup and restore, but again I feel like that is more likely to be a source of bugs than trusting kubectl to do its job. For anything mission critical, I would hope that the user has their own backup system in place for the kubecfg.

I think we just have to live with trusting kubectl if we want to have this feature.

**Comment by justinsb** [comment]
I think I agree with @yissachar.  We _could_ check that the value we are deleting is the value we are expecting, but eventually we still have to just make the delete call.  I worry that the failsafes will end up being more error prone than the deletion code itself.

If you're using kops, it isn't a big deal to lose your kubecfg anyway.

And I don't think this is much worse than our blindly overwriting the config anyway, from `kops export kubecfg`

**Comment by chrislovecnm** [comment]
Waiting on e2e, @yissachar appreciate your patience

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Pull request merged**
