### PR TITLE
add label to kube-proxy

### PR DESCRIPTION
**Pull request by ajohnstone**

### CODE REVIEW

**Comment by ajohnstone** [comment]
signed  cla/linuxfoundation

**Comment by justinsb** [comment]
Looks good.  Wondering though - does the k8s-app do anything special?  I'm not aware of any special significance, so I'd like to understand why you want the label, so we can be sure to add it to other things in future!

**Comment by ajohnstone** [comment]
I added to keep the same as kube-up. I'm using to validate that the cluster has been provisioned correctly with the number of nodes. Having a label on all pods makes it easier to validate :)

**Comment by chrislovecnm** [comment]
@ajohnstone `kube-up.sh` is depreciated, what are you trying to validate?  Wonder if we can do this another way.  I would like to model more of what `kubeadm` is doing now since we may integrate that in eventually.

**Comment by ajohnstone** [comment]
I've seen instances whereby kube-proxy was failing say 1/5 pods. I've wrote tests, that verify the health of the cluster that my colleagues can easily run. The above simply makes it easy to query for kube-proxy.

E.g.
```
bats tests/
 ✗ kube-proxy pods
   (from function `values_equal' in file tests/../helpers.bash, line 37,
    in test file tests/pod_counts.bats, line 63)
     `values_equal ${KUBE_PROXY_DESIRED} ${KUBE_PROXY_CURRENT};' failed
   KUBE_PROXY_DESIRED: 8 KUBE_PROXY_CURRENT: 0

```

Otherwise you have to grep for the name. ```kubectl --namespace=kube-system get pods -o name | grep -E 'pod/kube-proxy-.*'```

Ideally all applications should be easy to query with relevant labels.

**Comment by shamil** [comment]
>`kube-up.sh` is depreciated
@chrislovecnm do we have production grade replacement?

**Comment by chrislovecnm** [comment]
@shamil production nope.  `kubeadm` is scheduled but just released in 1.4.  We need to discuss as a group when, if, and we are going to use `kubeadm`

**Comment by justinsb** [comment]
I would say kops is our best bet for production readiness.  I feel we're well beyond where kube-up is/was.  Not tool is 100% out of the box for everyone, and I would like to see https://github.com/kubernetes/kops/issues/428 , but IMO we should be promoting kops, and identifying areas where it is not "production ready".

This seems like another PR that gets us closer @ajohnstone - thank you!

LGTM

**Pull request merged**
