### PR TITLE
Use -ginkgo.junit-report instead of -ginkgo.reportFile

### PR DESCRIPTION
**Pull request by hakman**
https://testgrid.k8s.io/kops-misc#kops-aws-aws-load-balancer-controller
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-aws-aws-load-balancer-controller/1525228677749542912

/cc @olemarkus

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by hakman** [comment]
All good, ready for final review @olemarkus.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
