### PR TITLE
cluster-autoscaler.yaml for 1.10

### PR DESCRIPTION
**Pull request by koooge**
Hi. I use kops 1.10 with cluster autoscaler. So I tried to create yaml for 1.10.
Will you please review it?

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
@koooge has anything changed in the spec from the 1.8.0 version besides the container Image version? Doing a quick diff I did not find anything else that had changed.

**Comment by gms-ta-koge** [comment]
@rdrgmnzs apiVersion was bumped to v1.

**Comment by chrisz100** [comment]
@rdrgmzs guess updating this none the less would be a good idea. This will get stuck otherwise... 

/lgtm

**Comment by justinsb** [comment]
Looks like the image has definitely changed, along with the RBAC, so we should get this merged!

Thanks @koooge 

/approve

**Pull request merged**
