### PR TITLE
Update to kubernetes 1.18.1 dependencies

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
Adding as WIP because controller-runtime doesn't build with 1.18 libraries.

**Comment by justinsb** [comment]
The latest (master) of controller-runtime actually does support 1.18, so we can update after all!

**Comment by hakman** [comment]
@justinsb now that v1.18.1 was release, should we just use that instead of v.1.18.0?

**Comment by justinsb** [comment]
Good call @hakman - updated to 1.18.1

**Comment by hakman** [comment]
@justinsb seems that this broke 1.10 and 1.11. I am not really sure what happens with the mount part to be able to fix it.
```
W0412 18:12:27.646560    3634 volume_mounter.go:79] unable to mount master volume: "error formatting and mounting disk \"/dev/xvdu\" on \"/mnt/master-vol-00b718c718950ef02\": MountSensitive not implemented for containerized mounter"
```

https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-aws-k8s-1-11/1249398784325062656/artifacts/3.8.78.27/protokube.log

**Pull request merged**
