### PR TITLE
Integration test cleanup

### PR DESCRIPTION
**Pull request by rifelpet**
Some integration tests were missing their cloudformation invocations, so their cloudformation.json wasn't being updated during ./hack/update-expected.sh.

We also had some orphaned files in the integration test source directories that shouldn't be there but we didnt assert that the number of actual source data files matches the expected number of data files. This adds an assertion for that and removes the orphaned files.

### CODE REVIEW

**Review by hakman — APPROVED** [review]
👍

**Comment by johngmyers** [comment]
@rifelpet `hack/update-expected.sh` is no longer creating missing golden files.

**Comment by rifelpet** [comment]
Ok I'll take a look

**Comment by johngmyers** [comment]
Never mind, it was something else

**Pull request merged**
