### PR TITLE
Add go 1.10 testing to travis CI

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by mikesplain** [comment]
Though it looks like we've found a nice UI bug in travis, unless you actually wanted to test go 1.1 ;) 
kops - travis ci 2018-02-26 09-20-15

**Comment by justinsb** [comment]
Hmmm... trying with a yaml quoted string.

**Comment by chrislovecnm** [comment]
/hold

go 1.10 is failing `go vet` on generated fakes.  @justinsb I think you opened an issue?

**Comment by justinsb** [comment]
Blocked on upstream fixes; punting to 1.10

**Comment by chrislovecnm** [comment]
@tvi how can we whitelist the problem with go vet so that it will pass?  You mentioned that in your mind the vet messages are incorrect?

**Comment by tvi** [comment]
@chrislovecnm So basically as I understand it: we are passing testing.Fake{} (which has a embedded  lock) by value, so `go vet` complains because that lock might have been locked (in reality when you look at the code it isn't). I strongly suggest ignoring that error here in kops as it kind of false positive. In reality its not adding any value and its hard to fix as it will require significant refactoring inside k8s clientset.

**Comment by chrislovecnm** [comment]
@tvi is it a bug in govet or actually a positive?  I understand that the refactor is nasty upstream, and surprised more people have not hit it.  kubernetes/kubernetes is already on 1.10.1 go.

**Comment by tvi** [comment]
I feel like k8s does not run go vet on this generated code, but I was looking at it quite some time ago.
Its definitely not a bug in govet.
Basically govet is trying to be defensive and warn us that given struct could have been locked, but we as humans know that its not because 5 lines before it was initialized and nobody locked it.

I understand that you are trying to protect against nasty failures, but this is only in testfiles, kops binary is not affected at all. If something, this is a 'bug' in apimachinery so there is nothing kops can do other than wait and that refactor is going to be hard to do.

**Comment by mikesplain** [comment]
Closing since this must've been done elsewhere

/close

**Pull request closed without merging**
