### PR TITLE
Automated cherry pick of #8020: Automatically install dependencies with local packages

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #8020 on release-1.17.

#8020: Automatically install dependencies with local packages

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by hakman** [comment]
Thanks @geojaz. I added one more small change for the Ubuntu 16.04 deps that were not presend when this change was done.

**Comment by geojaz** [comment]
cool! when it's all green, i'll re-/lgtm

**Comment by hakman** [comment]
Perfect. Thanks! :)

**Comment by hakman** [comment]
I think tide still expects the approval label.

**Comment by hakman** [comment]
Thanks @geojaz :)

**Pull request merged**
