### PR TITLE
Remove support for using Vault as state store

### PR DESCRIPTION
**Pull request by hakman**
Refs #14690 

/cc @olemarkus @johngmyers

### CODE REVIEW

**Comment by johngmyers** [comment]
If the CNCF's timeline allows, I'd suggest we deprecate in 1.26 for removal in 1.27.

**Comment by hakman** [comment]
It is an experimental feature, under feature flag. There are not guarantees of deprecation and removal.

**Comment by johngmyers** [comment]
Oh right, feature flagged.

**Review by johngmyers — APPROVED** [review]
/hold for consideration of wording change

**Pull request merged**
