### PR TITLE
 [spotinst-controller] Allow ServiceAccount to list pod metrics

### PR DESCRIPTION
**Pull request by msessa**
Proposed fix for #6644 

This PR adds list permissions for pods on the metrics metrics.k8s.io API group consistently with the [official specs](http://spotinst-public.s3.amazonaws.com/integrations/kubernetes/cluster-controller/spotinst-kubernetes-cluster-controller.yaml)

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
Thanks @msessa - are you able to sign the CLA? I know it's a little annoying, but once signed it then applies across all the Kubernetes projects.

**Comment by msessa** [comment]
@rdrgmnzs I'm fairly sure I did sign it, is there any other step required after receiving the hellosign confirmation?

**Comment by justinsb** [comment]
This looks good but @liranp is the expert at spotinst!  @liranp shall we merge this?

**Pull request closed without merging**
