### PR TITLE
Fix markdown typo

### PR DESCRIPTION
**Pull request by coryflucas**

### CODE REVIEW

**Comment by coryflucas** [comment]
CLA signed

**Comment by mikesplain** [comment]
Thanks for this @coryflucas! Are you sure your CLA is signed with the same email and name associated with your github account and your commit? Once this process is fixed, you'll be able to contribute for any CNCF project.  If you run into issues, please follow the directions [here](https://github.com/kubernetes/kops/pull/5838#issuecomment-424737699) and contact the help desk. Thanks!

We really shouldn't be testing or lgtming code without the CLA signed.

/lgtm cancel

**Comment by coryflucas** [comment]
I should be good on the CLA now, didn't realize I hadn't finished the whole process
/check-cla

**Comment by chrisz100** [comment]
Looks way better, thanks! 
@mikesplain sorry for that, I assumed as the cla-test will fail up until this is resolved anyways it couldn't get merged before. Noted for the future. 

/lgtm

**Comment by mikesplain** [comment]
Great! No worries all, thanks for figuring it out!

/lgtm
/approve

**Pull request merged**
