### PR TITLE
Fix confusing k8s upgrade docs for Terraform users

### PR DESCRIPTION
**Pull request by tspacek**
What I did: followed https://github.com/kubernetes/kops/blob/master/docs/upgrade.md#terraform-users
What I expected: `kops rolling-update cluster` to have changes to apply.
What happened instead: `kops rolling-update cluster` had no changes.

It turns out Terraform never registered any changes. When I tried again with `kops update cluster $NAME --target=terraform --out=.`, it worked.

While a better solution would be for `out=.` to be the default if `--target=terraform`, there might equally be a good reason it isn't already. This docs change could save someone else a few minutes in the future.

### CODE REVIEW

**Comment by geojaz** [comment]
Hrm- I think we have some inconsistencies in the workflow between `kops update cluster` and `kops rolling-update cluster`. I think the crux of the issue that leads to your submission is that kops writes the terraform files to some "mystery location" (https://github.com/kubernetes/kops/blob/master/cmd/kops/update_cluster.go#L147-L152) if you don't set it. I think there's probably more to think about in terms of making the UX simpler, but I think you're on the right track @tspacek 

For the quick fix presented here: would you mind either 
* adding a note to your command that says something like: `--out` specifies where the terraform files are written
* if you choose not to write your terraform plan to the current directory, you'll need to `cd out/terraform` before continuing.

**Comment by geojaz** [comment]
@tspacek would you mind squashing these commits and we'll get them merged for you? thanks for your contribution!

**Comment by justinsb** [comment]
Fixed the (trivial) merge conflict

/approve
/lgtm

**Pull request merged**
