### PR TITLE
Bump etcd manager to 20211117

### PR DESCRIPTION
**Pull request by justinsb**
WIP because we haven't tagged the build yet; I want to put it through testing.

### CODE REVIEW

**Comment by rifelpet** [comment]
Unfortunately we dont have any presubmit upgrade tests which is what this etcd-manager version should fix, maybe we could add some? it may be straight forward using the `upgrade-ab` scenario.

**Comment by justinsb** [comment]
I did run the upgrade test and it looks healthy (i.e. unrelated to etcd: one OIDC failure, one OwnerReferences failure - flake?)

I'm going to send the promotion PR and then update this PR to point to the promoted version.

**Comment by justinsb** [comment]
Promotion PR is https://github.com/kubernetes/k8s.io/pull/3088

(I'm also working on a release process doc :-) )

**Review by hakman — APPROVED** [review]

**Comment by justinsb** [comment]
Removed WIP, but grappling with a flake.

**Pull request merged**
