### PR TITLE
[Feature] CoreDNS: External CoreFile option

### LINKED ISSUE #7347: Feature Request: CoreDNS CoreFile fully configurable
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
The provided CoreDNS config/CoreFile is nice however not very flexible. We currently use a fairly customised CoreFile internally and use a

```
kubeDNS:
    provider: External
``` 

stanza to allow us to deploy our own CoreDNS setup. There's at least one PR already aiming at extending the flexibility of this setup: #5839 however we'd like to go the whole hog and allow users to provide a full string for the coreFile which would then be inserted here: https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/coredns.addons.k8s.io/k8s-1.6.yaml.template#L61
maintaining the existing behaviour otherwise.

Example config as imagined:
```
kubeDNS:
    provider: CoreDNS
    coreFileContents: |
        amazonaws.com:53 {
            errors
            log . {
                class denial error
            }
            health :8084
            prometheus :9153
            proxy . 169.254.169.253 {
            }
            cache 30
        }
        .:53 {
            errors
            health :8080
            autopath @kubernetes
            kubernetes cluster.local {
                pods verified
                upstream 169.254.169.253
                fallthrough in-addr.arpa ip6.arpa
            }
            prometheus :9153
            proxy . 169.254.169.253
            cache 300
        }
```

Obviously this would have to come with big warnings that no compatibility guarantees could be maintained on changing kops versions potentially changing CoreDNS compatibility so I would imagine also offering configurability of the CoreDNS image used at the same time (the PR mentioned above already provides this) to allow users to ensure they don't unexpectedly jump versions and find their CoreFile suddenly becoming invalid.

**2. Feel free to provide a design supporting your feature request.**
N/A for now.

### PR DESCRIPTION
**Pull request by gjtempleton**
Resolves #7347 as discussed at yesterday's office hours. Think this is the approach that was agreed on.

Allow users to specify entirely custom CoreFile contents for CoreDNS.

Provided example and warning(s) for users in the cluster spec.

FYI: I'm likely out of contact until next Saturday (the 12th) or so however I've given @maruina collaborator rights on my fork so he may be able to resolve any queries etc.

### CODE REVIEW

**Comment by justinsb** [comment]
Sorry for delay!

/ok-to-test

**Comment by mikesplain** [comment]
I fixed a conflict since I believe @gjtempleton isn't around this week.

**Comment by joshbranham** [comment]
Big fan of this as stated above!

/lgtm

**Comment by gjtempleton** [comment]
Awesome, great to come back from holiday to find this merged and cherry-picked back!

Thanks for the work in fixing the conflicts @mikesplain.

**Pull request merged**
