### PR TITLE
Set priority for static pods

### LINKED ISSUE #6615: Ability to specify priorityClassName in kops managed manifests
**1. Describe IN DETAIL the feature/behavior/change you would like to see.**
I'm not sure if this already supported or not, but was unable to find it in the docs or previous github issues. I'd like to be able to specify `priorityClassName` in the manifests generated by kops, such as kube-proxy, since pod priority is enabled by default in 1.11 and the rescheduler is deprecated. Is there a way to specify it in `cluster.spec`?
**2. Feel free to provide a design supporting your feature request.**
If it is not already supported, being able to specify it under `spec.kubeProxy` in `cluster.spec` would be good.

### PR DESCRIPTION
**Pull request by vainu-arto**
Setting a high priority for kube-proxy is important in clusters that run with PodPriority enabled, otherwise it will get evicted from worker nodes whenever there are unschedulable pods. Also set priorities for the other static pods defined by kops, mainly for completeness.

This should be safe these days since the API always accepts PriorityClassName even if PodPriority isn't enabled.

Fixes #6615.

### CODE REVIEW

**Comment by vainu-arto** [comment]
CLA should be fixed...

**Comment by mikesplain** [comment]
This looks good! We actually ran into this recently as well so I'm going to open cherry picks into the 1.13 and 1.14 branches too.

Thanks so much for the patience and for the contribution @vainu-arto!

/lgtm
/approve

**Comment by rifelpet** [comment]
@mikesplain thoughts on cherry-picking this to earlier branches?

**Pull request merged**
