### PR TITLE
Bump EBS CSI driver to 1.5.0

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Review by hakman — APPROVED** [review]

**Comment by rifelpet** [comment]
consider running pull-kops-e2e-aws-ebs-csi-driver too

**Comment by olemarkus** [comment]
Still need to wait for image promotion on this one. https://github.com/kubernetes/k8s.io/pull/3090

**Comment by olemarkus** [comment]
I am a bit skeptical about doing /test pull-kops-e2e-aws-ebs-csi-driver because of the flakes ... as we use CSI by default now, we shouldn't really need this.

**Review by hakman — APPROVED** [review]

**Pull request merged**
