### PR TITLE
external CCM for GCE

### PR DESCRIPTION
**Pull request by jiahuif**
This PR adds `ExternalCloudControllerManager` support for gcp.

### CODE REVIEW

**Comment by jiahuif** [comment]
Hmm...I just squashed the commits plus some white-space changes. Now it does not require `pull-kops-e2e-k8s-gce` for some reason.

**Comment by justinsb** [comment]
/test pull-kops-e2e-k8s-gce

Awesome contribution, thank you for this.  I say we get this in, so we can get this under e2e.

/approve
/lgtm

**Comment by johngmyers** [comment]
This e2e failure started in the periodic tests around 12/18.

**Comment by rifelpet** [comment]
It seems the prow environment doesn't have the necessary GCP permissions that kops requires now that https://github.com/kubernetes/kops/pull/12988 has landed. @justinsb could you check if we can have those permissions added or if we can otherwise reconfigure our prow jobs?

`W1221 22:50:30.248398   88390 executor.go:139] error running task "ProjectIAMBinding/serviceaccount-nodes" (4m57s remaining to succeed): error updating IAM for project k8s-jkns-gci-gce-slow-1-3: googleapi: Error 403: Policy update access denied., forbidden`

**Comment by justinsb** [comment]
Tackling the e2e failures in https://github.com/kubernetes/test-infra/pull/24749 and https://github.com/kubernetes/kops/pull/13043

**Comment by jiahuif** [comment]
/test pull-kops-e2e-k8s-gce
/hold cancel
Rebased, this test *should* pass now.

**Comment by johngmyers** [comment]
E1228 21:13:09.754081    4945 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: could not init cloud provider \"gce\": unexpected response listing zones: googleapi: Error 403: Required 'compute.zones.list' permission for 'projects/kubernetes-es-logging', forbidden"

**Comment by jiahuif** [comment]
Thank @justinsb for fixing the GCE test. It is now passing.

**Comment by jiahuif** [comment]
Thank you all for reviewing.

**Pull request merged**
