### PR TITLE
Add vSphere vendor codes

### PR DESCRIPTION
**Pull request by luomiao**
This PR is to submit necessary vendor code for supporting kops in vSphere platform.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2343)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Need you to sign the CLA please :)

**Comment by luomiao** [comment]
@chrislovecnm Thanks :)
I have signed CLA but Sandeep, the author of another commit, is not yet. He's working remotely now and I am hoping he will be able to get signed up later today.

**Comment by thelinuxfoundation** [comment]
bump for CLA check

**Comment by justinsb** [comment]
Thanks @luomiao and @SandeepPissay - exciting stuff :-)

**Pull request merged**
