### PR TITLE
Remove submodules

### PR DESCRIPTION
**Pull request by chrislovecnm**
Just cause I wanted to delete a bunch of files tonight.

/assign @rdrgmnzs 

Fixes https://github.com/kubernetes/kops/issues/4364

### CODE REVIEW

**Comment by justinsb** [comment]
Do you want to update docs/dependencies to state that we're doing dep now, along with the philosophy?

**Comment by chrislovecnm** [comment]
> Do you want to update docs/dependencies to state that we're doing dep now, along with the philosophy?

@justinsb I would if I understood how to write the doc.  No idea what the workflow is.

**Comment by chrislovecnm** [comment]
@justinsb do you want me to update the doc saying that we are using dep now, and someone needs to document this?

**Comment by KashifSaadat** [comment]
LGTM subject to updates to the developer docs :)

**Comment by justinsb** [comment]
/lgtm

I've realized I don't want to maintain dep docs :-)

**Pull request merged**
