### PR TITLE
Bump Weave Net version to 1.9.0

### PR DESCRIPTION
**Pull request by bboreham**
Weave Net Version 1.9 has optional IPSec encryption, is built for ARM as well as AMD64, and fixes quite a few issues.
Release notes https://github.com/weaveworks/weave/releases/tag/v1.9.0

I followed #1250 for the version number changes; the volume-mount changes are required by internal changes in Weave Net

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1893)

### CODE REVIEW

**Comment by hollowimage** [comment]
@bboreham Bryan, what would the upgrade path look like for clusters already up and in prod running weave 1.8.2?

**Comment by bboreham** [comment]
@hollowimage that's a good question.   Kubernetes doesn't do rolling updates for DaemonSets, but I see Kops has a `rolling-update` command.  Would it work for this?  We want to do something like this:

* Apply the updated manifest as in `kubectl apply -f networking.weave/v1.9.0.yaml`
* Kill each Weave Net pod and then wait for it to restart before moving on to the next pod

We do _not_ want to delete all pods at once.  That would play badly with Weave's eventually-consistent data store.

**Comment by hollowimage** [comment]
kops rolling update would reapply, potentially a lot of cluster stuff. I would say this is not a good way to upgrade the cluster.

I updated the DS config inline (kubectl edit ds weave-net) last night while enabling encryption and i only had to terminate all weave net pods, and wait for the to reinit. naturally while the weave pods are down, i would image this is not something that would be considered a transparent change.

**Comment by bboreham** [comment]
Yes, Weave Net 1.9.0 is fully backward-compatible; there will be a brief period as it restarts when no new pods can be added to the network but apart from that it can be done on a live system.

Now I think about it you'd ideally want to effect a `docker pull` on each node before triggering the restart, to minimise the downtime.  But I don't know of a way to do that via Kubernetes.

**Comment by chrislovecnm** [comment]
Closing this as we have a better on open with the same changes

**Pull request closed without merging**
