### PR TITLE
Add missing ServiceAccount in snapshot-validation-deployment

### PR DESCRIPTION
**Pull request by minkimipt**
Deployment manifest of snapshot-validation-deployment was missing a service account and hence was using the default one that exists in kube-system namespace.
This caused it to log `Failed to watch *v1.VolumeSnapshotClass` errors

### CODE REVIEW

**Comment by hakman** [comment]
@minkimipt Could you run `hack/update-expected` and commit the output? Probably you will need to also rebase.

**Comment by minkimipt** [comment]
@hakman from what I can see CI is happy.

**Review by hakman — APPROVED** [review]
Thanks @minkimipt! :)

**Pull request merged**
