### PR TITLE
Fix doc linkages to addons

### PR DESCRIPTION
**Pull request by s3than**
The linkage on the main readme and example page point to the wrong location for addons.

### CODE REVIEW

**Comment by s3than** [comment]
CLA Signed

**Comment by justinsb** [comment]
Thanks @s3than - this looks good.  The CLA bot hasn't woken up yet (or maybe there's a mismatched email?)

Let's see if this wakes it up...

/check-cla

**Comment by s3than** [comment]
Try again, I just went through the whole process again.

**Comment by justinsb** [comment]
Thanks @s3than - looks great.

(I also fixed up the merge conflict.)

/approve
/lgtm

**Pull request merged**
