### PR TITLE
WIP: Install docker from static binary archive

### PR DESCRIPTION
**Pull request by austinmoore-**
Add the functionality to install docker from a static binary archive.

This solution was discussed in the November 8th office hours. This is a solution to a problem that I've run into where I cannot download docker binaries from download.docker.com and must use an internal mirror. The initial fix I had for this problem was in #6956, but that solution doesn't handle heterogenous clusters.

NOTE: This assumes that all instance groups in your cluster are running with the same CPU architecture.

### CODE REVIEW

**Comment by austinmoore-** [comment]
I've marked this as a WIP, even though I think the work is pretty much finished. I just want to continue trying it out for a little while longer, and get community input.

**Comment by austinmoore-** [comment]
/assign @justinsb 

Assigning to Justin, at least for the initial review since he is aware of this from the office hours. Feel free to assign it to someone else

**Comment by mikesplain** [comment]
Awesome! Thanks for diving into this! I'll approve the PR for testing for now while we await reviews.

/ok-to-test

**Comment by michaelajr** [comment]
Hi. Where does this stand? We can longer cherry pick #6956 (for several reasons that I will not go into here). We need a way to specify the docker download location.

**Comment by michaelajr** [comment]
@austinmoore-  Any chance you resolve conflicts?

**Comment by austinmoore-** [comment]
@michaelajr Yeah I can resolve the conflicts and get this shored up soon. 

I think the end result is to refactor `docker.go`. As @justinsb mentioned in on of the bi-weekly meetings, docker.go has kinda outgrown its needs. I'll come up with something and propose it to the maintainers and get us an end state that I can just then implement.

**Comment by johngmyers** [comment]
I would much rather the docker/containerd download go through asset remapping like all the other downloads. I'm thinking we move the `packageVersion` information for the `PlainBinary` versions to cloudup so they can be remapped and then passed through NodeupConfig, leaving the older rpm/deb versions in nodeup until such time as we drop support for them.

**Pull request closed without merging**
