### PR TITLE
Override hostname with 'aws' only if hostname override is not specified.

### PR DESCRIPTION
**Pull request by tvi**

### CODE REVIEW

**Comment by justinsb** [comment]
/ok-to-test

Seems good, but can I ask - how are you setting this then?  Are you setting it to a different value?

**Comment by tvi** [comment]
`@hostname`

**Comment by justinsb** [comment]
That makes sense @tvi - I didn't think that worked in the general case, but we definitely want to get there :-)

/approve
/lgtm

**Pull request merged**
