### PR TITLE
nodeup: if apt-get tells us to run dpkg configure, run it

### PR DESCRIPTION
**Pull request by justinsb**
This is a fallback against some of nastier edge cases we can fall into
otherwise.

### CODE REVIEW

**Comment by hakman** [comment]
This looks good. Probably https://github.com/kubernetes/kops/pull/16751 should be combined with this to pass all the tests.

**Comment by justinsb** [comment]
Added the skiplist here, but I _think_ there's something happening on GCE also which might still fail....

**Comment by hakman** [comment]
> Added the skiplist here, but I _think_ there's something happening on GCE also which might still fail....

One step closer.

**Comment by rifelpet** [comment]
@justinsb I believe this is causing some regressions in GCE:

https://testgrid.k8s.io/kops-network-plugins#kops-gce-cni-cilium-k8s-ci

A node is failing to join the cluster, with:

```
W0828 12:39:10.230865    4618 executor.go:141] error running task "Package/cgroupfs-mount" (6m19s remaining to succeed): error installing package "cgroupfs-mount": exit status 100: Reading package lists...
Building dependency tree...
Reading state information...
cgroupfs-mount is already the newest version (1.4).
0 upgraded, 0 newly installed, 0 to remove and 103 not upgraded.
1 not fully installed or removed.
Need to get 0 B/316 kB of archives.
After this operation, 0 B of additional disk space will be used.
dpkg: error processing package chrony (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
Errors were encountered while processing:
 chrony
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Pull request merged**
