### PR TITLE
Update to Cilium 1.14.5

### PR DESCRIPTION
**Pull request by hakman**
This fixes Cilium ENI mode tests

/cc @rifelpet

### CODE REVIEW

**Comment by hakman** [comment]
@zadjadr FYI, bumping to Cilium 1.14.5 fixes the ENI mode.

**Review by rifelpet — APPROVED** [review]

**Comment by rifelpet** [comment]
I see the eni fix was backported to 1.13 and 1.12 https://github.com/cilium/cilium/pull/29335 we should bump the cilium versions in the kops release branches too

**Comment by zadjadr** [comment]
Thanks for the info and update. Seems like cilium just wasn’t quite ready yet.

**Comment by hakman** [comment]
> Thanks for the info and update. Seems like cilium just wasn’t quite ready yet.

Wondering how they actually test releases...

**Comment by rifelpet** [comment]
Spot checking the grid jobs that have already ran since this was merged, it doesn't seem to have helped:

https://testgrid.k8s.io/kops-grid#kops-grid-cilium-eni-amzn2-k26

**Comment by hakman** [comment]
@rifelpet See https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-cilium-eni

**Pull request merged**
