### PR TITLE
Move cloudbuild.yaml to repo root

### PR DESCRIPTION
**Pull request by rifelpet**
This file is used by the push-to-staging postsubmit job that builds images and pushes them to a staging repo.

When it was originally added, my theory for why the [job was failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1209130004504383489) is that we were only uploading the ci/postsubmit/push-to-staging directory to GCS for use in cloudbuild, when in reality we need to upload the entire kops repo so it can run `make kops-controller-push`.

A while back I had [updated the job](https://github.com/kubernetes/test-infra/pull/15692) to use the repo root but hadn't created the cloudbuild.yaml file there yet, so instead we've been getting a [cloudbuild.yaml not found error](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1213230826582446081).

This PR moves the cloudbuild.yaml into the repo root so that the current job configuration will recognize it and hopefully be able to run `make kops-controller-push` in GCB.

### CODE REVIEW

**Comment by justinsb** [comment]
/retest

Hopefully fixed by #8506?

**Comment by justinsb** [comment]
I think you might need to rebase to pick up the netlify fix?

**Comment by rifelpet** [comment]
done :)

**Comment by rifelpet** [comment]
@justinsb the postsubmit job now takes 3 minutes but still fails without any output:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kops-postsubmit-push-to-staging/1225777317905698816

I'm guessing GCB is outputting an error but it is not making its way back into the prow job. Any chance you can take a look at the GCB error?

**Comment by rifelpet** [comment]
ah nevermind it turns out the logs are public.

`gs://k8s-staging-kops-gcb/logs/log-a7dc3a24-97cd-42fe-bec3-971dc78a0e3a.txt` is from the most recent postsubmit.  It looks like there is a couple different errors.

```
starting build "a7dc3a24-97cd-42fe-bec3-971dc78a0e3a"

FETCHSOURCE
Fetching storage object: gs://k8s-staging-kops-gcb/source/1581083100.47-5704f1a294b84ab2bb3a315a714640f9.tgz#1581083100618990
Copying gs://k8s-staging-kops-gcb/source/1581083100.47-5704f1a294b84ab2bb3a315a714640f9.tgz#1581083100618990...
- [1 files][ 21.7 MiB/ 21.7 MiB]
Operation completed over 1 objects/21.7 MiB.
BUILD
Pulling image: gcr.io/k8s-testimages/bazelbuild:v20190916-ec59af8-0.29.1
v20190916-ec59af8-0.29.1: Pulling from k8s-testimages/bazelbuild
35c102085707: Pulling fs layer
251f5509d51d: Pulling fs layer
8e829fe70a46: Pulling fs layer
6001e1789921: Pulling fs layer
8c2226a44295: Pulling fs layer
1f809ff6a571: Pulling fs layer
fc05857c3753: Pulling fs layer
0d5989913f1f: Pulling fs layer
630fab9a8198: Pulling fs layer
c2249bbbbeeb: Pulling fs layer
6001e1789921: Waiting
8c2226a44295: Waiting
1f809ff6a571: Waiting
fc05857c3753: Waiting
0d5989913f1f: Waiting
630fab9a8198: Waiting
c2249bbbbeeb: Waiting
8e829fe70a46: Verifying Checksum
8e829fe70a46: Download complete
251f5509d51d: Verifying Checksum
251f5509d51d: Download complete
6001e1789921: Verifying Checksum
6001e1789921: Download complete
35c102085707: Verifying Checksum
35c102085707: Download complete
fc05857c3753: Verifying Checksum
fc05857c3753: Download complete
1f809ff6a571: Verifying Checksum
1f809ff6a571: Download complete
8c2226a44295: Verifying Checksum
8c2226a44295: Download complete
630fab9a8198: Verifying Checksum
630fab9a8198: Download complete
c2249bbbbeeb: Verifying Checksum
c2249bbbbeeb: Download complete
0d5989913f1f: Verifying Checksum
0d5989913f1f: Download complete
35c102085707: Pull complete
251f5509d51d: Pull complete
8e829fe70a46: Pull complete
6001e1789921: Pull complete
8c2226a44295: Pull complete
1f809ff6a571: Pull complete
fc05857c3753: Pull complete
0d5989913f1f: Pull complete
630fab9a8198: Pull complete
c2249bbbbeeb: Pull complete
Digest: sha256:3c358e1e53442da0bd092c36ae30505f4b56f8281d3945e0dd8d3ae82a38300b
Status: Downloaded newer image for gcr.io/k8s-testimages/bazelbuild:v20190916-ec59af8-0.29.1
gcr.io/k8s-testimages/bazelbuild:v20190916-ec59af8-0.29.1
/bin/sh: 1: go: not found
/bin/sh: 1: cd: can't cd to /src/k8s.io/kops
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
DOCKER_REGISTRY=gcr.io DOCKER_IMAGE_PREFIX=k8s-staging-kops/ KOPS_CONTROLLER_TAG=1.18.0-alpha.2 bazel run --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //cmd/kops-controller:push-image
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: Rule 'distroless' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1570036739 -0700"
DEBUG: Call stack for the definition of repository 'distroless' which is a git_repository (rule definition at /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /workspace/WORKSPACE:80:1
Loading: 0 packages loaded
Analyzing: target //cmd/kops-controller:push-image (1 packages loaded, 0 targets configured)
Analyzing: target //cmd/kops-controller:push-image (10 packages loaded, 20 targets configured)
Analyzing: target //cmd/kops-controller:push-image (10 packages loaded, 20 targets configured)
Analyzing: target //cmd/kops-controller:push-image (10 packages loaded, 20 targets configured)
Analyzing: target //cmd/kops-controller:push-image (10 packages loaded, 20 targets configured)
Analyzing: target //cmd/kops-controller:push-image (17 packages loaded, 108 targets configured)
Analyzing: target //cmd/kops-controller:push-image (30 packages loaded, 252 targets configured)
Analyzing: target //cmd/kops-controller:push-image (35 packages loaded, 1478 targets configured)
Analyzing: target //cmd/kops-controller:push-image (35 packages loaded, 1478 targets configured)
Analyzing: target //cmd/kops-controller:push-image (35 packages loaded, 1478 targets configured)
Analyzing: target //cmd/kops-controller:push-image (47 packages loaded, 6667 targets configured)
INFO: Analyzed target //cmd/kops-controller:push-image (498 packages loaded, 9482 targets configured).
INFO: Found 1 target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: Process exited with status 1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Target //cmd/kops-controller:push-image failed to build
INFO: Elapsed time: 92.554s, Critical Path: 0.03s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Makefile:889: recipe for target 'kops-controller-push' failed
make: *** [kops-controller-push] Error 1
ERROR
ERROR: build step 0 "gcr.io/k8s-testimages/bazelbuild:v20190916-ec59af8-0.29.1" failed: exit status 2
```

**Pull request merged**
