### PR TITLE
don’t discard user's changes

### LINKED ISSUE #124: Behave better if validation fails
Currently we just reject the update and discard the user's changes.  This could be frustrating.  Better to do the same loop that I think kubectl does.

### PR DESCRIPTION
**Pull request by sethpollack**
Fix #124

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1741)

### CODE REVIEW

**Comment by yissachar** [comment]
Since this seems to replicate `kubectl edit` behaviour, we should be mindful of the issues raised in https://github.com/kubernetes/kubernetes/issues/26050.

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by justinsb** [comment]
@yissachar I agree, but I think if we get closer to the kubectl edit code we can apply any fixes they make - and if we make fixes we can apply them there also.

I know you've done something similar @yissachar as well, which can pick up "extra" fields.  AFAICT that isn't in this PR, but this PR does have the functionality to insert it into the header to make it easier to edit (well, at least consistent with `kubectl edit`).  I haven't reviewed this in detail yet (I presume it's essentially the same as kubectl edit), but without digging into the details it feels like we should merge this and then you can get your "dropped fields" detection into the edit list as well?  Do you agree?

**Comment by sethpollack** [comment]
This still needs to be implemented for `edit_federation.go` and `edit_instancegroup.go`. If you like the approach I will port it to those as well.

Also some functions return errors that can't be inserted into the header. For example the errors returned from `ParseVersionedYaml` include the original yaml file. So those use `preservedFile` instead. I also used `preservedFile` for functions that I wasn't sure how to replicate failure for.

**Comment by chrislovecnm** [comment]
@justinsb assigning this to you

**Comment by yissachar** [comment]
@justinsb Sure. I don't love the kubectl edit flow, but I understand the rationale behind syncing up with what they're doing.

**Comment by justinsb** [comment]
Nice - thanks @sethpollack - this will make a huge difference when I typo things - and I'm told I'm not alone in that :-)

**Pull request merged**
