### PR TITLE
Block bootstrap when the node already exists

### PR DESCRIPTION
**Pull request by justinsb**
We now do this across all clouds, as it has been demonstrated on
OpenStack.

### CODE REVIEW

**Comment by hakman** [comment]
@justinsb `pull-kops-e2e-k8s-gce-ipalias` always running intentionally?

**Comment by justinsb** [comment]
/test pull-kops-e2e-k8s-gce-ipalias

Seems very unrelated: `creating apiservice v1alpha1.wardle.example.com: apiservices.apiregistration.k8s.io "v1alpha1.wardle.example.com" already exists`

This is the brand-new job though, so could be real (though unlikely to be related to the PR itself)

**Comment by hakman** [comment]
@justinsb Should this be removed from the OpenStack side?
/lgtm

**Comment by justinsb** [comment]
> @justinsb Should this be removed from the OpenStack side?

I think it should, but I thought it was harmless to double-check it first.  I can send a separate PR to @zetaab to approve, maybe that's the best way?

**Comment by zetaab** [comment]
@justinsb there is one possible problem: if you restart the node itself and after it will come back up, it will try to re-register itself if I remember correctly. We should think how it should behave in that case. Nodes are not restarting often but anyway it should work somehow.

**Comment by justinsb** [comment]
> if you restart the node itself and after it will come back up, it will try to re-register itself if I remember correctly.

Thanks for reminding me!  I think what we should do is to try to save keys to disk and reuse them.  (I think we're saving them to disk anyway).  I don't think we're reusing them today, but I don't think it's too hard, and with any luck, that should mean we don't need to issue the bootstrap request again.

But I will double-check this scenario.  If it doesn't work in general, we could create a "machine key" that we issue as normal, but then we can use this key if the node does need to do reauthentication.  We were talking about whether we should introduce a machine key anyway, but it's more complexity because we probably have to store that machine key and it isn't obvious where to store it.  It would probably have to be a new CRD, because the node likely doesn't exist until after this call completes and the kubelet eventually registers.  Anyway, @hakman and I were hoping to get away without it, but good call on testing node restart!

**Comment by hakman** [comment]
OK, let's iterate in separate PRs.
/approve

**Pull request merged**
