### PR TITLE
DO NOT MERGE - Test kops presubmit

### PR DESCRIPTION
**Pull request by krzyzacy**
test https://github.com/kubernetes/test-infra/pull/3304
/assign

### CODE REVIEW

**Comment by krzyzacy** [comment]
w/ https://github.com/kubernetes/test-infra/pull/3557

**Comment by chrislovecnm** [comment]
You are missing an environment var that sets the gs path in th build

**Comment by krzyzacy** [comment]
@chrislovecnm ah, figured, thanks :-)

**Comment by chrislovecnm** [comment]
Going to close this, please reopen if you need to

**Comment by krzyzacy** [comment]
@chrislovecnm thanks! and can you kindly review https://github.com/kubernetes/test-infra/pull/3566 :-)

**Comment by chrislovecnm** [comment]
Done

**Comment by krzyzacy** [comment]
/test pull-kops-e2e-kubernetes-aws-scenario
w/ https://github.com/kubernetes/test-infra/pull/3566

**Comment by chrislovecnm** [comment]
So I gotta get the low down, aka instructions, on what this does

**Comment by krzyzacy** [comment]
so currently kops presubmit uses https://github.com/kubernetes/test-infra/blob/master/jobs/pull-kops-e2e-kubernetes-aws.sh, which is a legacy long bash script, where all other kubernetes e2e jobs already uses [some other python wrapper](https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_kops_aws.py) so it will be easier to maintain for jobs have similar behaviors.

**Comment by krzyzacy** [comment]
wait how does `KOPS_BASE_URL="${GCS_LOCATION/gs:\/\//https:\/\/storage.googleapis.com\/}/${KOPS_VERSION}"` work? (me bash noob)

**Comment by krzyzacy** [comment]
/test pull-kops-e2e-kubernetes-aws-scenario
w/ https://github.com/kubernetes/test-infra/pull/3591

**Comment by krzyzacy** [comment]
/test pull-kops-e2e-kubernetes-aws-scenario
w/ https://github.com/kubernetes/test-infra/pull/3594

**Comment by krzyzacy** [comment]
woo, passed :-)

**Comment by krzyzacy** [comment]
okay passed with https://github.com/kubernetes/test-infra/pull/3114, assume that's good for now.

/close

**Pull request closed without merging**
