### PR TITLE
Fix RollingUpdate behaviour when using LaunchTemplates for both kops & terraform spec updates

### PR DESCRIPTION
**Pull request by KashifSaadat**
There have been a few regressions in the way InstanceGroups are marked for a RollingUpdate when `LaunchTemplates` are involved (e.g. when using Mixed Instance Policies). This bug resulted in one of two scenarios that I've seen (with previous attempted fixes regressing one of the scenarios):
- Updates via kops (`kops update cluster --yes`) did not set a LT Version, and so an Instance Group using a Mixed Instance Policy would always be marked as `NeedsUpdate` when performing a Rolling Update
- Updates via terraform (`kops update cluster --out=tf-files/ --target=terraform`) were not being marked for a RollingUpdate as the Version was not picked up and matched between changes

This PR aims to fix the above two scenarios. I've tested a cluster build with 2 different Instance Groups (one standard and another with mixed policy), via kops updates and terraform, and both appear to have expected behaviour with marking the correct nodes for an update between changes.

### CODE REVIEW

**Comment by KashifSaadat** [comment]
- Follows on from: #8038
- Fixes: #6796
- No longer required: #7118

**Comment by paalkr** [comment]
Will this be added to the 1.16 branch, and included in the next 1.16 release?

**Pull request merged**
