### PR TITLE
Adding a diagram covering rolling updates.

### PR DESCRIPTION
**Pull request by chrislovecnm**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2405)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@brandoncole can I get a review?

**Comment by justinsb** [comment]
Can we get the source file for this please?  Otherwise we can't update...

**Comment by chrislovecnm** [comment]
@justinsb it is omnigraffe ... I will include

**Comment by brandoncole** [comment]
LGTM @chrislovecnm

**Pull request merged**
