### PR TITLE
Add terraform target support for configuring Warm Pool

### PR DESCRIPTION
**Pull request by rsafonseca**
Addresses https://github.com/kubernetes/kops/issues/11633

### CODE REVIEW

**Comment by rsafonseca** [comment]
Seems like CLA site is currently broken, i've opened a support ticket with them so I can get that check fixed on this PR :)

**Comment by hakman** [comment]
Looks good to me also. Thanks @rsafonseca!
/approve

**Comment by rsafonseca** [comment]
@hakman can we also get this backported into current supported branches? I can do some PRs for each minor if needed :)

**Comment by hakman** [comment]
> @hakman can we also get this backported into current supported branches? I can do some PRs for each minor if needed :)

Done for 1.26 and 1.25. Let's see what @olemarkus thinks about it.

**Comment by rsafonseca** [comment]
> > @hakman can we also get this backported into current supported branches? I can do some PRs for each minor if needed :)
> 
> Done for 1.26 and 1.25. Let's see what @olemarkus thinks about it.

Awesome! Thanks for the speedy turnaround in this :D 
Do you have any plans for when the next patch release for 1.25 will be? :)

**Comment by hakman** [comment]
> Awesome! Thanks for the speedy turnaround in this :D Do you have any plans for when the next patch release for 1.25 will be? :)

Happy to help. Would say 1-2 weeks max.

**Pull request merged**
