### PR TITLE
Fix Terraform state link at docs

### PR DESCRIPTION
**Pull request by pfeodrippe**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/2162)

### CODE REVIEW

**Comment by pfeodrippe** [comment]
@k8s-ci-robot I signed it!

**Comment by yissachar** [comment]
@k8s-bot ok to test

**Comment by yissachar** [comment]
Thanks @pfeodrippe!

**Comment by pfeodrippe** [comment]
@yissachar kops is awesome! hope to help much more o/

**Pull request merged**
