### PR TITLE
chore(networking): bump aws cni to 1.16.2

### PR DESCRIPTION
**Pull request by moshevayner**
**What this PR does / why we need it**:
Update AWS CNI Version to latest release (v1.16.2)

**Special notes for your reviewer**:
Release page: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.16.2

/cc @hakman

### CODE REVIEW

**Comment by moshevayner** [comment]
Hey @hakman!
Following our chat on the previous PR (#16191) - I've been able to spin up a cluster on my personal AWS account using a binary built from my branch, and it successfully validated (see output below).
One caveat is that I had to specifically use a `focal` image, because with `jammy` I still hit the same issue from #16255 . I'll get to work on a fix as soon as possible, so that `jammy` will also work out of the box.
Let me know what you think.
Thanks!

Commands ran locally (with fast-forwarded output):
```
➜  kops git:(aws-cni-1.16.2) make kops
➜  kops git:(aws-cni-1.16.2) .build/dist/darwin/arm64/kops create cluster --name "cluster.kops-test.vayner.me" --zones us-east-1a --networking amazonvpc --image 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20240126
.
.
.
➜  kops git:(aws-cni-1.16.2) .build/dist/darwin/arm64/kops update cluster --name cluster.kops-test.vayner.me -y 
.
.
.
➜  kops git:(aws-cni-1.16.2) .build/dist/darwin/arm64/kops export kubecfg --admin --name cluster.kops-test.vayner.me                                                                                                          
kOps has set your kubectl context to cluster.kops-test.vayner.me
➜  kops git:(aws-cni-1.16.2) .build/dist/darwin/arm64/kops validate cluster --wait 10m
Using cluster from kubectl context: cluster.kops-test.vayner.me

Validating cluster cluster.kops-test.vayner.me

INSTANCE GROUPS
NAME                            ROLE            MACHINETYPE     MIN     MAX     SUBNETS
control-plane-us-east-1a        ControlPlane    t3.medium       1       1       us-east-1a
nodes-us-east-1a                Node            t3.medium       1       1       us-east-1a

NODE STATUS
NAME                    ROLE            READY
i-050537a81cc545dca     node            True
i-05f719733b1b6de37     control-plane   True

Your cluster cluster.kops-test.vayner.me is ready
```

**Review by hakman — APPROVED** [review]
Thanks @moshevayner! 😄

**Pull request merged**
