### PR TITLE
Set bazel version

### PR DESCRIPTION
**Pull request by mikesplain**
* Set bazel version for use with tools like [bazelisk](https://github.com/bazelbuild/bazelisk)
* As suggested by @justinsb, we should start with a more modern version

/assign @justinsb

### CODE REVIEW

**Comment by mikesplain** [comment]
Adding hold until more testing is done.

/hold

**Comment by justinsb** [comment]
I think this looks great - we're specifying what was previously unspecified, so it seems like a good thing.  I'm running 1.2.0 (it's the version in the apt repos), so I think this makes sense.  But also fine to hold for more verification!

/approve
/lgtm

**Comment by rdrgmnzs** [comment]
Looks great, thanks @mikesplain !

/lgtm

**Comment by mikesplain** [comment]
Since no objections...

/hold cancel

**Pull request merged**
