### PR TITLE
Fixup kubelet and controlPlaneKubelet config building

### PR DESCRIPTION
**Pull request by justinsb**
We need to differentiate between the version of the control plane
and the version of the nodes.

### CODE REVIEW

**Comment by justinsb** [comment]
/retest

Both on cilium, so _could_ be real, but worth a retest

**Comment by hakman** [comment]
> /retest
> 
> Both on cilium, so _could_ be real, but worth a retest

eni always fails on those 2 tests

**Review by hakman — APPROVED** [review]

**Pull request merged**
