### PR TITLE
Update prometheus-operator to support k8sv >= 1.16.0

### PR DESCRIPTION
**Pull request by flouthoc**
Following PR is a addon PR similar to : https://github.com/kubernetes/kops/pull/7067 , which adds latest supported prometheus-operator for `k8sv >= 1.16.0` to kops addons.

### CODE REVIEW

**Comment by flouthoc** [comment]
@chrisz100 Could you please take a look, adding you since you reviewed  previous PR related to addons.

**Comment by flouthoc** [comment]
@chrisz100 I think **tide** test needs approved label.

**Comment by hakman** [comment]
Thanks @flouthoc .
/approve

**Pull request merged**
