### PR TITLE
scale-test: Use single nodes instance group for AWS

### PR DESCRIPTION
**Pull request by hakman**
/cc @dims @hakuna-matatah @upodroid

### CODE REVIEW

**Comment by hakman** [comment]
```
INSTANCE GROUPS
NAME				ROLE		MACHINETYPE	MIN	MAX	SUBNETS
control-plane-us-east-2a	ControlPlane	c5.18xlarge	1	1	us-east-2a
control-plane-us-east-2b	ControlPlane	c5.18xlarge	1	1	us-east-2b
control-plane-us-east-2c	ControlPlane	c5.18xlarge	1	1	us-east-2c
nodes				Node		t3a.medium	5000	5000	us-east-2a-1,us-east-2a-4,us-east-2a-7,us-east-2a-10,us-east-2b-2,us-east-2b-5,us-east-2b-8,us-east-2b-11,us-east-2c-3,us-east-2c-6,us-east-2c-9,us-east-2c-12
```

**Comment by hakuna-matatah** [comment]
Thanks @hakman for making this change, I was looking in the account to see how the IP allocation was happening across subnets but it looks it's deleting the nodes already, scale test failed w following error.  
```
+ kubetest2 kops -v=2 --cloud-provider=aws --cluster-name=e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io --kops-binary-path=/home/prow/go/src/k8s.io/bin/kops --admin-access=0.0.0.0/0 --env=KOPS_FEATURE_FLAGS=AWSSingleNodesInstanceGroup, --validation-wait=55m --up --kubernetes-version=v1.29.0 '--create-args=--network-cidr=10.0.0.0/16,10.1.0.0/16,10.2.0.0/16,10.3.0.0/16,10.4.0.0/16,10.5.0.0/16,10.6.0.0/16,10.7.0.0/16,10.8.0.0/16,10.9.0.0/16,10.10.0.0/16,10.11.0.0/16,10.12.0.0/16 --networking=amazonvpc --set spec.networking.amazonVPC.env=ENABLE_PREFIX_DELEGATION=true --image=ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id --set spec.etcdClusters[0].manager.listenMetricsURLs=http://localhost:2382 --set spec.etcdClusters[0].manager.env=ETCD_QUOTA_BACKEND_BYTES=8589934592 --set spec.etcdClusters[1].manager.env=ETCD_QUOTA_BACKEND_BYTES=8589934592 --set spec.kubelet.maxPods=96 --set spec.kubeScheduler.authorizationAlwaysAllowPaths=/healthz --set spec.kubeScheduler.authorizationAlwaysAllowPaths=/metrics --set spec.kubeScheduler.kubeAPIQPS=500 --set spec.kubeScheduler.kubeAPIBurst=500 --set spec.kubeScheduler.enableProfiling=true --set spec.kubeScheduler.enableContentionProfiling=true --set spec.kubeControllerManager.endpointUpdatesBatchPeriod=500ms --set spec.kubeControllerManager.endpointSliceUpdatesBatchPeriod=500ms --set spec.kubeControllerManager.kubeAPIQPS=100 --set spec.kubeControllerManager.kubeAPIBurst=100 --set spec.kubeControllerManager.enableProfiling=true --set spec.kubeControllerManager.enableContentionProfiling=true --set spec.kubeAPIServer.maxRequestsInflight=800 --set spec.kubeAPIServer.maxMutatingRequestsInflight=400 --set spec.kubeAPIServer.enableProfiling=true --set spec.kubeAPIServer.enableContentionProfiling=true --set spec.kubeAPIServer.anonymousAuth=true --set spec.kubeProxy.metricsBindAddress=0.0.0.0:10249 --node-count=5000 --dns none --node-size=t3a.medium,t3.medium,t2.medium,t3a.large,c5a.large,t3.large,c5.large,m5a.large,m6a.large,m5.large,c4.large,c7a.large,r5a.large,r6a.large,m7a.large --node-volume-size=20 --control-plane-count=3 --master-size=c5.18xlarge --zones=us-east-2a,us-east-2b,us-east-2c --set spec.cloudProvider.aws.ebsCSIDriver.kubeAPIQPS=100 --set spec.cloudProvider.aws.ebsCSIDriver.kubeAPIBurst=100'
I0103 15:10:08.070486   14416 app.go:61] The files in RunDir shall not be part of Artifacts
I0103 15:10:08.070516   14416 app.go:62] pass rundir-in-artifacts flag True for RunDir to be part of Artifacts
I0103 15:10:08.070538   14416 app.go:64] RunDir for this run: "/home/prow/go/src/k8s.io/kops/_rundir/82bd5d80-4c72-4594-99c5-972a62b27c51"
I0103 15:10:08.114585   14416 app.go:130] ID for this run: "82bd5d80-4c72-4594-99c5-972a62b27c51"
I0103 15:10:08.121633   14416 up.go:58] Cleaning up any leaked resources from previous cluster
I0103 15:10:08.333799   14416 dumplogs.go:47] /home/prow/go/src/k8s.io/bin/kops toolbox dump --name e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io --dir /logs/artifacts --private-key /tmp/kops/e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io/id_ed25519 --ssh-user ubuntu
I0103 15:10:08.342055   14452 featureflag.go:168] FeatureFlag "AWSSingleNodesInstanceGroup"=true
W0103 15:10:37.878181   14452 toolbox_dump.go:172] cannot load kubeconfig settings for "e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io": context "e2e-ff02749ef8-a423a.test-cncf-aws.k8s.io" does not exist
```

**Comment by hakman** [comment]
@hakuna-matatah Give it another try

**Comment by upodroid** [comment]
/test presubmit-kops-aws-scale-amazonvpc-using-cl2

pod got killed :(

**Review by upodroid — APPROVED** [review]
LGTM

**Comment by hakuna-matatah** [comment]
This PR is relevant to this [issue](https://github.com/kubernetes/kops/issues/16180)

**Pull request merged**
