### PR TITLE
Only update kubeconfig user when we have user info

### PR DESCRIPTION
**Pull request by justinsb**
This preserves existing user configuration.

Issue #11537

### CODE REVIEW

**Review by johngmyers — APPROVED** [review]

**Comment by ryan-dyer-sp** [comment]
@justinsb Any chance this can get back ported to other releases?

**Comment by hakman** [comment]
@ryan-dyer-sp Which other releases?

**Comment by ryan-dyer-sp** [comment]
@hakman 1.20 would be great.

**Comment by hakman** [comment]
@ryan-dyer-sp Already in 1.20. See https://github.com/kubernetes/kops/pull/11587.

**Pull request merged**
