### PR TITLE
Update containerd to v1.6.20

### PR DESCRIPTION
**Pull request by anthonyhaussman**
- https://github.com/containerd/containerd/releases/tag/v1.6.19
 - https://github.com/containerd/containerd/releases/tag/v1.6.20

### CODE REVIEW

**Comment by hakman** [comment]
@anthonyhaussman This looks good. Could you split the Go part into a separate commit, like in https://github.com/kubernetes/kops/pull/15159/commits? It would make it easier to cherry-pick.

**Comment by anthonyhaussman** [comment]
> @anthonyhaussman This looks good. Could you split the Go part into a separate commit, like in https://github.com/kubernetes/kops/pull/15159/commits? It would make it easier to cherry-pick.

It's done @hakman :slightly_smiling_face:

**Comment by hakman** [comment]
Thanks @anthonyhaussman!
/retest

**Review by hakman — APPROVED** [review]

**Comment by olemarkus** [comment]
It's been released, but kOps needs to start supporting downloading and using it. The credentials provider is also not really tested upstream, so there may be more work needed there as well.

Currently working on what's needed kOps-side and will then add e2e in the aws cloud provider.

**Comment by rifelpet** [comment]
How about reverting the deps update? That way the head of master is not broken

**Comment by olemarkus** [comment]
The problem is that the functionality for pulling ECR-containers are removed from kubelet. So we'd have to run these tests with K8s 1.26 instead. Which I am not necessarily against. If the ECR credentials provider is also broken, we won't get the PR to start using it into the repo either.

**Comment by rifelpet** [comment]
If we know k8s 1.27 doesn't work with kops yet then temporarily pinning our presubmit tests to k8s 1.26 seems reasonable

**Pull request merged**
