### PR TITLE
Check NS records as part of kops apply

### PR DESCRIPTION
**Pull request by justinsb**
Issue #585

Also, move FindDNSHostedZone to utils

### CODE REVIEW

**Comment by chrislovecnm** [comment]
needs a rebase

**Comment by kris-nova** [comment]
Calling out test coverage, but the code looks solid.

**Comment by chrislovecnm** [comment]
You want to file an issue to improve tests or wait on merging the PR?

**Comment by kris-nova** [comment]
@chrislovecnm - https://github.com/kubernetes/kops/issues/663 Should cover the testing concern here - this PR LGTM, I am fine without a squash

**Comment by chrislovecnm** [comment]
LGTM

**Pull request merged**
