### PR TITLE
Write Terraform vpc_cidr_block output for shared VPCs

### PR DESCRIPTION
**Pull request by johngmyers**
Will need this for IPv6 `/64#N` support.

### CODE REVIEW

**Comment by johngmyers** [comment]
Fixing mock implementation bug in #14634 
/retest

**Comment by rifelpet** [comment]
should the terraform output name suggest that it is the ipv4 cidr block? `vpc_ipv4_cidr_block` or something along those lines

**Comment by johngmyers** [comment]
@rifelpet I was sticking with Terraform's terminology.

**Comment by johngmyers** [comment]
Plus, that was the name we were using for owned VPCs.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
