### PR TITLE
Copy alpha channel to stable

### PR DESCRIPTION
**Pull request by justinsb**
Recommend k8s 1.8.6, AMI with kernel 4.4.110

### CODE REVIEW

**Comment by mikesplain** [comment]
Doesn't this need tests updated to work? 

https://github.com/kubernetes/kops/blob/master/tests/integration/create_cluster/overrides/expected-v1alpha2.yaml

**Comment by justinsb** [comment]
@mikesplain - yes, it does! This just caught up in the problems with moving to the new AWS account, so I hadn't checked whether the failure was real or fake...

Should be good now :-)

**Pull request merged**
