### PR TITLE
update go version and ldflags

### PR DESCRIPTION
**Pull request by oilbeater**
update go version to 1.9.3 and add -w ldflag to remove DWARF symbol table from binary see: https://golang.org/cmd/link/

### CODE REVIEW

**Comment by oilbeater** [comment]
kubernetes has use 1.9.3 in this commit https://github.com/kubernetes/kubernetes/commit/c555a7f3c95d740bea5fa249dd30bcbdc7328a7a

**Comment by chrislovecnm** [comment]
We also have dockerfiles to update.  For instance https://github.com/kubernetes/kops/blob/master/images/dns-controller-builder/Dockerfile

If you could get those in another PR, that would be awesome.

**Comment by oilbeater** [comment]
Another PR https://github.com/kubernetes/kops/pull/4366

**Comment by justinsb** [comment]
@oilbeater thanks for bringing up up-to-date.  Question on the `-w` flag - I'm just trying to figure out what the consequences are of removing the DWARF table.  Does kubernetes/kubernetes use it?  What was the goal of setting the flag here?

**Comment by oilbeater** [comment]
Kubernetes has use this flag. This flag will trip some debugger needed information that map assemble code back to golang code. For a production environment we can strip them out to minimize binary size.

**Pull request merged**
