### PR TITLE
 Remove custom Statement IDs from IAM Policy Statements

### LINKED ISSUE #4953: Is there any value in the IAM Sid?
Our IAM policies set Sid, which is optional but must be unique if set.  That went wrong in #4951 .

We should revisit whether there is a case for setting these at all, particularly because the allowed characters makes them ugly anyway (A-Z,a-z,0-9)

### PR DESCRIPTION
**Pull request by KashifSaadat**
Fixes #4953

### CODE REVIEW

**Comment by justinsb** [comment]
I think this is right, but I think we should do this in 1.10 at this point

**Comment by justinsb** [comment]
Thanks for fixing @KashifSaadat !

**Comment by KashifSaadat** [comment]
Sure sounds good, no worries :)

**Comment by justinsb** [comment]
/lgtm

Thanks @KashifSaadat

**Pull request merged**
