### PR TITLE
Promote alphas to stable

### PR DESCRIPTION
**Pull request by olemarkus**
Been in alpha for 12 days. Also worth doing given  https://github.com/kubernetes/kubernetes/issues/92315

### CODE REVIEW

**Comment by hakman** [comment]
@olemarkus Could you also update the Ubuntu images?

**Comment by olemarkus** [comment]
@hakman alpha didn't bump image either. Don't we want to run the new image through alpha first?

**Comment by hakman** [comment]
In current situation, no. We did not release 1.18 yet so should be ok.
From now on, alphas bump should include image bumps also.

**Comment by olemarkus** [comment]
I'll do another PR to bump the ubuntu image in both channels then.
/retest

**Comment by olemarkus** [comment]
Or on second thoughs. I'll just do another commit.

**Pull request merged**
