### PR TITLE
Update CoreDNS version and manifest

### PR DESCRIPTION
**Pull request by rajansandeep**
CoreDNS is now v1.2.2

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks for this @rajansandeep! Can you also bump the version here, and leave the `-kops.1` appended so we can do kops specific bumps when needed.

https://github.com/kubernetes/kops/blob/d8a4f967ebf746a8f49f7906761fd0196969f0b4/upup/pkg/fi/cloudup/bootstrapchannelbuilder.go#L214

Besides that, looks good! Thanks!

**Comment by rajansandeep** [comment]
@mikesplain done!

**Comment by mikesplain** [comment]
Great thanks! 

/lgtm
/approve

**Pull request merged**
