### PR TITLE
[Add-on][kube-state-metrics] Bump version

### PR DESCRIPTION
**Pull request by tuannvm**
## Why?
- Bump kube-state-metrics version 1.1.0
- Bump addon-resizer version to 1.8.1
- Adjust `addon-resizer` scaling threshold

### CODE REVIEW

**Comment by justinsb** [comment]
/lgtm

Thanks @tuannvm !  I did notice that the addon-resizer version in the kube-state-metrics repo was still 1.0 (https://github.com/kubernetes/kube-state-metrics/blob/master/kubernetes/kube-state-metrics-deployment.yaml#L30) - do you know why that wasn't updated?

**Comment by tuannvm** [comment]
Hi @justinsb I think they just start to tag release version probably from 1.8.0, and it seems the version follow golang release as well.
The add-on resizer 1.0 is quite old already (back to 2016). Also, I've tested the latest version (1.8.1) on my end and it seems to work well.

**Comment by 23doors** [comment]
@tuannvm TBH dunno how you tested 1.8.1 but it doesn't work at all. For one, you can no longer pass default cpu and such as flags. In a result you just get crashloop on addon-resizer container (due to panic on MustParse as it defaults to empty values). 

I would suggest using 1.0 for now - or adapt to file-based config (like here https://github.com/kubernetes/autoscaler/tree/addon-resizer-release-1.8/addon-resizer#example-deployment-file). But considering that even 1.2.0 rc of kube-state-metrics didn't update it on their own, there seems to be no reason to force this update.

**Pull request merged**
