### PR TITLE
Use distroless image as base for Protokube

### PR DESCRIPTION
**Pull request by hakman**
This builds on #9377 and moves Protokube to the distroless base image.

### CODE REVIEW

**Comment by hakman** [comment]
@justinsb as you can see, distroless Protokube works without issues.
It uses the systemd binaries from the hosts and mounts are still handled with systemd.

**Comment by hakman** [comment]
As you can see, distroless Protokube works without issues.
It uses the systemd binaries from the hosts and mounts are still handled with systemd.
/cc @justinsb

**Comment by hakman** [comment]
@justinsb any chance you could review this?

**Comment by hakman** [comment]
This doesn't work for etcd legacy provider. It is fixable, if we want to keep it though. We would just have to run the commands in chroot.

**Comment by johngmyers** [comment]
Kops 1.19 currently supports k8s 1.11, which defaults to legacy provider.

**Comment by hakman** [comment]
> Kops 1.19 currently supports k8s 1.11, which defaults to legacy provider.

This is how I found out it doesn't work 😁

**Comment by hakman** [comment]
Simplest solution for legacy provider is to mount `/bin` and `/sbin` from the host.
This provides access to all the binaries required by `utils/mount` and `utils/nsenter`.

**Comment by hakman** [comment]
Current version of the PR works with both `Manager` and `Legacy` etcd providers.

**Comment by johngmyers** [comment]
Perhaps add TODO comments on the bits that can be removed with legacy etcd provider.

**Comment by hakman** [comment]
> Perhaps add TODO comments on the bits that can be removed with legacy etcd provider.

I think it is a bit premature to add a TODO for that. The `mount` and `nsenter` libs could be used for any number of other reasons by the time the Legacy etcd provider is removed. The comments for the mounts should be sufficient to remind about that.

**Comment by hakman** [comment]
I cleaned up the initial commit to only move the kubelet startup to nodeup.
That being said, this is good to go from my point of view.
/hold cancel

**Comment by olemarkus** [comment]
Looks good to me as well.
/lgtm

**Comment by justinsb** [comment]
Thanks for doing this, and for fixing the legacy issue.

I'm OK with trying this for 1.19.  I propose we not backport to 1.18 though, as we want plenty of time for this to "bake".

/approve
/lgtm

**Comment by hakman** [comment]
Thanks for reviewing this @justinsb :).
I agree that 1.18 should stay as is. I think we are all very eager to see it released.

**Pull request merged**
