### PR TITLE
fixing validate output, it was printing all of the same instance groups

### PR DESCRIPTION
**Pull request by chrislovecnm**
closes https://github.com/kubernetes/kops/issues/1059

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1060)

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM.

It's precisely because of this that we usually prefer `[]*T`.  And the idiom is usually:

```
for i := range list {
  item := &list[i]
  ...
```

**Comment by justinsb** [comment]
Not sure if you'd rather merge as is or tweak to keep a slice of pointers.  Feel free to self-merge either way...

**Comment by chrislovecnm** [comment]
I don't self-merge PRs :)  @kris-nova can handle that for me ;)

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
I want to fix this in the rolling-update PR.

**Pull request closed without merging**
