### PR TITLE
Add node/master size from create cluster into IG spec

### LINKED ISSUE #14346: kops not able to create arm64 type Kubernetes cluster
/kind bug

**1. kops version: v1.25.0**

**2. kubectl version: v1.25.2**

**3. cloud provider using: aws**

**4. Commands ran:**
```
export KOPS_STATE_STORE=s3://kops-state-store1
export AWS_ACCESS_KEY_ID=<your-aws-access-key-id>
export AWS_SECRET_ACCESS_KEY=<your-aws-secret-access-key>
export KOPS_CLUSTER_NAME=sample-cluster.k8s.local

kops create cluster --name=$KOPS_CLUSTER_NAME \
    --node-count=1 \
    --node-size=m6g.xlarge \
    --cloud aws \
    --zones us-west-2a \
    --master-size m6g.xlarge \
    --topology private \
    --networking amazon-vpc-routed-eni
```

**5. Output:**
```
I0927 17:12:35.211369   13029 new_cluster.go:1277]  Cloud Provider ID = aws
I0927 17:12:37.318956   13029 subnets.go:185] Assigned CIDR 172.20.32.0/19 to subnet us-west-2a
I0927 17:12:37.319437   13029 subnets.go:199] Assigned CIDR 172.20.0.0/22 to subnet utility-us-west-2a
Previewing changes that will be made:

Error: master-us-west-2a.spec.machineType: Invalid value: "m6g.xlarge": machine type architecture does not match image architecture: "arm64" - "x86_64"
```
and exited after this.

**6. With the earlier version of the kops (v1.24.3), it used to print the list of resources that would be created and other suggestions and later on running the below command would actually create the cluster:**
```
kops update cluster --name ${KOPS_CLUSTER_NAME} --yes --admin
```

**7. Cluster manifest:**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2022-09-27T11:42:47Z"
  name: sample-cluster.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state-store1/sample-cluster.k8s.local
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-us-west-2a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.25.2
  masterPublicName: api.sample-cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    amazonvpc: {}
  nonMasqueradeCIDR: 172.20.0.0/16
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.20.0.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-09-27T11:42:49Z"
  labels:
    kops.k8s.io/cluster: sample-cluster.k8s.local
  name: master-us-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220810
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: m6g.xlarge
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-west-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-09-27T11:42:50Z"
  labels:
    kops.k8s.io/cluster: sample-cluster.k8s.local
  name: nodes-us-west-2a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220810
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6g.xlarge
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2a
```

**8. kops get --name ${KOPS_CLUSTER_NAME} -o yaml -v 10**

```
I0927 17:32:23.305100   14461 factory.go:83] state store s3://kops-state-store1
I0927 17:32:23.306588   14461 s3context.go:345] GOOS="darwin", assuming not running on EC2
I0927 17:32:23.306596   14461 s3context.go:175] defaulting region to "us-east-1"
I0927 17:32:24.303517   14461 s3context.go:215] found bucket in region "us-west-2"
I0927 17:32:24.305024   14461 s3fs.go:329] Reading file "s3://kops-state-store1/sample-cluster.k8s.local/config"
I0927 17:32:25.528165   14461 s3fs.go:366] Listing objects in S3 bucket "kops-state-store1" with prefix "sample-cluster.k8s.local/instancegroup/"
I0927 17:32:25.911170   14461 s3fs.go:394] Listed files in s3://kops-state-store1/sample-cluster.k8s.local/instancegroup: [s3://kops-state-store1/sample-cluster.k8s.local/instancegroup/master-us-west-2a s3://kops-state-store1/sample-cluster.k8s.local/instancegroup/nodes-us-west-2a]
I0927 17:32:25.911281   14461 s3fs.go:329] Reading file "s3://kops-state-store1/sample-cluster.k8s.local/instancegroup/master-us-west-2a"
I0927 17:32:26.220812   14461 s3fs.go:329] Reading file "s3://kops-state-store1/sample-cluster.k8s.local/instancegroup/nodes-us-west-2a"
I0927 17:32:26.561562   14461 s3fs.go:329] Reading file "s3://kops-state-store1/sample-cluster.k8s.local/clusteraddons/default"
```
rest remains same as previous output

**9. This is working fine with kops version v1.24.3. Also I tried running on my mac as well as on ubuntu20, but on both places I am seeing the same error message.**

### PR DESCRIPTION
**Pull request by olemarkus**
Fixes #14346

### CODE REVIEW

**Comment by hakman** [comment]
Should we also remove these?
https://github.com/kubernetes/kops/blob/b193a3d35ccb9c19c88c3979858913f65192b203/cmd/kops/create_cluster.go#L547-L551
https://github.com/kubernetes/kops/blob/b193a3d35ccb9c19c88c3979858913f65192b203/cmd/kops/create_cluster.go#L583-L587

**Comment by olemarkus** [comment]
Yeah. Good catch

**Review by hakman — APPROVED** [review]

**Pull request merged**
