### PR TITLE
Containerd repo mirror auth

### PR DESCRIPTION
**Pull request by haad**
Add support for registry mirror authentication with containerD. This was managed byt overiding cotnainerd config as whole.

### CODE REVIEW

**Comment by haad** [comment]
Ping

**Comment by hakman** [comment]
Hi @haad. Sorry for the delay in answering. We had some discussions about this topic at our weekly meeting and some concerns were raised about adding passwords directly into kOps config. There was no consensus on how to approach this last week, but it's still on our list of priorities.

One question came up about the use of Docker secrets managed by kOps which are directly used by k8s even with containerd. Did you try to see if those work somehow for the mirrors too?.

**Comment by haad** [comment]
I understand, but We are not forcing our users to include those passwords there. Plus you have an option to use a token, too. Right no every Kops users has to override this config as a whole which isn't a good thing. It complicates workflow for them as they have to check if we have not changed default configuration(containerd/config.toml) before each upgrade.


We should be able to add some cloud based password insertion scheme (Use aws system parameters as passwords), but I would add/implment that functionality as a separate PR.

**Comment by blakebarnett** [comment]
Shouldn't this be implemented similarly to the host-level docker auth (as a secret)? We could maybe abstract it to be a generic "registry auth" secret, and have it apply to both...

https://github.com/kubernetes/kops/pull/3087

**Comment by olemarkus** [comment]
That would be my preferred way of implementing this

**Pull request closed without merging**
