### PR TITLE
WIP: Use instance group for bastions

### PR DESCRIPTION
**Pull request by justinsb**
@chrislovecnm @kris-nova this is where I am heading.  Lots to do whittling this down, and also figuring out what the v1alpha2 schema should look like

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1110)

### CODE REVIEW

**Comment by kris-nova** [comment]
CC @jmound @alok87 @geojaz - I know the bastion stuff directly effects some of you guys - this is a big change :)

**Comment by kris-nova** [comment]
@justinsb - let me know when you are ready for a code review - otherwise I am going to let you have it with your WIP

**Comment by chrislovecnm** [comment]
rebase time :)

**Comment by chrislovecnm** [comment]
Can we close this?

**Pull request closed without merging**
