### PR TITLE
Kops apiserver support for openapi and generated API docs

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by pwittrock** [comment]
@chrislovecnm @justinsb

**Comment by pwittrock** [comment]
you can look at the docs under docs/apireference/build/index.html

**Comment by chrislovecnm** [comment]
I assume this is ready?

**Comment by pwittrock** [comment]
Nope, some weird stuff going on with go vet :(

**Comment by pwittrock** [comment]
I think this is 90% done.  If anyone wants to pick it up and finish off the go vet errors, update the Make file to run the code generator, etc.  That would be great.

**Comment by pwittrock** [comment]
Yay, got travis passing.

**Comment by pwittrock** [comment]
@justinsb @chrislovecnm Please take a look at the first 2 commits.  The 3rd commit is huge, and a bunch of generated files.

**Comment by justinsb** [comment]
Oh cool - just sent you a PR (https://github.com/pwittrock/kops/pull/1), but I don't think I had your latest.  I'll take a look

**Comment by pwittrock** [comment]
That is really weird.  Any idea what the diff looks like?

**Comment by chrislovecnm** [comment]
We are going to need to get these up on kubernetes.io, not really useful on GitHub.

**Comment by pwittrock** [comment]
@chrislovecnm Agreed, they need to go somewhere better.

**Comment by pwittrock** [comment]
FYI, updated apiserver builder to have better backwards support for older versions of the apiserver and types code.  It should now generate both the openapi and the docs without any issues.  It can also run the server locally and produce a kubeconfig for kubectl to use.  Updated the README.md to reflect this.

**Comment by pwittrock** [comment]
@chrislovecnm I think we probably don't want the kops docs hosted in kubernetes.github.com.  Doing so would mean getting a review from the docs team everytime you wanted to update your docs, which would really slow you down.  WDYT of setting up a GitHub pages for kops: https://kubernetes.github.com/kops.  [link to instructions](https://help.github.com/articles/user-organization-and-project-pages/)

**Comment by pwittrock** [comment]
@justinsb I updated the README.md with all the information you should need to setup your Makefile.

**Comment by pwittrock** [comment]
Thanks for the merge.  You probably want to go update the files under https://github.com/kubernetes/kops/tree/master/docs/apireference/examples with the actual examples you want to show up in the documentation.

**Pull request merged**
