### PR TITLE
Automated cherry pick of #11713: Update controller-runtime to v0.9.0

### PR DESCRIPTION
**Pull request by hakman**
Cherry pick of #11713 on release-1.21.

#11713: Update k8s dependencies to v1.21.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by hakman** [comment]
Would be nice to ship kOps 1.21.0 or 1.21.1 with a stable controller-runtime.
/hold
/cc @rifelpet @johngmyers

**Comment by johngmyers** [comment]
For reference, currently using controller-runtime 0.9.0-beta.0 and k8s dependencies 1.21.0.

I'm slightly leaning towards taking this in kops 1.21.1.

**Comment by hakman** [comment]
Not sure if waiting for 1.21.1 will be of much help. Getting it into 1.21.0 would allow us to fix any issues in the (usually fast) 1.21.1.

**Comment by johngmyers** [comment]
Office Hours decision: Don't pull into 1.21.x until we have a particular reason to.
/close

**Pull request closed without merging**
