### PR TITLE
Fix cloudmock to pass govet

### PR DESCRIPTION
**Pull request by justinsb**
Builds on #4926

### CODE REVIEW

**Comment by chrislovecnm** [comment]
> So I'm guessing the behaviour changed in go 1.10, so we can't merge this until we're using go 1.10 (which I think is in k8s 1.10)

k8s 1.11 is go 1.10.1 if I am understanding your comment.

**Comment by justinsb** [comment]
Blocked on #5817

**Comment by justinsb** [comment]
/retest

Odd CI failure fetching kubelet hash; looking into adding a retry or a cache.

**Comment by rdrgmnzs** [comment]
LGTM, from the previous comments it sounds like we can land this on #5823 lands.

**Comment by justinsb** [comment]
Yes, should finally be good to go now :-)

**Pull request merged**
