### PR TITLE
Use debian as default image for DO images

### PR DESCRIPTION
**Pull request by srikiz**
Since coreOS will no longer be supported, changing the DO image default to Debian instead.

### CODE REVIEW

**Comment by rifelpet** [comment]
ugh there was an issue with the netlify jobs so prow won't merge the PR. I don't have permission to retry the jobs, but you could amend the commit and force push it to trigger a new set of jobs that would hopefully succeed.

**Comment by hakman** [comment]
Canceling LGTM until netlify is fixed.
/lgtm cancel

**Comment by johngmyers** [comment]
Should also update the references to CoreOS in docs/getting_started/digitalocean.md

**Comment by srikiz** [comment]
Thanks for mentioning this @johngmyers  - updated DO docs now.

**Comment by hakman** [comment]
@srikiz should this be part of 1.17?
/lgtm

**Comment by srikiz** [comment]
@hakman  - Yes, I'll create a cherry-pick PR sometime today. Thanks !
When is 1.17 getting freezed?

**Comment by hakman** [comment]
1.17 is being prepared for release, but this seems pretty important and simple change.
Maybe you can also cherry-pick https://github.com/kubernetes/kops/pull/9179 and hope that gets accepted also.
Thanks!

**Pull request merged**
