### PR TITLE
Rhel8 Support in release-1.13

### PR DESCRIPTION
**Pull request by neoakris**
https://github.com/kubernetes/kops/issues/7129
Cassandra added support for Rhel8 in a custom build of release 1.12, I validated for release 1.12 want to merge this change into the next release 1.13 so we can use upstream in the future.

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
Hi @neoakris can you please look into signing the CLA when you have a chance? When you do so it applies to all Kubernetes sub-projects and you'll be covered for all of them from then on.

Could you please also squash some of the changes here and resolve the merge conflicts?

**Comment by justinsb** [comment]
Ah - I think the issue might be that you're targeting the release-1.13 branch?  If you try targeting master there should be less problems!

We can then cherry-pick it from master to release-1.13 (and other release branches)

**Comment by neoakris** [comment]
@rdrgmnzs I looked into signing the CLA, and to my knowledge, I'm part of an organization that signed it, so I thought I was good on that part? 
Thanks justin I'll try to switch it to master.

**Comment by justinsb** [comment]
I do think this looks good (thought it is a little hard to see the rhel8 changes with everything else going on!)

The easiest way should be:
```
git checkout master
git checkout -b rhel8_support
git cherry-pick f449e6194f763063781e08c4922f0ca1260bc900
git cherry-pick 592d7cd211df45d7e1869d217889ee1d8490724e
git cherry-pick 05c5af4137fae4121fae7fb0633692b420b5457c
git push --force <remote>/rhel8
```

(or you can you just open a new PR from the rhel8_support branch, if that's easier!

**Comment by neoakris** [comment]
Thanks @justinsb I'm decent at git, but not so great at the advanced commands, this was enough guidance for me to move forward + the ping was needed to remind me about this. 

here's what I've done
git clone git@github.com:VibrentHealth/kops.git
cd kops
git remote add upstream https://github.com/kubernetes/kops
git fetch upstream
git merge upstream/master
git push origin 
//(our fork's master is now synced with upstream master)

git checkout -b rhel8_support
git cherry-pick f449e6194f763063781e08c4922f0ca1260bc900
git cherry-pick 592d7cd211df45d7e1869d217889ee1d8490724e
git cherry-pick 05c5af4137fae4121fae7fb0633692b420b5457c
git diff master
//(makes it look like only the desired diff is captured)

git push --force <remote>/rhel8
//had trouble figuring out this command, Instead of trying to debug command syntax and potential lack of rights to the repo, I went with the create a new PR option, so I'm closing this PR.

Here is the new PR, I'll add @justinsb as a reviewer
https://github.com/kubernetes/kops/pull/7287

**Pull request closed without merging**
