### PR TITLE
Cherry pick #7874 onto 1.15

### PR DESCRIPTION
**Pull request by ReillyProcentive**
Cherry pick of #7874, as we have run into the same issue of weave pods getting evicted from a host.

### CODE REVIEW

**Comment by joshbranham** [comment]
The branch is stale against the `release-1.15` branch, looks like the `make` target is nonexistent. Can you merge the head of `releast-1.15` into yours?

`make: *** No rule to make target 'build-docs-netlify'` @ReillyProcentive

**Comment by ReillyProcentive** [comment]
Any update on getting this merged?

**Comment by rifelpet** [comment]
/lgtm
sorry for the delay!

**Pull request merged**
