### PR TITLE
FeatureGates support in all the components

### PR DESCRIPTION
**Pull request by diegows**
Adding --feature-gates for all the Kubernetes components.

### CODE REVIEW

**Comment by diegows** [comment]
CLA already signed.

**Comment by chrislovecnm** [comment]
Does your GitHub config match the email address for the cla?

**Comment by chrislovecnm** [comment]
LGTM ... waiting on confirmation from other owners on what we are merging for 1.8

**Comment by justinsb** [comment]
/lgtm

Thanks @diegows !

**Pull request merged**
