### PR TITLE
typo fixes in stable for ci verify jobs

### PR DESCRIPTION
**Pull request by chrisz100**
The changelog for 1.10 includes typos our vetting now marks as a bug. Cleaned the typos and annotated where something was modified in 1.10 release notes.

### CODE REVIEW

**Comment by rdrgmnzs** [comment]
@chrisz100 do we know if the CI job will just fix these once again?

**Comment by chrisz100** [comment]
What do you mean fix these? As it’s just the last release and we don’t replicate this in the next release (my commit message is spelled correctly) that should be fine

**Comment by rdrgmnzs** [comment]
@chrisz100 I'm wondering if the CI bot will revert your fixes in the 1.10 changelog.

**Comment by chrisz100** [comment]
Highly doubt that but possibly @justinsb knows more about these scripts?

**Comment by mikesplain** [comment]
Hmm well these aren't really typos since they are the actual commit message and are the actual change. The CI just runs `make verify-misspelling` as far as I know, which passes on master for me.  Where are you seeing the issue @chrisz100? Thanks for the quick fix!

**Comment by chrisz100** [comment]
I don’t remember the PR ids but it’s been in quite a few pull requests.

**Comment by justinsb** [comment]
This looks like a good way to fix this - thanks!

I'm looking at our verify-spelling script in more detail as well now - we were pulling from github, and it's better to vendor, so tackling that.

/approve
/lgtm

**Pull request merged**
