### PR TITLE
Dependencies for Toolbox Instance Selector

### PR DESCRIPTION
**Pull request by bwagner5**
This PR updates dependencies for the new `kops toolbox instance-selector` command. 

It adds an AWS go pkg `github.com/aws/amazon-ec2-instance-selector` to go.mod and vendors the pkg.

### CODE REVIEW

**Comment by bwagner5** [comment]
I signed it

**Comment by hakman** [comment]
@bwagner5 I think deps and code should be in same PR, just different commits.

**Comment by bwagner5** [comment]
gotcha, I misread this as two PRs:

"Open a pull request with these changes separately from other work so that it is easier to review."

I'll close this PR in favor of the other that does include both deps and feature.

**Comment by hakman** [comment]
I think the docs are now quite up to date there. 😄 
Thanks!

**Pull request closed without merging**
