### PR TITLE
Update kube-router to v1.2.3

### PR DESCRIPTION
**Pull request by hakman**
https://github.com/cloudnativelabs/kube-router/releases/tag/v1.2.3

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by hakman** [comment]
@murali-reddy any ideas why this would not work with a simple version bump?
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/11124/pull-kops-e2e-cni-kuberouter/1374646230700789760/artifacts/ip-172-20-60-90.ap-southeast-2.compute.internal/kube-router-h9hk2.log

**Comment by murali-reddy** [comment]
@hakman Did the CI fail becuase there were errors in the logs or was there a test failure as well?

We address the errors part in https://github.com/cloudnativelabs/kube-router/pull/1054, ready to 1.2.1 release, but was wondering if this was the only issue.

**Comment by hakman** [comment]
@murali-reddy there were many failed tests. Tried 3 runs before reverting the change to see if I can reproduce it with v1.1.1.
You can see the test results and artifacts from one of the runs here:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kops/11124/pull-kops-e2e-cni-kuberouter/1374613539594964992

**Comment by murali-reddy** [comment]
@hakman Looking at the logs I am not able to figure what is going wrong. All the nodes end up in non-ready state after which tests are faling as nodes are not ready
```
Mar 25 15:28:30.198: FAIL: All nodes should be ready after test, Not ready nodes: ", ip-172-20-47-185.ap-northeast-1.compute.internal, ip-172-20-63-93.ap-northeast-1.compute.internal"
.....
Mar 25 16:09:09.931: All nodes should be ready after test, Not ready nodes: ", ip-172-20-45-197.ap-northeast-1.compute.internal, ip-172-20-47-185.ap-northeast-1.compute.internal, ip-172-20-48-60.        ap-northeast-1.compute.internal, ip-172-20-63-93.ap-northeast-1.compute.internal"
```

There is one test failure, I will check if that is causing any problem
```
{"msg":"FAILED [sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]","total":-1,"completed":5,"skipped":46,"failed":1,"failures":["[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]"]}

```

**Comment by hakman** [comment]
Thanks @murali-reddy. Please let me  know  if you need any help debugging.

**Comment by murali-reddy** [comment]
@hakman I am not quite familiar with kops CI tests. So I am not sure how to go about root causing in efficient way. Like I mentioned in earlier comment I analyzed the logs but I can only conclude that nodes were not ready (perhaps even after applying kube-router CNI). There was error dumping kube-router logs as well. Appriciate any help with how to go about it.

Do you mind doing manual install of cluster with kops and upgrading the latest version of kube-router and see if you run into any issue?

**Comment by hakman** [comment]
The issue seems fixed in v.1.2.3 and tests pass now.

**Review by rifelpet — APPROVED** [review]

**Pull request merged**
