### PR TITLE
docs: clarify /24 CIDR allocation

### PR DESCRIPTION
**Pull request by zytek**
Kubenet allocates /24 CIDR to each Node, not Pod

### CODE REVIEW

**Comment by zytek** [comment]
CLA signed.

**Comment by zytek** [comment]
linuxfoundation cla signed

**Comment by kris-nova** [comment]
We have to be patient with The Linux Foundation's CLA.. The change LGTM

**Comment by chrislovecnm** [comment]
Based on @kris-nova comment  LGTM

**Pull request merged**
