### PR TITLE
Cobra improvements

### PR DESCRIPTION
**Pull request by billyshambrook**
#783

### CODE REVIEW

**Comment by billyshambrook** [comment]
I chose to hide the genhelpdocs command as it should only be used by developers.

**Comment by chrislovecnm** [comment]
@billyshambrook your build is broken.  Please follow these instructions in another PR https://github.com/kubernetes/kops/blob/master/docs/development/dependencies.md and add the needed dependency.  Let's get the dependency in another PR that we can merge in before this one.

This is awesome!!

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
Not sure if that will work or not :P

**Comment by chrislovecnm** [comment]
@billyshambrook  any changed needed for this?  Travis is building, and google bot wigged out about your CLA.  "I signed it" in a comment sometimes helps.

**Comment by billyshambrook** [comment]
Sorry, think I have screwed this up after trying to rebase this with master.

**Comment by billyshambrook** [comment]
I signed it

**Comment by chrislovecnm** [comment]
I manually adjusted the labels ... LOL.  Removing the WIP tag.  Will let you fix the rebase, and ping me when I can review again.  I bumped the Travis build manually, so we can see if the PR with the vendor dep helped.

**Pull request closed without merging**
