### PR TITLE
WIP - Allow attaching to existing elbs/albs

### PR DESCRIPTION
**Pull request by tsupertramp**
Hey Ho,

added my Pull Request to support ALB/ELB attachments - See discussion in:

https://github.com/kubernetes/kops/issues/1543

Attachment/Detachment is working. Change output is fine as long as cluster spec api object is dns. If I switch it to loadbalancer the output/behaviour does not work anymore. This is caused by attachment handling of pkg/model/api_loadbalancer.go - Do anybody has a good solution to solve this?

Greetings, Thomas

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1748)

### CODE REVIEW

**Comment by tsupertramp** [comment]
I will close this. There is no sense to use ALB at all.

Take a great nginx ingress controller and the problem is solved.

Greetings, Thomas

**Comment by vendrov** [comment]
@tsupertramp Why did you closed the PR? do we really want to force the user to use nginx controller?

**Comment by tsupertramp** [comment]
@vendrov Yeah i think using a nginx controller is the better way to get towards the result. If ALB is required then i should be added in kubernetes as svc type from my point of view. Everything else is just a "hack". After i understood this i closed my pr. How is your opinion about that?

**Comment by vendrov** [comment]
@tsupertramp we need to support ELB as well for TCP connection. Doe's nginx controller support TCP connections?

**Pull request closed without merging**
