### PR TITLE
Remove copyright YEAR from generated Go files

### LINKED ISSUE #10515: Remove copyright year from generated go files
The copyright year being in the file header causes issues every new year requiring us to regenerate the apimachinery files for all active branches. This issue was raised and determined the year is not necessary: https://github.com/kubernetes/gengo/issues/24

> Legal guidance is that the year is literally meaningless on these files. My proposal is that we simply omit the year field, and fix the kubernetes linter(s) to accept boilerplate with or without year.

See also the linked PRs to that issue that are removing it from various kubernetes repos. We should update ours to do the same. One issue we might run into is that the header file we pass to apimachinery is shared by our hack/update-header.sh script which touches nearly _every_ file in the repo. We could remove the year from every file but that would increase the likelihood of merge conflicts. Or I think we could use a separate header file just for apimachinery that doesn't have the year in it, thereby only touching the apimachinery-generated files.

### PR DESCRIPTION
**Pull request by bmelbourne**
**What this PR does / why we need it**:
Fixes the following issue in kops CI test `make quick-ci` related to the change to _Copyright 2021_ in the Go boilerplate headers.

```
k8s.io/code-generator/cmd/client-gen
# These code-generator tools still depend on the kops repo being in GOPATH
# ref: https://github.com/kubernetes/gengo/issues/64
/home/runner/work/kops/kops/go/src/k8s.io/kops/_output/bin/conversion-gen --verify-only --skip-unsafe=true --input-dirs k8s.io/kops/pkg/apis/kops/v1alpha2 --v=0  --output-file-base=zz_generated.conversion \
	 --go-header-file "hack/boilerplate/boilerplate.go.txt"
F0101 13:16:16.689939   18295 main.go:134] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kops/pkg/apis/kops/v1alpha2":
output for "v1alpha2/zz_generated.conversion.go" differs; first existing/expected diff: 
  "0 The Kubernetes Authors.\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may n"
  "1 The Kubernetes Authors.\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may n"
```

Similar issue https://github.com/kubernetes/kubernetes/pull/59172 already addressed in Kubernetes project back in 2018.

**Which issue(s) this PR fixes**
Fixes #10515 

**Special notes for your reviewer**:
`hack/boilerplate/boilerplate.py` has been copied from Kubernetes as this project uses a similar approach to re-generating Go boilerplate headers and has been well tested for several years.

https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py

### CODE REVIEW

**Comment by bmelbourne** [comment]
@rifelpet 
Can you provide an `/ok-to-test` please?

**Comment by rifelpet** [comment]
Thanks for fixing this! I'm glad that python script will be more in line with k/k https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/hack/boilerplate/boilerplate.py

/lgtm
/approve

**Pull request merged**
