### PR TITLE
Update AWS CCM to 13.05.2022 releases

### PR DESCRIPTION
**Pull request by hakman**
/hold for images to be published
https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/provider-aws/cloud-controller-manager

The build for 1.21.0 has failed so image cannot be promoted for now:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-aws-push-images/1524937450936340480

The build for 1.22.1 cannot start due to a version related bug:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/13644/pull-kops-latest-e2e-aws-k8s-1-22/1525104500518424576/artifacts/cluster-info/kube-system/aws-cloud-controller-manager-kbrzg/logs.txt

/cc @olemarkus @rifelpet

### CODE REVIEW

**Review by olemarkus — APPROVED** [review]

**Comment by hakman** [comment]
Images were published in https://github.com/kubernetes/k8s.io/pull/3734.
/hold cancel

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
