### PR TITLE
Finding home directory so it will be happy for windows users

### PR DESCRIPTION
**Pull request by chrislovecnm**
Fixes: https://github.com/kubernetes/kops/issues/4523

### CODE REVIEW

**Comment by chrislovecnm** [comment]
/hold

Well, how the heck do I fix that one.  See if I can override the default.  Generated docs is now generating the docs with a default ssh key of /home/travis/.ssh/id_pub.

**Comment by chrislovecnm** [comment]
/hold cancel 

I think this is ok, but someone will need to test on windows

**Comment by chrislovecnm** [comment]
/hold

testing has shown that this does not quite work

**Comment by justinsb** [comment]
Believed fixed in #5249

**Pull request closed without merging**
