### PR TITLE
Bump COS version in alpha channel for k8s >= 1.16

### PR DESCRIPTION
**Pull request by justinsb**
We use the latest LTS version

### CODE REVIEW

**Comment by justinsb** [comment]
cc @geojaz ... moving into the modern era!

**Comment by geojaz** [comment]
seems a little weird that aws-e2e is failing on gce changes :/

**Comment by rifelpet** [comment]
It looks like we're now testing for k8s 1.18 and the docker images dont exist:

from kubelet logs:
```
E1216 03:27:25.329962    3030 pod_workers.go:191] Error syncing pod 1b741f13ac499aa52bbe3fdd0b70e693 ("kube-controller-manager-ip-172-20-42-166.eu-west-2.compute.internal_kube-system(1b741f13ac499aa52bbe3fdd0b70e693)"), skipping: failed to "StartContainer" for "kube-controller-manager" with ImagePullBackOff: "Back-off pulling image \"k8s.gcr.io/kube-controller-manager-amd64:v1.18.0-alpha.0.1765_0a61fd987eff6c\""
E1216 03:27:25.355449    3030 remote_image.go:113] PullImage "k8s.gcr.io/kube-proxy-amd64:v1.18.0-alpha.0.1765_0a61fd987eff6c" from image service failed: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/kube-proxy-amd64:v1.18.0-alpha.0.1765_0a61fd987eff6c not found: manifest unknown: Failed to fetch "v1.18.0-alpha.0.1765_0a61fd987eff6c" from request "/v2/kube-proxy-amd64/manifests/v1.18.0-alpha.0.1765_0a61fd987eff6c".
```

**Comment by justinsb** [comment]
/retest

That sounds more like k8s head being flaky ... let's give it another go!

**Comment by geojaz** [comment]
/lgtm
/approve
I want to know more. I was pretty sure that when aws e2e failed via some GCE channel changes, something wasn't right, so i tried running it again. How did @justinsb predict that this error was an upstream flake? Because kubelet was looking for a version that couldn't yet exist? Are there any signals or patterns that we could either document or automate against to improve our dev ux?

I guess i'm asking because we've had failing prow stuff on master for at least a couple of weeks and it's become hard (at least for me) to determine when we're at fault and what we need to do. Added an item to this week's agenda to try to get some more insight. thanks ;D

**Comment by rifelpet** [comment]
flaking E2E tests have been a problem for us for a while :) from our previous discussions it seems there are a couple sources:
* they just removed the ginkgo flake retry count in all upstream tests in order to help identify and hopefully fix flaky tests. see the discussion on the kubernetes-dev mailing list
* this time of the release cycle tends to be when significant code changes get merged to master, which can result in additional flaky tests
* not specific to e2e but all prow jobs: sometimes a job is missing all of its logs and needs to be retried. unclear whether it actually ran or not originally.

in terms of what we can do to improve dev ux, i have two suggestions:
1. somehow automatically retry failing e2e jobs or prow jobs with no logs
2. don't use the master branch HEAD for e2e, instead use something deemed more stable, such as a latest tag or something. i dont know much this would help. When Kops was more delayed,  our master branch was targeting K8s 1.X but k8s master was already on 1.X+1, so it would've been more appropriate for our master e2e jobs to target the release-1.X k8s branch, but i don't think that will continue to be an issue anymore.

definitely worth discussing during office hours.

**Pull request merged**
