### PR TITLE
remove the unnecessary break

### PR DESCRIPTION
**Pull request by tanjunchen**
#7800

### CODE REVIEW

**Comment by tanjunchen** [comment]
@mikesplain

**Comment by tanjunchen** [comment]
@yuxiaobo96  can you ok-to-test?

**Comment by tanjunchen** [comment]
@justinsb can you help  me review this pr? Thanks!!!

**Comment by tanjunchen** [comment]
@justinsb  can you review this pr ? maybe the test ci something wrong?

**Comment by justinsb** [comment]
Thanks @tanjunchen 

/approve
/lgtm

**Pull request merged**
