### PR TITLE
Move kops-controller client into its own package

### PR DESCRIPTION
**Pull request by justinsb**
This should allow more reuse.

### CODE REVIEW

**Comment by johngmyers** [comment]
I can see moving `Client` and `dial`, but I'd prefer we leave the bootstrap-specific portions of `QueryBootstrap` behind. Perhaps pass in a `req, resp interface{}`?

Possibly pass in the authenticator as well, since non-bootstrap requests will probably have a different authenticator?

**Comment by johngmyers** [comment]
Actually, `req` and `resp` should use type parameters.

**Comment by justinsb** [comment]
I don't think we can use type parameters today with struct methods (unless you know a trick).

I'm guessing you want to not move `nodeup.BootstrapRequest` because of versioning skew issues?  But we do have those skew issues, I think.  Although maybe if we always update the control plane first, and don't bootstrap control-plane nodes, it's not a problem in practice?

This refactor is to support updating gossip to just work through kops-controller.  For that I was thinking of using GRPC, because I think we want streaming support rather than polling.  I could just leave the existing QueryBootstrap client/logic where it is and make this a pure GRPC client - that would work too.  A bit of a code duplication for connecting, but not _too_ bad as the GRPC interfaces are a little different anyway.  Would that be better for you?

**Comment by johngmyers** [comment]
I sent you a PR to remove knowledge of the request and response types. I think it would be good to make the authenticator optional and possibly passed-in per request.

I see there are two bootstrap requests to kops-controller. It would be good to consolidate them, preferably into the one that is a `Task`. But that is probably a different PR.

**Comment by johngmyers** [comment]
I don't want to move BootstrapRequest because I don't want that knowledge outside of nodeup. It should be obvious that only nodeup can bootstrap or authenticate as a bootstrapping instance.

If you need GRPC features, then I suppose you need GRPC. I'd prefer to keep the bootstraprequest simple if possible. You could probably extract the connection logic into something shared by the REST and GRPC query methods.

**Comment by justinsb** [comment]
Thanks @johngmyers - pulled in your change :-)

**Review by johngmyers — APPROVED** [review]

**Pull request merged**
