### PR TITLE
WIP test commit for testing e2e job on release-1.15

### PR DESCRIPTION
**Pull request by rifelpet**

### CODE REVIEW

**Comment by rifelpet** [comment]
looks good 
/close

**Comment by rifelpet** [comment]
now testing the 1.15 e2e for this change: https://github.com/kubernetes/test-infra/pull/15847

**Comment by hakman** [comment]
One more try...
/test pull-kops-e2e-kubernetes-aws-1-15

**Comment by rifelpet** [comment]
testing complete
/close

**Pull request closed without merging**
