### PR TITLE
Feature/qps flag release 1.11

### PR DESCRIPTION
**Pull request by jeotic**
Add ApiQps and ApiBurst flags

### CODE REVIEW

**Comment by chrisz100** [comment]
Hi @jeotic can you please sign the cncf CLA? It’s a one time thing for the entire kubernetes project and allows us to move forward with this!

**Comment by maruina** [comment]
Hello @jeotic , are you able to pick this up? It's a feature we'd like to have for our cluster because we hit the default limit quite a lot. I appreciate if you don't have time and I would be happy to help.

**Comment by maruina** [comment]
~Hello @jeotic , are you able to pick this up? It's a feature we'd like to have for our cluster because we hit the default limit quite a lot. I appreciate if you don't have time and I would be happy to help.~

Ignore me, wrong flag :)

**Comment by kippandrew** [comment]
I'd love to see this merged in (we need the ability to customize the QPS/BURST limits), but it looks like the author @jeotic has abandoned the PR. Would it be okay if re-open as new PR?

**Comment by maruina** [comment]
Hello @KierranM , are you planning to pick this up soon?

**Pull request closed without merging**
