### PR TITLE
Log OIDC providers we don't delete

### PR DESCRIPTION
**Pull request by olemarkus**

### CODE REVIEW

**Comment by olemarkus** [comment]
/hold
Just to see why we have ~100 OIDC providers in our account.

**Comment by justinsb** [comment]
We should probably mark this one as "WIP" or "housekeeping", because with the `foundK8sTag` check it's pretty dangerous if we accidentally merged it :-)

**Comment by justinsb** [comment]
FYI I am proposing that the janitor also clean these up: https://github.com/kubernetes-sigs/boskos/pull/121

There will always be some instances where the e2e run is interrupted and `kops delete cluster` is not run.

**Pull request closed without merging**
