### PR TITLE
Update google SDK libraries

### PR DESCRIPTION
**Pull request by justinsb**
Updating to latest google SDK libraries, will be needed for
cluster-api support.

### CODE REVIEW

**Comment by justinsb** [comment]
/hold

Introduces new protobuf dependency which I want to validate...

**Comment by olemarkus** [comment]
Not really related, but what is our plan for cluster-api support these days?

**Comment by justinsb** [comment]
Re cluster-api, I think the blocking pieces have merged.  I was going to start the PR train to enable them (optionally) on GCE.  Targeting nodes only initially.  The big piece we needed (and might need a few more things for) was for kops-controller to support booting without the state store - but I _think_ that's mostly in now.

**Comment by justinsb** [comment]
OK so I was worried about that proto dependency, but it looks fine!

/hold cancel

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
